Repository NREL/EnergyPlus, pull requests merged in 2018-07, with the labels that each got.

#6760 Remove unnecessary warnings in two example files
  testfiles/AirflowNetwork_Simple_House.idf
  testfiles/AirflowNetwork_Simple_SmallOffice.idf
Labels: Defect

#6769 Remove extra space at end of readvars header
  doc/input-output-reference/src/output/using-readvarseso.tex
  src/ReadVars/ReadVarsESO.f90
Labels: Defect

#6776 Setup a correct value for an exp function with underflow value
  src/EnergyPlus/PlantHeatExchangerFluidToFluid.cc
  tst/EnergyPlus/unit/PlantHeatExchangerFluidToFluid.unit.cc
Labels: Defect

#6786 Improve error message when SetpointManager:SingleZone:Reheat does not find matching zone inlet node
  src/EnergyPlus/SetPointManager.cc
  testfiles/2ZoneDataCenterHVAC_wEconomizer.idf
  tst/EnergyPlus/unit/SetPointManager.unit.cc
Labels: Defect

#6775 Misspelled object names result in warning that says object type is wrong
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  tst/EnergyPlus/unit/InputProcessor.unit.cc
Labels: Defect

#6754 Address overshooting using correct zone air temperature at previous timestep
  src/EnergyPlus/DataZoneControls.hh
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Defect

#6765 Add plant initialization for SwimmingPool:Indoor.
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/SwimmingPool.hh
  tst/EnergyPlus/unit/SwimmingPool.unit.cc
Labels: Defect

#6764 Correction of Reference Temperature for Fisher-Pedersen Convection Models when Specified for Surfaces
  src/EnergyPlus/ConvectionCoefficients.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
Labels: Defect

#6461 179d reporting based on v8.8.0
  .decent_ci-Linux.yaml
  CMakeLists.txt
  cmake/179DReporting.cmake
  cmake/179D_Generate_Reports.sh.in
  scripts/dev/179D_Generate_Index.py
Labels: NewFeature, NotIDDChange

#6828 Fix allocation issue for metered output variables, Fixes #6827
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  tst/EnergyPlus/unit/RuntimeLanguageProcessor.unit.cc
Labels: AirflowNetwork, Defect

#6824 Fix issue when Output:Variable key uses regex symbols for full key comparison
  src/EnergyPlus/OutputProcessor.cc
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Defect

#6822 Address overwritten RunPeriod objects
  src/EnergyPlus/InputProcessing/IdfParser.cc
  tst/EnergyPlus/unit/InputProcessor.unit.cc
Labels: Defect

#6813 Heating water coil sizing mixing up hot and cold initialization temperatures
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACFourPipeBeam.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACUnitarySystem.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/ReportSizingManager.cc
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/VentilatedSlab.cc
  tst/EnergyPlus/unit/BoilerHotWater.unit.cc
  tst/EnergyPlus/unit/HVACFourPipeBeam.unit.cc
  tst/EnergyPlus/unit/HVACUnitarySystem.unit.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
  tst/EnergyPlus/unit/WaterCoils.unit.cc
Labels: Defect

#6805 Correct Fan:SystemModel crash when Continuous mode is used without power as a function of flow fraction curve
  src/EnergyPlus/HVACFan.cc
  tst/EnergyPlus/unit/HVACFan.unit.cc
Labels: Defect

#6807 Assign correct input values for Curve:ExponentialSkewNormal
  src/EnergyPlus/CurveManager.cc
  tst/EnergyPlus/unit/CurveManager.unit.cc
Labels: Defect

#6762 Correct terminal unit heating coil inlet air conditions used for sizing and/or reporting.
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/ReportSizingManager.cc
  tst/EnergyPlus/unit/ReportCoilSelection.unit.cc
Labels: Defect

#6850 Revert merge mistake of deleting initialization of CoilDesWaterDeltaT
  src/EnergyPlus/ReportSizingManager.cc
Labels: DoNotPublish

#6840 Correction of Equations in Exponential Curve Sections of Input/Output Reference
  doc/input-output-reference/src/overview/group-performance-curves.tex
Labels: Defect

#6825 Fix restrictive CLI requiring IDD for simulation
  src/EnergyPlus/CommandLineInterface.cc
Labels: Defect

#6818 Add a new example file for single sided natural ventilation
  testfiles/AirflowNetworkAdvanced_SingleSided_NV.idf
  testfiles/CMakeLists.txt
Labels: Defect

#6781 Bad initial tank temperature in WaterHeater:Mixed
  src/EnergyPlus/WaterThermalTanks.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Defect

#6826 Fix issue with infinite loop in epJSON schema generator
  scripts/dev/generate_epJSON_schema/idd_parser.py
Labels: DoNotPublish
