Repository NREL/EnergyPlus, pull requests merged in 2018-08, with the labels that each got.

#6778 Economizer faults do not work because fault objects are processed too late
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/Boilers.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixedAir.hh
  tst/EnergyPlus/unit/FaultsManager.unit.cc
Labels: Defect

#6600 AirloopHVAC:UnitarySystem with constant fan and multispeed gas/elec heating coil does not honor no load flow rate.
  src/EnergyPlus/HVACUnitarySystem.cc
  src/ExpandObjects/epfilter.f90
  testfiles/UnitarySystem_WaterCoils_wMultiSpeedFan.idf
  tst/EnergyPlus/unit/HVACUnitarySystem.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
Labels: Defect

#6812 Fan energy index
  design/FY2018/Fan Energy Index.md
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/air-system-fans.tex
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/Fans.hh
  src/EnergyPlus/HVACFan.cc
  src/EnergyPlus/HVACFan.hh
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportPredefined.hh
  src/Transition/OutputRulesFiles/OutputChanges8-9-0-to-9-0-0.md
  tst/EnergyPlus/unit/Fans.unit.cc
  tst/EnergyPlus/unit/HVACFan.unit.cc
Labels: NewFeature

#6914 Extend WindowTests example to include switchable glazing with illuminance control, and other minor test changes
  performance_tests/Inactive/10zone1vav.idf
  performance_tests/Inactive/20zone1vav.idf
  performance_tests/Inactive/30zone1vav.idf
  performance_tests/Inactive/40zone1vav.idf
  performance_tests/Inactive/50zone1vav.idf
  performance_tests/Inactive/60Zone1PVAV.idf
  performance_tests/Inactive/60Zone1VAV.idf
  performance_tests/Inactive/60zone2PVAV.idf
  performance_tests/Inactive/60zone3PVAV.idf
  performance_tests/Inactive/60zone6PVAV.idf
  performance_tests/Inactive/benchmarklargeofficenew_usa_ca_san_francisco.idf
  testfiles/CMakeLists.txt
  testfiles/WindowTests.idf
  testfiles/WindowTests.rvi
  testfiles/_5ZoneAirCooled_annual.idf
  testfiles/_5ZoneAirCooled_annual.rvi
  testfiles/_RefBldgSmallHotelNew2004_Chicago_annual.idf
Labels: Defect

#6915 Avoid crash of AirflowNetworkAdvanced_SingleSided_NV
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: Defect

#6924 HotFix: Update unit test fenestration fields for AFN
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: DoNotPublish

#6930 Drop small hotel annual test
  testfiles/CMakeLists.txt
  testfiles/_RefBldgSmallHotelNew2004_Chicago_annual.idf
Labels: DoNotPublish

#6858 Correct EIO Wind Angle Output
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/Transition/OutputRulesFiles/OutputChanges8-9-0-to-9-0-0.md
Labels: Defect, NotIDDChange, OutputChange

#6501 Simple python script to parse C++ code for EMS variable calls
  doc/tools/parse_ems_actuators.py
Labels: NewFeature

#6931 Update PR template md
  .github/pull_request_template.md
Labels: DoNotPublish

#6782 Addressed Incorrect Source Side Inlet Temperature in Stratified Tank
  src/EnergyPlus/WaterThermalTanks.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Defect

#6918 Fix infinite parsing loop caused by stray semicolon
  .gitignore
  src/EnergyPlus/InputProcessing/IdfParser.cc
  tst/EnergyPlus/unit/InputProcessor.unit.cc
Labels: Defect

#6876 Use outdoor air Cp to calculate reporting values of infiltration and ventilation
  src/EnergyPlus/HVACManager.cc
  tst/EnergyPlus/unit/HVACManager.unit.cc
Labels: Defect

#6885 Add API function RunEnergyPlus that uses return codes instead of std::exit()
  src/EnergyPlus/EnergyPlusPgm.cc
  src/EnergyPlus/FileSystem.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/UtilityRoutines.hh
  src/EnergyPlus/public/EnergyPlusPgm.hh
  src/EnergyPlus/test_ep_as_library.cc
Labels: NewFeature

#6867 Assign the same HeatTransferAlgorithms for an interior surface with reverse constructions
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#6877 Addressed Transformer Rated Capacity of 0 hard crashes
  src/EnergyPlus/ElectricPowerServiceManager.cc
  tst/EnergyPlus/unit/ElectricPowerServiceManager.unit.cc
Labels: Defect

#6757 AirloopHVAC:UnitarySystem: Correct AT Mixer operation for set point control and Improve error message when Control Type = Load and no control zone name is specified
  src/EnergyPlus/HVACUnitarySystem.cc
  tst/EnergyPlus/unit/HVACUnitarySystem.unit.cc
Labels: Defect
