Repository NREL/EnergyPlus, pull requests merged in 2018-05, with the labels that each got.

#6740 Dummy PR to get develop moving again
  README.md
Labels: DoNotPublish

#6608 Output Variable Parser Fix
  doc/tools/parse_output_variables.py
  src/EnergyPlus/IntegratedHeatPump.cc
  src/EnergyPlus/WeatherManager.cc
Labels: DoNotPublish

#6721 Change error call to use the higher level routine
  src/EnergyPlus/ElectricPowerServiceManager.cc
Labels: DoNotPublish, Refactoring

#6745 Set multiple CO2 controllers correctly
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  tst/EnergyPlus/unit/ZoneContaminantPredictorCorrector.unit.cc
Labels: Defect

#6751 Set multiple GenericContam controllers correctly
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  tst/EnergyPlus/unit/ZoneContaminantPredictorCorrector.unit.cc
Labels: Defect
