Repository NREL/EnergyPlus, pull requests merged in 2018-03, with the labels that each got.

#6446 Incorrect primary air mass flow rate in PIU due to missing inlet node and airloop number
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/PoweredInductionUnits.cc
  src/EnergyPlus/PoweredInductionUnits.hh
  tst/EnergyPlus/unit/AirTerminalSingleDuctPIUReheat.unit.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
Labels: NotIDDChange

#6474 Fix the running average outdoor air temperature in the first day
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/ThermalComfort.hh
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
Labels: Defect, NotIDDChange

#6519 Remove EMS exp error
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/RuntimeLanguageProcessor.unit.cc
Labels: NotIDDChange

#6505 Speed up DataSetFixture.FluidPropertiesRefData unit test
  src/EnergyPlus/DataGlobals.cc
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  tst/EnergyPlus/unit/Datasets.unit.cc
Labels: DoNotPublish

#6538 Fix OutputProvided for Hybrid AC Model
  src/EnergyPlus/HybridEvapCoolingModel.cc
  src/EnergyPlus/HybridEvapCoolingModel.hh
  src/EnergyPlus/HybridUnitaryAirConditioners.cc
Labels: DoNotPublish

#6527 Yearly reporting bug fixes
  doc/input-output-reference/src/input-for-output.tex
  src/EnergyPlus/SQLiteProcedures.cc
  tst/EnergyPlus/unit/SQLite.unit.cc
Labels: Defect

#6449 Correct VS coil air flow and fan RTF calculations
  src/EnergyPlus/HVACUnitarySystem.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  tst/EnergyPlus/unit/HVACUnitarySystem.unit.cc
Labels: NotIDDChange

#6042 Fix static Fortran compilation
  .decent_ci-Windows.yaml
  cmake/CPack.STGZ_Header.sh.in
  cmake/ProjectMacros.cmake
  cmake/RunSimulation.cmake
  cmake/darwinpostflight.sh.in
  src/AppGPostProcess/CMakeLists.txt
  src/Basement/CMakeLists.txt
  src/CalcSoilSurfTemp/CMakeLists.txt
  src/ConvertESOMTR/CMakeLists.txt
  src/ExpandObjects/CMakeLists.txt
  src/HVAC-Diagram/CMakeLists.txt
  src/ParametricPreprocessor/CMakeLists.txt
  src/ReadVars/CMakeLists.txt
  src/Slab/CMakeLists.txt
  src/Transition/CMakeLists.txt
Labels: DoNotPublish

#6466 EMS Actuator for Window Shading Control can cause crash if status set to "blind on" but there are no blinds
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/DataHeatBalance.unit.cc
Labels: NotIDDChange

#6460 Correct use of variable-speed DX cooling coil WB inlet temp during dry-coil operation.
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  tst/EnergyPlus/unit/HVACUnitarySystem.unit.cc
Labels: NotIDDChange

#6419 Fix DualDuct VAV and VAV:OA: Wrong int index used, fix for #6418
  src/EnergyPlus/DualDuct.cc
  tst/EnergyPlus/unit/DualDuct.unit.cc
Labels: NotIDDChange

#6540 Fix state that needed to be cleared in boilers for unit tests
  src/EnergyPlus/Boilers.cc
Labels: DoNotPublish

#6513 Fix specific values in component load summary reports
  doc/engineering-reference/src/special-modules-reporting/zone-component-loads-summary.tex
  doc/input-output-reference/src/standard-output-reports/output-table-summaryreports.tex
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#6338 Fix VAV min flow frac > 1.0 and a bunch of termunitsizing issues related to multiple airloops
  doc/engineering-reference/src/loop-equipment-sizing-and-other-design-data/system-design-loads-and-air-flow-rates.tex
  doc/engineering-reference/src/loop-equipment-sizing-and-other-design-data/zone-design-loads-and-air-flow-rates.tex
  doc/input-output-reference/src/overview/group-design-objects.tex
  src/EnergyPlus/AirTerminalUnit.hh
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/DirectAirManager.cc
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/EvaporativeCoolers.hh
  src/EnergyPlus/HVACCooledBeam.cc
  src/EnergyPlus/HVACFourPipeBeam.cc
  src/EnergyPlus/HVACFourPipeBeam.hh
  src/EnergyPlus/HVACSingleDuctInduc.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/ReportSizingManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/ZoneAirLoopEquipmentManager.cc
  src/EnergyPlus/ZoneAirLoopEquipmentManager.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/EvaporativeCoolers.unit.cc
  tst/EnergyPlus/unit/SimAirServingZones.unit.cc
  tst/EnergyPlus/unit/SingleDuct.unit.cc
  tst/EnergyPlus/unit/SizeWaterHeatingCoil.unit.cc
  tst/EnergyPlus/unit/UnitHeater.unit.cc
  tst/EnergyPlus/unit/VAVDefMinMaxFlow.unit.cc
  tst/EnergyPlus/unit/WaterCoils.unit.cc
Labels: Defect, NotIDDChange

#6489 add trap to not process population concurrence unless VRP present
  src/EnergyPlus/SizingManager.cc
Labels: DoNotPublish

#6514 Fix Followup issues for Enhancements to Data Center Model
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/zone-internal-gains.tex
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/ZoneAirLoopEquipmentManager.cc
  src/Transition/CreateNewIDFUsingRulesV8_9_0.f90
Labels: DoNotPublish

#6499 Move setpoint calculation from zone time step to system time step
  doc/input-output-reference/src/overview/group-zone-controls-thermostats.tex
  src/EnergyPlus/DataZoneControls.hh
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: NewFeature, NotIDDChange

#6500 Change remaining Coil:Heating:Gas to Fuel plus cleanups on new coil sizing reports
  design/FY2018/Sizing Reporting Enhancements-Design.md
  doc/input-output-reference/src/standard-output-reports/output-table-summaryreports.tex
  doc/output-details-and-examples/src/output-files/eplustbl-lt-ext-gt.tex
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataHVACGlobals.cc
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/ReportCoilSelection.hh
  src/EnergyPlus/ReportSizingManager.cc
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/WaterCoils.cc
  testfiles/RefBldgHospitalNew2004_Chicago.idf
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/DataPlant.unit.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/InputProcessor.unit.cc
  tst/EnergyPlus/unit/IntegratedHeatPump.unit.cc
  tst/EnergyPlus/unit/ReportCoilSelection.unit.cc
Labels: Defect, NotIDDChange

#6498 VRF power in heat recovery using thermostat offset priority is 0 when coils are active
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect, NotIDDChange

#6523 Continuation of Constant Speed Branch Pump Fixes
  src/EnergyPlus/Plant/PlantLoopSolver.cc
  src/EnergyPlus/Plant/PlantLoopSolver.hh
  testfiles/CMakeLists.txt
  testfiles/ConstSpeedBranchPumpExercise.idf
Labels: Defect

#6542 6464 Fix Fuel Cell Solver Bounds
  doc/input-output-reference/src/overview/group-electric-load-center-generator.tex
  src/EnergyPlus/DataGenerators.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/FuelCellElectricGenerator.unit.cc
Labels: Defect

#6541 Improve setpoint calculation
  doc/input-output-reference/src/overview/group-zone-controls-thermostats.tex
  src/EnergyPlus/DataZoneControls.hh
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: DoNotPublish

#6543 EnergyPlus 8.9.0 Release Preparation
  CMakeLists.txt
  OutputChanges8-8-0-to-8-9-0.md
  cmake/Install.cmake
  release/readme.html
  testfiles/1ZoneDataCenterCRAC_wApproachTemp.idf
  testfiles/HVAC3Zone-IntGains-Def.imf
  testfiles/HVAC3ZoneChillerSpec.imf
  testfiles/HVAC3ZoneGeometry.imf
  testfiles/HVAC3ZoneMat-Const.imf
Labels: DoNotPublish

#6547 Fix CBVAV terminal unit error introduced with multi-HVAC controls
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.hh
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
Labels: DoNotPublish
