Repository NREL/EnergyPlus, pull requests merged in 2018-09, with the labels that each got.

#6941 RunPeriod bug fixes
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  src/Transition/CreateNewIDFUsingRulesV9_0_0.f90
  tst/EnergyPlus/unit/RunPeriod.unit.cc
Labels: DoNotPublish

#6852 Allow any wall shape for Kiva Foundations
  doc/input-output-reference/src/overview/group-advanced-surface-concepts.tex
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/Vectors.cc
  src/EnergyPlus/Vectors.hh
  third_party/kiva-ep/vendor/boost-1.61.0/boost/config/compiler/visualc.hpp
  tst/EnergyPlus/unit/DataSurfaces.unit.cc
  tst/EnergyPlus/unit/Vectors.unit.cc
Labels: NewFeature, NotIDDChange

#6948 Fix VRF curve dimension check and clarify xy variables for all DX heat pump defrost EIR curves
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  doc/input-output-reference/src/overview/group-variable-refrigerant-flow-equipment.tex
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
Labels: Defect

#6890 Addressed Damper Normal Heating Action in VAV Reheat Air Terminal
  src/EnergyPlus/SingleDuct.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuct.unit.cc
Labels: Defect

#6726 Fix return flow basis node calculation
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Defect

#6957 Initial addition of EP-Launch workflow files
  CMakeLists.txt
  cmake/Install.cmake
  workflows/app_g_postprocess.py
  workflows/calc_soil_surface_temp.py
  workflows/coeff_check.py
  workflows/coeff_conv.py
  workflows/energyplus.py
Labels: NewFeature

#6753 Include fan heat when sizing zone cooling coils and adjust airloop coil inlet/outlet conditions
  design/FY2018/NFP_AddFanHeatToZoneCoolingCoils.md
  doc/engineering-reference/src/loop-equipment-sizing-and-other-design-data/component-sizing.tex
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DataAirSystems.cc
  src/EnergyPlus/DataAirSystems.hh
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/FanCoilUnits.hh
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/Furnaces.hh
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.hh
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.hh
  src/EnergyPlus/HVACUnitarySystem.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/OutdoorAirUnit.hh
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/ReportSizingManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/UnitHeater.cc
  src/EnergyPlus/UnitHeater.hh
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UnitVentilator.hh
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/VentilatedSlab.hh
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  src/EnergyPlus/WindowAC.cc
  src/EnergyPlus/WindowAC.hh
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/DataSizing.unit.cc
  tst/EnergyPlus/unit/HVACUnitarySystem.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/OutdoorAirUnit.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
Labels: NewFeature, NotIDDChange

#6788 Include impact of AirTerminal:SingleDuct:Mixer in ZoneHVAC coil sizing
  src/EnergyPlus/DataAirSystems.hh
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/FanCoilUnits.hh
  src/EnergyPlus/HVACUnitarySystem.cc
  src/EnergyPlus/HVACUnitarySystem.hh
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/ReportSizingManager.cc
  src/EnergyPlus/ReportSizingManager.hh
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SingleDuct.hh
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/UnitVentilator.cc
  testfiles/DOAToFanCoilSupply.idf
  testfiles/DOAToPTAC.idf
  testfiles/DOAToPTHP.idf
  testfiles/DOAToUnitVentilator.idf
  testfiles/DOAToUnitarySystem.idf
  testfiles/DOAToVRF.idf
  testfiles/DOAToWaterToAirHPSupply.idf
  tst/EnergyPlus/unit/FanCoilUnits.unit.cc
  tst/EnergyPlus/unit/HVACUnitarySystem.unit.cc
  tst/EnergyPlus/unit/PurchasedAirManager.unit.cc
  tst/EnergyPlus/unit/ReportSizingManager.unit.cc
  tst/EnergyPlus/unit/SingleDuct.unit.cc
  tst/EnergyPlus/unit/UnitHeater.unit.cc
Labels: Defect, Priority1

#6967 Third Set of Engineering Reference Comprehensive Edits
  doc/engineering-reference/engineering-reference.tex
  doc/engineering-reference/src/alternative-modeling-processes/airflownetwork-model.tex
  doc/engineering-reference/src/alternative-modeling-processes/hybrid-model.tex
  doc/engineering-reference/src/alternative-modeling-processes/room-air-models.tex
  doc/engineering-reference/src/demand-limiting.tex
  doc/engineering-reference/src/operational-faults.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/coils.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/ice-thermal-storage.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference/air-system-distribution-terminals.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference/boilers.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference/chillers.tex
Labels: Defect, Documentation Sources, EnergyPlus

#6966 Fourth Set of Engineering Reference Comprehensive Edits
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/baseboard-heaters.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/coils.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/electric-baseboard-heater-with-radiation.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/hvac-controllers.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/air-system-compound-component-groups.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/air-system-fans.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/cooling-towers-and-evaporative-fluid-coolers.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/demand-controlled-ventilation.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/evaporative-coolers.tex
Labels: Defect, Documentation Sources, EnergyPlus

#6374 update nist escalation rates
  cmake/Install.cmake
  datasets/ConvertENCOSTtoEnergyPlusLifeCycleCost.xls
  datasets/LCCusePriceEscalationDataSet2017.idf
  datasets/LCCusePriceEscalationDataSet2018.idf
Labels: NewFeature, NotIDDChange

#6861 Addressed Heat exchanger bypass control problems
  src/EnergyPlus/MixedAir.cc
  tst/EnergyPlus/unit/MixedAir.unit.cc
Labels: Defect

#6872 Improve Kiva longwave radiation methodology and performance
  .decent_ci-Linux.yaml
  CMakeLists.txt
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  third_party/.gitignore
  third_party/cmake/kiva.cmake
  third_party/kiva-ep/.clang-format
  third_party/kiva-ep/CMakeLists.txt
  third_party/kiva-ep/LICENSE
  third_party/kiva-ep/LICENSE-EnergyPlus
  third_party/kiva-ep/cmake/FindGcov.cmake
  third_party/kiva-ep/cmake/FindLcov.cmake
  third_party/kiva-ep/cmake/Findcodecov.cmake
  third_party/kiva-ep/cmake/Install.cmake
  third_party/kiva-ep/cmake/LICENSE
  third_party/kiva-ep/cmake/TargetArch.cmake
  third_party/kiva-ep/cmake/llvm-cov-wrapper
  third_party/kiva-ep/src/libkiva/Algorithms.cpp
  third_party/kiva-ep/src/libkiva/Algorithms.hpp
  third_party/kiva-ep/src/libkiva/BoundaryConditions.hpp
  third_party/kiva-ep/src/libkiva/CMakeLists.txt
  third_party/kiva-ep/src/libkiva/Cell.cpp
  third_party/kiva-ep/src/libkiva/Cell.hpp
  third_party/kiva-ep/src/libkiva/Domain.cpp
  third_party/kiva-ep/src/libkiva/Domain.hpp
  third_party/kiva-ep/src/libkiva/Errors.cpp
  third_party/kiva-ep/src/libkiva/Errors.hpp
  third_party/kiva-ep/src/libkiva/Foundation.cpp
  third_party/kiva-ep/src/libkiva/Foundation.hpp
  third_party/kiva-ep/src/libkiva/Functions.cpp
  third_party/kiva-ep/src/libkiva/Functions.hpp
  third_party/kiva-ep/src/libkiva/Geometry.cpp
  third_party/kiva-ep/src/libkiva/Geometry.hpp
  third_party/kiva-ep/src/libkiva/Ground.cpp
  third_party/kiva-ep/src/libkiva/Ground.hpp
  third_party/kiva-ep/src/libkiva/GroundOutput.hpp
  third_party/kiva-ep/src/libkiva/Mesher.cpp
  third_party/kiva-ep/src/libkiva/Mesher.hpp
  third_party/kiva-ep/src/libkiva/Version.hpp.in
  third_party/kiva-ep/test/CMakeLists.txt
  third_party/kiva-ep/test/unit/CMakeLists.txt
  third_party/kiva-ep/test/unit/cell_test.cpp
  third_party/kiva-ep/test/unit/domain_test.cpp
  third_party/kiva-ep/test/unit/fixtures/base-fixture.hpp
  third_party/kiva-ep/test/unit/fixtures/bestest-fixture.hpp
  third_party/kiva-ep/test/unit/fixtures/typical-fixture.hpp
  third_party/kiva-ep/test/unit/foundation.unit.cpp
  third_party/kiva-ep/vendor/CMakeLists.txt
Labels: NewFeature, NotIDDChange, Performance

#6801 Fix Daylighting EMS lag Part1 - move surface EMS inits from InitSurfaceHeatBalance to InitHeatBalance
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
Labels: Defect

#6901 CoolingTower:VariableSpeed:Merkel model crash with failure on air flow ratio
  src/EnergyPlus/DataErrorTracking.hh
  src/EnergyPlus/UtilityRoutines.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/UtilityRoutines.unit.cc
Labels: Defect

#6940 Window shade control followup to #6421
  src/EnergyPlus/DaylightingManager.cc
  src/Transition/InputRulesFiles/Rules8-9-0-to-9-0-0.md
  testfiles/PurchAirWithDaylightingAndShadeControl.idf
Labels: DoNotPublish

#6922 Correct relative humidity control for CoilSystem:Cooling:DX when using variable speed DX cooling coils
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  src/EnergyPlus/HVACDXSystem.cc
  tst/EnergyPlus/unit/HVACDXSystem.unit.cc
Labels: Defect

#6968 Fix bug in input parser
  src/EnergyPlus/InputProcessing/IdfParser.cc
  tst/EnergyPlus/unit/InputProcessor.unit.cc
Labels: Defect, Priority1, S1 - High

#6975 Fix console messages on Windows with Schedule:File or other extra files
  src/EnergyPlus/UtilityRoutines.cc
  tst/EnergyPlus/unit/UtilityRoutines.unit.cc
Labels: Defect

#6900 Use setpoints averaged in a zone time step to calculate "hours of setpoint not met" with onoff thermostat
  src/EnergyPlus/DataHeatBalFanSys.cc
  src/EnergyPlus/DataHeatBalFanSys.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
Labels: Defect

#6979 Revert "Include accidental missed cleanup"
  src/EnergyPlus/OutAirNodeManager.cc
Labels: DoNotPublish

#6889 Remove some dangling limitations to the number of daylighting reference points
  src/EnergyPlus/DaylightingManager.cc
Labels: Defect

#6791 VRP fix D term application and Vou reporting
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SizingManager.cc
Labels: Defect

#6821 Fuel cell bug fixes
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/ElectricPowerServiceManager.hh
  src/EnergyPlus/FuelCellElectricGenerator.cc
  src/EnergyPlus/FuelCellElectricGenerator.hh
  src/EnergyPlus/Plant/PlantManager.cc
Labels: Defect

#6886 Incorrect minimum OA amount when the Minimum Limit Type is FixedMinimum
  src/EnergyPlus/MixedAir.cc
  tst/EnergyPlus/unit/MixedAir.unit.cc
Labels: Defect

#6942 Add check to not show component loads when only SizingPeriod:WeatherFileConditionType is used
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/SizingManager.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#6983 Final path to Version 9.0
  cmake/CMakeCPackOptions.cmake.in
  cmake/Install.cmake
  release/readme.html
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabularAnnual.cc
  src/EnergyPlus/ReportSizingManager.cc
  src/Transition/InputRulesFiles/Rules8-9-0-to-9-0-0.md
Labels: DoNotPublish

#6984 Update View3D
  bin/ViewFactorCalculation/View3D.exe
Labels: DoNotPublish

#6985 Fix missing workflow
  CMakeLists.txt
Labels: DoNotPublish

#6988 Fix os.path.joins in EnergyPlus workflow for EP-Launch
  workflows/energyplus.py
Labels: DoNotPublish

#6990 Sixth (and Final) Set of Engineering Reference Comprehensive Edits
  doc/engineering-reference/src/daylighting-and-window-calculations/window-calculation-module.tex
  doc/engineering-reference/src/economics-calculations/component-costs.tex
  doc/engineering-reference/src/economics-calculations/life-cycle-cost-computations.tex
  doc/engineering-reference/src/economics-calculations/tariff-computation.tex
  doc/engineering-reference/src/on-site-generation.tex
  doc/engineering-reference/src/on-site-generation/electric-load-center-distribution-manager.tex
  doc/engineering-reference/src/on-site-generation/generators.tex
  doc/engineering-reference/src/on-site-generation/photovoltaic-arrays.tex
  doc/engineering-reference/src/on-site-generation/whole-facility-electric-service.tex
  doc/engineering-reference/src/performance-curves-and-lookup-tables/performance-curves.tex
  doc/engineering-reference/src/performance-curves-and-lookup-tables/performance-tables.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/air-system-compound-component-groups.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/air-system-humidifiers.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/heat-exchangers.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/variable-refrigerant-flow-heat-pumps.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/centralheatpumpsystem.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/chillerheaterperformance-electric-eir.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/ideal-loads-air-system.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/indoor-swimming-pool.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/pipes.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/plant-temperature-source-component.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/pumps.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/zone-internal-gains.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-004/radiant-system-models.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-004/refrigeration-equipment.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-004/setpoint-managers.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-004/solar-collectors.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-004/system-availability-managers.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/occupant-thermal-comfort.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/trombe-walls.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/water-systems.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/water-thermal-tanks-includes-water-heaters.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/zone-controls.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/zone-equipment-and-zone-forced-air-units.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference/air-system-distribution-terminals.tex
  doc/engineering-reference/src/special-modules-reporting/environmental-impacts.tex
  doc/engineering-reference/src/special-modules-reporting/zone-component-loads-summary.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/ground-heat-transfer-calculations-using-site-001.tex
Labels: Defect, Documentation Sources, EnergyPlus
