Repository NREL/EnergyPlus, pull requests merged in 2018-02, with the labels that each got.

#6387 Additional Source Term in the Surface Heat Balance Calculation
  design/FY2018/NFP-Additional Source Term in the Exterior Surface Heat Balance.md
  doc/engineering-reference/src/surface-heat-balance-manager-processes/inside-heat-balance.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/outside-surface-heat-balance.tex
  doc/input-output-reference/src/overview/group-advanced-surface-concepts.tex
  idd/Energy+.idd.in
  src/EnergyPlus/DataHeatBalSurface.cc
  src/EnergyPlus/DataHeatBalSurface.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/HeatBalanceHAMTManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SurfaceGeometry.cc
  testfiles/CMakeLists.txt
  testfiles/SurfaceHeatSourceTerm_RefBldgSmallOfficeNew2004.idf
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
Labels: IDDChange, NewFeature

#6433 Document Fixes found for V8.8.0 of Documents
  doc/auxiliary-programs/src/calcsoilsurftemp-program/running-the-program.tex
  doc/auxiliary-programs/src/csvproc.tex
  doc/auxiliary-programs/src/ground-heat-transfer-in-energyplus/running-the-slab-program.tex
  doc/auxiliary-programs/src/parametric-spreadsheets/water-to-air-heat-pump-parameter-coefficient-001.tex
  doc/auxiliary-programs/src/parametric-spreadsheets/water-to-air-heat-pump-parameter-coefficient.tex
  doc/auxiliary-programs/src/parametric-spreadsheets/water-to-water-heat-pump-parameter.tex
  doc/auxiliary-programs/src/running-console-applications.tex
  doc/auxiliary-programs/src/technical-details-of-running-energyplus/energyplus-file-extensions.tex
  doc/auxiliary-programs/src/technical-details-of-running-energyplus/energyplus-files.tex
  doc/auxiliary-programs/src/weather-converter-program/advanced-use-accessing-weather-conversion.tex
  doc/auxiliary-programs/src/weather-converter-program/data-sources-uncertainty.tex
  doc/auxiliary-programs/src/weather-converter-program/using-the-weather-converter.tex
  doc/ems-application-guide/src/ems-examples/example-9-demand-management.tex
  doc/ems-application-guide/src/energyplus-runtime-language/expressions.tex
  doc/ems-application-guide/src/energyplus-runtime-language/variables.tex
  doc/ems-application-guide/src/internal-variables/on-site-electricity-production.tex
  doc/engineering-reference/src/advanced-surface-concepts/green-roof-model-ecoroof.tex
  doc/engineering-reference/src/advanced-surface-concepts/surfaceproperty-underwater.tex
  doc/engineering-reference/src/air-heat-balance-manager-processes/air-exchange.tex
  doc/engineering-reference/src/air-heat-balance-manager-processes/infiltration-ventilation.tex
  doc/engineering-reference/src/alternative-modeling-processes/airflownetwork-model.tex
  doc/engineering-reference/src/alternative-modeling-processes/hybrid-model.tex
  doc/engineering-reference/src/building-system-simulation-system-manager/air-path-components.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/occupant-thermal-comfort.tex
  doc/input-output-reference/src/overview/group-airflow-network.tex
  doc/input-output-reference/src/overview/group-location-climate-weather-file-access.tex
  doc/input-output-reference/src/overview/group-simulation-parameters.tex
  doc/input-output-reference/src/overview/group-surface-construction-elements.tex
Labels: Documentation Sources

#6430 IDD cleanup and other minor fixes for v8.9.0
  idd/Energy+.idd.in
  src/EnergyPlus/WaterManager.cc
Labels: Defect, IDDChange

#6463 Addressed Documentation Issues - April-August 2016
  datasets/ASHRAE_2005_HOF_Materials.idf
  doc/auxiliary-programs/src/technical-details-of-running-energyplus/ep-launch-program.tex
  doc/auxiliary-programs/src/weather-converter-program/energyplus-weather-file-epw-data-dictionary.tex
  doc/auxiliary-programs/src/weather-converter-program/weather-data-availability.tex
  doc/auxiliary-programs/src/weather-converter-program/web-resources.tex
  doc/engineering-reference/src/daylighting-and-window-calculations/window-heat-balance-calculation.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/combined-heat-and-moisture-transfer-hamt.tex
  doc/getting-started/src/other-useful-programs-information/datafiles.tex
  doc/getting-started/src/other-useful-programs-information/weatherdata.tex
  doc/input-output-reference/media/image205.png
  doc/input-output-reference/media/image206.png
  doc/input-output-reference/media/image275.png
  doc/input-output-reference/media/image276.png
  doc/input-output-reference/src/overview/group-air-distribution-equipment.tex
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  doc/input-output-reference/src/overview/group-location-climate-weather-file-access.tex
  doc/input-output-reference/src/overview/group-performance-curves.tex
  doc/input-output-reference/src/overview/group-surface-construction-elements.tex
  doc/input-output-reference/src/overview/group-system-availability-managers.tex
  doc/input-output-reference/src/overview/group-variable-refrigerant-flow-equipment.tex
  doc/tips-and-tricks-using-energyplus/src/general/what-energyplus-is.tex
  doc/tips-and-tricks-using-energyplus/src/input/creating-files-for-energyplus.tex
  doc/tips-and-tricks-using-energyplus/src/introduction-support.tex
  idd/Energy+.idd.in
  testfiles/AirflowNetwork_MultiZone_House.idf
  testfiles/AirflowNetwork_MultiZone_House_OvercoolDehumid.idf
  testfiles/AirflowNetwork_MultiZone_House_TwoSpeed.idf
  testfiles/AirflowNetwork_MultiZone_LocalNode.idf
  testfiles/AirflowNetwork_Simple_House.idf
  testfiles/SingleFamilyHouse_TwoSpeed_ZoneAirBalance.idf
Labels: IDDChange

#6452 Reduce external interface maximum variables
  src/EnergyPlus/ExternalInterface.cc
Labels: NotIDDChange

#6451 PVWatts
  design/FY2018/NFP_PVWatts.md
  design/FY2018/pvwatts_tracking.png
  doc/engineering-reference/src/on-site-generation/photovoltaic-arrays.tex
  doc/input-output-reference/media/pvwatts_tracking.png
  doc/input-output-reference/src/overview/group-electric-load-center-generator.tex
  idd/Energy+.idd.in
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/DataGlobalConstants.cc
  src/EnergyPlus/DataGlobalConstants.hh
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/ElectricPowerServiceManager.hh
  src/EnergyPlus/PVWatts.cc
  src/EnergyPlus/PVWatts.hh
  src/EnergyPlus/PVWattsSSC.cc
  src/EnergyPlus/PVWattsSSC.hh
  testfiles/CMakeLists.txt
  testfiles/Generator_PVWatts.idf
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/PVWatts.unit.cc
Labels: IDDChange, NewFeature

#6477 Use C++latest to get fallthrough
  src/EnergyPlus/General.cc
  src/EnergyPlus/PierceSurface.hh
  src/EnergyPlus/PlantPipingSystemsManager.cc
Labels: DoNotPublish

#6355 Fix time-stepping and exposed perimeter logic for Kiva foundations
  idd/Energy+.idd.in
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.hh
  src/EnergyPlus/SurfaceGeometry.cc
Labels: Defect, IDDChange

#6385 On/Off Thermostat
  design/FY2018/NFP-OnOffThermostat.md
  doc/input-output-reference/src/overview/group-zone-controls-thermostats.tex
  idd/Energy+.idd.in
  src/EnergyPlus/DataZoneControls.hh
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  testfiles/CMakeLists.txt
  testfiles/SingleFamilyHouse_TwoSpeed_CutoutTemperature.idf
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: IDDChange, NewFeature

#6393 New Feature - ASHRAE 90.1 SZVAV control for Packaged Terminal Units.
  design/FY2017/NFP-Single-Zone VAV Fan Control for PackagedTerminalUnits.md
  design/FY2017/UnitarySystem_SZVAV_watercoils.png
  doc/auxiliary-programs/src/weather-converter-program/definitions-file-custom-file-processing.tex
  doc/engineering-reference/media/PTUnit_SZVAV_FanControl.png
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/zone-equipment-and-zone-forced-air-units.tex
  doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
  idd/Energy+.idd.in
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACDXSystem.cc
  src/EnergyPlus/HVACDXSystem.hh
  src/EnergyPlus/HVACUnitarySystem.cc
  src/EnergyPlus/HVACUnitarySystem.hh
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/PackagedTerminalHeatPump.hh
  src/EnergyPlus/SZVAVModel.cc
  src/EnergyPlus/SZVAVModel.hh
  src/ExpandObjects/epfilter.f90
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/HVACHXAssistedCoolingCoil.unit.cc
  tst/EnergyPlus/unit/HVACUnitarySystem.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
Labels: IDDChange, NewFeature

#6483 Add Annual Reporting to OutputChanges document
  src/Transition/OutputRulesFiles/OutputChanges8-8-0-to-8-9-0.md
Labels: DoNotPublish, NotIDDChange

#6491 Eliminate fallthrough warnings on new GCC
  src/EnergyPlus/General.cc
  src/EnergyPlus/PierceSurface.hh
  src/EnergyPlus/PlantPipingSystemsManager.cc
Labels: DoNotPublish

#6440 #6438 zone hvac baseboard convective water ua sizing fails if plant water temp is too low
  src/EnergyPlus/BaseboardRadiator.cc
  tst/EnergyPlus/unit/BaseboardRadiator.unit.cc
  tst/EnergyPlus/unit/CMakeLists.txt
Labels: NotIDDChange

#6494 Single Character Documentation Equation Fix
  doc/input-output-reference/src/overview/group-performance-curves.tex
Labels: DoNotPublish

#6441 User file with PTHP has negative heating electricity
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DXCoils.hh
  src/EnergyPlus/StandardRatings.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/StandardRatings.unit.cc
Labels: NotIDDChange

#6496 Fixup a unit test
  tst/EnergyPlus/unit/BaseboardRadiator.unit.cc
Labels: DoNotPublish

#6462 Add MDotOA in CO2 and contaminant balance equations
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/ZoneContaminantPredictorCorrector.unit.cc
Labels: Defect, NotIDDChange
