Repository NREL/EnergyPlus, pull requests merged in 2019-06, with the labels that each got.

#7300 Correction of ACH Set to Zero for CeilingDiffuser Convection Model
  src/EnergyPlus/ConvectionCoefficients.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
Labels: Defect

#7320 Add a clear_state to DataStringGlobals to avoid problems when running unit tests serially (FiniteDiff)
  src/EnergyPlus/DataStringGlobals.hh
  src/EnergyPlus/DataStringGlobals.in.cc
  tst/EnergyPlus/unit/FiniteDifferenceGroundTemperatureModel.unit.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
Labels: Defect

#7321 Fix check_non_utf8.py and UTF-8 encoding some files that weren't
  scripts/dev/check_non_utf8.py
  src/EnergyPlus/DataPhotovoltaics.hh
  src/EnergyPlus/DataStringGlobals.in.cc
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.hh
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.hh
Labels: DoNotPublish

#7322 Plant component continued - without boilers
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.cc
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.hh
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.cc
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.hh
  src/EnergyPlus/OutsideEnergySources.cc
  src/EnergyPlus/OutsideEnergySources.hh
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  src/EnergyPlus/PlantValves.cc
  src/EnergyPlus/PlantValves.hh
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
Labels: Refactoring

#7313 Fix #7256: Linux sh installer is broken in 9.1.0
  cmake/CMakeCPackOptions.cmake.in
  cmake/CPack.STGZ_Header.sh.in
  cmake/CompilerFlags.cmake
  cmake/Install.cmake
Labels: Defect

#7304 EvapCooler crash with autosized field and no design days run
  src/EnergyPlus/EvaporativeCoolers.cc
  tst/EnergyPlus/unit/EvaporativeCoolers.unit.cc
Labels: Defect

#7293 Correct cont fan control logic and add unit test
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#7288 AirloopHVAC:UnitaryHeatCool:VAVChangeoverBypass incorrectly indexes zone loads
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
Labels: Defect

#7305 Incorrect EvaporativeCooler:Direct:ResearchSpecial water pump power modifier curve use
  src/EnergyPlus/EvaporativeCoolers.cc
  tst/EnergyPlus/unit/EvaporativeCoolers.unit.cc
Labels: Defect

#7207 Fix #7147: Error Flag (ErrorsFound) passed by reference is overriden to false in some functions
  .decent_ci-Linux.yaml
  scripts/dev/find_byref_bool_override.py
  src/EnergyPlus/BaseboardElectric.cc
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/BoilerSteam.cc
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/BranchInputManager.cc
  src/EnergyPlus/BranchInputManager.hh
  src/EnergyPlus/BranchNodeConnections.cc
  src/EnergyPlus/BranchNodeConnections.hh
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DataRuntimeLanguage.cc
  src/EnergyPlus/DataRuntimeLanguage.hh
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/FanCoilUnits.hh
  src/EnergyPlus/FuelCellElectricGenerator.hh
  src/EnergyPlus/GlobalNames.cc
  src/EnergyPlus/GlobalNames.hh
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HVACControllers.hh
  src/EnergyPlus/HVACFourPipeBeam.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/IntegratedHeatPump.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/NodeInputManager.cc
  src/EnergyPlus/NodeInputManager.hh
  src/EnergyPlus/PackagedThermalStorageCoil.cc
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/PlantPressureSystem.cc
  src/EnergyPlus/PlantUtilities.cc
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/SteamCoils.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/UserDefinedComponents.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterToAirHeatPump.cc
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneEquipmentManager.hh
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
Labels: Defect

#7316 Fix #7310: ReadVarsEso launched from energyplus commandline does not work for folders with spaces in path
  src/EnergyPlus/EnergyPlusPgm.cc
  src/EnergyPlus/FileSystem.cc
  src/EnergyPlus/FileSystem.hh
Labels: Defect

#7331 Fixed the EcoRoof documentation issue #4416
  doc/engineering-reference/src/advanced-surface-concepts/green-roof-model-ecoroof.tex
  doc/input-output-reference/src/overview/group-surface-construction-elements.tex
Labels: Defect

#7333 Coil:Heating:Desuperheater continually updates water inlet temperature during iterations causing high water tank energy use.
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterThermalTanks.hh
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Defect

#7329 Plant component continued with boilers
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/Boilers.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/BoilerHotWater.unit.cc
Labels: Refactoring

#7366 Fix issue #5274 - Documentation for ComponentCost:LineItem
  doc/input-output-reference/src/energyplus-economics/cost-estimating.tex
Labels: Defect

#7358 Plant component refactor continued: fluid coolers
  src/EnergyPlus/FluidCoolers.cc
  src/EnergyPlus/FluidCoolers.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/FluidCoolers.unit.cc
Labels: Refactoring

#7349 Fix Issue #6650 - Better documentation for Counter Flow vs Parallel flow coil parameter
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/heat-exchangers.tex
  doc/input-output-reference/src/overview/group-condenser-equipment.tex
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
Labels: Defect

#7343 Fix windows line endings problem
  src/.editorconfig
  tst/.editorconfig
Labels: DoNotPublish

#7340 Removed Repeated I/O Reference Section on FC Factor Method
  doc/input-output-reference/src/overview/group-surface-construction-elements.tex
Labels: Defect, Documentation
