Repository NREL/EnergyPlus, pull requests merged in 2019-11, with the labels that each got.

#7566 MicroTurbine Generator Plant Comp Refactor
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/MicroturbineElectricGenerator.cc
  src/EnergyPlus/MicroturbineElectricGenerator.hh
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/ChillerExhaustAbsorption.unit.cc
Labels: Refactoring

#7554 Ice Thermal Storage Plant Comp Refactor
  src/EnergyPlus/IceThermalStorage.cc
  src/EnergyPlus/IceThermalStorage.hh
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/IceThermalStorage.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
Labels: Refactoring

#7564 IC Electric Generator Plant Comp Refactor
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/ICEngineElectricGenerator.cc
  src/EnergyPlus/ICEngineElectricGenerator.hh
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
Labels: Refactoring

#7603 Input file conversion utility
  CMakeLists.txt
  scripts/Epl-run.bat
  src/ConvertInputFormat/CMakeLists.txt
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/DataGlobals.cc
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/EnergyPlusPgm.cc
  src/EnergyPlus/FileSystem.cc
  src/EnergyPlus/InputProcessing/IdfParser.hh
  src/EnergyPlus/InputProcessing/InputProcessor.cc
Labels: NewFeature

#7568 MicroCHP Gen Plant Comp Refactor
  src/EnergyPlus/DataGenerators.cc
  src/EnergyPlus/DataGenerators.hh
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/GeneratorDynamicsManager.cc
  src/EnergyPlus/MicroCHPElectricGenerator.cc
  src/EnergyPlus/MicroCHPElectricGenerator.hh
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
Labels: Refactoring

#7598 Evaporative Fluid Coolers Plant Comp Refactor
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/EvaporativeFluidCoolers.cc
  src/EnergyPlus/EvaporativeFluidCoolers.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/EvaporativeCoolers.unit.cc
Labels: Refactoring

#7559 Combustion Turbine Generator Plant Comp Refactor
  src/EnergyPlus/CTElectricGenerator.cc
  src/EnergyPlus/CTElectricGenerator.hh
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
Labels: Refactoring

#7535 NFP for HAMT Enhancements Part 1
  design/FY2019/NFP-HAMT-Enhancements-Pt1.md
Labels: NewFeature

#7495 Corrected MultiSpeed DX Cooling Coil sizing variable names and capacity reporting issues
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DXCoils.hh
  src/EnergyPlus/UnitarySystem.cc
  src/Transition/OutputRulesFiles/OutputChanges9-2-0-to-9-3-0.md
  tst/EnergyPlus/unit/DXCoils.unit.cc
Labels: Defect

#7624 Addressed broken No Load Supply Air Flow Rate sizing methods in Unitary System
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#7634 Solar Collector Plant Comp Refactor
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  src/EnergyPlus/PlantUtilities.cc
  src/EnergyPlus/SolarCollectors.cc
  src/EnergyPlus/SolarCollectors.hh
  tst/EnergyPlus/unit/ICSCollector.unit.cc
Labels: Refactoring
