Repository NREL/EnergyPlus, pull requests merged in 2019-02, with the labels that each got.

#7141 Cleanup and Refactoring
  src/EnergyPlus/DataLoopNode.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/Plant/Branch.hh
  src/EnergyPlus/Plant/LoopSide.hh
  src/EnergyPlus/Plant/PlantLoopSolver.cc
  src/EnergyPlus/Plant/PlantLoopSolver.hh
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/Plant/PlantManager.hh
  src/EnergyPlus/PlantCondLoopOperation.cc
  src/EnergyPlus/PlantCondLoopOperation.hh
  src/EnergyPlus/PlantUtilities.cc
  src/EnergyPlus/PlantUtilities.hh
  src/EnergyPlus/PlantValves.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/PlantUtilities.unit.cc
Labels: Refactoring

#7148 Add support for QtIFW/Mac packaging
  cmake/Install.cmake
Labels: DoNotPublish

#7091 Fix #6445 - Avoid problems when PlantCentralGSHP's ChillerHeater Reference Evaporator Capacity is autosized
  src/EnergyPlus/PlantCentralGSHP.cc
  src/EnergyPlus/PlantCentralGSHP.hh
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/PlantCentralGSHP.unit.cc
Labels: Defect

#7074 CMake bug fixes including shipping AppGPostProcess
  .decent_ci-MacOS.yaml
  .gitignore
  CMakeLists.txt
  cmake/ProjectMacros.cmake
  src/AppGPostProcess/CMakeLists.txt
Labels: AppGPostProcess, Defect

#7158 Fix missed configure for new idd and report vars file
  CMakeLists.txt
Labels: DoNotPublish

#7159 Make the output variable parser script recurse through the source dirs
  doc/tools/parse_output_variables.py
Labels: Defect

#7163 Move array and allocate flag to namespace and include in clear_state
  .gitignore
  src/EnergyPlus/ZoneEquipmentManager.cc
Labels: DoNotPublish

#7025 Fix Zone Equipment Load Distribution
  src/EnergyPlus/DataHVACGlobals.cc
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Defect

#7180 Remove duplicate call to GetHybridModelZone
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
Labels: DoNotPublish

#7194 Fix Plant Piping System Argument Order Problem
  src/EnergyPlus/PlantLoopEquip.cc
Labels: Defect

#7192 Hotfix: GatherHeatEmissionReport fails when you have refrigeration objects after #7040
  src/EnergyPlus/OutputReportTabular.cc
Labels: DoNotPublish
