Repository NREL/EnergyPlus, pull requests merged in 2019-05, with the labels that each got.

#7261 Exterior vertical foundation insulation was sometimes assigned to multiple Kiva surfaces
  third_party/kiva-ep/src/libkiva/Domain.cpp
  third_party/kiva-ep/src/libkiva/Domain.hpp
  third_party/kiva-ep/src/libkiva/Foundation.cpp
  third_party/kiva-ep/test/unit/CMakeLists.txt
  third_party/kiva-ep/test/unit/fixtures/base-fixture.hpp
  third_party/kiva-ep/test/unit/fixtures/foundation-fixture.hpp
  third_party/kiva-ep/test/unit/fixtures/typical-fixture.hpp
  third_party/kiva-ep/test/unit/foundation.unit.cpp
Labels: Defect, NotIDDChange

#7262 Relax Kiva weighting checks
  src/EnergyPlus/HeatBalanceKivaManager.cc
  third_party/kiva-ep/src/libkiva/Aggregator.cpp
  third_party/kiva-ep/src/libkiva/Functions.cpp
  third_party/kiva-ep/src/libkiva/Functions.hpp
  third_party/kiva-ep/test/unit/foundation.unit.cpp
Labels: Defect, NotIDDChange

#7258 AirloopHVAC:UnitarySystem control type = SingleZoneVAV crashes with autosized water coils
  src/EnergyPlus/SZVAVModel.cc
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#7278 Use source mass flow rate in unmet energy calculation on stratified tank
  src/EnergyPlus/WaterThermalTanks.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Defect

#7295 Correct physics based VRF model to align inlet and outlet air flow rates
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/variable-refrigerant-flow-heat-pumps.tex
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#7301 Additional Warnings for Thermal Comfort Schedules
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/InternalHeatGains.hh
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
Labels: Defect

#7268 Correct VRF system model to use both capacity and EIR boundary curves for evaluating performance
  doc/input-output-reference/src/overview/group-variable-refrigerant-flow-equipment.tex
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect, PriorityHigh

#7214 Fix #7213: encode all IDF/IMF files as UTF-8, and add ci script to check encoding.
  .decent_ci-Linux.yaml
  performance_tests/15zonePSZ.idf
  performance_tests/15zonePTAC.idf
  performance_tests/15zonePVAV.idf
  performance_tests/15zonevav.idf
  performance_tests/15zonevav_no_reports.idf
  performance_tests/30zonePSZ.idf
  performance_tests/30zonePTAC.idf
  performance_tests/30zonePVAV.idf
  performance_tests/30zonevav.idf
  performance_tests/45zonePSZ.idf
  performance_tests/45zonePTAC.idf
  performance_tests/45zonePVAV.idf
  performance_tests/45zonevav.idf
  performance_tests/BenchmarkHospitalNew_USA_CA_SAN_FRANCISCO.idf
  performance_tests/BenchmarkLargeOfficeNew_USA_CA_SAN_FRANCISCO_10_windows_per_zone.idf
  performance_tests/Benchmarklargeofficenew_usa_ca_san_francisco_no_reports.idf
  performance_tests/Inactive/benchmarklargeofficenew_usa_ca_san_francisco.idf
  scripts/dev/verify_file_encodings.py
  testfiles/AbsorptionChiller_Macro.imf
  testfiles/AirflowNetwork_MultiAirLoops.idf
  testfiles/AirflowNetwork_PressureControl.idf
Labels: Defect

#7247 Fix #7082 - Site:GroundTemperature:Undisturbed:FiniteDifference results in crash
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc
  tst/EnergyPlus/unit/FiniteDifferenceGroundTemperatureModel.unit.cc
Labels: Defect

#7274 Fix daylighting for BSDF complex fenestration with shading layer
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/TarcogShading.cc
  testfiles/CmplxGlz_Daylighting_SouthVB45deg.idf
  testfiles/CmplxGlz_Daylighting_SouthVerticalVB45deg.idf
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
Labels: Defect

#7317 Temporarily disable finite diff tests to clean up unit test issue
  tst/EnergyPlus/unit/FiniteDifferenceGroundTemperatureModel.unit.cc
Labels: DoNotPublish
