Repository NREL/EnergyPlus, pull requests merged in 2019-07, with the labels that each got.

#7351 Fixed ASHRAE9012016 ApartmentMidSize and OutpatientHealthCare Test files
  testfiles/ASHRAE9012016_ApartmentMidRise_Denver.idf
  testfiles/ASHRAE9012016_OutPatientHealthCare_Denver.idf
  testfiles/CMakeLists.txt
Labels: Defect, Transitions

#7280 Correct load accounting for AirloopHVAC:UnitarySystem when used as zone equipment
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#7307 Modification of Thermal Comfort Setpoints Documentation to Clarify Air Conditions Used
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  doc/input-output-reference/src/overview/group-zone-controls-thermostats.tex
Labels: Defect

#7368 Update CI Package Generators
  .decent_ci-Linux.yaml
  .decent_ci-MacOS.yaml
  .decent_ci-Windows.yaml
  doc/tools/create_changelog.py
Labels: DoNotPublish

#7373 Bug Fix (Linux Build Warning) to WeatherManager.cc
  src/EnergyPlus/WeatherManager.cc
Labels: Defect

#7267 Streamline ManageSurfaceHeatBalance - Part 1
  design/FY2019/Streamline ManageSurfaceHeatBalance.md
  src/EnergyPlus/DataHeatBalSurface.cc
  src/EnergyPlus/DataHeatBalSurface.hh
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Performance

#7389 Fixed Read Vars compiler warnings on Mac
  src/ReadVars/ReadVarsESO.f90
Labels: Defect

#7235 Fix #7225 - Add Year field in SQL for DaylightMapHourlyReports
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/SQLiteProcedures.cc
  src/EnergyPlus/SQLiteProcedures.hh
  tst/EnergyPlus/unit/SQLite.unit.cc
Labels: Defect

#7084 Reference to trackSorageOpMeterName_ correction
  src/EnergyPlus/ElectricPowerServiceManager.cc
Labels: Defect

#7338 Fix #7328 - Crash if AFN zone doesn't have inlet or return node connection
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: Defect

#7387 Addressed SurfaceControl:MovableInsulation doesn't catch wrong Material types
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/HeatBalanceMovableInsulation.unit.cc
Labels: Defect

#7390 Refined fix for readvars
  src/ReadVars/ReadVarsESO.f90
Labels: DoNotPublish

#7357 Construction:WindowEquivalentLayer using invalid layer material fatal out with error message
  src/EnergyPlus/HeatBalanceManager.cc
  tst/EnergyPlus/unit/WindowEquivalentLayer.unit.cc
Labels: Defect

#7393 A couple CI fixups
  .decent_ci-Windows.yaml
  doc/tools/create_changelog.py
Labels: DoNotPublish

#7403 Fixed spelling of "point" in three files.
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/WindowAC.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
Labels: Defect

#7356 Fix #7346 - AirLoop/Facility Component Load Summary can apply conversion to IP twice
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#7386 Unit Ventilator Variable Fraction OA Control Correction and Fix Fan Mode Schedule with Fan:SystemModel
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/zone-equipment-and-zone-forced-air-units.tex
  doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UnitVentilator.hh
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/UnitVentilator.unit.cc
Labels: Defect
