Repository NREL/EnergyPlus, pull requests merged in 2019-01, with the labels that each got.

#7068 Use RunPeriod names in error messages and use right array for SizingPeriod:WeatherFileXXX
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/WeatherManager.cc
  tst/EnergyPlus/unit/ReportSizingManager.unit.cc
  tst/EnergyPlus/unit/RunPeriod.unit.cc
Labels: Defect

#7116 Compiler warnings
  src/EnergyPlus/InputProcessing/IdfParser.cc
  third_party/ObjexxFCL/src/ObjexxFCL/ubyte.hh
Labels: DoNotPublish

#7120 Fixes a few straggling compiler warnings
  third_party/ObjexxFCL/src/ObjexxFCL/Format.hh
Labels: DoNotPublish

#7079 Input Verification And Results Summary: handle "Not Part of Total" Zones correctly
  doc/output-details-and-examples/src/output-files/eplustbl-lt-ext-gt.tex
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/Fixtures/SQLiteFixture.hh
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
Labels: Defect, OutputChange

#7072 Update error handling in SizeTower and SurfaceGeometry
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/CondenserLoopTowers.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect
