Repository NREL/EnergyPlus, pull requests merged in 2020-05, with the labels that each got.

#7848 Refactor PlantChillers
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/PlantChillers.hh
  tst/EnergyPlus/unit/ChillerElectric.unit.cc
  tst/EnergyPlus/unit/PlantChillers.unit.cc
Labels: Refactoring

#7959 Clean up compiler warnings from GCC 9.3
  cmake/CompilerFlags.cmake
  third_party/ObjexxFCL/CMakeLists.txt
  third_party/Windows-CalcEngine/cmake/WCECompilerFlags.cmake
  third_party/eigen/CMakeLists.txt
  third_party/penumbra/cmake/compiler-flags.cmake
Labels: DoNotPublish

#7962 Clean a few things in the plugin manager
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PluginManager.hh
Labels: DoNotPublish

#7967 Mute unrecognized warnings so we can still emit them on newer compilers
  cmake/CompilerFlags.cmake
Labels: DoNotPublish

#7900 Reduce build time for Fortran
  .decent_ci-Linux.yaml
  .decent_ci-MacOS.yaml
  .decent_ci-Windows.yaml
  src/Transition/CMakeLists.txt
Labels: DoNotPublish

#7964 Fix Zone Component Loads Report delayed component calculation and correct row for Kiva surfaces
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  testfiles/5ZoneAirCooled.idf
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#7979 Windows installer always register ocx files
  cmake/qtifw/install_win_copydll.qs
Labels: Defect

#7946 Miscellaneous CondFD Engineering Ref Clean Up
  doc/engineering-reference/src/surface-heat-balance-manager-processes/conduction-finite-difference-solution.tex
  doc/header.tex
Labels: Documentation

#7965 Global exterior energy
  src/EnergyPlus/BaseboardElectric.hh
  src/EnergyPlus/BaseboardRadiator.hh
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/ExteriorEnergyUse.cc
  src/EnergyPlus/ExteriorEnergyUse.hh
  src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.hh
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/InternalHeatGains.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/api/EnergyPlusPgm.cc
  src/EnergyPlus/api/EnergyPlusPgm.hh
  src/EnergyPlus/api/runtime.cc
  src/EnergyPlus/main.cc
  src/EnergyPlus/test_ep_as_library.cc
  tst/EnergyPlus/unit/ExteriorEnergyUse.unit.cc
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
Labels: Refactoring

#7971 Convert misc formats from gio
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/BranchInputManager.cc
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/DXFEarClipping.cc
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/DataStringGlobals.hh
  src/EnergyPlus/DataStringGlobals.in.cc
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/EvaporativeFluidCoolers.cc
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/FluidCoolers.cc
  src/EnergyPlus/General.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACSizingSimulationManager.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.cc
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.cc
  src/EnergyPlus/InputProcessing/IdfParser.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/OutputFiles.cc
  src/EnergyPlus/OutputFiles.hh
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/PlantCentralGSHP.cc
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/PlantPipingSystemsManager.cc
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/RuntimeLanguageProcessor.hh
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SolarCollectors.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/TARCOGArgs.cc
  src/EnergyPlus/UserDefinedComponents.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/UtilityRoutines.hh
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/api/EnergyPlusPgm.cc
  src/EnergyPlus/api/EnergyPlusPgm.hh
  tst/EnergyPlus/unit/OutputFiles.unit.cc
Labels: Refactoring

#7919 Addressed idle/noload air flow rate for variable and multi speed coils of unitary system
  doc/input-output-reference/src/overview/group-unitary-equipment.tex
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#7948 Addressed HeatExchanger:AirToAir:SensibleAndLatent negative effectiveness and sizing
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/HeatRecovery.hh
  src/EnergyPlus/ReportSizingManager.cc
  tst/EnergyPlus/unit/HeatRecovery.unit.cc
Labels: Defect

#7985 Revert "Reduce build time for Fortran"
  .decent_ci-Linux.yaml
  .decent_ci-MacOS.yaml
  .decent_ci-Windows.yaml
  src/Transition/CMakeLists.txt
Labels: DoNotPublish

#7972 Convert outputreports from gio
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/DataStringGlobals.hh
  src/EnergyPlus/DataStringGlobals.in.cc
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/OutputFiles.cc
  src/EnergyPlus/OutputFiles.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/OutputReports.hh
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/UtilityRoutines.cc
Labels: Refactoring

#7968 Global Boilers and Chillers
  src/EnergyPlus/BoilerSteam.cc
  src/EnergyPlus/BoilerSteam.hh
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/Boilers.hh
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerAbsorption.hh
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerElectricEIR.hh
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerExhaustAbsorption.hh
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.hh
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/ChillerIndirectAbsorption.hh
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/ChillerReformulatedEIR.hh
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/CostEstimateManager.hh
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/ExteriorEnergyUse.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/OutputProcessor.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/Plant/Component.hh
  src/EnergyPlus/Plant/DataPlant.hh
  src/EnergyPlus/Plant/LoopSide.hh
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/Plant/PlantManager.hh
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/PlantChillers.hh
  src/EnergyPlus/PlantComponent.hh
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/ReportCoilSelection.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/StandardRatings.cc
  src/EnergyPlus/StandardRatings.hh
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/BoilerHotWater.unit.cc
  tst/EnergyPlus/unit/BoilerSteam.unit.cc
  tst/EnergyPlus/unit/ChillerAbsorption.unit.cc
  tst/EnergyPlus/unit/ChillerConstantCOP.unit.cc
  tst/EnergyPlus/unit/ChillerElectric.unit.cc
  tst/EnergyPlus/unit/ChillerElectricEIR.unit.cc
  tst/EnergyPlus/unit/ChillerExhaustAbsorption.unit.cc
  tst/EnergyPlus/unit/ChillerGasAbsorption.unit.cc
  tst/EnergyPlus/unit/ChillerIndirectAbsorption.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/PlantChillers.unit.cc
  tst/EnergyPlus/unit/StandardRatings.unit.cc
Labels: Refactoring

#7987 #7809 - Floating-point error when summing Daylighting Zone Fractions
  src/EnergyPlus/DaylightingManager.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
Labels: Defect, NotIDDChange, OutputChange

#7821 Add Report of SEER calculated using the user specified PLF curve and default AHRI curve and C_D
  doc/input-output-reference/src/standard-output-reports/output-table-summaryreports.tex
  doc/output-details-and-examples/src/output-files/eplusout-eio.tex
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportPredefined.hh
  src/EnergyPlus/StandardRatings.cc
  src/EnergyPlus/StandardRatings.hh
  tst/EnergyPlus/unit/StandardRatings.unit.cc
Labels: NewFeature, OutputChange

#7992 Use std::vector instead of std::array
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
Labels: DoNotPublish

#7991 Small fixes
  .decent_ci-Windows.yaml
  src/EnergyPlus/SimulationManager.cc
Labels: DoNotPublish

#7990 Correction of Crash in Indoor Pool Model Related to Improper Surface Reference
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  src/EnergyPlus/DataSurfaceLists.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/SwimmingPool.hh
  src/EnergyPlus/VentilatedSlab.cc
  tst/EnergyPlus/unit/SwimmingPool.unit.cc
Labels: Defect

#7947 Refactor RezeroZoneSizingArrays
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: DoNotPublish, Refactoring

#7966 Address error in water consumption calculation in evap cooled Chiller:Electric:EIR
  src/EnergyPlus/ChillerElectricEIR.cc
  testfiles/CMakeLists.txt
  testfiles/ElectricEIRChiller_EvapCooledCondenser.idf
  tst/EnergyPlus/unit/ChillerElectricEIR.unit.cc
Labels: Defect

#7941 Allow ExteriorScreen used in EMS Window Shading Control
  doc/ems-application-guide/src/ems-actuators/thermal-envelope.tex
  src/EnergyPlus/EMSManager.cc
  tst/EnergyPlus/unit/EMSManager.unit.cc
Labels: Defect

#7890 Fix ASHRAE simple method for vertical surfaces
  src/EnergyPlus/ConvectionCoefficients.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
Labels: Defect, NotIDDChange

#7934 #7902 - Fix inappopriate severe error: Heater Control Type for WaterHeater:Stratified must be CYCLE
  src/EnergyPlus/Untitled.ipynb
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterThermalTanks.hh
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Defect, NotIDDChange

#7736 Fix radiation variable outputs
  tst/EnergyPlus/unit/Resources/WeatherManagerIROutputTest.epw
  tst/EnergyPlus/unit/WeatherManager.unit.cc
Labels: Defect

#7886 Eliminate double counting of fan heat for water cooling coils
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/ReportSizingManager.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/WaterCoils.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#7874 Fix optimum start to not override thermostat post-occupancy
  src/EnergyPlus/SystemAvailabilityManager.cc
  testfiles/OptimalStart_RefBldgLargeOfficeNew2004_Chicago.idf
  tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc
Labels: Defect

#7860 Use hg to report latent load instead of hfg in AirflowNetwork
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  testfiles/AirflowNetwork_MultiAirLoops.idf
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: Defect

#7894 Correct VS coil operation with HX
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  tst/EnergyPlus/unit/HVACHXAssistedCoolingCoil.unit.cc
Labels: Defect

#7956 Remove FlowLock From Pond GHE
  src/EnergyPlus/PondGroundHeatExchanger.cc
  src/EnergyPlus/PondGroundHeatExchanger.hh
Labels: Defect, Refactoring

#7983 Fix identity matrix for diffuse solar exchange factors between zones
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
Labels: Defect

#8005 Prelude to #7388 - dependency bump for nlohmann json and valijson
  src/EnergyPlus/InputProcessing/InputValidation.cc
  third_party/PATCHES.md
  third_party/nlohmann/json.hpp
  third_party/nlohmann/json373.patch
  third_party/valijson/valijson/constraints/concrete_constraints.hpp
  third_party/valijson/valijson/internal/json_pointer.hpp
  third_party/valijson/valijson/validation_visitor.hpp
  third_party/valijson/valijson/valijson.patch
  tst/EnergyPlus/unit/RunPeriod.unit.cc
Labels: DoNotPublish
