Repository NREL/EnergyPlus, pull requests merged in 2020-02, with the labels that each got.

#7714 Fix HeatPump:PlantLoop:EIR:Heating/Cooling PLR Curve Name
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Defect

#7724 7640 remove a wrong error message
  src/EnergyPlus/SimulationManager.cc
  testfiles/CMakeLists.txt
  testfiles/MultispeedHeatPump_DirectSolution.idf
  tst/EnergyPlus/unit/SimulationManager.unit.cc
Labels: Defect

#7717 #7711 - Fix crash when using both WaterHeat:HeatPump:PumpedCondenser and WaterHeater:HeatPump:WrappedCondenser
  src/EnergyPlus/WaterThermalTanks.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Defect, NotIDDChange

#7672 Fix custom meter error with zone mechanical ventilation and airloop variables
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SystemReports.cc
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Defect

#7755 Fix Missed PsyCpAirFnWTb Calls
  doc/ems-application-guide/src/energyplus-runtime-language/built-in-functions.tex
  doc/engineering-reference/src/integrated-solution-manager/basis-for-the-zone-and-air-system-integration.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/zone-equipment-and-zone-forced-air-units.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference/air-system-distribution-terminals.tex
  doc/module-developer/src/energyplus-services/psychrometric-services.tex
  doc/module-developer/src/module-structure/module-example.tex
  src/EnergyPlus/DataRuntimeLanguage.cc
  src/EnergyPlus/DataRuntimeLanguage.hh
  src/EnergyPlus/EvaporativeFluidCoolers.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  src/EnergyPlus/Psychrometrics.hh
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  testfiles/1ZoneDataCenterCRAC_wApproachTemp.idf
  testfiles/1ZoneDataCenterCRAC_wPumpedDXCoolingCoil.idf
  testfiles/EMSTestMathAndKill.idf
  testfiles/EMSUserDefined5ZoneAirCooled.idf
  testfiles/EMSUserDefinedWindACAuto.idf
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/EMSManager.unit.cc
  tst/EnergyPlus/unit/HVACUnitarySystem.unit.cc
  tst/EnergyPlus/unit/Psychrometrics.unit.cc
Labels: DoNotPublish

#7778 Fix formatting warnings and also formatting checker
  scripts/dev/verify_file_formatting.sh
  tst/EnergyPlus/unit/Psychrometrics.unit.cc
Labels: DoNotPublish

#7772 Redefine Trim* and Round* functions in terms of {fmt}
  src/EnergyPlus/General.cc
Labels: Refactoring

#7734 Make HeatPump:* Output Variable Names Consistent
  doc/input-output-reference/src/overview/group-plant-equipment.tex
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.cc
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.cc
  src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
  testfiles/GSHP-GLHE.idf
  testfiles/GSHP-GLHE.rvi
  testfiles/GSHP-Slinky.idf
  testfiles/GSHPSimple-GLHE.idf
  testfiles/GSHPSimple-GLHE.rvi
  testfiles/PlateHeatExchanger.idf
  testfiles/PlateHeatExchanger.rvi
  testfiles/WWHPSimpleAuto.idf
Labels: OutputChange, Refactoring

#7743 Add outputs of eio and warning for PerformancePrecisionTradeoffs
  src/EnergyPlus/SimulationManager.cc
  src/Transition/OutputRulesFiles/OutputChanges9-2-0-to-9-3-0.md
  testfiles/CarrollMRT-RefBldgLargeOfficeNew2004_Chicago.idf
  tst/EnergyPlus/unit/SimulationManager.unit.cc
Labels: Defect, OutputChange

#7787 Use common sizing routines for sizing DX Coil SHR
  src/EnergyPlus/DXCoils.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
Labels: Defect

#7785 Coil refactor baseline - add new unitarysystem testfiles plus one bugfix
  src/EnergyPlus/DXCoils.cc
  testfiles/CMakeLists.txt
  testfiles/UnitarySystem_MultiSpeedDX.idf
  testfiles/UnitarySystem_SingleSpeedDX.idf
  testfiles/UnitarySystem_TwoSpeedDX.idf
  testfiles/UnitarySystem_TwoStageDX.idf
  testfiles/UnitarySystem_TwoStageDXWithHumidityControl.idf
  testfiles/UnitarySystem_VSCoolingCoil.idf
Labels: Refactoring

#7741 Fix Floating Point Precision Errors Caused by Unit Systems on Output:Table:SummaryReports AirLoopComponentLoadSummary Table
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect, OutputChange

#7794 Fix incorrect "other" row ABUPS end-used by subcategory table
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/Transition/OutputRulesFiles/OutputChanges9-2-0-to-9-3-0.md
  testfiles/UnitarySystem_TwoSpeedDX.idf
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Defect, OutputChange

#7801 Add Transition Rules for EMS @CpAirFnWTdb to @CpAirFnW
  src/Transition/CreateNewIDFUsingRulesV9_3_0.f90
  src/Transition/InputRulesFiles/Rules9-2-0-to-9-3-0.md
Labels: DoNotPublish
