Repository NREL/EnergyPlus, pull requests merged in 2020-08, with the labels that each got.

#8177 Correct fan heat accounting for multiple air loops
  src/EnergyPlus/ReportSizingManager.cc
Labels: Defect

#7928 Make latent Degradation work for Variable Speed DX coil in Coil System
  src/EnergyPlus/HVACDXSystem.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  tst/EnergyPlus/unit/HVACDXSystem.unit.cc
Labels: Defect

#8170 Enhancement of Low Temperature Radiant Models to Allow Multi-Zone Systems
  design/FY2020/NFPfy20-MultiZoneRadSys.md
  doc/input-output-reference/src/overview/group-radiative-convective-units.tex
  src/EnergyPlus/DataSurfaceLists.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/LowTempRadiantSystem.hh
  testfiles/CMakeLists.txt
  testfiles/RadLoTempHydrHeatCoolMultiZone.idf
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
Labels: NewFeature

#8179 Move unit tests to use EnergyPlusFixture and remove redundant ShowMessage statements
  tst/EnergyPlus/unit/DataSurfaces.unit.cc
  tst/EnergyPlus/unit/EvaporativeCoolers.unit.cc
  tst/EnergyPlus/unit/General.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/PierceSurface.unit.cc
  tst/EnergyPlus/unit/SimAirServingZones.unit.cc
  tst/EnergyPlus/unit/SizingManager.unit.cc
  tst/EnergyPlus/unit/SortAndStringUtilities.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
  tst/EnergyPlus/unit/Vector.unit.cc
  tst/EnergyPlus/unit/Vectors.unit.cc
  tst/EnergyPlus/unit/WindowLayerEffectiveMultipliers.unit.cc
Labels: DoNotPublish

#8156 Transition away blank Ouput:Table:SummaryReport report names in v8.8 to v8.9 transition
  src/Transition/CreateNewIDFUsingRulesV8_9_0.f90
  src/Transition/OutputRulesFiles/OutputChanges8-8-0-to-8-9-0.md
Labels: Defect

#8085 Allow for simulation of TDDs without Daylighting:Controls objects
  src/EnergyPlus/DaylightingManager.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
Labels: Defect, NotIDDChange

#8086 Suggested hooks for Spawn
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/DataGlobals.cc
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/HeatBalanceAirManager.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/api/EnergyPlusAPI.h
  src/EnergyPlus/api/runtime.cc
  src/EnergyPlus/api/runtime.h
  src/EnergyPlus/api/runtime.py
  tst/EnergyPlus/api/TestRuntime.c
Labels: DoNotPublish

#8003 #7896 - FaultPropertiesAirFilter::CheckFaultyAirFilterFanCurve is called before sizing occurs
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/FaultsManager.cc
  tst/EnergyPlus/unit/FaultsManager.unit.cc
Labels: Defect

#8182 Bypass interior solar distribution calculation at night
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
Labels: Performance

#8178 Avoid using DataStringConstants::NL whenever possible and trust OS
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/InputProcessing/IdfParser.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/UtilityRoutines.cc
  third_party/ObjexxFCL/src/ObjexxFCL/char.constants.cc
  third_party/ObjexxFCL/src/ObjexxFCL/char.constants.hh
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.hh
Labels: Defect

#8181 Fix #8155 - Improve API type checking and error handling, and produce Python traceback for Plugin
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PythonLibWrapper.cc
  src/EnergyPlus/PythonLibWrapper.hh
  src/EnergyPlus/api/common.py
  src/EnergyPlus/api/datatransfer.py
  tst/EnergyPlus/api/test_DataTransferTypes.py
Labels: Defect, NotIDDChange

#8157 WeatherManager clean up
  scripts/dev/find_byref_bool_override.py
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  tst/EnergyPlus/unit/WeatherManager.unit.cc
Labels: Refactoring

#8152 Add interior surface sections to Envelope Summary Report
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportPredefined.hh
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: NewFeature, OutputChange

#8215 Fix logic issue in special day calculation
  src/EnergyPlus/WeatherManager.cc
Labels: DoNotPublish

#8094 8093 error callback
  src/EnergyPlus/DataGlobals.cc
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/api/TypeDefs.h
  src/EnergyPlus/api/func.cc
  src/EnergyPlus/api/func.h
  src/EnergyPlus/api/func.py
  src/EnergyPlus/api/runtime.cc
  src/EnergyPlus/api/runtime.h
  tst/EnergyPlus/api/TestFunctional.c
  tst/EnergyPlus/api/TestFunctional.py
  tst/EnergyPlus/api/TestRuntime.c
  tst/EnergyPlus/api/TestRuntime.py
Labels: APIChange, DoNotPublish

#8172 Fix #8163 - Unable to avoid WaterHeater:Stratified warning
  src/EnergyPlus/WaterThermalTanks.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Defect, NotIDDChange

#8083 Revise calc zone sums
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Performance

#8236 Add Missing Argument on Call to InputOutputFile::open
  src/EnergyPlus/IOFiles.cc
Labels: Defect
