Repository NREL/EnergyPlus, pull requests merged in 2020-07, with the labels that each got.

#8108 Fix #6917 and Fix #8095 - Reimplement Object Count Summary Table
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/InputProcessing/InputProcessor.hh
  tst/EnergyPlus/unit/InputProcessor.unit.cc
Labels: Defect, NotIDDChange

#8129 Add a clear_state for DataReportingFlags
  src/EnergyPlus/DataReportingFlags.cc
  src/EnergyPlus/DataReportingFlags.hh
  src/EnergyPlus/StateManagement.cc
Labels: DoNotPublish

#7984 Add zone outdoor volume flow rate report variable to all single duct air terminal units
  doc/input-output-reference/src/overview/group-air-distribution-equipment.tex
  src/EnergyPlus/DualDuct.cc
  src/EnergyPlus/HVACCooledBeam.cc
  src/EnergyPlus/HVACCooledBeam.hh
  src/EnergyPlus/HVACFourPipeBeam.cc
  src/EnergyPlus/HVACFourPipeBeam.hh
  src/EnergyPlus/HVACSingleDuctInduc.cc
  src/EnergyPlus/HVACSingleDuctInduc.hh
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/PoweredInductionUnits.cc
  src/EnergyPlus/PoweredInductionUnits.hh
  src/EnergyPlus/SingleDuct.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuct.unit.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
  tst/EnergyPlus/unit/PoweredInductionUnits.unit.cc
Labels: Documentation, NewFeature, NotIDDChange

#8101 Support Electric Heating Coil with ASHRAE90VariableFan Capacity Control
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/SZVAVModel.cc
  src/EnergyPlus/SZVAVModel.hh
  testfiles/CMakeLists.txt
  testfiles/FanCoilAutoSize_ASHRAE90VariableFan.idf
  tst/EnergyPlus/unit/FanCoilUnits.unit.cc
  tst/EnergyPlus/unit/SZVAVModel.unit.cc
Labels: Defect, NewFeature

#8130 Solar shading test cleanup
  testfiles/SolarShadingTest.idf
  testfiles/SolarShadingTest.rvi
  testfiles/SolarShadingTestGPU.idf
  testfiles/SolarShadingTest_SQL.rvi
Labels: DoNotPublish

#7847 Streamline inside surface heat balance - reorder surfaces - add path for CTF-only simulations
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataHeatBalSurface.cc
  src/EnergyPlus/DataHeatBalSurface.hh
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DataViewFactorInformation.hh
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/Transition/OutputRulesFiles/OutputChanges9-3-0-to-9-4-0.md
  tst/EnergyPlus/unit/DataHeatBalance.unit.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
  tst/EnergyPlus/unit/ThermalChimney.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Performance

#8118 Fix #8111 - E+ Crash w/ RunPeriodControl:DaylightSavingTime that wraps around year
  src/EnergyPlus/ScheduleManager.cc
  tst/EnergyPlus/unit/ScheduleManager.unit.cc
Labels: Defect, NotIDDChange

#8104 Global ConvectionCoefficients
  src/EnergyPlus/BaseboardRadiator.hh
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/CommandLineInterface.hh
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  src/EnergyPlus/CrossVentMgr.cc
  src/EnergyPlus/CrossVentMgr.hh
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/DisplacementVentMgr.hh
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/EcoRoofManager.hh
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/ElectricBaseboardRadiator.hh
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/GeneralRoutines.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/LowTempRadiantSystem.hh
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/PhotovoltaicThermalCollectors.cc
  src/EnergyPlus/PhotovoltaicThermalCollectors.hh
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/TranspiredCollector.hh
  src/EnergyPlus/UFADManager.cc
  src/EnergyPlus/UFADManager.hh
  src/EnergyPlus/VentilatedSlab.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/DisplacementVentMgr.unit.cc
  tst/EnergyPlus/unit/HWBaseboardRadiator.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/ICSCollector.unit.cc
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
Labels: Refactoring

#8140 Fixing some clear_state issues
  src/EnergyPlus/BaseboardElectric.cc
  src/EnergyPlus/BaseboardElectric.hh
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/BaseboardRadiator.hh
  src/EnergyPlus/CoolTower.cc
  src/EnergyPlus/EarthTube.cc
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/EvaporativeCoolers.hh
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/HVACCooledBeam.cc
  src/EnergyPlus/HVACCooledBeam.hh
  src/EnergyPlus/HVACDuct.cc
  src/EnergyPlus/HVACDuct.hh
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.hh
  src/EnergyPlus/Photovoltaics.cc
  src/EnergyPlus/Photovoltaics.hh
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/api/runtime.py
  tst/EnergyPlus/api/TestRuntime.c
Labels: Defect

#8135 Global CoolTower
  src/EnergyPlus/CoolTower.cc
  src/EnergyPlus/CoolTower.hh
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
Labels: Refactoring

#8137 Global CostEstimateManager
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/CostEstimateManager.hh
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataCostEstimate.cc
  src/EnergyPlus/DataCostEstimate.hh
  src/EnergyPlus/EconomicLifeCycleCost.cc
  src/EnergyPlus/EconomicLifeCycleCost.hh
  src/EnergyPlus/EconomicTariff.cc
  src/EnergyPlus/EconomicTariff.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/OutputReportTabularAnnual.cc
  src/EnergyPlus/OutputReportTabularAnnual.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SimulationManager.hh
  tst/EnergyPlus/unit/EconomicLifeCycleCost.unit.cc
  tst/EnergyPlus/unit/EconomicTariff.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/WeatherManager.unit.cc
Labels: Refactoring

#8144 Fix transition truncating long field values
  src/Transition/DataGlobals.f90
Labels: Defect

#8149 Use correct IDD versions when configuring IDDs in build tree
  CMakeLists.txt
Labels: DoNotPublish

#8148 Global window ac
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/WindowAC.cc
  src/EnergyPlus/WindowAC.hh
  tst/EnergyPlus/unit/WindowAC.unit.cc
Labels: Refactoring

#8151 Global wind turbine
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/WindTurbine.cc
  src/EnergyPlus/WindTurbine.hh
Labels: Refactoring

#8153 Global CTElectricGenerator
  src/EnergyPlus/CTElectricGenerator.cc
  src/EnergyPlus/CTElectricGenerator.hh
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/CTElectricGenerator.unit.cc
Labels: Refactoring

#8145 Report zero values in HVAC Sizing Summary with zero loads
  src/EnergyPlus/SizingManager.cc
  src/Transition/OutputRulesFiles/OutputChanges9-3-0-to-9-4-0.md
  tst/EnergyPlus/unit/WindowAC.unit.cc
Labels: Defect

#8168 Removed SingleDuctAirTerminal Heat/Cool Rate/Energy variables
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SingleDuct.hh
  tst/EnergyPlus/unit/AirTerminalSingleDuctConstantVolumeNoReheat.unit.cc
Labels: Refactoring

#8136 Provide a recursive warning when OutAirMinFrac > MechVentOutsideAirMinFrac
  doc/input-output-reference/src/overview/group-controllers.tex
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixedAir.hh
  testfiles/5ZoneVAV-ChilledWaterStorage-Mixed_DCV_MaxZd.idf
  testfiles/5ZoneVAV-ChilledWaterStorage-Mixed_DCV_MultiPath.idf
  testfiles/RefMedOffVAVAllDefVRP.idf
  tst/EnergyPlus/unit/MixedAir.unit.cc
Labels: Defect
