Repository NREL/EnergyPlus, pull requests merged in 2020-09, with the labels that each got.

#8225 Add Zone Air Terminal Primary Damper Position Output to AirTerminal:SingleDuct:ParallelPIU:Reheat and AirTerminal:SingleDuct:SeriesPIU:Reheat
  doc/input-output-reference/src/overview/group-air-distribution-equipment.tex
  src/EnergyPlus/PoweredInductionUnits.cc
  src/EnergyPlus/PoweredInductionUnits.hh
  testfiles/5ZoneAirCooledConvCoef.idf
  testfiles/5ZoneAirCooledConvCoefPIU.idf
  testfiles/PIUAuto.idf
  tst/EnergyPlus/unit/PoweredInductionUnits.unit.cc
Labels: Defect, NotIDDChange

#8141 SurfaceWindow struct refactoring
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/RoomAirModelUserTempPattern.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/UFADManager.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorOptical.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkSimulationControl.unit.cc
  tst/EnergyPlus/unit/DataHeatBalance.unit.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
  tst/EnergyPlus/unit/EMSManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/WindowEquivalentLayer.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: InProgress, Performance

#8235 Preliminarily fixes #8228 -- better fixup of executables on mac
  cmake/PythonFixUpOnMac.cmake
Labels: Defect

#8217 Add SpecialDays to Annual Run
  testfiles/_5ZoneAirCooled_annual.idf
Labels: DoNotPublish

#8237 Resilience metrics fix issue #8220
  doc/engineering-reference/engineering-reference.tex
  doc/engineering-reference/src/special-modules-reporting/resilience-metrics.tex
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
Labels: Defect

#8242 Fix CSV files with carriage return line endings throw a sever error when read.
  src/EnergyPlus/CurveManager.cc
  tst/EnergyPlus/unit/CurveManager.unit.cc
  tst/EnergyPlus/unit/Resources/TestCarriageReturn.csv
Labels: Defect, NotIDDChange

#7899 Apply Direct solution in new dx coil
  doc/input-output-reference/src/overview/group-simulation-parameters.tex
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Performance

#8139 Fix #8084 - EMS Actuators Override Python Actuators Silently
  src/EnergyPlus/BoilerSteam.cc
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/DataLoopNode.cc
  src/EnergyPlus/DataLoopNode.hh
  src/EnergyPlus/DataRuntimeLanguage.hh
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/EMSManager.hh
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/NodeInputManager.cc
  src/EnergyPlus/PlantCentralGSHP.cc
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/api/datatransfer.cc
  testfiles/PythonPluginDemandManager_LargeOffice.idf
  testfiles/PythonPluginReplaceTraditionalManagers_LargeOffice.idf
  tst/EnergyPlus/unit/api/datatransfer.unit.cc
Labels: Defect, NotIDDChange

#8255 Make floating point exceptions consistent across platforms
  src/EnergyPlus/api/EnergyPlusPgm.cc
  src/EnergyPlus/main.cc
Labels: Defect, DoNotPublish

#7887 Subcool reheat dx coil follow up
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/coils.tex
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/Coils/CoilCoolingDX.hh
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
  src/EnergyPlus/DataHVACGlobals.cc
  src/EnergyPlus/DataHVACGlobals.hh
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  tst/EnergyPlus/unit/Coils/CoilCoolingDXCurveFitPerformance.unit.cc
Labels: Defect

#8261 A few doc fixes in the engineering ref for water heaters
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/water-thermal-tanks-includes-water-heaters.tex
Labels: DoNotPublish, Documentation

#8264 Github Actions Trial
  .decent_ci-Linux.yaml
  .github/disabled-workflows/cmake.yml
  .github/workflows/cppcheck.yml
  .github/workflows/custom_check.yml
  .github/workflows/documentation.yml
  .github/workflows/pr_labels.yml
  scripts/dev/check_for_bom_in_idfs.py
  scripts/dev/check_for_tabs_in_idfs.py
  scripts/dev/check_non_utf8.py
  scripts/dev/check_pr_labels.py
  scripts/dev/check_stray_fields_in_idd.py
  scripts/dev/custom_check.sh
  scripts/dev/find_byref_bool_override.py
  scripts/dev/find_included_cc_files.py
  scripts/dev/license-check.py
  scripts/dev/licensetext.py
  scripts/dev/validate_idd_units.py
  scripts/dev/verify_cmake_dirs.py
  scripts/dev/verify_file_encodings.py
  scripts/dev/verify_idfs_in_cmake.py
Labels: DoNotPublish

#8258 Correction of Flow Fraction Maximum for Variable Flow Radiant Systems
  src/EnergyPlus/LowTempRadiantSystem.cc
  testfiles/RadLoHydrHeatCoolAuto.idf
  testfiles/RadLoHydrHeatCoolAuto.rvi
  testfiles/RadLoHydrHeatCoolAutoCondFD.idf
  testfiles/RadLoHydrHeatCoolAutoCondFD.rvi
  testfiles/RadLoTempHydrChangeoverDelay.idf
  testfiles/RadLoTempHydrCoolTower.idf
  testfiles/RadLoTempHydrCoolTower.rvi
  testfiles/RadLoTempHydrCoolTowerCondFD.idf
  testfiles/RadLoTempHydrCtrlOpt.idf
  testfiles/RadLoTempHydrCtrlOpt.rvi
  testfiles/RadLoTempHydrCtrlOpt2.idf
  testfiles/RadLoTempHydrCtrlOpt2.rvi
  testfiles/RadLoTempHydrCtrlOpt3.idf
  testfiles/RadLoTempHydrHeatCool.idf
  testfiles/RadLoTempHydrHeatCool.rvi
  testfiles/RadLoTempHydrHeatCool2D.idf
  testfiles/RadLoTempHydrHeatCool2D.rvi
  testfiles/RadLoTempHydrHeatCoolDry.idf
  testfiles/RadLoTempHydrHeatCoolDry.rvi
  testfiles/RadLoTempHydrHeatCoolDryCondFD.idf
  testfiles/RadLoTempHydrHeatCoolMultiZone.idf
  testfiles/RadLoTempHydrISOPipeHT.idf
  testfiles/RadLoTempHydrInterMulti.idf
  testfiles/RadLoTempHydrInterMulti.rvi
  testfiles/RadLoTempHydrMulti10.idf
  testfiles/RadLoTempHydrMulti10.rvi
  testfiles/RadLoTempHydrTermReheat.idf
  testfiles/RadLoTempHydrTermReheat.rvi
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
Labels: Defect

#8250 #8249 - Adjustments for OutputControl:Files: properly register it, and do not output END file if set to No
  src/EnergyPlus/IOFiles.cc
  src/EnergyPlus/IOFiles.hh
Labels: Defect

#8244 Ceiling Diffuser Convection Model Causes Oscillating Winter Design Day Loads
  doc/engineering-reference/src/surface-heat-balance-manager-processes/inside-heat-balance.tex
  src/EnergyPlus/ConvectionCoefficients.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
Labels: Defect

#8273 Protect Debug File from FatalError on processInput
  src/EnergyPlus/UtilityRoutines.cc
Labels: Defect

#8266 Steam conversion factor
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PollutionModule.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect, NotIDDChange

#8226 Fix #8224 - Packages Need OS Version Number
  .decent_ci-MacOS.yaml
  .decent_ci-Windows.yaml
  cmake/CMakeAddFortranSubdirectory/config_mingw.cmake.in
  cmake/Install.cmake
  src/AppGPostProcess/CMakeLists.txt
  src/CalcSoilSurfTemp/CMakeLists.txt
  src/ExpandObjects/CMakeLists.txt
  src/Transition/CMakeLists.txt
Labels: Defect, NotIDDChange

#8239 Fix geometry relation check problems in shading calculations
  src/EnergyPlus/SolarShading.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: Defect

#8247 Fix #8066 - Coil:Cooling:DX:CurveFit:OperatingMode: Nominal Evaporative Condenser Pump Power is marked autosizabled, but not autosized, and other autosized missing units
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDXCurveFitOperatingMode.unit.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDXFixture.hh
Labels: Defect

#8280 Fixed Documentation Issues - 2020b
  doc/auxiliary-programs/src/weather-converter-program/definitions-file-custom-file-processing.tex
  doc/ems-application-guide/media/DrawingFileForEMSCallingPointFigures_LibreOfficeDraw.odg
  doc/ems-application-guide/media/image003.jpg
  doc/ems-application-guide/media/image004.jpg
  doc/ems-application-guide/media/image005.jpg
  doc/ems-application-guide/src/ems-calling-points/begin-timestep-before-predictor.tex
  doc/engineering-reference/src/integrated-solution-manager/generic-contaminant-predictor-corrector.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/ground-heat-transfer-calculations-using-c.tex
  doc/input-output-reference/src/overview/group-condenser-equipment.tex
  doc/input-output-reference/src/overview/group-design-objects.tex
  doc/input-output-reference/src/overview/group-exterior-energy-use-equipment.tex
  doc/input-output-reference/src/overview/group-fans.tex
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  doc/input-output-reference/src/overview/group-performance-curves.tex
  doc/input-output-reference/src/overview/group-schedules.tex
Labels: Defect

#8283 Fix the resource portion of end-use subcategory meter names in v9.3 to v9.4 transition
  doc/input-output-reference/src/input-for-output.tex
  src/Transition/CreateNewIDFUsingRulesV9_4_0.f90
Labels: Defect

#8263 Enable AFN with air boundary surfaces and fix ignored Ventilation Availability Schedule for horizontal opening
  doc/ems-application-guide/src/ems-actuators/air-movement.tex
  doc/input-output-reference/src/overview/group-airflow-network.tex
  doc/tips-and-tricks-using-energyplus/src/building-geometry-shading-zone-model/air-wall-open-air-connection-between-zones.tex
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: Defect

#8270 Action test 2
  .decent_ci-Linux.yaml
  .decent_ci-MacOS.yaml
  .decent_ci-Windows.yaml
  .github/disabled-workflows/cmake.yml
  .github/disabled-workflows/mac_test.yml
  .github/disabled-workflows/windows_test.yml
  .github/unfinished-workflows/linux_test.yml
  .github/unfinished-workflows/linux_test_debug.yml
  .github/workflows/linux_release.yml
  .github/workflows/mac_release.yml
  .github/workflows/pr_labels.yml
  .github/workflows/windows_release.yml
  README.md
  cmake/ProjectMacros.cmake
  cmake/PythonFixUpOnMac.cmake
Labels: DoNotPublish

#8272 Fix Zone Equipment sensible heat gain summary calculation and reporting
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportPredefined.hh
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#8001 Fix issue where simple glazing system had negative absorptance at some incident angles
  doc/engineering-reference/src/daylighting-and-window-calculations/window-calculation-module.tex
  src/EnergyPlus/WindowManager.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Defect, NotIDDChange

#8109 Allow EMS to actuate mass flow and supply temperature for Ideal Loads when the zone load is zero
  doc/ems-application-guide/src/ems-actuators/hvac-systems-001.tex
  src/EnergyPlus/PurchasedAirManager.cc
  src/EnergyPlus/PurchasedAirManager.hh
  testfiles/EMSConstantVolumePurchasedAir.idf
  testfiles/PythonPluginConstantVolumePurchasedAir.idf
  tst/EnergyPlus/unit/PurchasedAirManager.unit.cc
Labels: Defect

#8288 Fix AirflowNetworkBalanceManager divide by zero overflow issue causing NaN values in window temperature nan calculations
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
  tst/EnergyPlus/unit/General.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Defect

#8269 Allow Multiple Scheduled Shades to Reference a Single Window
  design/FY2020/NFP-MultipleScheduledShades.md
  doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SolarShading.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorOptical.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  tst/EnergyPlus/unit/EMSManager.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: NewFeature, NotIDDChange

#7988 Fix water coil user-specified sizing and Component Sizing Summary table for fan coils
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/WaterCoils.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/FanCoilUnits.unit.cc
  tst/EnergyPlus/unit/WaterCoils.unit.cc
Labels: Defect, NotIDDChange

#7861 Address total/sensible/latent calculations issues for DX cooling coils and others
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/GeneralRoutines.hh
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACSingleDuctInduc.cc
  src/EnergyPlus/HVACStandAloneERV.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/Psychrometrics.hh
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/ZoneAirLoopEquipmentManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctConstantVolumeNoReheat.unit.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/GeneralRoutines.unit.cc
  tst/EnergyPlus/unit/HVACHXAssistedCoolingCoil.unit.cc
  tst/EnergyPlus/unit/HVACMultiSpeedHeatPump.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#8291 Fix #8289 segfault when using new window shading control
  src/EnergyPlus/SurfaceGeometry.cc
Labels: DoNotPublish

#8143 Added two weather variables for outputs and calculate sky emissivity and temperature using timestep interpolated inputs
  doc/input-output-reference/src/overview/group-location-climate-weather-file-access.tex
  src/EnergyPlus/DataEnvironment.cc
  src/EnergyPlus/DataEnvironment.hh
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  tst/EnergyPlus/unit/WeatherManager.unit.cc
Labels: Defect, NewFeature

#8293 Fix DX Coil crankcase heater meter
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/DXCoils.cc
  testfiles/HVACTemplate-5ZonePTAC-DOAS.idf
  testfiles/MultiStory.idf
  testfiles/UnitarySystem_MultiSpeedDX.idf
  testfiles/UnitarySystem_SingleSpeedDX.idf
  testfiles/UnitarySystem_SubcoolReheatDX.idf
  testfiles/UnitarySystem_TwoSpeedDX.idf
  testfiles/UnitarySystem_TwoStageDX.idf
  testfiles/UnitarySystem_TwoStageDXWithHumidityControl.idf
Labels: Defect

#8287 Prevent non-convex errors from appearing when using PixelCounting
  src/EnergyPlus/PierceSurface.hh
  src/EnergyPlus/SolarShading.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.hh
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: Defect, NotIDDChange

#8294 CSV output, I/O, IDD parser, and file conversion bugfixes
  scripts/dev/generate_epJSON_schema/idd_parser.py
  src/EnergyPlus/IOFiles.hh
  src/EnergyPlus/InputProcessing/IdfParser.cc
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/ResultsFramework.cc
  src/EnergyPlus/ResultsFramework.hh
  src/EnergyPlus/api/EnergyPlusPgm.cc
  tst/EnergyPlus/unit/Fixtures/IdfParserFixture.hh
  tst/EnergyPlus/unit/IdfParser.unit.cc
  tst/EnergyPlus/unit/TestHelpers/IdfParser.cc
Labels: Defect

#8297 Skip Meter:Custom* Transitions
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/Transition/CreateNewIDFUsingRulesV9_4_0.f90
Labels: DoNotPublish

#8296 Documentation changes - #7760
  doc/input-output-reference/CMakeLists.txt
  doc/input-output-reference/src/overview.tex
  doc/input-output-reference/src/overview/group-air-distribution-equipment.tex
  doc/input-output-reference/src/overview/group-electric-load-center-generator.tex
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  doc/input-output-reference/src/overview/group-humidifiers-and-dehumidifiers.tex
  doc/input-output-reference/src/overview/group-humidifiers.tex
  doc/input-output-reference/src/overview/group-plant-equipment.tex
  doc/input-output-reference/src/overview/group-water-heaters.tex
Labels: Defect

#8307 OutputControl documentation and bugfix for tabular file control
  doc/input-output-reference/src/input-for-output.tex
  src/EnergyPlus/EconomicTariff.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/SQLiteProcedures.cc
  src/EnergyPlus/SimulationManager.cc
  testfiles/CMakeLists.txt
  testfiles/RefBldgMediumOfficeNew2004_Chicago_OutputControl.idf
Labels: DoNotPublish

#8306 Fix Fueltype renames of IDFs in \datasets and \performance_tests
  datasets/Macro/UtilityTariffObjects.imf
  datasets/PerfCurves.idf
  datasets/StandardReports.idf
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  doc/input-output-reference/src/standard-output-reports/output-table-summaryreports.tex
  performance_tests/15zonePSZ.idf
  performance_tests/15zonePTAC.idf
  performance_tests/15zonePVAV.idf
  performance_tests/15zonevav.idf
  performance_tests/30zonePSZ.idf
  performance_tests/30zonePTAC.idf
  performance_tests/30zonePVAV.idf
  performance_tests/30zonevav.idf
  performance_tests/45zonePSZ.idf
  performance_tests/45zonePTAC.idf
  performance_tests/45zonePVAV.idf
  performance_tests/45zonevav.idf
  performance_tests/BenchmarkHospitalNew_USA_CA_SAN_FRANCISCO.idf
  performance_tests/BenchmarkLargeOfficeNew_USA_CA_SAN_FRANCISCO_10_windows_per_zone.idf
  performance_tests/Benchmarklargeofficenew_usa_ca_san_francisco_no_reports.idf
  performance_tests/Inactive/benchmarklargeofficenew_usa_ca_san_francisco.idf
Labels: Defect

#8298 Parametric Preprocessor and EP-Launch error handling cleanup
  bin/EP-Launch/EP-Launch.exe
  src/EP-Launch/epl-ui.frm
  src/EP-Launch/epl-ui.frx
  src/EP-Launch/epl.vbp
  src/EP-Launch/epl.vbw
  src/EP-Launch/frmAbout.frm
  src/ParametricPreprocessor/ParametricPreprocessor.f90
  workflows/energyplus.py
Labels: Defect

#8308 Remove python wrapper intermediary
  .github/workflows/mac_release.yml
  cmake/PythonCopyStandardLib.py
  cmake/PythonFixUpOnMac.cmake
  cmake/PythonGetLibAndLinkUp.cmake
  scripts/dev/find_byref_bool_override.py
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PluginManager.hh
  src/EnergyPlus/PythonLibWrapper.cc
  src/EnergyPlus/PythonLibWrapper.hh
Labels: DoNotPublish

#8304 Fix EMS FuelTypes
  doc/ems-application-guide/src/ems-actuators/internal-gains-and-exterior-lights.tex
  doc/ems-application-guide/src/ems-examples/example-9-demand-management.tex
  doc/ems-application-guide/src/internal-variables/internal-gains.tex
  doc/ems-application-guide/src/internal-variables/on-site-electricity-production.tex
  doc/output-details-and-examples/src/output-files/eplusout-edd.tex
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/Transition/CreateNewIDFUsingRulesV9_4_0.f90
  src/Transition/InputRulesFiles/Rules9-3-0-to-9-4-0.md
  src/Transition/OutputRulesFiles/OutputChanges9-3-0-to-9-4-0.md
  testfiles/ASHRAE9012016_OfficeLarge_Denver.idf
  testfiles/ASHRAE9012016_OfficeMedium_Denver.idf
  testfiles/ASHRAE9012016_OfficeSmall_Denver.idf
  testfiles/ASHRAE9012016_RestaurantFastFood_Denver.idf
  testfiles/ASHRAE9012016_RestaurantSitDown_Denver.idf
  testfiles/ASHRAE9012016_RetailStandalone_Denver.idf
  testfiles/ASHRAE9012016_RetailStripmall_Denver.idf
  testfiles/ASHRAE9012016_SchoolPrimary_Denver.idf
  testfiles/ASHRAE9012016_SchoolSecondary_Denver.idf
  testfiles/ASHRAE9012016_Warehouse_Denver.idf
  testfiles/EMSDemandManager_LargeOffice.idf
  testfiles/PythonPluginDemandManager_LargeOffice.py
Labels: DoNotPublish

#8315 Final Changes for 9.4
  doc/input-output-reference/src/overview/api-usage.tex
  doc/input-output-reference/src/overview/group-python-plugins.tex
  release/readme.html
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/api/docs/c/Doxyfile
  src/EnergyPlus/api/docs/python/conf.py
  src/Transition/CreateNewIDFUsingRulesV9_4_0.f90
Labels: DoNotPublish
