Repository NREL/EnergyPlus, pull requests merged in 2020-11, with the labels that each got.

#8330 Fix file name in path returned by getAbsolutePath when a directory is not provided
  src/EnergyPlus/FileSystem.cc
  tst/EnergyPlus/unit/FileSystem.unit.cc
Labels: Defect, DoNotPublish, NotIDDChange

#8323 Unitary system now reports warning when cycling supply fan schedule is used with setpoint control type
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect, NotIDDChange

#8326 ZoneHVAC:HybridUnitaryHVAC ERR object type output
  doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
  src/EnergyPlus/HybridUnitaryAirConditioners.cc
  tst/EnergyPlus/unit/UnitaryHybridAirConditioner.unit.cc
Labels: Defect, NotIDDChange

#8345 Move static VRF variables to namespace
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
Labels: Defect

#8360 Global DataWater
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/CoolTower.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataWater.cc
  src/EnergyPlus/DataWater.hh
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/EvaporativeCoolers.hh
  src/EnergyPlus/EvaporativeFluidCoolers.cc
  src/EnergyPlus/Humidifiers.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PackagedThermalStorageCoil.cc
  src/EnergyPlus/PackagedThermalStorageCoil.hh
  src/EnergyPlus/RefrigeratedCase.cc
  src/EnergyPlus/RefrigeratedCase.hh
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/UserDefinedComponents.cc
  src/EnergyPlus/UserDefinedComponents.hh
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/WaterManager.cc
  src/EnergyPlus/WaterManager.hh
  src/EnergyPlus/WaterUse.cc
  src/EnergyPlus/WaterUse.hh
  src/EnergyPlus/ZoneDehumidifier.cc
  tst/EnergyPlus/unit/WaterManager.unit.cc
Labels: Refactoring

#8368 Global DataTiming
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataSystemVariables.hh
  src/EnergyPlus/DataTimings.cc
  src/EnergyPlus/DataTimings.hh
Labels: Refactoring

#8322 Fix Unitary System with Heating Coil Temperature Setpoint Node Name Field Non-Blank
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/UnitarySystem.cc
  testfiles/5Zone_Unitary_VSDesuperheater.idf
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect, NotIDDChange

#8348 Fix #8317 - Warn in Output:Table:Monthly when invalid 'Variable or Meter Name' field
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect, NotIDDChange

#8351 Global SurfaceGeometry
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
  tst/EnergyPlus/unit/BaseboardRadiator.unit.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/DElightManager.unit.cc
  tst/EnergyPlus/unit/DataSurfaces.unit.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
  tst/EnergyPlus/unit/ElectricBaseboardRadiator.unit.cc
  tst/EnergyPlus/unit/HeatBalanceMovableInsulation.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/OutputReports.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
  tst/EnergyPlus/unit/ThermalChimney.unit.cc
  tst/EnergyPlus/unit/TranspiredCollector.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Refactoring

#8371 Change References to RTD Site
  README.md
  doc/readthedocs/README.md
  doc/readthedocs/doxygen/header.html
  doc/readthedocs/sphinx/.templates/layout.html
Labels: DoNotPublish

#8324 Fix file not found output message
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/CurveManager.hh
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/DataSystemVariables.hh
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/ScheduleManager.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/DataSystemVariables.unit.cc
Labels: Defect, NotIDDChange

#8358 Fix tdd calculations in CalcInteriorSolarDistribution
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarShading.cc
Labels: Defect

#8364 Fix #8357 - tweak GitHub actions
  .github/disabled-workflows/release.yml
  .github/workflows/linux_release.yml
  .github/workflows/mac_release.yml
  .github/workflows/windows_release.yml
Labels: Defect, NotIDDChange

#8347 Heat balance surface data structure refactoring
  doc/engineering-reference/src/climate-sky-and-solar-shading-calculations/shading-module.tex
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/DXFEarClipping.cc
  src/EnergyPlus/DXFEarClipping.hh
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceHAMTManager.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/MoistureBalanceEMPDManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/RoomAirModelUserTempPattern.cc
  src/EnergyPlus/SolarReflectionManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SolarShading.hh
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/ThermalChimney.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkSimulationControl.unit.cc
  tst/EnergyPlus/unit/DisplacementVentMgr.unit.cc
  tst/EnergyPlus/unit/EMSManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceMovableInsulation.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
  tst/EnergyPlus/unit/SwimmingPool.unit.cc
  tst/EnergyPlus/unit/WeatherManager.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Performance, Refactoring

#8385 Global DataBranchNodeConnections
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/BranchNodeConnections.cc
  src/EnergyPlus/BranchNodeConnections.hh
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataBranchAirLoopPlant.hh
  src/EnergyPlus/DataBranchNodeConnections.cc
  src/EnergyPlus/DataBranchNodeConnections.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/SystemReports.cc
  tst/EnergyPlus/unit/SZVAVModel.unit.cc
Labels: Refactoring

#8388 Global sim manager sim air
  scripts/dev/analyze_state.py
  scripts/dev/custom_check.sh
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HVACControllers.hh
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  src/EnergyPlus/PlantLoopHeatPumpEIR.hh
  src/EnergyPlus/PlantValves.cc
  src/EnergyPlus/PlantValves.hh
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/SetPointManager.hh
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SimulationManager.hh
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SingleDuct.hh
  src/EnergyPlus/SizingAnalysisObjects.cc
  src/EnergyPlus/SizingAnalysisObjects.hh
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SizingManager.hh
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/WaterCoils.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuct.unit.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctConstantVolumeNoReheat.unit.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/HVACControllers.unit.cc
  tst/EnergyPlus/unit/PlantCondLoopOperation.unit.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
  tst/EnergyPlus/unit/PlantManager.unit.cc
  tst/EnergyPlus/unit/SetPointManager.unit.cc
  tst/EnergyPlus/unit/SingleDuct.unit.cc
  tst/EnergyPlus/unit/SizeWaterHeatingCoil.unit.cc
  tst/EnergyPlus/unit/VAVDefMinMaxFlow.unit.cc
Labels: Refactoring

#8366 Fix 9-3-0 to 9-4-0 transition for objects that accept report variable or meter name
  src/Transition/CreateNewIDFUsingRulesV9_4_0.f90
Labels: Defect

#8378 Fix when Compiling with non-standard CMake Configurations
  .github/workflows/mac_build.yml
  CMakeLists.txt
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/FluidProperties.cc
  src/EnergyPlus/FluidProperties.hh
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/Psychrometrics.hh
  tst/EnergyPlus/unit/CMakeLists.txt
Labels: Defect, DoNotPublish

#8393 Global Daylighting
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataConvergParams.cc
  src/EnergyPlus/DataConvergParams.hh
  src/EnergyPlus/DataConversions.cc
  src/EnergyPlus/DataConversions.hh
  src/EnergyPlus/DataDaylighting.cc
  src/EnergyPlus/DataDaylighting.hh
  src/EnergyPlus/DataDaylightingDevices.cc
  src/EnergyPlus/DataDaylightingDevices.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingDevices.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/DualDuct.cc
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HVACInterfaceManager.cc
  src/EnergyPlus/HVACInterfaceManager.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/DElightManager.unit.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
  tst/EnergyPlus/unit/EMSManager.unit.cc
  tst/EnergyPlus/unit/HVACControllers.unit.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
Labels: Refactoring
