Repository NREL/EnergyPlus, pull requests merged in 2020-01, with the labels that each got.

#7544 Require Python 3
  CMakeLists.txt
  scripts/dev/license-check.py
  scripts/dev/license-update.py
  scripts/dev/licensetext.py
Labels: DoNotPublish

#7662 Refrigeration Components Plant Component Refactor
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  src/EnergyPlus/RefrigeratedCase.cc
  src/EnergyPlus/RefrigeratedCase.hh
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
Labels: Refactoring

#7667 Plant Fluid HX Plant Component Refactor
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantHeatExchangerFluidToFluid.cc
  src/EnergyPlus/PlantHeatExchangerFluidToFluid.hh
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/PlantHeatExchangerFluidToFluid.unit.cc
Labels: Refactoring

#7665 Update Manifest Year
  CMakeLists.txt
  src/EnergyPlus/energyplus.rc.in
  src/EnergyPlus/energyplusapi.rc.in
Labels: DoNotPublish

#7626 Corrected CapFTemp curve index used in multi-speed DX coils for capacity sizing
  src/EnergyPlus/DXCoils.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
Labels: Defect

#7584 Modify End Use by Subcategory tables in SQL so they can be queried
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/Transition/OutputRulesFiles/OutputChanges9-2-0-to-9-3-0.md
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#7572 Update Water Mains Correlation Temperature Calculation to be Consistent with Reference and E+
  src/EnergyPlus/WeatherManager.cc
Labels: Defect

#7660 Fix VS2017 build error in OpenMP code
  src/ConvertInputFormat/main.cpp
Labels: DoNotPublish

#7675 Fix unit test build problem on windows and cleanup ZoneTempPredictorCorrector unit tests
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/OutputFiles.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: DoNotPublish

#7541 Water Thermal Tanks Plant Component Refactor
  src/EnergyPlus/IntegratedHeatPump.cc
  src/EnergyPlus/NonZoneEquipmentManager.cc
  src/EnergyPlus/NonZoneEquipmentManager.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PackagedThermalStorageCoil.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterThermalTanks.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/IntegratedHeatPump.unit.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Refactoring

#7637 Chiller Plant Component Refactor
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/PlantChillers.hh
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/ChillerConstantCOP.unit.cc
  tst/EnergyPlus/unit/ChillerElectric.unit.cc
  tst/EnergyPlus/unit/PlantChillers.unit.cc
Labels: Refactoring

#7677 Remove objexx gio part 2
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/AirflowNetworkBalanceManager.hh
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/EnergyPlusPgm.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceManager.hh
  src/EnergyPlus/OutputFiles.cc
  src/EnergyPlus/OutputFiles.hh
  third_party/fmt-6.1.2/include/fmt/core.h
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkSimulationControl.unit.cc
  tst/EnergyPlus/unit/BaseboardRadiator.unit.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/DElightManager.unit.cc
  tst/EnergyPlus/unit/DataHeatBalance.unit.cc
  tst/EnergyPlus/unit/DataSurfaces.unit.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
  tst/EnergyPlus/unit/ElectricBaseboardRadiator.unit.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceMovableInsulation.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
  tst/EnergyPlus/unit/MoistureBalanceEMPD.unit.cc
  tst/EnergyPlus/unit/OutputReports.unit.cc
  tst/EnergyPlus/unit/PlantPipingSystemsManager.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
  tst/EnergyPlus/unit/TranspiredCollector.unit.cc
  tst/EnergyPlus/unit/UnitHeater.unit.cc
  tst/EnergyPlus/unit/VentilatedSlab.unit.cc
  tst/EnergyPlus/unit/WinCalcEngine.unit.cc
  tst/EnergyPlus/unit/WindowAC.unit.cc
  tst/EnergyPlus/unit/WindowEquivalentLayer.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Refactoring

#7669 ZoneHVAC VRF Plant Component Refactor
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Refactoring

#7689 Remove 9-3 idd install from idd/CMakeLists.txt
  idd/CMakeLists.txt
Labels: DoNotPublish

#7679 Chiller Electric EIR Plant Component Refactor
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerElectricEIR.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/ChillerElectricEIR.unit.cc
  tst/EnergyPlus/unit/StandardRatings.unit.cc
Labels: Refactoring

#7685 Plant component refactor of Absorption ChillerHeater
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.hh
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/ChillerGasAbsorption.unit.cc
Labels: Refactoring

#7684 Cleanup some lingering issues in PlantLoopEquip
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/FuelCellElectricGenerator.cc
  src/EnergyPlus/IceThermalStorage.cc
  src/EnergyPlus/PlantLoopEquip.cc
  src/EnergyPlus/WaterThermalTanks.cc
Labels: Refactoring

#7694 Exhaust Absorber refactor
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerExhaustAbsorption.hh
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/ChillerExhaustAbsorption.unit.cc
Labels: Refactoring

#7580 Update transition rule for TableMultiVariableLookup Normalization Reference from 9.1.0 to 9.2.0
  src/Transition/CreateNewIDFUsingRulesV9_2_0.f90
Labels: Defect

#7696 Zone Air Terminal VAV Damper Position variable is always zero for VAV Rheat with VS Fan air terminal
  src/EnergyPlus/SingleDuct.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuct.unit.cc
Labels: Defect

#7683 Chiller Electric Reformulated EIR Plant Component Refactor
  src/EnergyPlus/ChillerElectricEIR.hh
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/ChillerReformulatedEIR.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantLoopEquip.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
Labels: Refactoring

#7703 Collapse PlantLoopEquip nested IF block
  src/EnergyPlus/PlantLoopEquip.cc
Labels: Refactoring

#7542 Fix Divide by Zero in CentralHeatPump
  src/EnergyPlus/PlantCentralGSHP.cc
Labels: Defect

#7715 Fix up a couple paper cuts
  .decent_ci-Linux.yaml
  src/EnergyPlus/SingleDuct.cc
Labels: DoNotPublish

#7723 Fix #7648 - VRF model EIR heat recovery term uses capacity instead of EIR
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect, NotIDDChange

#7726 HotFix 7723 unit test
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: DoNotPublish

#7730 Fix Report Variables CSV Ordering
  src/Transition/SupportFiles/Report Variables 8-8-0 to 8-9-0.csv
  src/Transition/SupportFiles/Report Variables 9-2-0 to 9-3-0.csv
Labels: Defect
