Repository NREL/EnergyPlus, pull requests merged in 2020-06, with the labels that each got.

#8002 Added new functions to validate fuel types and set output strings
  src/EnergyPlus/BoilerSteam.cc
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/CTElectricGenerator.cc
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/ICEngineElectricGenerator.cc
  src/EnergyPlus/MicroturbineElectricGenerator.cc
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/UtilityRoutines.hh
  tst/EnergyPlus/unit/BoilerHotWater.unit.cc
  tst/EnergyPlus/unit/BoilerSteam.unit.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/CTElectricGenerator.unit.cc
  tst/EnergyPlus/unit/ChillerGasAbsorption.unit.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/ICEngineElectricGenerator.unit.cc
  tst/EnergyPlus/unit/MicroturbineElectricGenerator.unit.cc
  tst/EnergyPlus/unit/PlantChillers.unit.cc
Labels: Defect

#7923 When BUILD_DOCS is enabled, allow choosing if it should be in default make rule & install doc index.html
  CMakeLists.txt
  cmake/Install.cmake
  doc/CMakeLists.txt
Labels: DoNotPublish, Documentation, NotIDDChange

#7955 Address zone air terminal zone outdoor air flow rate reporting issues
  doc/input-output-reference/src/overview/group-air-distribution-equipment.tex
  src/EnergyPlus/DualDuct.cc
  src/EnergyPlus/DualDuct.hh
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SingleDuct.hh
  tst/EnergyPlus/unit/AirTerminalSingleDuctConstantVolumeNoReheat.unit.cc
Labels: Defect

#8031 Delete Debugging File
  src/EnergyPlus/PondGroundHeatExchanger.cc
Labels: DoNotPublish

#8014 Correct optimum start for partial hour fan start operation
  src/EnergyPlus/SystemAvailabilityManager.cc
  tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc
Labels: Defect, NotIDDChange

#7996 Fix #6204 - Coil:Cooling:DX:VariableSpeed air-to-air coil should autosize cooling capacity using CapFT curve results based on OutTemp and not RatedInletWaterTemp
  src/EnergyPlus/VariableSpeedCoils.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#7995 #7651 - VRF Condenser not simulated when one VRF TU not in Equipment List
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: DoNotPublish

#8006 #7388 - Non UTF-8 characters throwing false blank name error
  src/EnergyPlus/InputProcessing/InputValidation.cc
  tst/EnergyPlus/unit/InputProcessor.unit.cc
Labels: Defect

#8028 Protect ScanPlantLoopsForObject call with member var flag
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterThermalTanks.hh
  src/EnergyPlus/WaterUse.cc
  src/EnergyPlus/WaterUse.hh
Labels: Defect

#8039 Add missing includes for VS2019 16.6.1
  third_party/Windows-CalcEngine/src/MultiLayerOptics/src/MultiPaneSampleData.cpp
  third_party/Windows-CalcEngine/src/MultiLayerOptics/src/MultiPaneSpectralSample.cpp
  third_party/penumbra/src/gl/context.h
Labels: DoNotPublish

#8029 Developer - Organize build targets into folders for IDEs
  CMakeLists.txt
  cmake/CMakeAddFortranSubdirectory.cmake
  doc/CMakeLists.txt
  doc/cmake/doc-targets.cmake
  src/AppGPostProcess/CMakeLists.txt
  src/Basement/CMakeLists.txt
  src/CalcSoilSurfTemp/CMakeLists.txt
  src/ConvertESOMTR/CMakeLists.txt
  src/ConvertInputFormat/CMakeLists.txt
  src/ExpandObjects/CMakeLists.txt
  src/HVAC-Diagram/CMakeLists.txt
  src/ParametricPreprocessor/CMakeLists.txt
  src/ReadVars/CMakeLists.txt
  src/Slab/CMakeLists.txt
  src/Transition/CMakeLists.txt
  third_party/re2/CMakeLists.txt
Labels: DoNotPublish

#8008 Change rename function for FileSystem for Windows
  src/EnergyPlus/FileSystem.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/FileSystem.unit.cc
Labels: Defect, NotIDDChange

#8017 Fix #6976 - Clean up daylighting output reporting for more than two reference points
  doc/input-output-reference/src/input-for-output.tex
  doc/output-details-and-examples/src/output-files/eplusout-dfs.tex
  src/EnergyPlus/DataDaylighting.hh
  src/EnergyPlus/DaylightingManager.cc
  src/Transition/OutputRulesFiles/OutputChanges9-3-0-to-9-4-0.md
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.hh
Labels: Defect, NotIDDChange, OutputChange

#8040 Fix Site:Precipitation divide-by-zero
  src/EnergyPlus/WaterManager.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/WaterManager.unit.cc
Labels: Defect, NotIDDChange

#8049 Fix Python Plugin DLL path issues when EnergyPlus is called through a symlink
  src/EnergyPlus/FileSystem.cc
  src/EnergyPlus/PluginManager.cc
Labels: Defect, NotIDDChange

#8063 Fix DaylightManager Unit Test on Some Machines
  src/EnergyPlus/DaylightingManager.cc
Labels: DoNotPublish

#8074 Fix Unit Tests to Run Serially
  src/EnergyPlus/DataWater.cc
  src/EnergyPlus/DataWater.hh
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/WaterManager.cc
  src/EnergyPlus/WaterManager.hh
Labels: DoNotPublish

#7978 Remove FlowLock from Surface GHE
  src/EnergyPlus/SurfaceGroundHeatExchanger.cc
  src/EnergyPlus/SurfaceGroundHeatExchanger.hh
Labels: Defect, Refactoring

#7963 Skip interzone diffuse solar exchange factors calculations when no interzone window exists
  src/EnergyPlus/DataReportingFlags.cc
  src/EnergyPlus/DataReportingFlags.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
Labels: Performance, Refactoring

#7980 Fix Controller:WaterCoil chilled water temperature and humidity control
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/RootFinder.cc
  src/EnergyPlus/RootFinder.hh
  src/EnergyPlus/SimAirServingZones.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/RootFinder.unit.cc
Labels: Defect

#8027 Fix latex issues via value added scripts
  .decent_ci-Linux.yaml
  CMakeLists.txt
  doc/CMakeLists.txt
  doc/acknowledgments/src/notices-and-acknowledgments/other-software-included-or-referenced.tex
  doc/cmake/doc-targets.cmake
  doc/engineering-reference/src/climate-sky-and-solar-shading-calculations/climate-calculations.tex
  doc/engineering-reference/src/climate-sky-and-solar-shading-calculations/shading-module.tex
  doc/engineering-reference/src/daylighting-and-window-calculations/time-step-daylighting-calculation.tex
  doc/engineering-reference/src/demand-limiting.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/coils.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/heat-exchangers.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-004/refrigeration-equipment.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/water-systems.tex
  doc/engineering-reference/src/special-modules-reporting/heat-emissions.tex
  doc/getting-started/src/idf-editor-brief-introduction.tex
  doc/input-output-reference/src/energyplus-economics/cost-estimating.tex
  doc/input-output-reference/src/energyplus-economics/currencytype.tex
  doc/input-output-reference/src/hvac-template-objects/group-hvac-templates.tex
  doc/input-output-reference/src/overview/group-advanced-surface-concepts.tex
  doc/input-output-reference/src/overview/group-air-distribution-equipment.tex
  doc/input-output-reference/src/overview/group-air-distribution.tex
  doc/input-output-reference/src/overview/group-air-path.tex
  doc/input-output-reference/src/overview/group-airflow-network.tex
  doc/input-output-reference/src/overview/group-coil-cooling-dx.tex
  doc/input-output-reference/src/overview/group-condenser-equipment.tex
  doc/input-output-reference/src/overview/group-daylighting.tex
  doc/input-output-reference/src/overview/group-demand-limiting-controls.tex
  doc/input-output-reference/src/overview/group-electric-load-center-generator.tex
  doc/input-output-reference/src/overview/group-evaporative-coolers.tex
  doc/input-output-reference/src/overview/group-fans.tex
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  doc/input-output-reference/src/overview/group-location-climate-weather-file-access.tex
  doc/input-output-reference/src/overview/group-operational-faults.tex
  doc/input-output-reference/src/overview/group-performance-tables.tex
  doc/input-output-reference/src/overview/group-plant-equipment.tex
  doc/input-output-reference/src/overview/group-pumps.tex
  doc/input-output-reference/src/overview/group-radiative-convective-units.tex
  doc/input-output-reference/src/overview/group-room-air-models.tex
  doc/input-output-reference/src/overview/group-simulation-parameters.tex
  doc/input-output-reference/src/overview/group-system-availability-managers.tex
  doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex
  doc/input-output-reference/src/overview/group-unitary-equipment.tex
  doc/input-output-reference/src/overview/group-variable-refrigerant-flow-equipment.tex
  doc/input-output-reference/src/overview/group-water-heaters.tex
  doc/input-output-reference/src/overview/group-zone-controls-thermostats.tex
  doc/input-output-reference/src/overview/group-zone-equipment.tex
  doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
  doc/interface-developer/src/input-details/idd-conventions.tex
  doc/module-developer/src/energyplus-services/input-services.tex
  doc/module-developer/src/energyplus-services/other-useful-utilities.tex
  doc/output-details-and-examples/src/output-files/eplusout-eio.tex
  doc/plant-application-guide/src/example-01-chiller-and-condenser-loops/condenser-loop.tex
  doc/tips-and-tricks-using-energyplus/src/input/getting-data-from-window-program.tex
  doc/tips-and-tricks-using-energyplus/src/schedule-and-availability-manager/schedule-and-availability-manager.tex
  doc/tools/parse_latex_log.py
  doc/using-energyplus-for-compliance/src/introduction/tabular-summary-reports.tex
Labels: Defect, Documentation

#8052 Global AirloopHVACDOAS
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/AirLoopHVACDOAS.hh
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/ReportSizingManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
Labels: Refactoring

#7884 Assign Fan AirLoopNum even if fan is not yet activated
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/AirflowNetworkBalanceManager.hh
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: AirflowNetwork, Defect, NotIDDChange

#8089 Clarify VRF engineering documentation and move essentials content to source directory
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/coils.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/air-system-humidifiers.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/variable-refrigerant-flow-heat-pumps.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-004/setpoint-managers.tex
  doc/essentials/essentials.tex
  doc/essentials/src/title.tex
  doc/input-output-reference/src/overview/group-simulation-parameters.tex
Labels: Defect, Documentation

#8067 Add Boiler Efficiency output for Boiler objects
  doc/input-output-reference/src/overview/group-plant-equipment.tex
  src/EnergyPlus/BoilerSteam.cc
  src/EnergyPlus/BoilerSteam.hh
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/Boilers.hh
  testfiles/5ZoneSteamBaseboard.idf
  testfiles/5ZoneVAV-Pri-SecLoop.idf
  testfiles/IceStorage-Parallel.idf
  testfiles/IceStorage-Series-ChillerDownstream.idf
  testfiles/IceStorage-Series-ChillerUpstream.idf
  testfiles/IndirectAbsorptionChiller.idf
  testfiles/SteamSystemAutoSize.idf
  tst/EnergyPlus/unit/BoilerHotWater.unit.cc
  tst/EnergyPlus/unit/BoilerSteam.unit.cc
Labels: Defect, NotIDDChange

#8090 Finish removing gio::write()
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Solver.hpp
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataDaylighting.hh
  src/EnergyPlus/DataGlobals.cc
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/DataStringGlobals.hh
  src/EnergyPlus/DataStringGlobals.in.cc
  src/EnergyPlus/DataTimings.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/GroundTemperatureModeling/SiteBuildingSurfaceGroundTemperatures.cc
  src/EnergyPlus/GroundTemperatureModeling/SiteDeepGroundTemperatures.cc
  src/EnergyPlus/GroundTemperatureModeling/SiteShallowGroundTemperatures.cc
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HVACControllers.hh
  src/EnergyPlus/OutputFiles.cc
  src/EnergyPlus/OutputFiles.hh
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/Psychrometrics.hh
  src/EnergyPlus/RootFinder.cc
  src/EnergyPlus/RootFinder.hh
  src/EnergyPlus/TARCOGArgs.cc
  src/EnergyPlus/TARCOGArgs.hh
  src/EnergyPlus/TARCOGMain.cc
  src/EnergyPlus/TARCOGOutput.cc
  src/EnergyPlus/TARCOGOutput.hh
  src/EnergyPlus/ThermalEN673Calc.cc
  src/EnergyPlus/ThermalEN673Calc.hh
  src/EnergyPlus/ThermalISO15099Calc.cc
  src/EnergyPlus/ThermalISO15099Calc.hh
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/api/EnergyPlusPgm.cc
  third_party/ObjexxFCL/CMakeLists.txt
  third_party/ObjexxFCL/src/ObjexxFCL/Write.cc
  third_party/ObjexxFCL/src/ObjexxFCL/Write.fwd.hh
  third_party/ObjexxFCL/src/ObjexxFCL/Write.hh
  third_party/ObjexxFCL/src/ObjexxFCL/gio.cc
  third_party/ObjexxFCL/src/ObjexxFCL/gio.hh
  third_party/ObjexxFCL/tst/unit/Write.unit.cc
Labels: Refactoring

#8080 Global ZonePlenum
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/GeneralRoutines.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/InternalHeatGains.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/PurchasedAirManager.cc
  src/EnergyPlus/ReturnAirPathManager.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.hh
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZonePlenum.cc
  src/EnergyPlus/ZonePlenum.hh
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/HVACMultiSpeedHeatPump.unit.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
  tst/EnergyPlus/unit/HybridModel.unit.cc
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
  tst/EnergyPlus/unit/PurchasedAirManager.unit.cc
  tst/EnergyPlus/unit/SetPointManager.unit.cc
  tst/EnergyPlus/unit/SimAirServingZones.unit.cc
  tst/EnergyPlus/unit/ZoneContaminantPredictorCorrector.unit.cc
  tst/EnergyPlus/unit/ZonePlenum.unit.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Refactoring

#8043 AirflowNetwork Miscellaneous Refactors
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Elements.hpp
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Solver.hpp
  src/EnergyPlus/AirflowNetwork/src/Elements.cpp
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/AirflowNetworkBalanceManager.hh
  src/EnergyPlus/CrossVentMgr.cc
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/AdvancedAFN.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkSolver.unit.cc
  tst/EnergyPlus/unit/HybridModel.unit.cc
Labels: AirflowNetwork, Refactoring

#8058 Fix hybridevap solution space searching
  src/EnergyPlus/HybridEvapCoolingModel.cc
  src/EnergyPlus/HybridEvapCoolingModel.hh
  tst/EnergyPlus/unit/UnitaryHybridAirConditioner.unit.cc
Labels: Defect, NotIDDChange

#8060 Global ChilledCeilingPanelSimple
  src/EnergyPlus/BranchNodeConnections.cc
  src/EnergyPlus/BranchNodeConnections.hh
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ChilledCeilingPanelSimple.hh
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/ChilledCeilingPanelSimple.unit.cc
Labels: Refactoring

#8023 #7814 - Daylight savings time leading to incorrect season for tariff calculation
  src/EnergyPlus/EconomicTariff.cc
  tst/EnergyPlus/unit/EconomicTariff.unit.cc
Labels: Defect, NotIDDChange, OutputChange

#8105 Fix current_time Function in Python API
  src/EnergyPlus/api/datatransfer.h
  src/EnergyPlus/api/datatransfer.py
Labels: Defect

#8018 Separate Infiltration from Natural Ventilation for AirflowNetwork
  doc/input-output-reference/src/overview/group-airflow-network.tex
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Elements.hpp
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: Defect

#8077 Support Electric Heating Coil in FanCoilUnit with MultiSpeedFan Capacity Control
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/FanCoilUnits.hh
  tst/EnergyPlus/unit/FanCoilUnits.unit.cc
Labels: Defect, NewFeature

#7981 Obtain same results with and without EMS Construction:ComplexFenestrationState
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
Labels: Defect

#8076 Global CondenserLoopTowers
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/ChillerReformulatedEIR.hh
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/CondenserLoopTowers.hh
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/TempSolveRoot.cc
  tst/EnergyPlus/unit/BoilerHotWater.unit.cc
  tst/EnergyPlus/unit/ChillerElectric.unit.cc
  tst/EnergyPlus/unit/ChillerElectricEIR.unit.cc
  tst/EnergyPlus/unit/CondenserLoopTowers.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Refactoring

#8096 Global zone dehumidifier
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/BaseboardElectric.hh
  src/EnergyPlus/BaseboardRadiator.hh
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ChilledCeilingPanelSimple.hh
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/ExteriorEnergyUse.cc
  src/EnergyPlus/ExteriorEnergyUse.hh
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/GeneralRoutines.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/PurchasedAirManager.cc
  src/EnergyPlus/ReturnAirPathManager.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.hh
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/ZoneAirLoopEquipmentManager.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneDehumidifier.cc
  src/EnergyPlus/ZoneDehumidifier.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/RoomAirflowNetwork.unit.cc
Labels: Refactoring

#8024 Fix #8022 - ScheduleManager::GetCurrentScheduleValue and LookUpScheduleValue return different results
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/ScheduleManager.hh
  src/EnergyPlus/SolarShading.cc
  tst/EnergyPlus/unit/EconomicTariff.unit.cc
  tst/EnergyPlus/unit/ScheduleManager.unit.cc
Labels: Defect, NotIDDChange

#7993 Provide accurate value of RatedInletAirHumRat in DXCoils
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.hh
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/ReportSizingManager.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#7916 Use correct argument to calculate hg in AirflowNetwork
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: Defect

#8097 Global ZoneContaminantPredictorCorrector
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.hh
Labels: Refactoring

#8072 Fix HeatPump:PlantLoop:EIR:* Inlet Temperatures
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Defect

#8098 Global ZoneAirLoopEquipmentManager
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SingleDuct.hh
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/ZoneAirLoopEquipmentManager.cc
  src/EnergyPlus/ZoneAirLoopEquipmentManager.hh
  tst/EnergyPlus/unit/AirTerminalSingleDuct.unit.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctConstantVolumeNoReheat.unit.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctPIUReheat.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
  tst/EnergyPlus/unit/DualDuct.unit.cc
  tst/EnergyPlus/unit/HVACMultiSpeedHeatPump.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
  tst/EnergyPlus/unit/PoweredInductionUnits.unit.cc
  tst/EnergyPlus/unit/SetPointManager.unit.cc
  tst/EnergyPlus/unit/SimAirServingZones.unit.cc
  tst/EnergyPlus/unit/SingleDuct.unit.cc
  tst/EnergyPlus/unit/SizeWaterHeatingCoil.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/VAVDefMinMaxFlow.unit.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Refactoring

#8073 Prevent Kiva exposed perimeter warning
  src/EnergyPlus/SurfaceGeometry.cc
Labels: Defect

#8115 Fixes AirTerminal Mixer used with FanCoilUnit does not respond to fan availability schedule
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/FanCoilUnits.hh
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
Labels: Defect
