Repository NREL/EnergyPlus, pull requests merged in 2021-04, with the labels that each got.

#8696 Fix Alternate Configurations Build
  .github/workflows/linux_build.yml
  src/EnergyPlus/PsychCacheData.hh
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/Psychrometrics.hh
  src/EnergyPlus/api/EnergyPlusPgm.cc
Labels: Defect, DoNotPublish

#8702 Add a new test file to test multi shaded window in the same enclosure
  testfiles/PurchAirWindowBlind.idf
Labels: Defect

#8681 Fix issue #8680
  src/EnergyPlus/SolarShading.cc
Labels: Defect

#8692 Multi-dimensional array reordering and refactoring
  src/EnergyPlus/Construction.cc
  src/EnergyPlus/Construction.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Performance

#8711 Add clang format action
  .github/workflows/clang-format-check.yml
  scripts/dev/verify_file_formatting.sh
  scripts/dev/verify_formatting.sh
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/Construction.hh
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/PipeHeatTransfer.cc
  src/EnergyPlus/Plant/LoopSide.cc
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManager.cc
  src/README.md
  tst/EnergyPlus/unit/InputProcessor.unit.cc
Labels: DoNotPublish

#8712 Greenify CI Results
  .decent_ci-Linux.yaml
  testfiles/CMakeLists.txt
Labels: DoNotPublish

#8674 Storm window refactoring
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/EcoRoofManager.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Performance

#8717 format cleanup
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/EcoRoofManager.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/WindowManager.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: DoNotPublish

#8689 Separate Infiltration from Natural Ventilation Flows for AirflowNetwork
  doc/input-output-reference/src/overview/group-airflow-network.tex
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Elements.hpp
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/AirflowNetworkBalanceManager.hh
  src/EnergyPlus/CrossVentMgr.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  testfiles/AirflowNetwork3zVent.idf
  testfiles/AirflowNetwork3zVentAutoWPC.idf
  testfiles/AirflowNetwork_MultiAirLoops.idf
  testfiles/AirflowNetwork_MultiZone_SmallOffice.idf
  testfiles/AirflowNetwork_MultiZone_SmallOffice_CoilHXAssistedDX.idf
  testfiles/AirflowNetwork_MultiZone_SmallOffice_GenericContam.idf
  testfiles/AirflowNetwork_MultiZone_SmallOffice_HeatRecoveryHXSL.idf
  testfiles/AirflowNetwork_Multizone_HorizontalOpening.idf
  testfiles/EMSAirflowNetworkOpeningControlByHumidity.idf
  testfiles/HybridVentilationControl.idf
  testfiles/PythonPluginAirflowNetworkOpeningControlByHumidity.idf
  testfiles/RoomAirflowNetwork.idf
  testfiles/_FanCoilHybridVentAFN.idf
  testfiles/_HybridVentilationControlGlobalAN.idf
  testfiles/_HybridVentilationControl_MinTime.idf
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: Defect

#8704 Coil:Cooling:DX cleanup
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.hh
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.hh
Labels: Defect

#8697 ZoneTempPredictorCorrector State Variable Cleanup using Local Reference Variables
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
Labels: Refactoring

#8726 Restructure unitary system get input
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
Labels: Refactoring

#8734 Fix ObjexxFCL maxloc bug
  third_party/ObjexxFCL/src/ObjexxFCL/Array.functions.hh
Labels: Defect, DoNotPublish

#8685 Unit test for Outdoor Air Details report
  tst/EnergyPlus/unit/SystemReports.unit.cc
Labels: DoNotPublish

#8677 Fix uninit water mains
  src/EnergyPlus/WeatherManager.hh
Labels: Defect

#8454 Airflow Network Default Behavior Enhancements
  design/FY2021/AFNDefaultEnhancement.md
  doc/input-output-reference/src/overview/group-airflow-network.tex
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Elements.hpp
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: NewFeature

#8664 Detect arm64 target arch (M1 silicon chips)
  cmake/TargetArch.cmake
  third_party/kiva-ep/cmake/TargetArch.cmake
Labels: DoNotPublish
