Repository NREL/EnergyPlus, pull requests merged in 2021-12, with the labels that each got.

#9185 Enhancing Multi-speed Coil Speed Level Control Actuators
  design/FY2022/NFP-CoilSpeedEMSActuators.md
  doc/ems-application-guide/src/ems-actuators/hvac-systems-001.tex
  src/EnergyPlus/UnitarySystem.cc
  testfiles/CMakeLists.txt
  testfiles/EMSLoadBasedMultiSpeedDXCoilOverrideControl.idf
  testfiles/EMSSetpointBasedMultiSpeedDXCoilOverrideControl.idf
  testfiles/PythonPluginLoadBasedMultiSpeedDXCoilOverrideControl.idf
  testfiles/PythonPluginLoadBasedMultiSpeedDXCoilOverrideControl.py
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: NewFeature

#9101 Correct and update all emissions meter source names from 'Electric' to 'Electricity' for consistency.
  doc/input-output-reference/src/input-for-output.tex
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PollutionModule.cc
  src/Transition/OutputRulesFiles/OutputChanges9-6-0-to-22-1-0.md
  src/Transition/SupportFiles/Report Variables 9-6-0 to 22-1-0.csv
  testfiles/_SmallOffice_Dulles.idf
  testfiles/_SmallOffice_Dulles.mvi
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Defect, NotIDDChange

#9078 Resolve warnings/errors for unreasonable DHW temperatures in Example Files
  src/EnergyPlus/WaterUse.cc
  src/EnergyPlus/WaterUse.hh
  testfiles/ASHRAE901_ApartmentHighRise_STD2019_Denver.idf
  testfiles/ASHRAE901_Hospital_STD2019_Denver.idf
  testfiles/ASHRAE901_HotelLarge_STD2019_Denver.idf
  testfiles/ASHRAE901_HotelSmall_STD2019_Denver.idf
  testfiles/ASHRAE901_OfficeLarge_STD2019_Denver.idf
  testfiles/ASHRAE901_OfficeMedium_STD2019_Denver.idf
  testfiles/ASHRAE901_OfficeSmall_STD2019_Denver.idf
  testfiles/ASHRAE901_OutPatientHealthCare_STD2019_Denver.idf
  testfiles/ASHRAE901_RestaurantFastFood_STD2019_Denver.idf
  testfiles/ASHRAE901_RestaurantSitDown_STD2019_Denver.idf
  testfiles/ASHRAE901_SchoolPrimary_STD2019_Denver.idf
  testfiles/ASHRAE901_SchoolSecondary_STD2019_Denver.idf
  testfiles/HeatPumpWaterHeater.idf
  testfiles/HeatPumpWaterHeaterStratified.idf
  testfiles/PerformancePrecision_ASHRAE9012016_SchoolSecondary_Denver.idf
  testfiles/RefBldgLargeHotelNew2004_Chicago.idf
  testfiles/RefBldgSmallHotelNew2004_Chicago.idf
  testfiles/SingleFamilyHouse_HP_Slab.idf
  testfiles/SingleFamilyHouse_HP_Slab_Dehumidification.idf
  tst/EnergyPlus/unit/WaterUse.unit.cc
Labels: Defect, NotIDDChange

#9089 Fix Emission Output Variable Names "Environmental Impact OtherFuel1 CO2 Water Consumption Volume" and "Environmental Impact OtherFuel2 CO2 Water Consumption Volume"
  src/EnergyPlus/PollutionModule.cc
  src/Transition/OutputRulesFiles/OutputChanges9-6-0-to-22-1-0.md
  src/Transition/SupportFiles/Report Variables 9-6-0 to 22-1-0.csv
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/PollutionModule.unit.cc
Labels: Defect, NotIDDChange

#9208 Fix barometric pressure in some DX coil unit tests
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#9210 Convert too-big raw idf string to delimited string
  tst/EnergyPlus/unit/PollutionModule.unit.cc
Labels: DoNotPublish

#9151 CondFD Surface Heat Source Actuators
  .github/workflows/clang-format-check.yml
  design/FY2022/NFP-CondFDHeatSinkActuators.md
  doc/ems-application-guide/src/ems-actuators/thermal-envelope.tex
  doc/input-output-reference/src/overview/group-surface-construction-elements.tex
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.hh
  testfiles/PythonPlugin1ZoneUncontrolledCondFD.idf
  testfiles/PythonPlugin1ZoneUncontrolledCondFD.py
Labels: NewFeature
