Repository NREL/EnergyPlus, pull requests merged in 2021-01, with the labels that each got.

#8447 Add Missing clear_state for HVACInterfaceMgr
  src/EnergyPlus/Data/EnergyPlusData.cc
Labels: DoNotPublish

#8437 Global SimAirServingZones
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DXCoils.hh
  src/EnergyPlus/DataHVACGlobals.cc
  src/EnergyPlus/DataHVACGlobals.hh
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/EconomicLifeCycleCost.cc
  src/EnergyPlus/EconomicLifeCycleCost.hh
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/FanCoilUnits.hh
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/Fans.hh
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/Furnaces.hh
  src/EnergyPlus/HVACDXHeatPumpSystem.cc
  src/EnergyPlus/HVACDXHeatPumpSystem.hh
  src/EnergyPlus/HVACDXSystem.cc
  src/EnergyPlus/HVACDXSystem.hh
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/HVACHXAssistedCoolingCoil.hh
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.hh
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.hh
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixedAir.hh
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/PackagedTerminalHeatPump.hh
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/EconomicLifeCycleCost.unit.cc
  tst/EnergyPlus/unit/HVACControllers.unit.cc
  tst/EnergyPlus/unit/HVACMultiSpeedHeatPump.unit.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
  tst/EnergyPlus/unit/SecondaryDXCoils.unit.cc
  tst/EnergyPlus/unit/StandardRatings.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Refactoring

#8448 Delete Unsupported FlowLock Logic Branch
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.cc
Labels: DoNotPublish

#8403 Refactoring of CalcInteriorSolarDistributions and reduce condition checkings
  src/EnergyPlus/DataEnvironment.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarShading.cc
Labels: Refactoring

#8417 CondFD Surface Actuators
  design/FY2021/CondFD_Layers.png
  design/FY2021/NFP-CondFDSurfaceEMSActuators.md
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.hh
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
  src/EnergyPlus/api/datatransfer.cc
  src/EnergyPlus/api/datatransfer.h
  src/EnergyPlus/api/datatransfer.py
  testfiles/CMakeLists.txt
  testfiles/PythonPlugin1ZoneUncontrolledCondFD.idf
  testfiles/PythonPlugin1ZoneUncontrolledCondFD.py
Labels: NewFeature
