Repository NREL/EnergyPlus, pull requests merged in 2021-09, with the labels that each got.

#9035 Hot fix - Set Conv Report Vars
  src/EnergyPlus/ConvectionCoefficients.cc
Labels: DoNotPublish

#8906 Add Kiva deep ground depth check and recalculation if needed
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.hh
  tst/EnergyPlus/unit/HeatBalanceKivaManager.unit.cc
Labels: Defect, NotIDDChange

#8953 Modify HVACTemplate:Zone:BaseboardHeat Rated Average Water Temperature
  src/ExpandObjects/epfilter.f90
Labels: Defect, NotIDDChange

#8808 Add warnings/errors for unreasonable DHW temperatures for WaterUse:Equipment
  src/EnergyPlus/WaterUse.cc
  src/EnergyPlus/WaterUse.hh
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/WaterUse.unit.cc
Labels: Defect, NotIDDChange

#9037 Update geojson to S3
  weather/master.geojson
Labels: Refactoring

#8952 Fix #8847 - Microsoft Edge or Google Chrome web browser having problems in fully displaying HVAC schematics SVG files
  src/HVAC-Diagram/HVAC-Diagram-Main.f90
Labels: Defect, AuxiliaryTool

#8892 Add check for maxNumRefPtInAnyZone before calculating daylighting interior illuminance
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
Labels: Defect, NotIDDChange

#9011 Correction of Low Temperature Hydronic Radiant System Tube Spacing Issues
  doc/input-output-reference/src/overview/group-surface-construction-elements.tex
  src/EnergyPlus/Construction.cc
  src/EnergyPlus/Construction.hh
  src/EnergyPlus/HeatBalanceManager.cc
  tst/EnergyPlus/unit/DataHeatBalance.unit.cc
Labels: Defect

#9040 Hot fix - Convection report vars initialization
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/SurfaceGeometry.cc
Labels: DoNotPublish

#8932 Consolidate HVAC radiant surface variables
  doc/engineering-reference/src/climate-sky-and-solar-shading-calculations/shading-module.tex
  doc/engineering-reference/src/daylighting-and-window-calculations/window-calculation-module.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/surface-heat-balance-with-moveable-insulation.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/transparent-insulation-material.tex
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/DataHeatBalFanSys.hh
  src/EnergyPlus/DataHeatBalSurface.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceHAMTManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/SolarCollectors.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Defect, NotIDDChange

#8923 ElectricLoadCenter:Storage:Simple Zero Efficiency Fix
  doc/input-output-reference/src/overview/group-electric-load-center-generator.tex
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/ElectricPowerServiceManager.hh
  tst/EnergyPlus/unit/ElectricPowerServiceManager.unit.cc
Labels: Defect, IDDChange

#8997 Correction of Defect in Transition Program and Recent Bug Fix
  src/Transition/CreateNewIDFUsingRulesV9_6_0.f90
  src/Transition/VCompareGlobalRoutines.f90
Labels: Defect

#8992 Update the cubic spline interpolation for PerformancePrecisionTradeoffs
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/Psychrometrics.hh
  tst/EnergyPlus/unit/Psychrometrics.unit.cc
Labels: Performance

#9043 Add Celsius to Kelvin conversion to the radiation calculation for TDDs
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
Labels: Defect, NotIDDChange

#9024 Change from 24 bit to 20 bit caching for PsyTsatFnPb when using PerformancePrecisionTradeoffs Mode06 or higher
  src/EnergyPlus/PsychCacheData.hh
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/Psychrometrics.hh
  src/EnergyPlus/SimulationManager.cc
Labels: NewFeature

#9003 Crash when using ITE in an Uncontrolled Zone
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/InternalHeatGains.cc
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
Labels: Defect

#8905 Correct Kiva accelerated date calculation to account for run period start date of May 1st
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.hh
  tst/EnergyPlus/unit/HeatBalanceKivaManager.unit.cc
Labels: Defect, NotIDDChange

#8833 Fix #8599 - Incorrect psychrometric calculation causes error
  src/EnergyPlus/DataGlobalConstants.hh
  src/EnergyPlus/General.cc
  src/EnergyPlus/Psychrometrics.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/Psychrometrics.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#9009 FIx #9008 - run clang format and linux_build only on PR to develop or push to develop itself
  .github/workflows/clang-format-check.yml
  .github/workflows/linux_build.yml
Labels: DoNotPublish

#9017 Correct Coil Sizing Summary report of Coil Total Capacity at Ideal Loads Peak
  src/EnergyPlus/ReportCoilSelection.cc
  tst/EnergyPlus/unit/ReportCoilSelection.unit.cc
Labels: Defect, NotIDDChange

#8175 Fix the Thermal Comfort CEN 15251 Running Mean Temperature Calculation
  src/EnergyPlus/ThermalComfort.cc
  tst/EnergyPlus/unit/Resources/ThermalComfortCEN15251Test.epw
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
Labels: Defect

#8949 Profiling based refactoring in heat balance functions
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  src/EnergyPlus/DataHeatBalSurface.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
Labels: Performance

#9007 Fix #8921 - SQL file report for Output:Table:Monthly ColumnName field missing closing curly brace
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabularAnnual.cc
  src/Transition/OutputRulesFiles/OutputChanges9-5-0-to-9-6-0.md
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/OutputReportTabularAnnual.unit.cc
Labels: Defect, NotIDDChange, OutputChange

#9019 Fix various HVACTemplate issues
  src/ExpandObjects/epfilter.f90
Labels: Defect

#8980 Bugfix of Coil:Foo:WaterToAirHeatPump:EquationFit objects always use rated air mass flow rate in calculations
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  src/EnergyPlus/WaterToAirHeatPumpSimple.hh
  tst/EnergyPlus/unit/WaterToAirHeatPumpSimple.unit.cc
Labels: Defect

#8951 Fix AirTerminal:singleDuct:ConstantVolume:FourPipeBeam Minimum OA Reference
  tst/EnergyPlus/unit/HVACFourPipeBeam.unit.cc
Labels: Defect

#8994 Add GetInternalHeatGainsInput call into Kiva function for thermal comfort calculations
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/HeatBalanceKivaManager.unit.cc
Labels: Defect, NotIDDChange

#8936 Fix Sizing:System Heating Design Capacity Method FractionOfAutosizedHeatingCapacity
  src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc
  src/EnergyPlus/Autosizing/HeatingWaterDesCoilLoadUsedForUASizing.cc
  src/EnergyPlus/Autosizing/HeatingWaterDesCoilLoadUsedForUASizing.hh
  tst/EnergyPlus/unit/Autosizing/HeatingWaterDesCoilLoadUsedForUASizing.unit.cc
Labels: Defect, NotIDDChange

#9016 Consolidate Surface Reporting
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataHeatBalSurface.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceHAMTManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/PlantPipingSystemsManager.cc
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Defect, DoNotPublish, Refactoring, NotIDDChange

#9046 Code compliant chiller performance curves
  datasets/CodeCompliantEquipment.idf
  design/FY2021/NFP-CodeCompliantEquipmentDataset.md
  design/FY2021/NFP-CodeCompliantEquipmentDataset.png
  doc/output-details-and-examples/src/data-sets/simple-list-data-sets.tex
  tst/EnergyPlus/unit/Datasets.unit.cc
Labels: NewFeature

#8653 Enhancement to the Simple Window Model
  design/FY2021/CrossSecWettedLengthFrame.png
  design/FY2021/Enhancement to Simple Window Model.md
  design/FY2021/FrontViewCrossSecWindowFrame.png
  design/FY2021/ThermalCircuitWindowFrame.png
  design/FY2021/inputU_nominalU.png
  doc/engineering-reference/src/daylighting-and-window-calculations/window-calculation-module.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/inside-heat-balance.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/outside-surface-heat-balance.tex
  doc/input-output-reference/src/overview/group-surface-construction-elements.tex
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataHeatBalSurface.hh
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManager.hh
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/ICSCollector.unit.cc
  tst/EnergyPlus/unit/OASystemHWPreheatCoil.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/WindowEquivalentLayer.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: NewFeature, IDDChange

#9055 Fix annoying err file diff
  datasets/CodeCompliantEquipment.idf
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/WindowManager.cc
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: DoNotPublish

#9034 View Factor Discrepancy when Using Autosize for Ground View Factor for Window with Light Shelf
  doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingDevices.hh
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/DaylightingDevices.unit.cc
Labels: Defect

#9068 Fix typo in code compliant equipment dataset
  datasets/CodeCompliantEquipment.idf
Labels: Defect

#9062 Fix #9061 hvac template boiler fuel type check problem
  src/ExpandObjects/epfilter.f90
Labels: Defect

#9057 Miscellaneous Documentation Fixes
  doc/engineering-reference/src/surface-heat-balance-manager-processes/combined-heat-and-moisture-transfer-hamt.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/outside-surface-heat-balance.tex
  doc/input-output-reference/CMakeLists.txt
  doc/input-output-reference/media/image262.png
  doc/input-output-reference/src/energyplus-economics/utilitycost-ratchet.tex
  doc/input-output-reference/src/overview.tex
  doc/input-output-reference/src/overview/group-electric-load-center-generator.tex
  doc/input-output-reference/src/overview/group-location-climate-weather-file-access.tex
  doc/input-output-reference/src/overview/group-node-branch-management.tex
  doc/input-output-reference/src/overview/group-plant-condenser-flow-control.tex
  doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex
  doc/input-output-reference/src/overview/group-zone-equipment.tex
Labels: Defect, Documentation

#9054 Fix bug when writing binary files
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/FileSystem.hh
  src/EnergyPlus/GroundHeatExchangers.cc
  src/EnergyPlus/IOFiles.cc
  src/EnergyPlus/IOFiles.hh
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/ResultsFramework.cc
  src/EnergyPlus/ResultsFramework.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SimulationManager.hh
  src/EnergyPlus/UtilityRoutines.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.hh
Labels: DoNotPublish

#9025 Water Thermal Tank Resulting in Negative Electric Consumption Fix
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterThermalTanks.hh
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Defect

#9070 Enable Group Runs in EP-Launch 3 Workflow
  .gitignore
  workflows/energyplus.py
Labels: NewFeature

#9064 Improve Spaces example file and implement DesignSpecification:OutdoorAir:SpaceList everywhere
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/DataZoneEquipment.hh
  src/EnergyPlus/DualDuct.cc
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HybridUnitaryAirConditioners.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/PurchasedAirManager.cc
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  testfiles/5ZoneAirCooledWithSpaces.idf
  tst/EnergyPlus/unit/DataZoneEquipment.unit.cc
  tst/EnergyPlus/unit/UnitaryHybridAirConditioner.unit.cc
Labels: NewFeature

#9071 Some more docs updates
  doc/engineering-reference/src/building-system-simulation-system-manager/primary-air-system-simulation.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/combined-heat-and-moisture-transfer-hamt.tex
  doc/input-output-reference/src/overview/group-air-distribution.tex
  doc/input-output-reference/src/overview/group-air-path.tex
  doc/input-output-reference/src/overview/group-condenser-equipment.tex
  doc/input-output-reference/src/overview/group-electric-load-center-generator.tex
  doc/input-output-reference/src/overview/group-node-branch-management.tex
  doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
  testfiles/GSHP-GLHE-CalcGFunctions-cpg.idf
  testfiles/GSHP-GLHE-CalcGFunctions.idf
  testfiles/ZoneCoupledGroundHTSlabInGrade.idf
  testfiles/ZoneCoupledGroundHTSlabOnGrade.idf
Labels: Defect

#8865 Adding Multispeed Coil Speed Level Control Actuators
  design/FY2021/NFP-CoilSpeedEMSActuators.md
  doc/ems-application-guide/src/ems-actuators/hvac-systems-001.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/coils.tex
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.hh
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  testfiles/CMakeLists.txt
  testfiles/EMSMultiSpeedHeatPumpOverrideControl.idf
  testfiles/PythonPluginMultiSpeedHeatPumpOverrideControl.idf
  testfiles/PythonPluginMultiSpeedHeatPumpOverrideControl.py
  tst/EnergyPlus/unit/HVACMultiSpeedHeatPump.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: NewFeature

#9067 Reduce daylighting allocations
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/HeatBalanceManager.cc
Labels: Performance

#9065 Representative surface heat balance calculations (follow up)
  doc/input-output-reference/src/overview/group-simulation-parameters.tex
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: DoNotPublish, NewFeature, Performance

#8979 Modify approximate view factor calculation logic
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  testfiles/5ZoneAirCooled.idf
  tst/EnergyPlus/unit/HeatBalanceIntRadExchange.unit.cc
Labels: Defect

#9076 Fix HVACDiagram Error Messages
  src/HVAC-Diagram/HVAC-Diagram-Main.f90
Labels: Defect

#9077 Use specified program root for API usage
  src/EnergyPlus/PluginManager.cc
Labels: Defect

#9081 EnergyPlus crash when CoilSystem:Cooling:DX or AirloopHVAC:UnitarySystem is used in OutdoorAirSystem
  src/EnergyPlus/AirLoopHVACDOAS.cc
Labels: Defect

#9079 macOS 11 Release Packages
  .github/workflows/mac_release.yml
Labels: DoNotPublish

#9086 Hotfix #9085 - DaylightMaps output is broken in SQLite in 9.6.0-rc3
  src/EnergyPlus/SQLiteProcedures.cc
  tst/EnergyPlus/unit/SQLite.unit.cc
Labels: Defect

#9088 Final Prep for 9.6 Release
  cmake/Install.cmake
  doc/essentials/src/essentials.tex
  doc/tips-and-tricks-using-energyplus/src/input/converting-older-version-energyplus-files.tex
  doc/tips-and-tricks-using-energyplus/src/introduction-support/energyplus-support.tex
  doc/tools/parse_output_variables.py
  release/Deprecation.html
  release/readme.html
  src/EnergyPlus/InternalHeatGains.cc
  src/Transition/SupportFiles/Report Variables 9-5-0 to 9-6-0.csv
  workflows/energyplus.py
Labels: DoNotPublish

#9109 Change to Edwin for aging PR notification
  .decent_ci.yaml
Labels: DoNotPublish
