Repository NREL/EnergyPlus, pull requests merged in 2021-11, with the labels that each got.

#9115 Corrected a link in the readme
  README.md
Labels: Defect

#9129 Fix Bugs in Emmel and Blocken Convection Algorithms
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
Labels: Defect

#9166 Convert remaining `const` `int`/`double` in `state` to `constexpr`
  src/EnergyPlus/DataPhotovoltaics.hh
  src/EnergyPlus/DataSystemVariables.hh
  src/EnergyPlus/DataTimings.cc
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/ElectricPowerServiceManager.hh
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/FanCoilUnits.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/PhotovoltaicThermalCollectors.cc
  src/EnergyPlus/Photovoltaics.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SolarShading.hh
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/SteamCoils.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/SystemAvailabilityManager.hh
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/ThermalComfort.hh
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/TranspiredCollector.hh
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UnitVentilator.hh
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/VentilatedSlab.hh
  src/EnergyPlus/WeatherManager.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
  tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Refactoring

#9179 EIO transition changes for simple glazing
  doc/output-details-and-examples/src/output-files/eplusout-eio.tex
  src/Transition/OutputRulesFiles/OutputChanges9-6-0-to-9-7-0.md
Labels: Defect, Documentation

#9162 Fix multiple absorption chillerheater objects input processing
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  tst/EnergyPlus/unit/ChillerExhaustAbsorption.unit.cc
Labels: Defect

#9192 EPLaunch classic to support two digit version numbers
  bin/EP-Launch/EP-Launch.exe
  src/EP-Launch/epl-ui.frm
  src/EP-Launch/epl.vbp
  src/EP-Launch/epl.vbw
  src/EP-Launch/frmAbout.frm
Labels: Defect

#9163 Enum Refactor: DataZoneEquipment
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/BaseboardElectric.cc
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataAirLoop.hh
  src/EnergyPlus/DataDefineEquip.hh
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/DataZoneEquipment.hh
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/HVACStandAloneERV.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HybridUnitaryAirConditioners.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/PackagedTerminalHeatPump.hh
  src/EnergyPlus/PurchasedAirManager.cc
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/ReturnAirPathManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SingleDuct.hh
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/UnitHeater.cc
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WindowAC.cc
  src/EnergyPlus/ZoneAirLoopEquipmentManager.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneEquipmentManager.hh
  src/EnergyPlus/ZonePlenum.cc
  src/EnergyPlus/ZonePlenum.hh
  tst/EnergyPlus/unit/AirTerminalSingleDuctConstantVolumeNoReheat.unit.cc
  tst/EnergyPlus/unit/HVACControllers.unit.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/ReportCoilSelection.unit.cc
  tst/EnergyPlus/unit/SingleDuct.unit.cc
  tst/EnergyPlus/unit/SystemReports.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/ZoneHVACEvaporativeCooler.unit.cc
Labels: Refactoring

#9182 Add workflow file for ConvertInputFormat
  CMakeLists.txt
  workflows/convert_input_format.py
Labels: NewFeature

#9170 Convert `int constexpr` to `enum` : EconomicLifeCycleCost.*
  src/EnergyPlus/EconomicLifeCycleCost.cc
  src/EnergyPlus/EconomicLifeCycleCost.hh
  src/EnergyPlus/UtilityRoutines.hh
  tst/EnergyPlus/unit/EconomicLifeCycleCost.unit.cc
Labels: Refactoring

#9194 Add custom_check script for case label parentheses
  scripts/dev/check_for_switch_case_parentheses.py
  scripts/dev/custom_check.sh
  src/EnergyPlus/BoilerSteam.cc
  src/EnergyPlus/EconomicLifeCycleCost.cc
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/Plant/LoopSide.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantCondLoopOperation.cc
  src/EnergyPlus/PlantUtilities.cc
  src/EnergyPlus/PoweredInductionUnits.cc
  src/EnergyPlus/Pumps.cc
  src/EnergyPlus/WaterThermalTanks.cc
Labels: DoNotPublish
