Repository NREL/EnergyPlus, pull requests merged in 2021-03, with the labels that each got.

#8573 Fix #8484 - Flush all files when Running via API before finish
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/IOFiles.cc
  src/EnergyPlus/IOFiles.hh
  src/EnergyPlus/UtilityRoutines.cc
  tst/EnergyPlus/api/test_OutputFiles.py
Labels: APIChange, Defect, NotIDDChange

#8570 Static lib ssc
  CMakeLists.txt
  cmake/Install.cmake
  cmake/PythonFixUpOnMac.cmake
  third_party/ssc/ssc/CMakeLists.txt
Labels: DoNotPublish

#8569 Cleaning up LowTemperatureRadiantSystems
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/LowTempRadiantSystem.hh
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
Labels: Defect

#8544 Fix #8542 - Escape HTML characters.
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect, NotIDDChange

#8561 PMV follow up
  doc/engineering-reference/CMakeLists.txt
  doc/engineering-reference/media/ankle_draft.png
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/occupant-thermal-comfort.tex
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/ThermalComfort.hh
Labels: Defect, Documentation

#8511 #8492 #8513 - Add a FuelCellElectricGenerator Unit Test and do not zero out Constant Skin Loss Rate in Generator:FuelCell:PowerModule
  doc/input-output-reference/src/overview/group-electric-load-center-generator.tex
  src/EnergyPlus/FuelCellElectricGenerator.cc
  src/EnergyPlus/FuelCellElectricGenerator.hh
  tst/EnergyPlus/unit/FuelCellElectricGenerator.unit.cc
Labels: Defect, NotIDDChange

#8571 UnitarySystem used as single zone vav will crash with blank no load air flow method
  doc/input-output-reference/src/overview/group-unitary-equipment.tex
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect, NotIDDChange

#8574 Fix #8483 - pyenergyplus: system exit called when energyplus can't run
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/CommandLineInterface.hh
  src/EnergyPlus/api/EnergyPlusPgm.cc
  tst/EnergyPlus/api/test_SysExit.py
Labels: APIChange, Defect, NotIDDChange

#8327 Expand access for ancillary power inputs and total electricity rate/energy to all coil types in UnitarySystem
  doc/input-output-reference/src/overview/group-unitary-equipment.tex
  src/EnergyPlus/DataHVACGlobals.cc
  src/EnergyPlus/DataHVACGlobals.hh
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/HeatingCoils.hh
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/WaterToAirHeatPump.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: NewFeature, NotIDDChange

#8540 TDD surface reordering and bug fixing
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/MundtSimMgr.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/RoomAirModelUserTempPattern.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/ThermalChimney.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/HybridModel.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/PurchasedAirManager.unit.cc
  tst/EnergyPlus/unit/RoomAirflowNetwork.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Defect, Performance

#8583 Global EvaporativeCoolers
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/EvaporativeCoolers.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/EvaporativeCoolers.unit.cc
  tst/EnergyPlus/unit/ZoneHVACEvaporativeCooler.unit.cc
Labels: Refactoring

#8501 Pass correct mass flow rate to calculate flow fraction for DX coil performance curves
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#8585 Global EcoRoofManager, RoomAirModelManager, InternalHeatGains, HVACDXHeatPumpSystem, and HVACUnitaryBypassVAV
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/EcoRoofManager.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/HVACDXHeatPumpSystem.cc
  src/EnergyPlus/HVACDXHeatPumpSystem.hh
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.hh
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/InternalHeatGains.hh
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/RoomAirModelManager.hh
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/DElightManager.unit.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
Labels: Refactoring

#8582 HotFix #8581: make AirLoopHVAC:DedicatedOutdoorAirSystem's airloophvac_name extension case-insentive
  src/EnergyPlus/AirLoopHVACDOAS.cc
  testfiles/SmallOffice_CentralDOAS.idf
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
Labels: Defect, NotIDDChange

#8519 Ideal loads air system ems override enthalpy update correction
  src/EnergyPlus/PurchasedAirManager.cc
  tst/EnergyPlus/unit/PurchasedAirManager.unit.cc
Labels: Defect

#8595 Fix VS2017 compile error
  src/EnergyPlus/EvaporativeCoolers.cc
Labels: DoNotPublish

#8588 Global DataSystemVariables+FaultsManager
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/DataSystemVariables.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DisplayRoutines.cc
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/FaultsManager.hh
  src/EnergyPlus/GroundHeatExchangers.cc
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HVACDXHeatPumpSystem.cc
  src/EnergyPlus/HVACDXSystem.cc
  src/EnergyPlus/HVACFan.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACSizingSimulationManager.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SolarReflectionManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/api/EnergyPlusPgm.cc
  tst/EnergyPlus/unit/FaultsManager.unit.cc
  tst/EnergyPlus/unit/GroundHeatExchangers.unit.cc
  tst/EnergyPlus/unit/SimulationManager.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: Refactoring

#7932 Fix plant heat storage tracking
  src/EnergyPlus/HVACInterfaceManager.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/Plant/PlantManager.hh
  tst/EnergyPlus/unit/HVACInterfaceManager.unit.cc
Labels: Defect

#8605 Global HeatBalanceManager+HeatBalanceSurfaceManager+SimAirServingZones
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceManager.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/SimAirServingZones.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
Labels: Refactoring

#8617 Global FanCoilUnits, EcoRoofManager, & SolarReflectionManager
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/EcoRoofManager.hh
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/FanCoilUnits.hh
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/RoomAirModelManager.hh
  src/EnergyPlus/SZVAVModel.cc
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/FanCoilUnits.unit.cc
  tst/EnergyPlus/unit/SZVAVModel.unit.cc
  tst/EnergyPlus/unit/WaterCoils.unit.cc
Labels: Refactoring

#8619 Global Daylighting Manager, External Interface, Erl Processor
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/ExternalInterface.hh
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/RuntimeLanguageProcessor.hh
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/UtilityRoutines.cc
Labels: Refactoring

#8607 Address VS DX cooling coil outlet air condition calculation problem when PLR is zero
  src/EnergyPlus/VariableSpeedCoils.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/VariableSpeedCoils.unit.cc
Labels: Defect

#8622 Global DataHeatBalSurface, InternalHeatGains, and SolarReflectionManager
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  src/EnergyPlus/CrossVentMgr.cc
  src/EnergyPlus/DataHeatBalSurface.cc
  src/EnergyPlus/DataHeatBalSurface.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceHAMTManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/InternalHeatGains.hh
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/MundtSimMgr.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/Photovoltaics.cc
  src/EnergyPlus/PlantPipingSystemsManager.cc
  src/EnergyPlus/PlantPipingSystemsManager.hh
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/SolarReflectionManager.cc
  src/EnergyPlus/SolarReflectionManager.hh
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/ThermalChimney.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/UFADManager.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/DisplacementVentMgr.unit.cc
  tst/EnergyPlus/unit/HeatBalFiniteDiffManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/ICSCollector.unit.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
  tst/EnergyPlus/unit/MoistureBalanceEMPD.unit.cc
  tst/EnergyPlus/unit/RoomAirflowNetwork.unit.cc
  tst/EnergyPlus/unit/ThermalChimney.unit.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Refactoring

#8577 Addresses zone air mass flow balance enforcing problem when there is "balanced" exhaust flow
  doc/input-output-reference/src/overview/group-fans.tex
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Defect

#8626 Fix build error on windows - remove constexpressed externs
  src/EnergyPlus/HeatBalFiniteDiffManager.hh
Labels: DoNotPublish

#8594 Exclude air boundaries and non-used constructions in conduction finite difference
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  tst/EnergyPlus/unit/HeatBalFiniteDiffManager.unit.cc
Labels: Defect

#8560 Address NFP-Zone Air Mass Flow Balance Improvement Followup
  doc/engineering-reference/src/integrated-solution-manager/zone-air-mass-flow-conservation.tex
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataZoneEquipment.hh
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneEquipmentManager.hh
  tst/EnergyPlus/unit/HeatBalFiniteDiffManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: DoNotPublish

#8625 Global-Elements
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Elements.hpp
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Solver.hpp
  src/EnergyPlus/AirflowNetwork/src/Elements.cpp
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/CrossVentMgr.cc
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/ReturnAirPathManager.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkSimulationControl.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkSolver.unit.cc
  tst/EnergyPlus/unit/CrossVentMgr.unit.cc
  tst/EnergyPlus/unit/DOASEffectOnZoneSizing.unit.cc
  tst/EnergyPlus/unit/Furnaces.unit.cc
  tst/EnergyPlus/unit/HybridModel.unit.cc
  tst/EnergyPlus/unit/RoomAirflowNetwork.unit.cc
  tst/EnergyPlus/unit/ZoneContaminantPredictorCorrector.unit.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Refactoring

#8627 Global HVACManager, HVACMultiSpeedHeatPump, and HVACDXHeatPumpSystem
  src/EnergyPlus/HVACDXHeatPumpSystem.cc
  src/EnergyPlus/HVACDXHeatPumpSystem.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACManager.hh
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.hh
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/HVACMultiSpeedHeatPump.unit.cc
Labels: Refactoring

#8630 Deglobalizes a bunch of files.
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/Construction.hh
  src/EnergyPlus/CrossVentMgr.cc
  src/EnergyPlus/DataErrorTracking.cc
  src/EnergyPlus/DataErrorTracking.hh
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataMoistureBalance.cc
  src/EnergyPlus/DataMoistureBalance.hh
  src/EnergyPlus/DataRoomAirModel.cc
  src/EnergyPlus/DataRoomAirModel.hh
  src/EnergyPlus/DataSurfaceColors.cc
  src/EnergyPlus/DataSurfaceColors.hh
  src/EnergyPlus/DataUCSDSharedData.cc
  src/EnergyPlus/DataUCSDSharedData.hh
  src/EnergyPlus/DataWindowEquivalentLayer.cc
  src/EnergyPlus/DataWindowEquivalentLayer.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/DisplacementVentMgr.hh
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceHAMTManager.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/MoistureBalanceEMPDManager.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/Plant/PlantManager.hh
  src/EnergyPlus/PlantCondLoopOperation.cc
  src/EnergyPlus/PlantCondLoopOperation.hh
  src/EnergyPlus/PlantPressureSystem.cc
  src/EnergyPlus/PlantPressureSystem.hh
  src/EnergyPlus/PollutionModule.cc
  src/EnergyPlus/PollutionModule.hh
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/UFADManager.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/WindowEquivalentLayer.cc
  tst/EnergyPlus/unit/CrossVentMgr.unit.cc
  tst/EnergyPlus/unit/DisplacementVentMgr.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/MoistureBalanceEMPD.unit.cc
  tst/EnergyPlus/unit/RoomAirflowNetwork.unit.cc
  tst/EnergyPlus/unit/WindowEquivalentLayer.unit.cc
Labels: Refactoring

#8633 Fix clear_state missing vars in pollution module
  src/EnergyPlus/PollutionModule.hh
Labels: DoNotPublish

#8320 Fix Inlet and Outlet Node idf errors with AirLoopHVAC:UnitarySystem objects cause are not caught, resulting in faulty data members.
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect, NotIDDChange

#8632 Global-SimAirServingZone, HighTemperatureRadiantSystems, HeatRecovery
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/DataSystemVariables.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/FaultsManager.hh
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/Furnaces.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceManager.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/HeatRecovery.hh
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/HighTempRadiantSystem.hh
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/LowTempRadiantSystem.hh
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/ScheduleManager.hh
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/HeatRecovery.unit.cc
  tst/EnergyPlus/unit/HighTempRadiantSystem.unit.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
Labels: Refactoring

#8612 Set default value for OpaqueSkyCover when missing
  src/EnergyPlus/HeatBalanceKivaManager.cc
  tst/EnergyPlus/unit/HeatBalanceKivaManager.unit.cc
  tst/EnergyPlus/unit/Resources/HeatBalanceKivaManagerOSkyTest.epw
Labels: Defect, NotIDDChange

#8629 Global OutputReportTabular, OutputReportTabularAnnual, DXFEarClipping, PVWatts
  src/EnergyPlus/DXFEarClipping.cc
  src/EnergyPlus/DXFEarClipping.hh
  src/EnergyPlus/EarthTube.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/OutputReportTabularAnnual.cc
  src/EnergyPlus/OutputReportTabularAnnual.hh
  src/EnergyPlus/PVWatts.cc
  src/EnergyPlus/PVWatts.hh
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/OutputReportTabularAnnual.unit.cc
  tst/EnergyPlus/unit/PVWatts.unit.cc
Labels: Refactoring

#8592 Pass correct mass flow rate to calculate flow function multiplier for MS DX heating coil
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#8620 Fix idf transition issues in EMS Actuator
  src/Transition/CreateNewIDFUsingRulesV9_3_0.f90
Labels: Defect

#8556 Absorption chillerheater plant loop fixes
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/Plant/Enums.hh
  tst/EnergyPlus/unit/ChillerExhaustAbsorption.unit.cc
  tst/EnergyPlus/unit/ChillerGasAbsorption.unit.cc
Labels: Defect

#8596 Outdoor Air Details Report - part 2
  doc/input-output-reference/src/overview/group-controllers.tex
  doc/input-output-reference/src/standard-output-reports/output-table-summaryreports.tex
  doc/output-details-and-examples/src/output-files/eplustbl-lt-ext-gt.tex
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixedAir.hh
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportPredefined.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/SystemReports.hh
Labels: Defect, NewFeature

#8637 Global HeatingCoils, DualDuct, DataPhotovoltaics & Fix #8635
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/DataPhotovoltaics.cc
  src/EnergyPlus/DataPhotovoltaics.hh
  src/EnergyPlus/DualDuct.cc
  src/EnergyPlus/DualDuct.hh
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/HeatingCoils.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PhotovoltaicThermalCollectors.cc
  src/EnergyPlus/Photovoltaics.cc
  src/EnergyPlus/Photovoltaics.hh
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/DesiccantDehumidifiers.unit.cc
  tst/EnergyPlus/unit/DualDuct.unit.cc
  tst/EnergyPlus/unit/FanCoilUnits.unit.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/HeatingCoils.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
  tst/EnergyPlus/unit/Photovoltaics.unit.cc
  tst/EnergyPlus/unit/SZVAVModel.unit.cc
  tst/EnergyPlus/unit/UnitHeater.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect, Refactoring

#8572 Fix Thermal Comfort zone temperature and humidity lag
  src/EnergyPlus/HVACManager.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
Labels: Defect

#8575 Li-ion battery code and docs updates
  doc/engineering-reference/src/on-site-generation/electric-load-center-distribution-manager.tex
  src/EnergyPlus/ElectricPowerServiceManager.cc
  third_party/ssc/shared/lib_battery.cpp
  third_party/ssc/shared/lib_battery.h
  third_party/ssc/shared/lib_battery_dispatch.cpp
  third_party/ssc/shared/lib_battery_lifetime.cpp
  third_party/ssc/shared/lib_battery_lifetime.h
  third_party/ssc/shared/lib_battery_lifetime_calendar_cycle.cpp
  third_party/ssc/shared/lib_battery_lifetime_calendar_cycle.h
  third_party/ssc/shared/lib_battery_lifetime_nmc.cpp
  third_party/ssc/shared/lib_battery_lifetime_nmc.h
  third_party/ssc/shared/lib_battery_voltage.cpp
  third_party/ssc/shared/lib_util.cpp
  third_party/ssc/shared/lib_utility_rate_equations.cpp
  third_party/ssc/shared/lib_utility_rate_equations.h
  third_party/ssc/shared/logger.cpp
  third_party/ssc/ssc/cmod_battery.cpp
  third_party/ssc/ssc/cmod_battery_stateful.cpp
  third_party/ssc/ssc/cmod_mhk_costs.cpp
  third_party/ssc/ssc/cmod_mhk_tidal.cpp
  third_party/ssc/ssc/cmod_mhk_wave.cpp
  third_party/ssc/ssc/cmod_utilityrate5.cpp
  third_party/ssc/ssc/common.cpp
  third_party/ssc/ssc/core.cpp
  third_party/ssc/ssc/sscapi.cpp
  third_party/ssc/test/input_cases/utility_rate_data/gen_1_yr_residential.csv
  third_party/ssc/test/input_cases/utility_rate_data/load_commercial_large.csv
  third_party/ssc/test/shared_test/lib_battery_dispatch_automatic_btm_test.cpp
  third_party/ssc/test/shared_test/lib_battery_lifetime_test.cpp
  third_party/ssc/test/shared_test/lib_battery_test.cpp
  third_party/ssc/test/shared_test/lib_utility_rate_equations_test.cpp
  third_party/ssc/test/ssc_test/cmod_battery_pvsamv1_test.cpp
  third_party/ssc/test/ssc_test/cmod_battery_stateful_test.cpp
  third_party/ssc/test/ssc_test/cmod_battery_stateful_test.h
  third_party/ssc/test/ssc_test/cmod_battwatts_test.cpp
  third_party/ssc/test/ssc_test/cmod_pvsamv1_test.cpp
  third_party/ssc/test/ssc_test/cmod_utilityrate5_test.cpp
  tst/EnergyPlus/unit/ElectricPowerServiceManager.unit.cc
Labels: Documentation, InProgress, NewFeature

#8624 Fix issue 6998 Fuel Cell Zero Cp causing div-by-zero and repeated root solver errors
  doc/input-output-reference/src/overview/group-electric-load-center-generator.tex
  src/EnergyPlus/FuelCellElectricGenerator.cc
  src/EnergyPlus/FuelCellElectricGenerator.hh
  src/EnergyPlus/WeatherManager.cc
  tst/EnergyPlus/unit/FuelCellElectricGenerator.unit.cc
Labels: Defect

#8631 Add Py_SetProgramName to make sure sys.argv[0] is set
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PluginManager.hh
  src/EnergyPlus/api/plugin.py
Labels: Defect

#8576 Various DX coil fixes
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/HVACMultiSpeedHeatPump.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#8647 Fix #8553 - Clean up Python version string in usage
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  src/EnergyPlus/PluginManager.cc
Labels: DoNotPublish

#8646 Remove Statics from ErrorsFound, some "W" files.
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/DualDuct.cc
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/ExteriorEnergyUse.cc
  src/EnergyPlus/HVACCooledBeam.cc
  src/EnergyPlus/HVACDXSystem.cc
  src/EnergyPlus/HVACDuct.cc
  src/EnergyPlus/HVACFourPipeBeam.cc
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/HVACSingleDuctInduc.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.cc
  src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/Humidifiers.cc
  src/EnergyPlus/HybridUnitaryAirConditioners.cc
  src/EnergyPlus/ICEngineElectricGenerator.cc
  src/EnergyPlus/IntegratedHeatPump.cc
  src/EnergyPlus/MatrixDataManager.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixerComponent.cc
  src/EnergyPlus/MoistureBalanceEMPDManager.cc
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/ThermalChimney.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/UnitHeater.cc
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowComplexManager.hh
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowEquivalentLayer.hh
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManager.hh
  src/EnergyPlus/ZoneAirLoopEquipmentManager.cc
  src/EnergyPlus/ZoneDehumidifier.cc
  src/EnergyPlus/ZoneDehumidifier.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/FuelCellElectricGenerator.unit.cc
Labels: Refactoring

#8649 Grounding EnergyPlus (removing the static), Cont'd
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/AirLoopHVACDOAS.hh
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/AirflowNetworkBalanceManager.hh
  src/EnergyPlus/BaseboardElectric.cc
  src/EnergyPlus/BaseboardElectric.hh
  src/EnergyPlus/BranchInputManager.cc
  src/EnergyPlus/BranchInputManager.hh
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ChilledCeilingPanelSimple.hh
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/DXFEarClipping.cc
  src/EnergyPlus/DXFEarClipping.hh
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/DataZoneEquipment.hh
  src/EnergyPlus/DisplayRoutines.cc
  src/EnergyPlus/DualDuct.cc
  src/EnergyPlus/DualDuct.hh
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/EMSManager.hh
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/ElectricBaseboardRadiator.hh
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/ExternalInterface.hh
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/Fans.hh
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/Furnaces.hh
Labels: Refactoring

#8650 Deglobalizing & removing the static DesiccantDehumidifiers, HeatBalanceIntRadExchange, and HVACDXSystem
  src/EnergyPlus/Autosizing/All_Simple_Sizing.cc
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/DesiccantDehumidifiers.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/HVACDXSystem.cc
  src/EnergyPlus/HVACDXSystem.hh
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.hh
  src/EnergyPlus/PackagedThermalStorageCoil.cc
  src/EnergyPlus/PackagedThermalStorageCoil.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/Autosizing/All_Simple_Sizing.unit.cc
  tst/EnergyPlus/unit/DesiccantDehumidifiers.unit.cc
  tst/EnergyPlus/unit/HVACDXSystem.unit.cc
Labels: Refactoring

#8651 Remove More Statics
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UnitVentilator.hh
  src/EnergyPlus/UserDefinedComponents.cc
  src/EnergyPlus/UserDefinedComponents.hh
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  src/EnergyPlus/Vectors.cc
  src/EnergyPlus/Vectors.hh
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/VentilatedSlab.hh
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  src/EnergyPlus/WaterToAirHeatPumpSimple.hh
  src/EnergyPlus/WindowAC.cc
  src/EnergyPlus/WindowAC.hh
  src/EnergyPlus/ZoneDehumidifier.cc
Labels: Refactoring

#8652 Continued Grounding of EnergyPlus
  doc/engineering-reference/src/on-site-generation/electric-load-center-distribution-manager.tex
  src/EnergyPlus/DataGenerators.hh
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/GeneralRoutines.hh
  src/EnergyPlus/GeneratorDynamicsManager.cc
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc
  src/EnergyPlus/GroundTemperatureModeling/XingGroundTemperatureModel.cc
  src/EnergyPlus/HVACSingleDuctInduc.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  src/EnergyPlus/HybridUnitaryAirConditioners.cc
  src/EnergyPlus/HybridUnitaryAirConditioners.hh
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/OutdoorAirUnit.hh
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/PackagedTerminalHeatPump.hh
  src/EnergyPlus/PackagedThermalStorageCoil.cc
  src/EnergyPlus/PackagedThermalStorageCoil.hh
  src/EnergyPlus/Photovoltaics.cc
  src/EnergyPlus/Photovoltaics.hh
  src/EnergyPlus/PipeHeatTransfer.cc
  src/EnergyPlus/Plant/Component.cc
  src/EnergyPlus/Plant/DataPlant.hh
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PluginManager.hh
  src/EnergyPlus/PoweredInductionUnits.cc
  src/EnergyPlus/PoweredInductionUnits.hh
  src/EnergyPlus/Pumps.cc
  src/EnergyPlus/RefrigeratedCase.cc
  src/EnergyPlus/RefrigeratedCase.hh
  src/EnergyPlus/RoomAirModelUserTempPattern.cc
  src/EnergyPlus/RoomAirModelUserTempPattern.hh
  src/EnergyPlus/RootFinder.cc
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/RuntimeLanguageProcessor.hh
Labels: Refactoring

#8655 Remove statics, WaterCoils, WaterToAirHeatPump, TranspiredCollector, UFADManager, UnitHeater
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/TranspiredCollector.hh
  src/EnergyPlus/UFADManager.cc
  src/EnergyPlus/UFADManager.hh
  src/EnergyPlus/UnitHeater.cc
  src/EnergyPlus/UnitHeater.hh
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/WaterCoils.hh
  src/EnergyPlus/WaterToAirHeatPump.cc
  src/EnergyPlus/WaterToAirHeatPump.hh
Labels: Refactoring

#8656 Continued Grounding of EnergyPlus
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DXCoils.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingDevices.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/DualDuct.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/Furnaces.hh
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.hh
  src/EnergyPlus/HVACCooledBeam.cc
  src/EnergyPlus/HVACFourPipeBeam.cc
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/HVACHXAssistedCoolingCoil.hh
  src/EnergyPlus/HVACInterfaceManager.cc
  src/EnergyPlus/HVACInterfaceManager.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACManager.hh
  src/EnergyPlus/HVACSingleDuctInduc.cc
  src/EnergyPlus/HVACSingleDuctInduc.hh
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.hh
  src/EnergyPlus/HeatBalanceHAMTManager.cc
  src/EnergyPlus/HeatBalanceHAMTManager.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.cc
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.hh
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.cc
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.hh
  src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
  src/EnergyPlus/HeatPumpWaterToWaterSimple.hh
  src/EnergyPlus/Humidifiers.cc
  src/EnergyPlus/MatrixDataManager.cc
  src/EnergyPlus/MatrixDataManager.hh
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixedAir.hh
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/UtilityRoutines.hh
  tst/EnergyPlus/unit/AirTerminalSingleDuct.unit.cc
Labels: Refactoring

#8657 Continued Grounding of EnergyPlus Round 4
  src/EnergyPlus/DataHVACGlobals.hh
  src/EnergyPlus/NodeInputManager.cc
  src/EnergyPlus/NodeInputManager.hh
  src/EnergyPlus/StandardRatings.cc
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SteamBaseboardRadiator.hh
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/SteamCoils.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  src/EnergyPlus/SurfaceGroundHeatExchanger.cc
  src/EnergyPlus/SurfaceGroundHeatExchanger.hh
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/SystemAvailabilityManager.hh
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/SystemReports.hh
Labels: Refactoring

#8591 Refactoring of interpolation functions for blinds Prof and Slat Angle
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: Performance

#8658 Ground psychrometrics
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/Psychrometrics.hh
  src/EnergyPlus/Pumps.cc
  src/EnergyPlus/Pumps.hh
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SingleDuct.hh
  src/EnergyPlus/TARCOGGasses90.cc
  src/EnergyPlus/TARCOGGasses90.hh
  src/EnergyPlus/TARCOGMain.cc
  src/EnergyPlus/TARCOGMain.hh
  src/EnergyPlus/TARCOGOutput.cc
  src/EnergyPlus/TarcogShading.cc
  src/EnergyPlus/TarcogShading.hh
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/ThermalComfort.hh
  src/EnergyPlus/ThermalEN673Calc.cc
  src/EnergyPlus/ThermalEN673Calc.hh
  src/EnergyPlus/ThermalISO15099Calc.cc
  src/EnergyPlus/ThermalISO15099Calc.hh
  third_party/ObjexxFCL/src/ObjexxFCL/Array1D.hh
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Refactoring

#8659 Continued Grounding of EnergyPlus
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/Autosizing/Base.cc
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataStringGlobals.hh
  src/EnergyPlus/DataStringGlobals.in.cc
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/GroundHeatExchangers.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HWBaseboardRadiator.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/HeatRecovery.hh
  src/EnergyPlus/IOFiles.cc
  src/EnergyPlus/IOFiles.hh
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/MoistureBalanceEMPDManager.cc
  src/EnergyPlus/MoistureBalanceEMPDManager.hh
  src/EnergyPlus/MundtSimMgr.cc
  src/EnergyPlus/MundtSimMgr.hh
  src/EnergyPlus/NonZoneEquipmentManager.cc
  src/EnergyPlus/OutAirNodeManager.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/SQLiteProcedures.cc
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/SetPointManager.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/api/EnergyPlusPgm.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/SimulationManager.unit.cc
  tst/EnergyPlus/unit/UtilityRoutines.unit.cc
Labels: Refactoring

#8641 Global-Psychrometric
  src/EnergyPlus/DataViewFactorInformation.cc
  src/EnergyPlus/DataViewFactorInformation.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingDevices.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/EvaporativeFluidCoolers.cc
  src/EnergyPlus/EvaporativeFluidCoolers.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/Furnaces.hh
  src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.cc
  src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.hh
  src/EnergyPlus/HVACDXSystem.cc
  src/EnergyPlus/HVACDuct.cc
  src/EnergyPlus/HVACDuct.hh
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/HVACSingleDuctInduc.cc
  src/EnergyPlus/HVACSingleDuctInduc.hh
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HybridModel.cc
  src/EnergyPlus/HybridModel.hh
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
  src/EnergyPlus/PhaseChangeModeling/HysteresisModel.hh
  src/EnergyPlus/Photovoltaics.cc
  src/EnergyPlus/Photovoltaics.hh
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/Psychrometrics.hh
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.hh
  src/EnergyPlus/RoomAirModelUserTempPattern.cc
  src/EnergyPlus/RoomAirModelUserTempPattern.hh
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/RuntimeLanguageProcessor.hh
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/ScheduleManager.hh
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/SetPointManager.hh
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/EvaporativeFluidCoolers.unit.cc
  tst/EnergyPlus/unit/HeatBalanceIntRadExchange.unit.cc
  tst/EnergyPlus/unit/HybridModel.unit.cc
  tst/EnergyPlus/unit/Psychrometrics.unit.cc
  tst/EnergyPlus/unit/RoomAirflowNetwork.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
  tst/EnergyPlus/unit/ZoneContaminantPredictorCorrector.unit.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Refactoring

#8660 Statics Cleanup
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/ExteriorEnergyUse.cc
  src/EnergyPlus/ExteriorEnergyUse.hh
  src/EnergyPlus/FluidProperties.cc
  src/EnergyPlus/FluidProperties.hh
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/OutputReports.hh
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/TARCOGCommon.cc
  src/EnergyPlus/TARCOGCommon.hh
  src/EnergyPlus/ThermalISO15099Calc.cc
Labels: Refactoring

#8662 Grounding SolarShading, Deglobalizing ICEngineElectricGenerator
  src/EnergyPlus/ICEngineElectricGenerator.cc
  src/EnergyPlus/ICEngineElectricGenerator.hh
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SolarShading.hh
  tst/EnergyPlus/unit/ICEngineElectricGenerator.unit.cc
Labels: Refactoring

#8558 Coil:Cooling:DX updates
  doc/ems-application-guide/src/ems-actuators/hvac-systems-001.tex
  doc/input-output-reference/src/overview/group-coil-cooling-dx.tex
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/Coils/CoilCoolingDX.hh
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.hh
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.hh
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.hh
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  testfiles/UnitarySystem_VSCoolingCoil.idf
  tst/EnergyPlus/unit/Coils/CoilCoolingDX.unit.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDXCurveFitSpeed.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#8645 Fix heating energy calculation and reporting errors for gas fired and exhaust fired absorption chillerheater models
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.cc
  tst/EnergyPlus/unit/ChillerExhaustAbsorption.unit.cc
  tst/EnergyPlus/unit/ChillerGasAbsorption.unit.cc
Labels: Defect

#8665 WaterToAirHeatPump statics fix
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  src/EnergyPlus/WaterToAirHeatPumpSimple.hh
Labels: Defect, DoNotPublish

#8667 Add an explicit "EnergyPlus" namespace to a state argument
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
Labels: Defect, DoNotPublish

#8661 Fix epJSON minfields and extensible input processing
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/InputProcessing/InputProcessor.hh
  testfiles/RefBldgMediumOfficeNew2004_Chicago_epJSON.epJSON
  tst/EnergyPlus/unit/InputProcessor.unit.cc
Labels: Defect

#8675 Final prep for 9.5 release
  cmake/Version.cmake
  doc/tools/create_changelog.py
  release/readme.html
  src/Transition/CMakeLists.txt
  testfiles/ShopWithPVandLiIonBattery.idf
Labels: DoNotPublish
