Repository NREL/EnergyPlus, pull requests merged in 2021-08, with the labels that each got.

#8887 HVACTemplate:System:ConstantVolume fixes
  src/ExpandObjects/epfilter.f90
Labels: Defect

#8889 Fix Daylighting Map Output Header and Remove Maximum Reference Points (of 2) Variable
  doc/input-output-reference/src/overview/group-surface-construction-elements.tex
  src/EnergyPlus/DataDaylighting.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/SQLiteProcedures.cc
  src/EnergyPlus/SQLiteProcedures.hh
  src/Transition/InputRulesFiles/Rules9-5-0-to-9-6-0.md
  src/Transition/OutputRulesFiles/OutputChanges9-5-0-to-9-6-0.md
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
  tst/EnergyPlus/unit/SQLite.unit.cc
Labels: Defect, OutputChange

#8918 Update EPLaunch Workflow to use API
  .gitignore
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/api/func.cc
  src/EnergyPlus/api/func.h
  src/EnergyPlus/api/func.py
  src/EnergyPlus/api/runtime.cc
  src/EnergyPlus/api/runtime.h
  src/EnergyPlus/api/runtime.py
  tst/EnergyPlus/api/TestFunctional.c
  tst/EnergyPlus/api/TestFunctional.py
  tst/EnergyPlus/api/TestRuntime.c
  tst/EnergyPlus/api/TestRuntime.py
  tst/EnergyPlus/api/test_OutputFiles.py
  workflows/energyplus.py
Labels: NewFeature

#8913 Allow Plugin Plugins in Runtime API Calls
  doc/input-output-reference/src/overview/api-usage.tex
  doc/input-output-reference/src/overview/group-python-plugins.tex
  doc/readthedocs/README.md
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PluginManager.hh
  src/EnergyPlus/SimulationManager.cc
  third_party/CMakeLists.txt
  tst/EnergyPlus/api/TestRuntime.c
Labels: NewFeature

#8858 Add object-level output variables for ZoneInfiltration
  design/FY2021/ReportIndividualInfiltrationObject.md
  doc/input-output-reference/src/overview/group-airflow.tex
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneEquipmentManager.hh
  tst/EnergyPlus/unit/HVACManager.unit.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: NewFeature, OutputChange

#8791 Support HVACTemplate objects in converter and trap unsupported objects in epJSON input
  doc/essentials/CMakeLists.txt
  doc/essentials/essentials.tex
  doc/essentials/src/essentials.tex
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/InputProcessing/IdfParser.cc
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/InputProcessing/InputProcessor.hh
  tst/EnergyPlus/unit/InputProcessor.unit.cc
Labels: Defect

#8959 Account for rated capacity modifier in chiller IPLV calculations
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportPredefined.hh
  src/EnergyPlus/StandardRatings.cc
  src/Transition/OutputRulesFiles/OutputChanges9-5-0-to-9-6-0.md
  tst/EnergyPlus/unit/StandardRatings.unit.cc
Labels: Defect, NotIDDChange, OutputChange

#8991 Address MSVS compile issue with recent commit.
  third_party/cpgfunctionEP-0.5/src/boreholes.cpp
  third_party/cpgfunctionEP-0.5/third_party/qdt-master/methods/adaptive.h
Labels: Defect, DoNotPublish

#8961 gitignore CMakeSettings.json (MSVC/VSCode) and more in-source build folder names
  .gitignore
Labels: DoNotPublish, NotIDDChange

#8942 update python plugin file to duplicate all EMS
  testfiles/PythonPluginConstantVolumePurchasedAir.idf
  testfiles/PythonPluginConstantVolumePurchasedAir.py
Labels: NewFeature

#8937 Fixed Crash in CondFD for Interzone Surfaces for Very Specific Condition
  src/EnergyPlus/DataHeatBalance.cc
  tst/EnergyPlus/unit/DataHeatBalance.unit.cc
Labels: Defect

#8960 PVWatts Speed Up
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/ElectricPowerServiceManager.hh
  src/EnergyPlus/PVWatts.cc
  src/EnergyPlus/PVWatts.hh
  third_party/ssc/ssc/cmod_pvwattsv5.cpp
  third_party/ssc/ssc/core.cpp
  tst/EnergyPlus/unit/PVWatts.unit.cc
Labels: Performance

#8929 ConvectionCoefficients Refactoring and Enums - Part 2
  doc/input-output-reference/src/overview/group-advanced-surface-concepts.tex
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  src/EnergyPlus/ConvectionConstants.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/Transition/OutputRulesFiles/OutputChanges9-5-0-to-9-6-0.md
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
Labels: Refactoring

#9005 Hot fix #8961 - gitignore doc/build
  .gitignore
Labels: DoNotPublish

#9023 Fix #9022 - conversion should respect outDirPath
  src/EnergyPlus/DataStringGlobals.hh
  src/EnergyPlus/InputProcessing/InputProcessor.cc
Labels: Defect

#8801 Fix the ground slab horizontal insulation thickness issue (Issues 7881 and 8800)
  src/EnergyPlus/PlantPipingSystemsManager.cc
  testfiles/5ZoneAirCooledWithCoupledInGradeSlab_HorizInsThickness.idf
  testfiles/CMakeLists.txt
  tst/EnergyPlus/unit/PlantPipingSystemsManager.unit.cc
Labels: Defect

#9031 Remove `using namspace *` in cpgfunction headers
  third_party/cpgfunctionEP-0.5/CMakeLists.txt
  third_party/cpgfunctionEP-0.5/include/blas/blas.h
  third_party/cpgfunctionEP-0.5/include/cpgfunction/boreholes.h
  third_party/cpgfunctionEP-0.5/include/cpgfunction/coordinates.h
  third_party/cpgfunctionEP-0.5/include/cpgfunction/gfunction.h
  third_party/cpgfunctionEP-0.5/include/cpgfunction/heat_transfer.h
  third_party/cpgfunctionEP-0.5/include/cpgfunction/interpolation.h
  third_party/cpgfunctionEP-0.5/include/cpgfunction/segments.h
  third_party/cpgfunctionEP-0.5/include/cpgfunction/statistics.h
  third_party/cpgfunctionEP-0.5/include/cpgfunction/utilities.h
  third_party/cpgfunctionEP-0.5/src/blas.cpp
  third_party/cpgfunctionEP-0.5/src/boreholes.cpp
  third_party/cpgfunctionEP-0.5/src/coordinates.cpp
  third_party/cpgfunctionEP-0.5/src/gfunction.cpp
  third_party/cpgfunctionEP-0.5/src/heat_transfer.cpp
  third_party/cpgfunctionEP-0.5/src/interpolation.cpp
  third_party/cpgfunctionEP-0.5/src/segments.cpp
  third_party/cpgfunctionEP-0.5/src/utilities.cpp
  third_party/cpgfunctionEP-0.5/third_party/LU-Decomposition-0.1/include/LU-Decomposition/lu.h
  third_party/cpgfunctionEP-0.5/third_party/LU-Decomposition-0.1/src/lu.cpp
Labels: DoNotPublish

#9026 Fix of a Previously Accepted Fix in for Zone Cooling Design Supply Air Temperature Issue
  src/EnergyPlus/SizingManager.cc
Labels: Defect
