Repository NREL/EnergyPlus, pull requests merged in 2021-02, with the labels that each got.

#8422 Fix Hybrid Unitary Operating Settings Initialization
  src/EnergyPlus/HybridEvapCoolingModel.cc
  tst/EnergyPlus/unit/UnitaryHybridAirConditioner.unit.cc
Labels: Defect, NotIDDChange

#8493 Global PlantPipingSystemsMgr
  src/EnergyPlus/FluidCoolers.cc
  src/EnergyPlus/FluidCoolers.hh
  src/EnergyPlus/FuelCellElectricGenerator.cc
  src/EnergyPlus/FuelCellElectricGenerator.hh
  src/EnergyPlus/GeneratorFuelSupply.cc
  src/EnergyPlus/GeneratorFuelSupply.hh
  src/EnergyPlus/GlobalNames.cc
  src/EnergyPlus/GlobalNames.hh
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HVACControllers.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.cc
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.hh
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.cc
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.hh
  src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
  src/EnergyPlus/HeatPumpWaterToWaterSimple.hh
  src/EnergyPlus/IceThermalStorage.cc
  src/EnergyPlus/IceThermalStorage.hh
  src/EnergyPlus/MicroCHPElectricGenerator.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/Plant/PlantManager.hh
  src/EnergyPlus/PlantHeatExchangerFluidToFluid.cc
  src/EnergyPlus/PlantHeatExchangerFluidToFluid.hh
  src/EnergyPlus/PlantLoadProfile.cc
  src/EnergyPlus/PlantLoadProfile.hh
  src/EnergyPlus/PlantPipingSystemsManager.cc
  src/EnergyPlus/PlantPipingSystemsManager.hh
  src/EnergyPlus/PlantPressureSystem.cc
  src/EnergyPlus/PlantPressureSystem.hh
  src/EnergyPlus/PlantUtilities.cc
  src/EnergyPlus/PlantUtilities.hh
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PondGroundHeatExchanger.cc
  src/EnergyPlus/PondGroundHeatExchanger.hh
  src/EnergyPlus/RootFinder.cc
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/CondenserLoopTowers.unit.cc
  tst/EnergyPlus/unit/FanCoilUnits.unit.cc
  tst/EnergyPlus/unit/FluidCoolers.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/HeatPumpWaterToWaterSimple.unit.cc
  tst/EnergyPlus/unit/IceThermalStorage.unit.cc
  tst/EnergyPlus/unit/PlantHeatExchangerFluidToFluid.unit.cc
  tst/EnergyPlus/unit/PlantPipingSystemsManager.unit.cc
  tst/EnergyPlus/unit/SiteGroundDomain.unit.cc
  tst/EnergyPlus/unit/WaterCoils.unit.cc
Labels: Refactoring

#8477 Add EMS Actuator for View Factor to Ground
  doc/ems-application-guide/src/ems-actuators/thermal-envelope.tex
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  tst/EnergyPlus/unit/EMSManager.unit.cc
Labels: NewFeature

#8506 Updated weather geojson with mos time series file links
  weather/master.geojson
Labels: DoNotPublish, Weather

#8479 Plant Cleanups
  src/EnergyPlus/BoilerSteam.cc
  src/EnergyPlus/BoilerSteam.hh
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/Boilers.hh
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerAbsorption.hh
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerElectricEIR.hh
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerExhaustAbsorption.hh
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.hh
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/ChillerIndirectAbsorption.hh
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/ChillerReformulatedEIR.hh
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/CondenserLoopTowers.hh
  src/EnergyPlus/EarthTube.cc
  src/EnergyPlus/EarthTube.hh
  src/EnergyPlus/FluidCoolers.cc
  src/EnergyPlus/FluidCoolers.hh
  src/EnergyPlus/PipeHeatTransfer.cc
  src/EnergyPlus/PipeHeatTransfer.hh
  src/EnergyPlus/Pipes.cc
  src/EnergyPlus/Pipes.hh
  src/EnergyPlus/PlantComponent.hh
  src/EnergyPlus/StateManagement.cc
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/SwimmingPool.hh
  tst/EnergyPlus/unit/EarthTube.unit.cc
  tst/EnergyPlus/unit/SwimmingPool.unit.cc
Labels: DoNotPublish

#8510 Minor Variable Name Cleanup in Python CondFD Example File
  testfiles/PythonPlugin1ZoneUncontrolledCondFD.py
Labels: DoNotPublish

#8491 GHE Updates
  src/EnergyPlus/GroundHeatExchangers.cc
  src/EnergyPlus/GroundHeatExchangers.hh
  src/EnergyPlus/StateManagement.cc
  tst/EnergyPlus/unit/GroundHeatExchangers.unit.cc
Labels: Refactoring

#8517 Windows package build
  .github/workflows/mac_release.yml
  .github/workflows/windows_release.yml
Labels: DoNotPublish

#8515 Global Tarcog
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/TARCOGArgs.cc
  src/EnergyPlus/TARCOGArgs.hh
  src/EnergyPlus/TARCOGCommon.cc
  src/EnergyPlus/TARCOGCommon.hh
  src/EnergyPlus/TARCOGDeflection.cc
  src/EnergyPlus/TARCOGDeflection.hh
  src/EnergyPlus/TARCOGGasses90.cc
  src/EnergyPlus/TARCOGGasses90.hh
  src/EnergyPlus/TARCOGGassesParams.cc
  src/EnergyPlus/TARCOGGassesParams.hh
  src/EnergyPlus/TARCOGMain.cc
  src/EnergyPlus/TARCOGMain.hh
  src/EnergyPlus/TARCOGOutput.cc
  src/EnergyPlus/TARCOGOutput.hh
  src/EnergyPlus/TARCOGParams.cc
  src/EnergyPlus/TARCOGParams.hh
  src/EnergyPlus/ThermalISO15099Calc.cc
  src/EnergyPlus/ThermalISO15099Calc.hh
  src/EnergyPlus/WindowComplexManager.cc
Labels: DoNotPublish

#8521 Reduce Alternate Build Configurations Built by Github Actions
  .github/workflows/linux_build.yml
  .github/workflows/mac_build.yml
Labels: DoNotPublish

#8522 Fix build error on gcc10, which has `Default to -fno-common`
  third_party/BCVTB/utilXml.c
  third_party/BCVTB/utilXml.h
Labels: Defect, DoNotPublish

#8410 #8376 - EnergyPlus with option --expandobjects set fails when working directory is not on the same device as the output directory (on Unix)
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/FileSystem.cc
  src/EnergyPlus/FileSystem.hh
  tst/EnergyPlus/unit/FileSystem.unit.cc
Labels: Defect

#8525 Fix #8524 - CPack packages missing the vast majority of files
  cmake/Install.cmake
  third_party/ssc/CMakeLists.txt
Labels: Defect, DoNotPublish

#8302 Add Output Variables to Ideal Air loads
  doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
  src/EnergyPlus/PurchasedAirManager.cc
  src/EnergyPlus/PurchasedAirManager.hh
  src/EnergyPlus/ScheduleManager.hh
  testfiles/HVACTemplate-5ZonePurchAir.idf
  testfiles/HVACTemplate-5ZonePurchAir.rvi
  tst/EnergyPlus/unit/PurchasedAirManager.unit.cc
Labels: NewFeature

#8531 Fix #8509 - remove duplicate InstallRequiredSystemLibraries block
  cmake/Install.cmake
Labels: DoNotPublish

#8463 LowTempRadiantSystem - Fix minor bug
  src/EnergyPlus/LowTempRadiantSystem.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
Labels: Defect

#8390 Outside range warning and error when using linear interpolation with Schedule:Day:Interval
  src/EnergyPlus/ScheduleManager.cc
  tst/EnergyPlus/unit/ScheduleManager.unit.cc
Labels: Defect

#8541 Fix compiler warning on MSVC
  src/EnergyPlus/MatrixDataManager.cc
Labels: DoNotPublish

#8498 Fixes Zone Air Mass Balance report variables reporting issues
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Defect

#8546 Fix SSC Packaging
  cmake/PythonFixUpOnMac.cmake
Labels: DoNotPublish

#8548 Prep for 95 IO freeze
  cmake/Install.cmake
  doc/engineering-reference/src/surface-heat-balance-manager-processes/inside-heat-balance.tex
  scripts/dev/find_byref_bool_override.py
Labels: DoNotPublish

#8552 Change floats to real64 to clean out build warnings
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: DoNotPublish

#8435 Convert window shading flag to enum class
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SolarShading.hh
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/UFADManager.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
  tst/EnergyPlus/unit/EMSManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Refactoring
