Repository NREL/EnergyPlus, pull requests merged in 2021-07, with the labels that each got.

#8852 Fix #8837 - use more reliable way to install qtifw
  .github/workflows/linux_release.yml
  .github/workflows/mac_release.yml
  .github/workflows/windows_release.yml
Labels: DoNotPublish

#8832 Fix #8778 - FindPython in modern cmake and handle issue when LINK_WITH_PYTHON on windows with both Release/debug libraries
  CMakeLists.txt
  cmake/Install.cmake
  cmake/ProjectMacros.cmake
  doc/CMakeLists.txt
  doc/cmake/doc-targets.cmake
  src/EnergyPlus/CMakeLists.txt
  tst/EnergyPlus/unit/CMakeLists.txt
Labels: Defect

#8834 Eliminate Other Usages of readItem
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WindTurbine.cc
Labels: Performance, Refactoring

#8888 Remove unused functions that were not implemented
  src/EnergyPlus/IOFiles.hh
Labels: Refactoring

#8796 Use correct array index in IntraZoneNodeData
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
Labels: Defect

#8868 Fix struct name for NumTimesCalled
  src/EnergyPlus/Psychrometrics.cc
Labels: Defect

#8839 Fix Sqlite.err writing to parent dir
  src/EnergyPlus/CommandLineInterface.cc
Labels: Defect

#8857 Fix windows documentation on CI
  .github/workflows/documentation-windows.yml
  .github/workflows/windows_release.yml
  doc/energyplus_packages_windows.lst
  doc/test/dependencies.tex
Labels: DoNotPublish

#8862 ConvectionCoefficients Enums and Refactoring - Part 1
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  src/EnergyPlus/ConvectionConstants.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/GeneralRoutines.hh
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/TranspiredCollector.hh
  src/EnergyPlus/WindowManager.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/ICSCollector.unit.cc
  tst/EnergyPlus/unit/TranspiredCollector.unit.cc
Labels: Defect, Refactoring

#8850 On-Off Fan Showing Zero Fan Power During Cooling for Unitary Systems with Single Speed Cooling Coil
  src/EnergyPlus/UnitarySystem.cc
  testfiles/FurnaceWithDXSystem.idf
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#8823 Fix #8722 - HVAC-Diagram.exe broken in v9.5 (Modernize CMake Fortran Settings)
  CMakeLists.txt
  cmake/Fortran.cmake
  cmake/Install.cmake
  src/AppGPostProcess/CMakeLists.txt
  src/Basement/CMakeLists.txt
  src/CalcSoilSurfTemp/CMakeLists.txt
  src/ConvertESOMTR/CMakeLists.txt
  src/ExpandObjects/CMakeLists.txt
  src/HVAC-Diagram/CMakeLists.txt
  src/ParametricPreprocessor/CMakeLists.txt
  src/ReadVars/CMakeLists.txt
  src/Slab/CMakeLists.txt
  src/Transition/CMakeLists.txt
Labels: AuxiliaryTool, Defect

#8871 Beam Solar Radiation Not Taking Solar Angle into Account for Some Models
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/EcoRoofManager.hh
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc
  src/EnergyPlus/PlantPipingSystemsManager.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/EcoRoofManager.unit.cc
  tst/EnergyPlus/unit/FiniteDifferenceGroundTemperatureModel.unit.cc
Labels: Defect

#8729 Simulate CoilSystem:Cooling:DX using AirloopHVAC:UnitarySystem code base
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/Autosizing/CoolingAirFlowSizing.cc
  src/EnergyPlus/Autosizing/HeatingAirFlowSizing.cc
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataAirLoop.hh
  src/EnergyPlus/DataAirSystems.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/HVACDXHeatPumpSystem.cc
  src/EnergyPlus/HVACDXSystem.cc
  src/EnergyPlus/HVACDXSystem.hh
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.hh
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PackagedThermalStorageCoil.cc
  src/EnergyPlus/PackagedThermalStorageCoil.hh
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  testfiles/UnitarySystem_FurnaceWithDXSystemRHcontrol.idf
  tst/EnergyPlus/unit/EvaporativeCoolers.unit.cc
  tst/EnergyPlus/unit/HVACDXSystem.unit.cc
  tst/EnergyPlus/unit/HVACHXAssistedCoolingCoil.unit.cc
  tst/EnergyPlus/unit/OutdoorAirUnit.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: NewFeature, Refactoring

#8864 [Refactor] Enums - Psychrometrics.hh
  src/EnergyPlus/PsychCacheData.hh
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/Psychrometrics.hh
  tst/EnergyPlus/unit/Psychrometrics.unit.cc
Labels: Refactoring

#8890 Correct Input Logic for Autosized Cooling Only Variable Flow Low Temperature Radiant
  src/EnergyPlus/LowTempRadiantSystem.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
Labels: Defect

#8870 Correction to CO2 and Generic Contaminant Modeling with Refrigeration Door Mixing
  src/EnergyPlus/ZoneEquipmentManager.cc
  testfiles/RefrigeratedWarehouse.idf
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Defect

#8855 Revision to Sizing:Zone Error Message
  doc/input-output-reference/src/overview/group-design-objects.tex
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SizingManager.hh
  tst/EnergyPlus/unit/SizingManager.unit.cc
Labels: Defect

#8831 Fix #8822 - new warning to explain why Standard62.1Summary may not be available in Output:Table:SummaryReports
  doc/input-output-reference/src/standard-output-reports/output-table-summaryreports.tex
  doc/output-details-and-examples/src/output-files/eplustbl-lt-ext-gt.tex
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect
