Repository NREL/EnergyPlus, pull requests merged in 2022-12, with the labels that each got.

#9694 Fix 9301 DX Coil incorrect curve that could result severe errors
  src/EnergyPlus/DXCoils.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
Labels: Defect

#9719 Fix 9317 space people density report
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#9752 Fix circular include in BaseGroundTemperatureModel.hh
  src/EnergyPlus/GroundHeatExchangers.cc
  src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.hh
  src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.cc
  src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.hh
  src/EnergyPlus/GroundTemperatureModeling/KusudaAchenbachGroundTemperatureModel.cc
  src/EnergyPlus/GroundTemperatureModeling/KusudaAchenbachGroundTemperatureModel.hh
  src/EnergyPlus/GroundTemperatureModeling/SiteBuildingSurfaceGroundTemperatures.cc
  src/EnergyPlus/GroundTemperatureModeling/SiteBuildingSurfaceGroundTemperatures.hh
  src/EnergyPlus/GroundTemperatureModeling/SiteDeepGroundTemperatures.cc
  src/EnergyPlus/GroundTemperatureModeling/SiteDeepGroundTemperatures.hh
  src/EnergyPlus/GroundTemperatureModeling/SiteFCFactorMethodGroundTemperatures.cc
  src/EnergyPlus/GroundTemperatureModeling/SiteFCFactorMethodGroundTemperatures.hh
  src/EnergyPlus/GroundTemperatureModeling/SiteShallowGroundTemperatures.cc
  src/EnergyPlus/GroundTemperatureModeling/SiteShallowGroundTemperatures.hh
  src/EnergyPlus/GroundTemperatureModeling/XingGroundTemperatureModel.cc
  src/EnergyPlus/GroundTemperatureModeling/XingGroundTemperatureModel.hh
  src/EnergyPlus/PlantPipingSystemsManager.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  tst/EnergyPlus/unit/KusudaAchenbachGroundTemperatureModel.unit.cc
  tst/EnergyPlus/unit/SiteBuildingSurfaceGroundTemperatures.unit.cc
  tst/EnergyPlus/unit/SiteDeepGroundTemperatures.unit.cc
  tst/EnergyPlus/unit/SiteFCFactorMethodGroundTemperatures.unit.cc
  tst/EnergyPlus/unit/SiteShallowGroundTemperatures.unit.cc
  tst/EnergyPlus/unit/XingGroundTemperatureModel.unit.cc
Labels: DoNotPublish

#9744 Fix epw holidays header processing and fix eio reporting for holidays
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/ScheduleManager.hh
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  src/EnergyPlus/api/datatransfer.py
  testfiles/_5ZoneAirCooled_LeapYear_annual.idf
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
  tst/EnergyPlus/unit/RunPeriod.unit.cc
  tst/EnergyPlus/unit/WeatherManager.unit.cc
  weather/MadeUpLeapYear.epw
Labels: Defect, Refactoring

#9720 Sizing:System and AirloopHVAC objects in different order causes differences
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/SizingManager.cc
  tst/EnergyPlus/unit/Autosizing/BaseClassSizing.unit.cc
  tst/EnergyPlus/unit/DataSizing.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/WaterCoils.unit.cc
Labels: Defect

#9723 Fix 9686 and 9724---Correct the zone ideal loads SA HumRat value calculation and the units in Total Outdoor Air by AirLoop report table
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/PurchasedAirManager.cc
  tst/EnergyPlus/unit/PurchasedAirManager.unit.cc
Labels: Defect

#9759 Removing minimum temperature for HPWH operation
  src/EnergyPlus/WaterThermalTanks.cc
Labels: Defect

#9741 Correct setpoint target for EIRPlantLoopHeatPump::getLoadSideOutletSetPointTemp when using a dual setpoint deadband loop demand calculation scheme
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Defect, NotIDDChange

#9693 Clean up Par arrays in SolveRoot calls
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixedAir.hh
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SingleDuct.hh
  src/EnergyPlus/StandardRatings.cc
  src/EnergyPlus/StandardRatings.hh
  src/EnergyPlus/UnitHeater.cc
  src/EnergyPlus/UnitHeater.hh
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UnitVentilator.hh
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/WaterCoils.hh
  src/EnergyPlus/WaterToAirHeatPump.cc
  src/EnergyPlus/WaterToAirHeatPump.hh
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Refactoring

#9725 Airloop table reports are using cooling coil sizing type instead of Sizing:System Type of Load to Size On
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SizingManager.cc
  tst/EnergyPlus/unit/Autosizing/BaseClassSizing.unit.cc
  tst/EnergyPlus/unit/DataSizing.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#9734 Move HeatPump:PlantLoop:EIR:* sizing calculations
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Defect, NotIDDChange

#9766 Solve root cleanups continued
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Solver.hpp
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/Autosizing/WaterHeatingCoilUASizing.cc
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/FanCoilUnits.hh
  src/EnergyPlus/FluidCoolers.cc
  src/EnergyPlus/FluidCoolers.hh
  src/EnergyPlus/FuelCellElectricGenerator.cc
  src/EnergyPlus/FuelCellElectricGenerator.hh
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/Furnaces.hh
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/HVACCooledBeam.cc
  src/EnergyPlus/HVACCooledBeam.hh
  src/EnergyPlus/HVACDXHeatPumpSystem.cc
  src/EnergyPlus/HVACDXHeatPumpSystem.hh
  src/EnergyPlus/HVACFourPipeBeam.cc
  src/EnergyPlus/HVACFourPipeBeam.hh
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.hh
  src/EnergyPlus/HVACSingleDuctInduc.cc
  src/EnergyPlus/HVACSingleDuctInduc.hh
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.hh
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/HeatRecovery.hh
  src/EnergyPlus/MixedAir.hh
  src/EnergyPlus/PlantHeatExchangerFluidToFluid.cc
  src/EnergyPlus/PlantHeatExchangerFluidToFluid.hh
  src/EnergyPlus/SZVAVModel.cc
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/StandardRatings.cc
  src/EnergyPlus/UnitHeater.cc
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/WaterCoils.hh
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterThermalTanks.hh
  src/EnergyPlus/WaterToAirHeatPump.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/FanCoilUnits.unit.cc
  tst/EnergyPlus/unit/General.unit.cc
Labels: Refactoring
