Repository NREL/EnergyPlus, pull requests merged in 2022-02, with the labels that each got.

#9256 `static inline` nlohmann/json `unescape` function to cleanup warning
  third_party/nlohmann/json.hpp
Labels: DoNotPublish

#9257 Fix exception thrown by OpenGL destruction in Windows.
  src/EnergyPlus/main.cc
Labels: Defect, NotIDDChange

#9292 Fix #8999 - OutputControl:Files is marked unused
  src/EnergyPlus/IOFiles.cc
  tst/EnergyPlus/unit/OutputFiles.unit.cc
Labels: Defect, NotIDDChange

#9278 Fix Schedule Limits Error Message
  src/EnergyPlus/ScheduleManager.cc
Labels: Defect

#9276 Pin a specific python version on Github Actions
  .github/workflows/linux_release.yml
  .github/workflows/mac_release.yml
  .github/workflows/windows_release.yml
  CMakeLists.txt
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PluginManager.hh
  tst/EnergyPlus/unit/CMakeLists.txt
Labels: Defect, NotIDDChange

#9293 Fix #9150 - Wild card in meter name no longer works for Output:Meter
  src/EnergyPlus/OutputProcessor.cc
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Defect, NotIDDChange

#9296 #9228 - Tabular file not generated with only Output:Table:Annual
  src/EnergyPlus/OutputReportTabularAnnual.cc
  src/EnergyPlus/SimulationManager.cc
  tst/EnergyPlus/unit/OutputReportTabularAnnual.unit.cc
Labels: Defect, NotIDDChange

#9255 Speed up execution of test suite
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/InputProcessing/InputProcessor.hh
  src/EnergyPlus/InputProcessing/InputValidation.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/Fixtures/InputProcessorFixture.hh
Labels: Performance, Refactoring
