Repository NREL/EnergyPlus, pull requests merged in 2022-09, with the labels that each got.

#9602 Fix for CondFD Problem that Improperly Led to Fatal Error
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.hh
  tst/EnergyPlus/unit/HeatBalFiniteDiffManager.unit.cc
Labels: Defect

#9600 Update MovingAvg function
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/General.unit.cc
Labels: Performance

#9638 Correct unit ventilator when using zone equipment night cycle manager
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/UnitVentilator.cc
Labels: Defect

#9346 Add Initial Ruleset Model Description JSON File Output File-NFP Only
  design/FY2022/NFP-InitialRulesetModelDescription.md
Labels: DoNotPublish, NewFeature

#9622 Correction of Fatal Error when Window5 Data File has SC or SHGC = 0
  src/EnergyPlus/HeatBalanceManager.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/Resources/Window5DataFile_ZeroSCandSHGC.dat
Labels: Defect

#9628 Calculate Mean Radiant Temperature (MRT) for Enclosures (not zones)
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DataViewFactorInformation.hh
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/ThermalComfort.hh
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
Labels: Defect

#9611 Actual ZoneNum Followup
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/BaseboardElectric.cc
  src/EnergyPlus/BaseboardElectric.hh
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/BaseboardRadiator.hh
  src/EnergyPlus/BranchInputManager.cc
  src/EnergyPlus/BranchNodeConnections.cc
  src/EnergyPlus/BranchNodeConnections.hh
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DataBranchNodeConnections.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataLoopNode.hh
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/DataZoneEquipment.hh
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/ElectricBaseboardRadiator.hh
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HWBaseboardRadiator.hh
  src/EnergyPlus/HeatBalanceInternalHeatGains.cc
  src/EnergyPlus/HeatBalanceInternalHeatGains.hh
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/InputProcessing/InputProcessor.hh
  src/EnergyPlus/IntegratedHeatPump.cc
  src/EnergyPlus/IntegratedHeatPump.hh
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/NodeInputManager.cc
  src/EnergyPlus/NodeInputManager.hh
  src/EnergyPlus/PlantCondLoopOperation.cc
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  src/EnergyPlus/RoomAirModelUserTempPattern.cc
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SimulationManager.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZonePlenum.cc
  tst/EnergyPlus/unit/BaseboardRadiator.unit.cc
  tst/EnergyPlus/unit/HVACDXSystem.unit.cc
  tst/EnergyPlus/unit/SZVAVModel.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Refactoring

#9575 Convert `constexpr int` to enum class.
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/RoomAirModelUserTempPattern.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorOptical.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
  tst/EnergyPlus/unit/WindowEquivalentLayer.unit.cc
Labels: Refactoring

#9652 Add warnings to AirloopHVAC:UnitarySystem when Setpoint control is used and no set point is present
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  tst/EnergyPlus/unit/HVACDXSystem.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#9629 Documentation 2022a
  doc/input-output-reference/src/input-for-output.tex
  doc/input-output-reference/src/overview/group-airflow.tex
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  doc/input-output-reference/src/overview/group-plant-equipment.tex
  doc/input-output-reference/src/overview/group-schedules.tex
  doc/input-output-reference/src/overview/group-surface-construction-elements.tex
  doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex
  doc/input-output-reference/src/overview/group-variable-refrigerant-flow-equipment.tex
  doc/input-output-reference/src/overview/group-water-systems.tex
  doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
Labels: Defect, Documentation

#9633 Update Kiva to v0.6.4
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.hh
  third_party/CMakeLists.txt
  third_party/cmake/kiva.cmake
  third_party/kiva-ep/CMakeLists.txt
  third_party/kiva-ep/cmake/compiler-flags.cmake
  third_party/kiva-ep/src/libkiva/CMakeLists.txt
  third_party/kiva-ep/src/libkiva/Cell.cpp
  third_party/kiva-ep/src/libkiva/Cell.hpp
  third_party/kiva-ep/src/libkiva/Domain.cpp
  third_party/kiva-ep/src/libkiva/Domain.hpp
  third_party/kiva-ep/src/libkiva/Foundation.cpp
  third_party/kiva-ep/src/libkiva/Geometry.cpp
  third_party/kiva-ep/src/libkiva/Geometry.hpp
  third_party/kiva-ep/src/libkiva/Ground.cpp
  third_party/kiva-ep/src/libkiva/Ground.hpp
  third_party/kiva-ep/test/unit/CMakeLists.txt
  third_party/kiva-ep/vendor/CMakeLists.txt
  third_party/zlib/CMakeLists.txt
Labels: Defect, NotIDDChange

#9639 Correction of U-Value Calculation with Film Coefficient
  doc/output-details-and-examples/src/output-files/eplusout-eio.tex
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataSurfaces.hh
  tst/EnergyPlus/unit/DataHeatBalance.unit.cc
Labels: Defect

#9655 Correct example file PackagedTerminalHeatPump_LatentSizing_SensibleAndLatent Sizing:Zone humidity set point schedules
  testfiles/PackagedTerminalHeatPump_LatentSizing_SensibleAndLatent.idf
Labels: Defect

#9641 Updated Code Compliant Dataset to Reflect Approved Changes in ASHRAE 90.1
  cmake/Install.cmake
  datasets/CodeCompliantEquipment.idf
Labels: Refactoring

#9626 ASHRAE Natural Convection Vertical Surface Concern
  doc/engineering-reference/src/surface-heat-balance-manager-processes/inside-heat-balance.tex
  src/EnergyPlus/ConvectionCoefficients.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
Labels: Defect

#9658 Fix urls in engineering reference doc source
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/coils.tex
Labels: DoNotPublish

#9644 Correction of Cumulative Green Roof Output Variables
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/EcoRoofManager.hh
  tst/EnergyPlus/unit/EcoRoofManager.unit.cc
Labels: Defect, Refactoring

#9653 Warn when Pixel counting used with shading surface transmittance schedule
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SolarShading.hh
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: Defect

#9657 Check and Enforce Limits on Schedule for SetpointManager:OutdoorAirReset
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/SetPointManager.hh
  tst/EnergyPlus/unit/SetPointManager.unit.cc
Labels: Defect

#9656 Fix for Pumps Turning Off and an Overhaul of the C++ Code in Pumps
  doc/input-output-reference/src/overview/group-pumps.tex
  src/EnergyPlus/Pumps.cc
  src/EnergyPlus/Pumps.hh
  tst/EnergyPlus/unit/Pumps.unit.cc
Labels: Defect, Refactoring

#9647 #Fix 9436 - TIMESTAMP Column in Custom Monthly Report Tables under both peak heating and peak cooling report has a trailing space
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabularAnnual.cc
  src/Transition/OutputRulesFiles/OutputChanges22-1-0-to-22-2-0.md
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#9634 Use currDifSolarRad, currBeamSolarRad to hold adjusted solar and other cleanups in the incident solar multiplier feature
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarShading.cc
Labels: Performance, Refactoring

#9618 SEER2 Calculations for Coil:Cooling:DX > CurveFitPerformance > CurveF…
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.hh
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.hh
Labels: NewFeature

#9569 Use condenser flow rate to calculate condenser inlet temperature in IPLV calculation
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/StandardRatings.cc
  src/EnergyPlus/StandardRatings.hh
  tst/EnergyPlus/unit/StandardRatings.unit.cc
Labels: Defect

#9646 Fix #9331 - Crash if window construction is zero due to bad construction name
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#9640 IDF Editor added dialog explaining workaround for #9010 out of memory error
  bin/IDFEditor/IDFEditor.exe
  src/IDF_Editor/IDFEd-main.frm
  src/IDF_Editor/IDFEd-project.VBP
  src/IDF_Editor/IDFEd-project.vbw
  src/IDF_Editor/IDFEditMain.bas
  src/IDF_Editor/about.frm
Labels: Defect, AuxiliaryTool

#9660 Fix curve negative energy issue in plant loop heat pumps
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  src/EnergyPlus/PlantLoopHeatPumpEIR.hh
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Defect

#9659 Test shadow calculation warning preprocessor directives in unit test
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: Defect

#9666 Add missing DLLs to fix IDFVersionUpdater on Windows
  bin/IDFVersionUpdater/Run-Win/IDFVersionUpdater Libs/Cryptox64.dll
  bin/IDFVersionUpdater/Run-Win/IDFVersionUpdater Libs/GZipx64.dll
  bin/IDFVersionUpdater/Run-Win/IDFVersionUpdater Libs/Internet Encodingsx64.dll
  bin/IDFVersionUpdater/Run-Win/vcruntime140_1.dll
Labels: Defect, DoNotPublish

#9665 A few dedicated exhaust related issues
  src/EnergyPlus/ExhaustAirSystemManager.cc
  src/EnergyPlus/ExhaustAirSystemManager.hh
  tst/EnergyPlus/unit/ExhaustSystem.unit.cc
Labels: Defect

#9661 9651 water use followup
  src/EnergyPlus/WaterUse.cc
  src/EnergyPlus/WaterUse.hh
  tst/EnergyPlus/unit/WaterUse.unit.cc
Labels: Defect, Refactoring

#9667 Fix ashrae205chiller crashing/repeated warnings issue
  src/EnergyPlus/ChillerElectricASHRAE205.cc
  third_party/btwxt/src/griddeddata.cpp
  third_party/btwxt/test/griddeddata_test.cpp
Labels: Defect, DoNotPublish, NotIDDChange

#9672 Add ITE design power to Zone Summary report
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#9676 #9303 - Effectively static link fortran utilities (and make them work on M1)
  cmake/Fortran.cmake
  cmake/Install.cmake
  cmake/qtifw/install_unix_createsymlinks.qs
Labels: Defect, Developer Issue

#9682 #9676 Follow Up - Make it more resilient to subtle differences in gfortran versions
  cmake/Fortran.cmake
Labels: Defect, Developer Issue

#9681 Fix #9680 - Avoid an override when getObjectItems is called a second time inside getting Internal heat Gains
  src/EnergyPlus/InternalHeatGains.cc
  testfiles/CMakeLists.txt
  testfiles/_CrashLights_9680.idf
  testfiles/emall.list
Labels: Defect, NotIDDChange
