Repository NREL/EnergyPlus, pull requests merged in 2022-05, with the labels that each got.

#9363 Fix node connection check
  src/EnergyPlus/BranchNodeConnections.cc
  tst/EnergyPlus/unit/BranchNodeConnections.unit.cc
Labels: Defect

#9413 Remove `select_case_var`s & `enum` cleanup
  src/EnergyPlus/HVACDXHeatPumpSystem.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/PhotovoltaicThermalCollectors.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/ThermalISO15099Calc.cc
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/UnitarySystem.cc
Labels: Refactoring

#9416 Clean headers from zup
  scripts/dev/find_byref_bool_override.py
  src/EnergyPlus/DataDefineEquip.hh
  src/EnergyPlus/WindTurbine.cc
  src/EnergyPlus/WindTurbine.hh
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManager.hh
  src/EnergyPlus/WindowManagerExteriorData.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  src/EnergyPlus/ZoneAirLoopEquipmentManager.cc
  src/EnergyPlus/ZoneAirLoopEquipmentManager.hh
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.hh
  src/EnergyPlus/ZoneDehumidifier.cc
  src/EnergyPlus/ZoneDehumidifier.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneEquipmentManager.hh
  src/EnergyPlus/ZonePlenum.cc
  src/EnergyPlus/ZonePlenum.hh
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/WindowManager.unit.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Refactoring

#9417 Continuing to eliminate SELECT_CASE_Var
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SolarCollectors.cc
  src/EnergyPlus/SolarCollectors.hh
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/SteamCoils.hh
  src/EnergyPlus/TARCOGArgs.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/UnitHeater.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterThermalTanks.hh
  src/EnergyPlus/WindowManager.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Refactoring

#9399 Move DataHVACGlobals::SetPointType to enum and switch/case
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/DataHVACGlobals.hh
  src/EnergyPlus/DataHeatBalFanSys.hh
  src/EnergyPlus/DataZoneControls.hh
  src/EnergyPlus/DemandManager.cc
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/Plant/Loop.hh
  src/EnergyPlus/PoweredInductionUnits.cc
  src/EnergyPlus/PurchasedAirManager.cc
  src/EnergyPlus/RefrigeratedCase.cc
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/WindowAC.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/AdvancedAFN.unit.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuct.unit.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/DOASEffectOnZoneSizing.unit.cc
  tst/EnergyPlus/unit/DualDuct.unit.cc
  tst/EnergyPlus/unit/FanCoilUnits.unit.cc
  tst/EnergyPlus/unit/HVACHXAssistedCoolingCoil.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/HeatBalanceKivaManager.unit.cc
  tst/EnergyPlus/unit/MixedAir.unit.cc
  tst/EnergyPlus/unit/OutdoorAirUnit.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
  tst/EnergyPlus/unit/PoweredInductionUnits.unit.cc
  tst/EnergyPlus/unit/PurchasedAirManager.unit.cc
  tst/EnergyPlus/unit/SingleDuct.unit.cc
  tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/WaterCoils.unit.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Refactoring

#9428 Continued Refactoring SELECT_CASE_var
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PackagedThermalStorageCoil.cc
  src/EnergyPlus/PackagedThermalStorageCoil.hh
  src/EnergyPlus/PipeHeatTransfer.cc
  src/EnergyPlus/PipeHeatTransfer.hh
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/PlantPipingSystemsManager.cc
  src/EnergyPlus/PlantPipingSystemsManager.hh
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/ScheduleManager.hh
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  src/EnergyPlus/UtilityRoutines.hh
Labels: Refactoring

#9408 Fixes DOAS system coils report cooling/heating power when system is off
  src/EnergyPlus/AirLoopHVACDOAS.cc
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
Labels: Defect

#9376 Slab ground heat transfer program has an exception during execution
  src/Slab/CMakeLists.txt
Labels: Defect, NotIDDChange

#9429 AirflowNetwork Refactor
  src/EnergyPlus/AirflowNetwork/CMakeLists.txt
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Elements.hpp
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Properties.hpp
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Solver.hpp
  src/EnergyPlus/AirflowNetwork/src/Elements.cpp
  src/EnergyPlus/AirflowNetwork/src/Properties.cpp
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/AirflowNetworkBalanceManager.cc
  src/EnergyPlus/AirflowNetworkBalanceManager.hh
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/CrossVentMgr.cc
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/ExhaustAirSystemManager.cc
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/ReturnAirPathManager.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/AdvancedAFN.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkBalanceManager.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkSimulationControl.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkSolver.unit.cc
  tst/EnergyPlus/unit/CrossVentMgr.unit.cc
  tst/EnergyPlus/unit/DOASEffectOnZoneSizing.unit.cc
  tst/EnergyPlus/unit/Furnaces.unit.cc
  tst/EnergyPlus/unit/HybridModel.unit.cc
  tst/EnergyPlus/unit/RoomAirflowNetwork.unit.cc
  tst/EnergyPlus/unit/ZoneContaminantPredictorCorrector.unit.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Refactoring

#9435 Continued select case var efforts
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DualDuct.cc
  src/EnergyPlus/DualDuct.hh
  src/EnergyPlus/EarthTube.cc
  src/EnergyPlus/EarthTube.hh
  src/EnergyPlus/EnergyPlus.hh
  src/EnergyPlus/EvaporativeFluidCoolers.cc
  src/EnergyPlus/EvaporativeFluidCoolers.hh
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/Fans.hh
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HVACControllers.hh
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.hh
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/OutdoorAirUnit.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/RoomAirModelManager.hh
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  third_party/ObjexxFCL/src/ObjexxFCL/numeric.hh
  tst/EnergyPlus/unit/EarthTube.unit.cc
  tst/EnergyPlus/unit/EvaporativeFluidCoolers.unit.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Refactoring

#9442 Fix failing debug test
  src/EnergyPlus/DualDuct.cc
Labels: DoNotPublish

#9364 Fix coil user defined node registration problem
  src/EnergyPlus/NodeInputManager.hh
  src/EnergyPlus/UserDefinedComponents.cc
  tst/EnergyPlus/unit/PlantManager.unit.cc
Labels: Defect

#9438 fix airloop index problem in std. 62.1 calculations
  src/EnergyPlus/SizingManager.cc
Labels: Defect

#9371 Update group-heating-and-cooling-coils.tex
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
Labels: Defect

#9440 Continued select case var and cleanup
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/DataAirLoop.hh
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/EvaporativeCoolers.hh
  src/EnergyPlus/FaultsManager.cc
  tst/EnergyPlus/unit/EvaporativeCoolers.unit.cc
Labels: Refactoring

#9444 #9420 - Parsing for precipitation values fails for some weather stat files (TMYx)
  scripts/dev/find_byref_bool_override.py
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/Resources/USA_IL_Chicago.OHare.Intl.AP.725300_TMYx.stat
Labels: Defect, SeverityLow
