Repository NREL/EnergyPlus, pull requests merged in 2022-04, with the labels that each got.

#9360 Side Quest: Cleaning a few files
  src/EnergyPlus/AirLoopHVACDOAS.hh
  src/EnergyPlus/AirTerminalUnit.hh
  src/EnergyPlus/BaseboardElectric.cc
  src/EnergyPlus/BaseboardElectric.hh
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/BaseboardRadiator.hh
  src/EnergyPlus/SimAirServingZones.cc
  tst/EnergyPlus/unit/BaseboardRadiator.unit.cc
Labels: DoNotPublish

#8714 Correct heating coil sizing in AirTerminal:SingleDuct:ConstantVolume:Reheat
  src/EnergyPlus/SingleDuct.cc
  tst/EnergyPlus/unit/SingleDuct.unit.cc
Labels: Defect

#9373 typo
  src/EnergyPlus/DataBSDFWindow.hh
Labels: Refactoring

#9375 Fix typo in error message
  src/EnergyPlus/DataErrorTracking.hh
Labels: Defect

#9356 Fix Basement preprocessor NaN fatal error
  .github/workflows/windows_release.yml
  src/Basement/CMakeLists.txt
Labels: Defect

#9352 Silence a warning on mac
  cmake/PythonFixUpOnMac.cmake
Labels: DoNotPublish, NotIDDChange, Developer Issue

#9323 Enum Refactor & Remove `SELECT_CASE_var`
  src/EnergyPlus/BranchInputManager.cc
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/CondenserLoopTowers.hh
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/CoolTower.cc
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/CostEstimateManager.hh
  src/EnergyPlus/CrossVentMgr.cc
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/MundtSimMgr.cc
  src/EnergyPlus/Plant/Enums.hh
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/RoomAirModelUserTempPattern.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/UFADManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/DisplacementVentMgr.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Refactoring

#9385 Remove `select_case_var`s & `enum class` cleanup
  src/EnergyPlus/Autosizing/Base.hh
  src/EnergyPlus/Autosizing/BaseSizerWithScalableInputs.cc
  src/EnergyPlus/Autosizing/CoolingAirFlowSizing.cc
  src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc
  src/EnergyPlus/Autosizing/HeatingAirFlowSizing.cc
  src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc
  src/EnergyPlus/Autosizing/SystemAirFlowSizing.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DataAirSystems.hh
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACSystemRootFindingAlgorithm.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/Humidifiers.cc
  src/EnergyPlus/Pumps.hh
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UserDefinedComponents.cc
  src/EnergyPlus/WeatherManager.hh
  src/EnergyPlus/WindowAC.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
Labels: Refactoring

#9389 Support External Linkage with Constexprs in Visual Studio
  cmake/CompilerFlags.cmake
  src/EnergyPlus/Boilers.hh
Labels: DoNotPublish

#9391 Fix readme badges links
  README.md
Labels: DoNotPublish

#9396 Fix Missing Brace in LaTeX which caused issue with HTML docs generation
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-004/radiant-system-models.tex
Labels: DoNotPublish, Documentation

#9401 Update documentation-windows miktek setup version to 4.2
  .github/workflows/documentation-windows.yml
Labels: DoNotPublish
