Repository NREL/EnergyPlus, pull requests merged in 2022-06, with the labels that each got.

#9433 Add fmt validation custom check
  scripts/dev/check_format_strings.py
  scripts/dev/custom_check.sh
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/FileSystem.cc
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
Labels: Defect

#9445 #9410 - ConvertInputFormat incorrectly handles file name with period in name
  src/ConvertInputFormat/CMakeLists.txt
  src/ConvertInputFormat/main.cpp
  src/ConvertInputFormat/test_convert_input_format.py
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/DataStringGlobals.hh
Labels: Defect, AuxiliaryTool

#9469 UpdateZoneSizing(EndDay) should only be called after warmup
  src/EnergyPlus/SizingManager.cc
Labels: DoNotPublish, NotIDDChange, Developer Issue

#9454 Expose EPVector resize method, change allocation handling
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Solver.hpp
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/EPVector.hh
  tst/EnergyPlus/unit/AirflowNetworkSolver.unit.cc
  tst/EnergyPlus/unit/EPVector.unit.cc
Labels: Refactoring

#9452 Refactor and Cleanup OutputReports.cc
  doc/input-output-reference/src/overview/group-radiative-convective-units.tex
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/OutputReports.hh
Labels: Refactoring

#9447 #7383 - Avoid issuing 'not fully enclosed' warning when zone is in fact enclosed
  src/EnergyPlus/DataVectorTypes.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#9425 Change VariableSpeed coil sizing to use StdRhoAir
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  tst/EnergyPlus/unit/HVACDXSystem.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/VariableSpeedCoils.unit.cc
Labels: Defect

#9473 Hotfix #9445 - Shlex chokes on WindowsPaths due to forward slashes
  src/ConvertInputFormat/test_convert_input_format.py
Labels: DoNotPublish, Developer Issue

#9457 Fix #9455 and #9456 - Address water-to-air cooling coils sizing related issues
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  tst/EnergyPlus/unit/VariableSpeedCoils.unit.cc
Labels: Defect

#9477 Enum & SelectCaseVar Cleanups Continued
  doc/module-developer/src/energyplus-services/global-data-flags-and-parameters.tex
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/DataHeatBalFanSys.hh
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc
  src/EnergyPlus/HVACSizingSimulationManager.cc
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/HeatRecovery.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/UtilityRoutines.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/HeatPumpWaterToWaterSimple.unit.cc
  tst/EnergyPlus/unit/HeatRecovery.unit.cc
  tst/EnergyPlus/unit/PlantHeatExchangerFluidToFluid.unit.cc
Labels: Refactoring

#9482 Random line of code resets FanOpMode when UnitarySystem uses multi-speed heating coil and Setpoint control
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  tst/EnergyPlus/unit/VariableSpeedCoils.unit.cc
Labels: Defect

#9441 Address set sky and ground surfaces view factors for surfaces property object
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManager.cc
  testfiles/SurfacePropTest_SurfLWR.idf
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Defect

#9488 Add Custom Check to Report on Enum Class Usage/Scope
  scripts/dev/check_constexpr.py
  scripts/dev/check_for_enum_scope_usage.py
  scripts/dev/check_for_malformed_enums.py
  scripts/dev/check_format_strings.py
  scripts/dev/custom_check.sh
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionConstants.hh
  src/EnergyPlus/DataComplexFenestration.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/EarthTube.cc
  src/EnergyPlus/EarthTube.hh
  src/EnergyPlus/Humidifiers.hh
  src/EnergyPlus/IceThermalStorage.hh
  src/EnergyPlus/PipeHeatTransfer.cc
  src/EnergyPlus/PipeHeatTransfer.hh
  src/EnergyPlus/RefrigeratedCase.hh
  src/EnergyPlus/Shape.hh
  src/EnergyPlus/TARCOGParams.hh
  src/EnergyPlus/TarcogShading.cc
  src/EnergyPlus/ThermalISO15099Calc.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
Labels: DoNotPublish

#9487 Fix crash if number of ATUs on one airloop exceeds number of zones and Fix OA Details Report with Multipliers
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/HVACCooledBeam.cc
  src/EnergyPlus/HVACFourPipeBeam.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SizingManager.cc
  tst/EnergyPlus/unit/SimAirServingZones.unit.cc
Labels: Defect

#9478 Remove include from hh that is in cc
  src/EnergyPlus/Autosizing/CoolingAirFlowSizing.cc
  src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc
  src/EnergyPlus/Autosizing/HeatingCapacitySizing.hh
Labels: Defect, DoNotPublish

#9475 ZoneHVAC:FourPipeFanCoil shows a fatal sizing error when autosized coil inlet temperature is negative
  src/EnergyPlus/Autosizing/Base.cc
  tst/EnergyPlus/unit/Autosizing/BaseClassSizing.unit.cc
Labels: Defect

#9424 Add Exterior solar surface lists and maybe other performance tweaks
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarReflectionManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Performance

#9499 Fix Missing Argument in Runtime API
  src/EnergyPlus/api/runtime.py
  tst/EnergyPlus/api/TestRuntime.py
Labels: Defect

#9490 Complex window solar or ground ray calculation potential overflow
  src/EnergyPlus/WindowComplexManager.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: Defect

#9502 `enum` & `Select_Case_Var` Cleanups Continued
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/DemandManager.cc
Labels: Refactoring

#9514 Addressed Inccorret declaration of dataIsDXCoil variable in BaseSizer
  src/EnergyPlus/Autosizing/Base.hh
Labels: Defect

#9501 AirloopHVAC:UnitarySystem uses outdoor air temperature to size water source dx cooling coils and incorrectly reports autosized supplemental heating coil capacity for CoolReheat control
  src/EnergyPlus/Autosizing/BaseSizerWithScalableInputs.cc
  src/EnergyPlus/Autosizing/BaseSizerWithScalableInputs.hh
  src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc
  src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/UnitarySystem.cc
  testfiles/CMakeLists.txt
  testfiles/UnitarySystem_ZoneVSWSHP_wDOAS.idf
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect
