Repository NREL/EnergyPlus, pull requests merged in 2022-03, with the labels that each got.

#9300 #9298 #9174 #7546 #8199 - V22-1-0-IOFreeze installer issues
  cmake/Install.cmake
  cmake/qtifw/install_registerfiletype.qs
  cmake/qtifw/install_script.qs
  cmake/qtifw/install_win_copydll.qs
Labels: Defect, DoNotPublish, Developer Issue

#9249 Fix Integrated Heat Pump Output Variable Setup
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/IntegratedHeatPump.cc
  src/EnergyPlus/IntegratedHeatPump.hh
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  src/EnergyPlus/WaterThermalTanks.cc
  tst/EnergyPlus/unit/IntegratedHeatPump.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
Labels: Defect, Refactoring

#9285 ZoneHVAC:UnitVentilator shows different autosized min/max OA flow rates for FixedAmount OA control option
  doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
  src/EnergyPlus/UnitVentilator.cc
  testfiles/UnitVent5Zone.idf
  testfiles/UnitVent5ZoneAuto.idf
  testfiles/UnitVent5ZoneFixedOANoCoilOpt.idf
  tst/EnergyPlus/unit/UnitVentilator.unit.cc
Labels: Defect

#9187 Add coil cooling dx saturation check
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDXCurveFitSpeed.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#9288 Unit ventilator refactor
  src/EnergyPlus/Autosizing/Base.cc
  src/EnergyPlus/Autosizing/Base.hh
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/SteamCoils.hh
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UnitVentilator.hh
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/WaterCoils.hh
  tst/EnergyPlus/unit/UnitVentilator.unit.cc
Labels: DoNotPublish

#9258 Remove `SELECT_CASE_var` in WindTurbine.cc
  src/EnergyPlus/WaterToAirHeatPump.cc
  src/EnergyPlus/WaterToAirHeatPump.hh
  src/EnergyPlus/WaterUse.cc
  src/EnergyPlus/WaterUse.hh
  src/EnergyPlus/WindTurbine.cc
  src/EnergyPlus/WindTurbine.hh
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowComplexManager.hh
  src/EnergyPlus/WindowManagerExteriorData.cc
Labels: Refactoring

#9274 Remove `SELECT_CASE_var` in VentilatedSlab.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/VentilatedSlab.hh
Labels: Refactoring

#9299 Clean ups from some window assembly reporting comments
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/WindowManagerExteriorOptical.cc
  src/EnergyPlus/WindowManagerExteriorOptical.hh
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  src/EnergyPlus/WindowManagerExteriorThermal.hh
Labels: DoNotPublish, NewFeature, NotIDDChange

#9324 Correct Window5 Data File window name if it contains spaces
  src/EnergyPlus/HeatBalanceManager.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/Resources/Window5DataFile_NameWithSpace.dat
Labels: Defect, NotIDDChange

#9316 Correct Kiva::setMessageCallback std:pair argument
  src/EnergyPlus/HeatBalanceKivaManager.cc
  tst/EnergyPlus/unit/HeatBalanceKivaManager.unit.cc
Labels: Defect, NotIDDChange

#9310 #9264 - EnergyPlus missing vcomp140.dll on Windows
  CMakeLists.txt
  cmake/Install.cmake
  cmake/qtifw/install_operations.qs
  cmake/qtifw/install_registerfiletype.qs
  cmake/qtifw/install_script.qs
  cmake/qtifw/install_win_copydll.qs
  src/ConvertInputFormat/CMakeLists.txt
Labels: Defect, DoNotPublish, NotIDDChange, Developer Issue

#9328 Add warning for Kiva deep-ground boundary condition and deep-ground depth for auto
  doc/input-output-reference/src/overview/group-advanced-surface-concepts.tex
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceKivaManager.hh
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect, NotIDDChange

#9327 AirLoopHVAC:DedicatedOutdoorAirSystem does not size correctly when multiple DOAS systems are simulated
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/AirLoopHVACDOAS.hh
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
Labels: Defect

#9308 Fix User-input Floor Area for Zone and Space
  doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex
  src/EnergyPlus/SurfaceGeometry.cc
  testfiles/5ZoneEndUses.idf
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#9319 Cleanup `SELECT_CASE_VAR` in SystemAvailabilityManager
  src/EnergyPlus/DataAirLoop.hh
  src/EnergyPlus/DataHVACGlobals.hh
  src/EnergyPlus/Plant/PlantAvailManager.hh
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/SystemAvailabilityManager.hh
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/SystemAvailabilityManager.unit.cc
Labels: Refactoring

#9231 Fix 8638 chiller condenser recurring warnings
  doc/input-output-reference/src/overview/group-water-heaters.tex
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerExhaustAbsorption.hh
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.hh
  tst/EnergyPlus/unit/ChillerExhaustAbsorption.unit.cc
Labels: Defect, Documentation

#9269 Modify ground surface conduction calculation for Kiva surfaces and ensure conduction heat balance
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/ThermalComfort.hh
  tst/EnergyPlus/unit/HeatBalanceKivaManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
Labels: Defect, NotIDDChange

#9322 Fix #7511 which shows warning for too many controlled shades
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
Labels: Defect

#9321 #9164 - #9313 - Paths problems
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/FileSystem.cc
  src/EnergyPlus/IOFiles.cc
Labels: Defect

#9337 Fix bug in SystemAvailabilityManager when it has an empty name
  src/EnergyPlus/SystemAvailabilityManager.cc
Labels: DoNotPublish

#9294 #9000 - Average values for integer output variables fail debug assert and are rounded to 1 place
  src/EnergyPlus/OutputProcessor.cc
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Defect, NotIDDChange

#9290 Fix Rainfall is handled differently between weather file values and Site:Precipitation water manager values #4153
  doc/auxiliary-programs/src/weather-converter-program/energyplus-weather-file-epw-data-dictionary.tex
  doc/input-output-reference/src/overview/group-location-climate-weather-file-access.tex
  src/EnergyPlus/DataWater.hh
  src/EnergyPlus/WaterManager.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  tst/EnergyPlus/unit/WeatherManager.unit.cc
Labels: Defect

#9267 Add EPVector bounds checking for debug builds
  src/EnergyPlus/EPVector.hh
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/EPVector.unit.cc
Labels: DoNotPublish, NotIDDChange

#9341 Fix crash in Window Assembly report with multiple shading states
  src/EnergyPlus/WindowManagerExteriorThermal.cc
Labels: Defect

#9345 Prep for 22.1 release
  release/Bugreprt.txt
  release/Deprecation.html
  release/readme.html
  src/Transition/InputRulesFiles/Rules9-6-0-to-22-1-0.md
Labels: DoNotPublish

#9349 Use epin variable properly for EPLaunch
  release/readme.html
  src/EnergyPlus/PluginManager.cc
Labels: DoNotPublish

#9354 Fix #9353 - Kiva build error on mac with clang >= 13
  cmake/CompilerFlags.cmake
  third_party/kiva-ep/src/libkiva/Ground.cpp
  third_party/kiva-ep/src/libkiva/Ground.hpp
Labels: Defect, DoNotPublish, NotIDDChange, Developer Issue
