Repository NREL/EnergyPlus, pull requests merged in 2022-07, with the labels that each got.

#9409 New Feature Multiple Ground Temperature and Ground Reflectance
  design/FY2022/GroundSurfaceProperties.png
  design/FY2022/NFP-MultipleGroundTemperatureReflectance.md
  doc/engineering-reference/src/solar-radiation-reflected-from-exterior/diffuse-reflection-of-beam-solar-and-sky.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/outside-surface-heat-balance.tex
  doc/input-output-reference/src/overview/group-advanced-surface-concepts.tex
  scripts/dev/check_for_tabs.py
  scripts/dev/check_for_tabs_in_idfs.py
  scripts/dev/custom_check.sh
  scripts/dev/generate_epJSON_schema/modify_schema.py
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManager.cc
  src/Transition/CreateNewIDFUsingRulesV22_2_0.f90
  src/Transition/InputRulesFiles/Rules22-1-0-to-22-2-0.md
  src/Transition/OutputRulesFiles/OutputChanges22-1-0-to-22-2-0.md
  testfiles/CMakeLists.txt
  testfiles/SurfacePropGndSurfs.csv
  testfiles/SurfacePropGroundSurfaces_LWR.idf
  tst/EnergyPlus/unit/DataSurfaces.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/ICSCollector.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: NewFeature, IDDChange

#9505 `Select_Case_Var` & `enum` Cleanups Continued
  src/EnergyPlus/DemandManager.cc
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/EMSManager.hh
  src/EnergyPlus/FaultsManager.cc
  src/EnergyPlus/FuelCellElectricGenerator.cc
  src/EnergyPlus/FuelCellElectricGenerator.hh
Labels: Refactoring

#9518 Fixes ExtShadingSchedNum variable in SolarShading should be checked as an integer
  src/EnergyPlus/SolarShading.cc
Labels: Defect, DoNotPublish

#9520 Set Zone Floor Area = Zone CalcFloorArea in SurfaceGeometr
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#9504 Correct logic in AirflowNetwork Duct Autosizing
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
Labels: Defect, DoNotPublish, AirflowNetwork

#9531 Fix #9508 - Warning message round up precisions for water flow or other liquid volume flow rates
  src/EnergyPlus/Pumps.cc
Labels: DoNotPublish

#9543 Correct copy to reference
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DXCoils.hh
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/Furnaces.hh
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/PackagedTerminalHeatPump.cc
  src/EnergyPlus/PackagedTerminalHeatPump.hh
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  tst/EnergyPlus/unit/Furnaces.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
Labels: Defect, DoNotPublish

#9552 OA reports no-diff code cleanup
  src/EnergyPlus/DataAirLoop.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/SystemReports.hh
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
  tst/EnergyPlus/unit/SystemReports.unit.cc
  tst/EnergyPlus/unit/UnitaryHybridAirConditioner.unit.cc
Labels: Refactoring

#9533 Fix fluid property interpolation for single concentration case
  src/EnergyPlus/FluidProperties.cc
  tst/EnergyPlus/unit/FluidProperties.unit.cc
Labels: Defect

#9476 Fix AirLoop Component Loads Report Coincident Peak
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/SimAirServingZones.cc
  tst/EnergyPlus/unit/Autosizing/BaseClassSizing.unit.cc
Labels: Defect

#9513 Addresses Coil:Cooling:DX reports full load capacity for lower speeds
  src/EnergyPlus/Autosizing/Base.cc
  src/EnergyPlus/Autosizing/Base.hh
  src/EnergyPlus/Autosizing/CoolingAirFlowSizing.cc
  src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.cc
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  tst/EnergyPlus/unit/Coils/CoilCoolingDX.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#9562 Update helpdesk URL in README.md
  README.md
Labels: DoNotPublish

#9530 Fix #9060 - Stepped daylighting control can produce lighting power multipliers > 1.0
  src/EnergyPlus/DaylightingManager.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
Labels: Defect

#9561 9560 eliminate loop for surface heat transfer algorithm and replace with select reset
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Performance

#9529 Fixes supply fan heat effect is incorrect in standard ratings calculation for two speed DX cooling coil
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/StandardRatings.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
Labels: Defect, PriorityHigh

#9535 Update GHE Interpolation Routine
  src/EnergyPlus/GroundHeatExchangers.cc
  tst/EnergyPlus/unit/GroundHeatExchangers.unit.cc
Labels: Refactoring

#9541 Fix #9538 ElectricEquipment:ITE:AirCooled Environmental Class Code Specifications
  src/EnergyPlus/InternalHeatGains.cc
  testfiles/2ZoneDataCenterHVAC_wEconomizer_ClassA1A2.idf
  testfiles/CMakeLists.txt
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
Labels: Defect

#9545 Fix #9123 - GetVertices is dropping vertices inconsistently, causing fatal error
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#9446 Fix #9432 - Roof perimeter in the outside surface convection calculations can be wrong for rotated rectangular shapes
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: Defect

#9544 Fix #9118 - CheckConvexity is not removing collinear points consistently, causing fatal error
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#9565 Fix #9551 - Update LCC using NIST 135 supplement for years 2020, 2021 and 2022
  cmake/Install.cmake
  datasets/LCCusePriceEscalationDataSet2019.idf
  datasets/LCCusePriceEscalationDataSet2020.idf
  datasets/LCCusePriceEscalationDataSet2021.idf
  datasets/LCCusePriceEscalationDataSet2022.idf
  scripts/dev/update_nist_escalation.py
  tst/EnergyPlus/unit/Datasets.unit.cc
Labels: Defect, AuxiliaryTool

#9573 Fix VRF central condenser EIRFPLR curve bound and add warning messages
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#9567 Correct argument list for DownInterpolate4HistoryValues function calls
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.hh
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/HybridModel.unit.cc
  tst/EnergyPlus/unit/ZoneContaminantPredictorCorrector.unit.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Defect
