Repository NREL/EnergyPlus, pull requests merged in 2022-08, with the labels that each got.

#9577 9576 vs coil model sets heating capacity
  src/EnergyPlus/UnitarySystem.cc
Labels: Defect

#9525 Corrects Coil:Heating:Gas:MultiStage to call the gas coil model instead of electric coil model
  src/EnergyPlus/UnitarySystem.cc
Labels: Defect

#9336 Include SizingPeriod:WeatherFileDays in DOAS sizing
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SimulationManager.hh
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
Labels: Defect

#9402 Allow running just load calculations and no full simulations
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SizingManager.cc
  tst/EnergyPlus/unit/UnitHeater.unit.cc
Labels: NewFeature, Performance, NotIDDChange

#9386 9157 9191 simulation control adjustments
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/WeatherManager.cc
  tst/EnergyPlus/unit/Autosizing/BaseClassSizing.unit.cc
  tst/EnergyPlus/unit/HVACFourPipeBeam.unit.cc
  tst/EnergyPlus/unit/SimulationManager.unit.cc
  tst/EnergyPlus/unit/WeatherManager.unit.cc
Labels: Defect, NotIDDChange

#9556 Fix #9550 - Avoid expensive calls inside BuildKeyVarList
  src/EnergyPlus/DataOutputs.cc
  src/EnergyPlus/DataOutputs.hh
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Defect

#9392 Add staging actuator to Coil:Heating:Electric:MultiStage
  design/FY2022/NFP-ElectricCoilStageEMSActuators.md
  doc/ems-application-guide/src/ems-actuators/hvac-systems-001.tex
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  testfiles/CMakeLists.txt
  testfiles/PythonPlugin_SingleFamilyHouse_TwoSpeed_MultiStageElectricSuppCoil.idf
  testfiles/PythonPlugin_SingleFamilyHouse_TwoSpeed_MultiStageElectricSuppCoil.py
  testfiles/SingleFamilyHouse_TwoSpeed_MultiStageElectricSuppCoilEMS.idf
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: NewFeature

#9557 Test SetupOutputVariable changes to accept std::string_view type for parameters
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataOutputs.cc
  src/EnergyPlus/DataOutputs.hh
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/ResultsFramework.cc
  src/EnergyPlus/ResultsFramework.hh
  src/EnergyPlus/SQLiteProcedures.cc
  src/EnergyPlus/SQLiteProcedures.hh
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/UtilityRoutines.hh
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Performance, Refactoring

#9498 Accept Air Terminal objects in RoomAir:Node:AirflowNetwork:HVACEquipment
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  tst/EnergyPlus/unit/RoomAirflowNetwork.unit.cc
Labels: Defect

#9582 Fix #9489 - Construction:AirBoundary fails for fenestration surfaces
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportPredefined.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/Transition/OutputRulesFiles/OutputChanges22-1-0-to-22-2-0.md
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect, OutputChange

#9536 Allow fan placement in any order in air loop hvac dedicated outdoor air system
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/AirLoopHVACDOAS.hh
  src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc
  src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
  tst/EnergyPlus/unit/Autosizing/CoolingCapacitySizing.unit.cc
  tst/EnergyPlus/unit/Autosizing/HeatingCapacitySizing.unit.cc
Labels: Defect

#9584 Clean up array references in sizing code to speed up code execution
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
Labels: Refactoring

#9526 Add Integers to epJSON Schema
  scripts/dev/check_for_malformed_enums.py
  scripts/dev/generate_epJSON_schema/idd_parser.py
  scripts/dev/generate_epJSON_schema/idd_parser_draft_v4.py
  src/EnergyPlus/InputProcessing/IdfParser.cc
  src/EnergyPlus/InputProcessing/IdfParser.hh
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  tst/EnergyPlus/unit/DesiccantDehumidifiers.unit.cc
  tst/EnergyPlus/unit/HVACHXAssistedCoolingCoil.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/InputProcessor.unit.cc
  tst/EnergyPlus/unit/IntegratedHeatPump.unit.cc
  tst/EnergyPlus/unit/TranspiredCollector.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/VariableSpeedCoils.unit.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
  tst/EnergyPlus/unit/WindowAC.unit.cc
Labels: Defect, OutputChange

#9604 Fix IDF Editor issues and add units
  bin/IDFEditor/IDFEditor.exe
  src/IDF_Editor/IDFEd-main.frm
  src/IDF_Editor/IDFEd-project.VBP
  src/IDF_Editor/IDFEditMain.bas
  src/IDF_Editor/about.frm
Labels: Defect, AuxiliaryTool

#9610 Fix HXAssisted Cooling Coil CI build warning
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/HVACHXAssistedCoolingCoil.hh
Labels: DoNotPublish

#9615 Fix #9614 - Ajust YAML permissions to allow action to upload asset to release
  .github/workflows/linux_release.yml
  .github/workflows/mac_release.yml
  .github/workflows/windows_release.yml
Labels: Defect, DoNotPublish, Developer Issue

#9619 Fix #9616 - Update GHA runners: Add ubuntu-22.04 and macos-12
  .github/workflows/linux_release.yml
  .github/workflows/mac_release.yml
  src/EnergyPlus/FluidProperties.hh
  src/EnergyPlus/Psychrometrics.hh
  third_party/Windows-CalcEngine/cmake/WCECompilerFlags.cmake
  third_party/Windows-CalcEngine/src/Gases/src/Gas.cpp
  third_party/kiva-ep/src/libkiva/CMakeLists.txt
  third_party/ssc/jsoncpp/CMakeLists.txt
Labels: Defect, DoNotPublish, Developer Issue

#9555 `select_case_var` & `constexpr int` Cleanups Continued
  src/EnergyPlus/Autosizing/Base.cc
  src/EnergyPlus/Autosizing/Base.hh
  src/EnergyPlus/Autosizing/CoolingAirFlowSizing.cc
  src/EnergyPlus/Autosizing/HeatingAirFlowSizing.cc
  src/EnergyPlus/Autosizing/HeatingAirflowUASizing.cc
  src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc
  src/EnergyPlus/Autosizing/SystemAirFlowSizing.cc
  src/EnergyPlus/DataAirLoop.hh
  src/EnergyPlus/DataAirSystems.hh
  src/EnergyPlus/DataHVACGlobals.hh
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DualDuct.cc
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/General.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/Humidifiers.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixedAir.hh
  src/EnergyPlus/PhotovoltaicThermalCollectors.cc
  src/EnergyPlus/PoweredInductionUnits.cc
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimAirServingZones.hh
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/Autosizing/CoolingAirFlowSizing.unit.cc
  tst/EnergyPlus/unit/Autosizing/CoolingWaterDesWaterInletTempSizing.unit.cc
  tst/EnergyPlus/unit/Autosizing/HeatingAirFlowSizing.unit.cc
  tst/EnergyPlus/unit/Autosizing/HeatingAirflowUASizing.unit.cc
  tst/EnergyPlus/unit/Autosizing/HeatingCapacitySizing.unit.cc
  tst/EnergyPlus/unit/Autosizing/HeatingWaterDesAirInletTempSizing.unit.cc
  tst/EnergyPlus/unit/Autosizing/SystemAirFlowSizing.unit.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDX.unit.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/DataZoneEquipment.unit.cc
  tst/EnergyPlus/unit/DualDuct.unit.cc
  tst/EnergyPlus/unit/HeatRecovery.unit.cc
  tst/EnergyPlus/unit/MixedAir.unit.cc
  tst/EnergyPlus/unit/SingleDuct.unit.cc
  tst/EnergyPlus/unit/SizeWaterHeatingCoil.unit.cc
  tst/EnergyPlus/unit/SizingManager.unit.cc
  tst/EnergyPlus/unit/SystemReports.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Refactoring

#9627 No diff clean up
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: DoNotPublish
