Repository NREL/EnergyPlus, pull requests merged in 2023-06, with the labels that each got.

#10050 ConvectionCoefficients Enumeration-based Cleanup
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  src/EnergyPlus/ConvectionConstants.hh
  src/EnergyPlus/CrossVentMgr.cc
  src/EnergyPlus/DataGlobalConstants.hh
  src/EnergyPlus/DataHeatBalSurface.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/PhotovoltaicThermalCollectors.cc
  src/EnergyPlus/PipeHeatTransfer.cc
  src/EnergyPlus/PondGroundHeatExchanger.cc
  src/EnergyPlus/SQLiteProcedures.cc
  src/EnergyPlus/SQLiteProcedures.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  src/EnergyPlus/SurfaceGroundHeatExchanger.cc
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/UFADManager.cc
  src/EnergyPlus/WindowManager.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/DataSurfaces.unit.cc
  tst/EnergyPlus/unit/DisplacementVentMgr.unit.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/ICSCollector.unit.cc
  tst/EnergyPlus/unit/SQLite.unit.cc
  tst/EnergyPlus/unit/TranspiredCollector.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: DoNotPublish, Refactoring

#10018 CppCheck HVACUnitaryBypassVAV
  src/EnergyPlus/DataHVACGlobals.cc
  src/EnergyPlus/DataHVACGlobals.hh
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.hh
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
Labels: DoNotPublish

#10023 CppCheck 2nd attempt at HWBaseboardRadiator
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HWBaseboardRadiator.hh
  tst/EnergyPlus/unit/HWBaseboardRadiator.unit.cc
Labels: DoNotPublish

#10031 CppCheck HeatBalFiniteDiffManager
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.hh
  src/EnergyPlus/HeatBalanceAirManager.cc
Labels: DoNotPublish

#10032 CppCheck HeatBalanceIntRadExchange
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.hh
  src/EnergyPlus/HeatBalanceInternalHeatGains.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceManager.hh
Labels: DoNotPublish

#10044 API-ish Cleanups May 2023
  .decent_ci-Windows.yaml
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/api/runtime.py
  tst/EnergyPlus/api/TestRuntime.py
Labels: Defect, APIChange

#10047 Correct HTML code when reporting `≤` and `≥`
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#10034 CppCheck HeatPumpWaterToWater
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.cc
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.hh
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.cc
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.hh
  src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
  src/EnergyPlus/HeatPumpWaterToWaterSimple.hh
  src/EnergyPlus/HeatRecovery.cc
Labels: DoNotPublish

#10015 Refactor logic in VRF control function to simplify code readability
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
Labels: Refactoring

#9970 Address peak sensible load with sizing factor at cooling peak conditions reports zero value
  src/EnergyPlus/SimAirServingZones.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect, NotIDDChange

#10013 Integration of FuelTypeName enums Round 2
  src/EnergyPlus/BoilerSteam.cc
  src/EnergyPlus/BoilerSteam.hh
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/Boilers.hh
  src/EnergyPlus/CTElectricGenerator.cc
  src/EnergyPlus/CTElectricGenerator.hh
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.hh
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.hh
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DXCoils.hh
  src/EnergyPlus/DataGlobalConstants.hh
  src/EnergyPlus/DataZoneEquipment.hh
  src/EnergyPlus/EconomicLifeCycleCost.hh
  src/EnergyPlus/EconomicTariff.cc
  src/EnergyPlus/EconomicTariff.hh
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/HeatingCoils.hh
  src/EnergyPlus/ICEngineElectricGenerator.cc
  src/EnergyPlus/ICEngineElectricGenerator.hh
  src/EnergyPlus/MicroturbineElectricGenerator.cc
  src/EnergyPlus/MicroturbineElectricGenerator.hh
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/Plant/MeterData.hh
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/PlantChillers.hh
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  src/EnergyPlus/PlantLoopHeatPumpEIR.hh
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterThermalTanks.hh
  tst/EnergyPlus/unit/BoilerHotWater.unit.cc
  tst/EnergyPlus/unit/BoilerSteam.unit.cc
  tst/EnergyPlus/unit/CTElectricGenerator.unit.cc
  tst/EnergyPlus/unit/ChillerGasAbsorption.unit.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDX.unit.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/EconomicLifeCycleCost.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/HeatingCoils.unit.cc
  tst/EnergyPlus/unit/ICEngineElectricGenerator.unit.cc
  tst/EnergyPlus/unit/MicroturbineElectricGenerator.unit.cc
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/PlantChillers.unit.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
  tst/EnergyPlus/unit/StandardRatings.unit.cc
  tst/EnergyPlus/unit/UnitaryHybridAirConditioner.unit.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
Labels: Refactoring

#10021 Address AirloopHVAC:UnitarySystem CoolReheat Humidity Control Problem
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect, SeverityHigh

#10039 Correction of Calculation Error when using Multiple Swimming Pools
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/indoor-swimming-pool.tex
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  src/EnergyPlus/SwimmingPool.cc
  tst/EnergyPlus/unit/SwimmingPool.unit.cc
Labels: SeverityMedium, Defect

#10060 CppCheck HeatingCoils
  src/EnergyPlus/HeatingCoils.cc
Labels: DoNotPublish

#10070 Fix #10068 - Progress Callback should report 100 when simulation completely succesfully
  src/EnergyPlus/UtilityRoutines.cc
  tst/EnergyPlus/api/TestRuntime.c
  tst/EnergyPlus/api/TestRuntime.py
Labels: Defect

#10054 Only execute epJSON schema generation steps when dependencies are modified
  .gitignore
  CMakeLists.txt
  doc/readthedocs/sphinx/conf.py
  scripts/dev/generate_epJSON_schema/generate_epJSON_schema.py
  scripts/dev/generate_epJSON_schema/modify_schema.py
  src/EnergyPlus/CMakeLists.txt
Labels: Defect, DoNotPublish, NotIDDChange, Developer Issue

#10069 Fix SQLite unit tests
  src/EnergyPlus/SQLiteProcedures.cc
  src/EnergyPlus/SQLiteProcedures.hh
  src/EnergyPlus/SimulationManager.cc
  tst/EnergyPlus/unit/Autosizing/BaseClassSizing.unit.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDX.unit.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDXCurveFitOperatingMode.unit.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/EconomicTariff.unit.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.hh
  tst/EnergyPlus/unit/HVACSizingSimulationManager.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/OutputReportTabularAnnual.unit.cc
  tst/EnergyPlus/unit/WeatherManager.unit.cc
Labels: DoNotPublish, PriorityHigh, Developer Issue

#10071 Fixes failed unit tests when no cooling design day
  src/EnergyPlus/SizingManager.cc
Labels: Defect

#10040 Fix overlapping shadow calculations for shading surface transmittance >0 and <1
  doc/engineering-reference/src/climate-sky-and-solar-shading-calculations/shading-module.tex
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SolarShading.hh
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: Defect

#10036 Fix EIO airflow and capacity reporting for `Coil:Cooling:DX:Multispeed`
  src/EnergyPlus/DXCoils.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.hh
Labels: Defect

#10066 Second Convection Coefficients cleanup pass
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/CurveManager.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/GeneralRoutines.hh
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/ScheduleManager.hh
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/TranspiredCollector.hh
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/UtilityRoutines.hh
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WindowManager.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/DataSurfaces.unit.cc
  tst/EnergyPlus/unit/DisplacementVentMgr.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/HighTempRadiantSystem.unit.cc
  tst/EnergyPlus/unit/ICSCollector.unit.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
Labels: DoNotPublish, Refactoring

#10061 CppCheck HighTempRadiantSystems
  src/EnergyPlus/BaseboardElectric.cc
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ChilledCeilingPanelSimple.hh
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/GeneralRoutines.hh
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/HighTempRadiantSystem.hh
  src/EnergyPlus/PlantUtilities.cc
  src/EnergyPlus/PlantUtilities.hh
  tst/EnergyPlus/unit/HighTempRadiantSystem.unit.cc
Labels: DoNotPublish

#10077 Disable test on debug
  testfiles/CMakeLists.txt
Labels: DoNotPublish

#10067 Daylighting cleanup pass 1
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/DataDaylighting.hh
  src/EnergyPlus/DataDaylightingDevices.hh
  src/EnergyPlus/DataEnvironment.hh
  src/EnergyPlus/DataMoistureBalance.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingDevices.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/EnergyPlus.hh
  src/EnergyPlus/General.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  third_party/ObjexxFCL/CMakeLists.txt
  third_party/ObjexxFCL/src/ObjexxFCL/Array.all.fwd.hh
  third_party/ObjexxFCL/src/ObjexxFCL/Array.functions.hh
  third_party/ObjexxFCL/src/ObjexxFCL/Array5.all.fwd.hh
  third_party/ObjexxFCL/src/ObjexxFCL/Array5.fwd.hh
  third_party/ObjexxFCL/src/ObjexxFCL/Array5.hh
  third_party/ObjexxFCL/src/ObjexxFCL/Array5D.fwd.hh
  third_party/ObjexxFCL/src/ObjexxFCL/Array5D.hh
  third_party/ObjexxFCL/src/ObjexxFCL/ArrayS.all.fwd.hh
  third_party/ObjexxFCL/src/ObjexxFCL/ArrayS.functions.hh
  third_party/ObjexxFCL/src/ObjexxFCL/MArray.all.fwd.hh
  tst/EnergyPlus/unit/DElightManager.unit.cc
  tst/EnergyPlus/unit/DaylightingDevices.unit.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/WindowEquivalentLayer.unit.cc
Labels: DoNotPublish, Refactoring
