Repository NREL/EnergyPlus, pull requests merged in 2023-05, with the labels that each got.

#10000 Try using the dashboard clone repo
  .decent_ci.yaml
Labels: DoNotPublish

#9999 #9957 #9998 - get_construction_handle should be available to the EnergyPlus API and not limited to PythonPlugin + API fixes
  src/EnergyPlus/api/datatransfer.cc
  src/EnergyPlus/api/datatransfer.h
  src/EnergyPlus/api/datatransfer.py
  tst/EnergyPlus/api/TestDataTransfer.c
  tst/EnergyPlus/api/TestDataTransfer.py
  tst/EnergyPlus/unit/api/datatransfer.unit.cc
Labels: Defect, APIChange

#9907 Fix possible incorrect surface azimuth angle calculations when a surface has non convex vertice
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/Vectors.cc
  src/EnergyPlus/Vectors.hh
  src/EnergyPlus/WeatherManager.cc
  tst/EnergyPlus/unit/DataSurfaces.unit.cc
Labels: Defect

#9941 CppCheck Furnace
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/CurveManager.hh
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/DataEnvironment.cc
  src/EnergyPlus/DataEnvironment.hh
  src/EnergyPlus/DataOutputs.cc
  src/EnergyPlus/DataOutputs.hh
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/DataZoneEquipment.hh
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/DesiccantDehumidifiers.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/Furnaces.hh
Labels: DoNotPublish

#9947 OA Limiting Factor enum and Related Cleanup
  src/EnergyPlus/HVACStandAloneERV.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixedAir.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/SystemReports.cc
  tst/EnergyPlus/unit/HeatRecovery.unit.cc
  tst/EnergyPlus/unit/MixedAir.unit.cc
Labels: Refactoring

#9976 Refactor AvailabilityManager status to equipment managers
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DataHVACGlobals.hh
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/ExhaustAirSystemManager.cc
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/Fans.hh
  src/EnergyPlus/HVACFan.cc
  src/EnergyPlus/HVACFan.hh
  src/EnergyPlus/HVACStandAloneERV.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/PoweredInductionUnits.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/UnitHeater.cc
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WindowAC.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/Autosizing/BaseClassSizing.unit.cc
  tst/EnergyPlus/unit/Autosizing/CoolingCapacitySizing.unit.cc
  tst/EnergyPlus/unit/Autosizing/HeatingCapacitySizing.unit.cc
  tst/EnergyPlus/unit/FanCoilUnits.unit.cc
  tst/EnergyPlus/unit/Fans.unit.cc
  tst/EnergyPlus/unit/HVACFan.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
  tst/EnergyPlus/unit/PoweredInductionUnits.unit.cc
  tst/EnergyPlus/unit/SZVAVModel.unit.cc
  tst/EnergyPlus/unit/UnitHeater.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Refactoring

#9980 CppCheck HVACHXAssisted and HVACManager
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/HVACManager.cc
Labels: DoNotPublish

#9920 Use rotational angle diffs when comparing the Azimuth angles differences between two surfaces
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#10003 CppCheck HVACSingleDuct
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/HVACInterfaceManager.cc
  src/EnergyPlus/HVACSingleDuctInduc.cc
  src/EnergyPlus/HVACSizingSimulationManager.cc
Labels: DoNotPublish

#10009 Fix #9997 - don't try to export when BUILD_STATIC_ENERGYPLUS_API=ON
  src/EnergyPlus/CMakeLists.txt
Labels: DoNotPublish, Developer Issue

#10012 CppCheck HVACStandAloneERV
  src/EnergyPlus/HVACStandAloneERV.cc
Labels: DoNotPublish

#9973 Add a couple new API endpoints
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/api/datatransfer.cc
  src/EnergyPlus/api/datatransfer.h
  src/EnergyPlus/api/datatransfer.py
  tst/EnergyPlus/api/TestDataTransfer.c
  tst/EnergyPlus/api/TestDataTransfer.py
Labels: NewFeature, APIChange

#10008 Fix EMS control of shading surface transmittance
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/EMSManager.hh
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SolarShading.hh
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#10024 Quick fixes
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/coils.tex
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  doc/output-details-and-examples/src/output-files/eplusout-eio.tex
  src/EnergyPlus/DataGlobals.hh
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/SolarShading.cc
Labels: DoNotPublish

#10026 Try specifying Python executable path directly for Decent Windows
  .decent_ci-Windows.yaml
Labels: DoNotPublish

#10025 Address Zone Component Load Summary - DOAS Direct to Zone Output Zone Multiplier Issue
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect, NotIDDChange
