Repository NREL/EnergyPlus, pull requests merged in 2023-11, with the labels that each got.

#10231 SetupOutputVariable wrapper to use enum type parameters (endUseCategory, ReportingFrequency, and eResouceType)
  scripts/dev/check_for_malformed_enums.py
  src/EnergyPlus/BaseboardElectric.cc
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/CoolTower.cc
  src/EnergyPlus/EarthTube.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Refactoring

#10268 Fix Controller:MechanicalVentilation ProportionalControlBasedOnDesignOccupancy
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixedAir.hh
  testfiles/CMakeLists.txt
  testfiles/HeatPumpProportionalControl_DCVDesignOccAllZones.idf
  tst/EnergyPlus/unit/MixedAir.unit.cc
Labels: Defect

#10289 First (and only?) Pollution module refactor
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/DataGlobalConstants.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PollutionModule.cc
  src/EnergyPlus/PollutionModule.hh
  src/EnergyPlus/SimulationManager.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/PollutionModule.unit.cc
Labels: DoNotPublish, Refactoring

#10288 Fix #10287 - ExpandObjects - Incorrect warning about Boiler:HotWater having too many fields
  src/ExpandObjects/epfilter.f90
Labels: Defect, AuxiliaryTool

#10301 Add missing initializations to squelch false table diffs in Annual Heat Emissions Report
  src/EnergyPlus/Construction.hh
  src/EnergyPlus/DXCoils.hh
  src/EnergyPlus/DataOutputs.hh
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/ElectricPowerServiceManager.hh
  src/EnergyPlus/FuelCellElectricGenerator.hh
  src/EnergyPlus/GroundTemperatureModeling/XingGroundTemperatureModel.hh
  src/EnergyPlus/MicroturbineElectricGenerator.hh
  src/EnergyPlus/OutputProcessor.hh
  src/EnergyPlus/OutputReportPredefined.hh
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/WeatherManager.hh
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#10271 Correct VRF supplemental heater operation with cycling fan
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
Labels: Defect

#10261 Fix hint value assignment in SetupUnitConversion() and check if there are any diffs
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#10303 Correction of Inconsistent Flow Rates from Swimming Pools
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/SwimmingPool.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/SwimmingPool.unit.cc
Labels: Defect

#10236 Fixes approach definition for Std 229 fluid cooler reports and adds cooling tower implementation
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/FluidCoolers.cc
Labels: Defect
