Repository NREL/EnergyPlus, pull requests merged in 2023-02, with the labels that each got.

#9827 Remove Optionals from CurveManager
  scripts/dev/check_formatting.bat
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.cc
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/CurveManager.hh
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/VariableSpeedCoils.cc
Labels: DoNotPublish

#9823 Quick cleaning in General.cc
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HVACControllers.hh
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabularAnnual.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/UtilityRoutines.cc
  third_party/ObjexxFCL/src/ObjexxFCL/string.functions.cc
  third_party/ObjexxFCL/src/ObjexxFCL/string.functions.hh
  tst/EnergyPlus/unit/General.unit.cc
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Refactoring

#9830 Addresses Chillers IPLV calculation issue and missing warning when the curves limit are outside the AHRI test condition
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/StandardRatings.cc
  src/EnergyPlus/StandardRatings.hh
  tst/EnergyPlus/unit/StandardRatings.unit.cc
Labels: Defect

#9836 Fix #9835 - The "value" datatype is incorrect in TabularData
  src/EnergyPlus/SQLiteProcedures.cc
Labels: Defect

#9808 Fix #9780 - Blank epJSON inputs needed for ZoneHVAC:EquipmentList
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/InputProcessing/InputProcessor.hh
  tst/EnergyPlus/unit/DataZoneEquipment.unit.cc
Labels: Defect

#9804 #9803 - GetVRFInputData throws a vector error when using multiple VRF types
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  src/EnergyPlus/StandardRatings.hh
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#9623 Enhance perf logging
  CMakeLists.txt
  cmake/ProjectMacros.cmake
  cmake/RunSimulation.cmake
  src/EnergyPlus/CMakeLists.txt
Labels: Performance

#9846 Remove remaining meaningful global variables
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/ExhaustAirSystemManager.cc
  src/EnergyPlus/ExhaustAirSystemManager.hh
  src/EnergyPlus/FluidProperties.cc
  src/EnergyPlus/FluidProperties.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/WindowManagerExteriorData.cc
  src/EnergyPlus/WindowManagerExteriorData.hh
  src/EnergyPlus/WindowManagerExteriorOptical.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  tst/EnergyPlus/unit/WinCalcEngine.unit.cc
Labels: DoNotPublish

#9854 Refactor in RefrigeratedCase and new unit test process_idf for string_view
  src/EnergyPlus/RefrigeratedCase.cc
  src/EnergyPlus/RefrigeratedCase.hh
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.hh
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Refactoring
