Repository NREL/EnergyPlus, pull requests merged in 2023-07, with the labels that each got.

#10098 Fix #9787 - Large negative values in tables can come out as "Too Big" when they should switch to scientific notation
  src/EnergyPlus/OutputReportPredefined.cc
Labels: Defect

#9905 Fix several issues in checkSubSurfAzTiltNorm() and GetSurfaceData() (lcsz assignment, enum loop etc)
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#10075 CppCheck WaterCoils
  src/EnergyPlus/WaterCoils.cc
Labels: DoNotPublish

#10097 Fix #10064 - EPW file not working if it doesn't have an ending newline
  src/EnergyPlus/IOFiles.cc
  src/EnergyPlus/IOFiles.hh
  src/EnergyPlus/WeatherManager.cc
  tst/EnergyPlus/unit/Resources/chicago_no_eol_at_end_of_file.epw
  tst/EnergyPlus/unit/WeatherManager.unit.cc
Labels: Defect

#10078 Correction of Bug in HW Baseboard Get Input Routine
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/SteamBaseboardRadiator.cc
  testfiles/5ZoneWaterCooled_Baseboard.idf
  tst/EnergyPlus/unit/HWBaseboardRadiator.unit.cc
Labels: Defect

#10113 edited curve names to match tables J5/J7 (> changed to >=)
  datasets/CodeCompliantEquipment.idf
Labels: Defect

#10099 fix curve arg order in documentation in AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl
  doc/input-output-reference/src/overview/group-variable-refrigerant-flow-equipment.tex
Labels: Defect, Documentation

#10114 Fix #10103 - CheckConvexity removes colinear vertices but stops when surface is determined non-convex, causing vertex size mismatch fatal error
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#10093 Daylighting -- Part 2
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/DataDaylighting.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/OutputReports.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
Labels: DoNotPublish, Refactoring

#10120 #9825 - Handle non ASCII command line parameters such as path
  cmake/CompilerFlags.cmake
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/CommandLineInterface.hh
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PluginManager.hh
  src/EnergyPlus/api/EnergyPlusPgm.cc
  src/EnergyPlus/api/EnergyPlusPgm.hh
  src/EnergyPlus/api/runtime.cc
  src/EnergyPlus/main.cc
  third_party/CLI/CLI11.hpp
  third_party/CLI/LICENSE
  third_party/CLI/MIT-LICENSE
  third_party/CLI/README.md
  third_party/CLI/ezOptionParser.hpp
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/CommandLineInterface.unit.cc
Labels: Defect

#10087 Fix reversed low vs high curves in ResidentialACsAndHPsPerfCurves.idf
  datasets/ResidentialACsAndHPsPerfCurves.idf
Labels: Defect

#10127 Revert "#9825 - Handle non ASCII command line parameters such as path"
  cmake/CompilerFlags.cmake
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/CommandLineInterface.hh
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PluginManager.hh
  src/EnergyPlus/api/EnergyPlusPgm.cc
  src/EnergyPlus/api/EnergyPlusPgm.hh
  src/EnergyPlus/api/runtime.cc
  src/EnergyPlus/main.cc
  third_party/CLI/CLI11.hpp
  third_party/CLI/LICENSE
  third_party/CLI/MIT-LICENSE
  third_party/CLI/README.md
  third_party/CLI/ezOptionParser.hpp
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/CommandLineInterface.unit.cc
Labels: DoNotPublish

#10006 Address linearize exterior surface longwave radiation exchange with surrounding surfaces
  doc/engineering-reference/src/surface-heat-balance-manager-processes/outside-surface-heat-balance.tex
  doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/ConvectionCoefficients.hh
  src/EnergyPlus/DataHeatBalSurface.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/PhotovoltaicThermalCollectors.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManager.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: DoNotPublish, NotIDDChange

#10030 Address DOAS Zone Load Calculation Uses Incorrect Mass Flow Rate
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/DOASEffectOnZoneSizing.unit.cc
  tst/EnergyPlus/unit/HeatRecovery.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Defect, NotIDDChange
