Repository NREL/EnergyPlus, pull requests merged in 2023-09, with the labels that each got.

#10139 Add new `ENABLE_UNITY` CMake option to toggle unity build on/off
  CMakeLists.txt
  cmake/CompilerFlags.cmake
  src/EnergyPlus/AirflowNetwork/CMakeLists.txt
  src/EnergyPlus/CMakeLists.txt
  third_party/kiva/cmake/compiler-flags.cmake
Labels: DoNotPublish, Developer Issue

#10042 Issue severe errors for component node connection in AirLoopHVAC:OutdoorAirSystem:EquipmentList
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/AirLoopHVACDOAS.hh
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
Labels: Defect

#10083 Correction of Incorrect Reporting of Solar at Night with Interzone Windows
  doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex
  src/EnergyPlus/DataHeatBalSurface.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
Labels: Defect

#10131 Allow zone/space output aggregation of OtherEquipment objects with different fuels
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/ExteriorEnergyUse.hh
  src/EnergyPlus/InternalHeatGains.cc
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
Labels: Defect

#10200 Fix #10197 - Spurious unit test failure in CommandLineInterfaceFixture
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/CommandLineInterface.unit.cc
  tst/EnergyPlus/unit/WeatherManager.unit.cc
Labels: Defect, DoNotPublish, Developer Issue

#10216 Fix #10037 - Allow DDY file to epJSON with ConverterInputFormat
  src/ConvertInputFormat/CMakeLists.txt
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/FileSystem.cc
  src/EnergyPlus/FileSystem.hh
Labels: Defect, AuxiliaryTool

#10212 Fix #10190 - Zero DistrictHeatingStream reported in ABUPS
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#10128 AirloopHVAC:UnitarySystem crashes when no heating coil exists and CoolReheat or Multimode dehumidification is used
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect, NotIDDChange

#9953 Fix the default parameter type for the exhaust control function
  src/EnergyPlus/ExhaustAirSystemManager.cc
  src/EnergyPlus/ExhaustAirSystemManager.hh
  tst/EnergyPlus/unit/ExhaustSystem.unit.cc
Labels: Defect

#10174 Space Sizing and HVAC part2 - Code cleanups
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/CoolTower.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataZoneEnergyDemands.cc
  src/EnergyPlus/DataZoneEnergyDemands.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/MoistureBalanceEMPDManager.cc
  src/EnergyPlus/MundtSimMgr.cc
  src/EnergyPlus/PurchasedAirManager.cc
  src/EnergyPlus/RoomAirModelAirflowNetwork.cc
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/RoomAirModelUserTempPattern.cc
  src/EnergyPlus/SingleDuct.hh
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/ThermalChimney.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/UFADManager.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WaterUse.cc
  src/EnergyPlus/WindowComplexManager.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/AirflowNetworkConditions.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/CoolTower.unit.cc
  tst/EnergyPlus/unit/HVACManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/HybridModel.unit.cc
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
  tst/EnergyPlus/unit/MoistureBalanceEMPD.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
  tst/EnergyPlus/unit/PurchasedAirManager.unit.cc
  tst/EnergyPlus/unit/RoomAirflowNetwork.unit.cc
  tst/EnergyPlus/unit/SecondaryDXCoils.unit.cc
  tst/EnergyPlus/unit/ThermalChimney.unit.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
  tst/EnergyPlus/unit/ZoneContaminantPredictorCorrector.unit.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: DoNotPublish

#10076 Variable Relocation for Various Models using Radiant Style Updating
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ChilledCeilingPanelSimple.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HWBaseboardRadiator.hh
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/HighTempRadiantSystem.hh
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/LowTempRadiantSystem.hh
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SteamBaseboardRadiator.hh
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/SwimmingPool.hh
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/VentilatedSlab.hh
  tst/EnergyPlus/unit/HWBaseboardRadiator.unit.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
  tst/EnergyPlus/unit/SwimmingPool.unit.cc
Labels: Defect, Refactoring

#10198 Fix typos in new warnings
  doc/input-output-reference/src/overview/group-condenser-equipment.tex
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/UnitarySystem.cc
Labels: DoNotPublish

#10144 OA Systems with HXAssisted coils fail when both water and DX coils are used leading to invalid warnings and fatal error
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/HeatRecovery.hh
  src/EnergyPlus/MixedAir.cc
Labels: Defect

#10217 Correction of Mass Flow Conservation Crash with Uncontrolled Zone using Mixing
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/HeatBalanceAirManager.unit.cc
Labels: Defect

#10186 Fixes multispeed DX coil defrost calculation when using ReverseCycle w/ Timed control
  src/EnergyPlus/DXCoils.cc
Labels: Defect

#10214 Fix the Heat Pump Water Heater Information table
  src/EnergyPlus/WaterThermalTanks.cc
  src/Transition/OutputRulesFiles/OutputChanges23-1-0-to-23-2-0.md
Labels: Defect, OutputChange

#10211 Fix #9621 - AllSummaryAndMonthly option in Output:Table:SummaryReports prompts many warnings and incomplete reports
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#10158 Fix default design condenser inlet and design evaporator outlet temperatures for Chiller:ConstantCOP
  src/EnergyPlus/PlantChillers.cc
  tst/EnergyPlus/unit/ChillerConstantCOP.unit.cc
Labels: Defect

#10014 Additional rotational azimuth angles differences changes across the code
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/TranspiredCollector.cc
Labels: Defect

#10207 Fix water heater outputs in documentation
  doc/input-output-reference/src/overview/group-water-heaters.tex
  doc/input-output-reference/src/standard-output-reports/output-table-summaryreports.tex
Labels: Defect, Documentation

#10115 Fix #9873 - GetVertices is dropping vertices inconsistently, causing fatal error
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#10209 Fix WaterHeaterReportMonthly source energy output field
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/Transition/OutputRulesFiles/OutputChanges23-1-0-to-23-2-0.md
Labels: Defect, OutputChange

#10124 Corrects ADU upstream air leakage model to use the maximum available flow rate for CV air terminals
  doc/input-output-reference/src/overview/group-zone-equipment.tex
  src/EnergyPlus/DataDefineEquip.hh
  src/EnergyPlus/ZoneAirLoopEquipmentManager.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Defect

#10154 Fixing VRF fluid control model heating issue in compressor speed decrease with temperature, TU heating rate much larger than system
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  testfiles/CMakeLists.txt
  testfiles/US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf
  weather/USA_NY_New.York-John.F.Kennedy.Intl.AP.744860_TMY3.epw
Labels: Defect

#10150 Energy Meters Table and Increase Decimals for Air Flow (bug fixes to issues #9642 and #9589)
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/SimulationManager.cc
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Defect

#10185 Fix issue 9241 leap day monthly reporting
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/SQLiteProcedures.cc
  src/EnergyPlus/SQLiteProcedures.hh
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
  tst/EnergyPlus/unit/SQLite.unit.cc
Labels: Defect

#10167 escape objectName for xml
  src/EnergyPlus/OutputReportTabular.cc
Labels: Defect

#10225 Clarify CMake Messages for CMAKE_OSX_DEPLOYMENT_TARGET
  CMakeLists.txt
Labels: DoNotPublish, Developer Issue

#10221 Fix #10210 - add Calendar Year to ERL, C and Python API
  doc/ems-application-guide/src/energyplus-runtime-language/variables.tex
  doc/readthedocs/requirements.txt
  doc/readthedocs/sphinx/conf.py
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/RuntimeLanguageProcessor.hh
  src/EnergyPlus/api/datatransfer.cc
  src/EnergyPlus/api/datatransfer.h
  src/EnergyPlus/api/datatransfer.py
  src/EnergyPlus/api/plugin_tester.py
  tst/EnergyPlus/api/TestDataTransfer.c
  tst/EnergyPlus/api/TestDataTransfer.py
  tst/EnergyPlus/unit/EMSManager.unit.cc
Labels: Defect, APIChange

#10230 Fix #9878 - ChillerHeater:Absorption:DoubleEffect should calculate Specific heat of Water and Air at the right temperatures
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  tst/EnergyPlus/unit/ChillerExhaustAbsorption.unit.cc
Labels: Defect

#10227 Correction to Reporting of a Conduction Finite Difference Flux Imbalance
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  tst/EnergyPlus/unit/HeatBalFiniteDiffManager.unit.cc
Labels: Defect

#10193 Fixes issue 10055 - If zone sizing is zero and system sizing is zero there is a fatal error leaving no information to help diagnose why
  src/EnergyPlus/SimAirServingZones.cc
  tst/EnergyPlus/unit/SimAirServingZones.unit.cc
Labels: Defect

#10010 Fix floor solar heat gain issue from incident solar multiplier
  src/EnergyPlus/SolarShading.cc
Labels: Defect

#10222 Steam features part 1 (#9260) follow-up
  doc/engineering-reference/src/building-system-simulation-system-manager/plant-load-profile.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/district-heating.tex
  doc/input-output-reference/src/hvac-template-objects/group-hvac-templates.tex
  doc/input-output-reference/src/input-for-output.tex
  doc/input-output-reference/src/overview/group-energy-management-system-ems.tex
  doc/input-output-reference/src/overview/group-exterior-energy-use-equipment.tex
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  doc/input-output-reference/src/overview/group-non-zone-equipment.tex
  doc/input-output-reference/src/overview/group-plant-equipment.tex
  doc/input-output-reference/src/overview/group-simulation-parameters.tex
  doc/input-output-reference/src/overview/group-water-heaters.tex
  doc/input-output-reference/src/overview/group-water-systems.tex
  doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
  doc/input-output-reference/src/standard-output-reports/output-table-summaryreports.tex
  src/EnergyPlus/DataGlobalConstants.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/ExteriorEnergyUse.cc
  src/EnergyPlus/ExteriorEnergyUse.hh
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/OutsideEnergySources.cc
  src/EnergyPlus/OutsideEnergySources.hh
  src/EnergyPlus/PluginManager.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/EconomicLifeCycleCost.unit.cc
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
  tst/EnergyPlus/unit/OutsideEnergySources.unit.cc
  tst/EnergyPlus/unit/PlantLoadProfile.unit.cc
Labels: Defect, Documentation, Refactoring

#10085 Update VRF Heat Pump Cooling/Heating COP documentation
  doc/input-output-reference/src/overview/group-variable-refrigerant-flow-equipment.tex
Labels: Defect, Documentation

#10199 HeatPump:PlantLoop:EIR:* objects using the same inlet/outlet source node is incorrect 9740
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Defect

#10205 Space Sizing and HVAC Part 3
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/DataZoneEquipment.hh
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/EcoRoofManager.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/HeatBalanceAirManager.hh
  src/EnergyPlus/HeatBalanceHAMTManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/InternalHeatGains.hh
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneEquipmentManager.hh
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/HVACManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
Labels: NewFeature

#10240 Allow heat recovery for air-cooled EIR chillers
  doc/input-output-reference/src/overview/group-plant-equipment.tex
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
Labels: Defect

#10250 Fix MikTex on windows_release (and post installers to release)
  .github/workflows/windows_release.yml
Labels: DoNotPublish, Developer Issue

#10249 Fix crash with new Multi-speed Fans for WSHP Zone Equipment
  src/EnergyPlus/HVACFan.hh
  src/EnergyPlus/UnitarySystem.cc
Labels: Defect

#10242 Correct autosized heat recovery volume flow rate for air-cooled equip…
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
Labels: Defect

#10254 AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass with CoilSystem:Cooling:DX:HeatExchangerAssisted shows false fatal error
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
Labels: Defect

#10251 AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass with Fan:SystemModel crashes
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
Labels: Defect

#10255 Update windows doc action miktex version
  .github/workflows/documentation-windows.yml
Labels: DoNotPublish

#10258 Corrects non-ASCII characters for Coil Sizing Details and other tables.
  src/EnergyPlus/ReportCoilSelection.cc
Labels: Defect, DoNotPublish
