Repository NREL/EnergyPlus, pull requests merged in 2023-01, with the labels that each got.

#9776 Fix the speed control method field of Fan:SystemModel autogenerated by HVACTemplate:Zone:FanCoil
  src/ExpandObjects/epfilter.f90
Labels: Defect

#9789 Fix #9772 - AirLoop Component Load Summary report for Cooling Peak Conditions always shows Mixed Air Temperature = 0
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabularAnnual.cc
  testfiles/5ZoneAirCooled.idf
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect, SeverityLow, NotIDDChange

#9774 To be or not to be correct when using auto
  scripts/dev/generate_embeddable_epJSON_schema/generate_embeddable_epJSON_schema.cpp
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/Autosizing/Base.cc
  src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc
  src/EnergyPlus/Autosizing/SystemAirFlowSizing.cc
  src/EnergyPlus/BaseboardElectric.cc
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerElectricASHRAE205.cc
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/Construction.cc
  src/EnergyPlus/EconomicTariff.cc
  src/EnergyPlus/GlobalNames.cc
  src/EnergyPlus/GlobalNames.hh
  src/EnergyPlus/api/datatransfer.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/HeatRecovery.unit.cc
Labels: DoNotPublish

#9795 Cleanup std::move warnings on Clang
  src/EnergyPlus/ChillerElectricASHRAE205.cc
Labels: DoNotPublish

#9796 Fix #9709 - Output:Diagnostics:DisplayWeatherMissingDataWarnings returns false warnings
  src/EnergyPlus/StringUtilities.hh
  src/EnergyPlus/WeatherManager.cc
  tst/EnergyPlus/unit/WeatherManager.unit.cc
Labels: Defect, NotIDDChange

#9794 Fix #9710 - Autocalculated Cw factor for `ZoneVentilation:WindandStackOpenArea` appears wrong
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Defect, NotIDDChange

#9791 Fix #9790 - Crash with Pipe:Indoor when temperature is below 1.85C
  src/EnergyPlus/PipeHeatTransfer.cc
  src/EnergyPlus/PipeHeatTransfer.hh
  tst/EnergyPlus/unit/Pipes.unit.cc
Labels: Defect, NotIDDChange

#9799 Fix #9798 - Conversion from std::string to heap-allocated char pointer is missing a +1
  src/EnergyPlus/api/datatransfer.cc
Labels: Defect, SeverityLow

#9786 Indexing issue when using multiple CoilSystem objects in OA System
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/BranchNodeConnections.cc
  src/EnergyPlus/BranchNodeConnections.hh
  src/EnergyPlus/DataAirLoop.hh
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/GeneralRoutines.hh
  src/EnergyPlus/GlobalNames.cc
  src/EnergyPlus/GlobalNames.hh
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixedAir.hh
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/WindowAC.cc
  tst/EnergyPlus/unit/MixedAir.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#9782 Refactor loops for zone sizing array initialization
  src/EnergyPlus/ZoneEquipmentManager.cc
Labels: Performance, Refactoring

#9806 Fix water to air heat pump are sized to an infinite capacity
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  tst/EnergyPlus/unit/WaterToAirHeatPumpSimple.unit.cc
Labels: Defect, NotIDDChange

#9768 Addresses VRF Terminal Unit Supplemental Heating Coil Control Problem
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#9816 Optional Refactoring Examples
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterThermalTanks.hh
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowEquivalentLayer.hh
Labels: DoNotPublish

#9779 Curve Manager Round 2
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.cc
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/CurveManager.hh
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/IceThermalStorage.cc
  src/EnergyPlus/PackagedThermalStorageCoil.cc
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/StandardRatings.cc
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  src/EnergyPlus/WindowManager.cc
  tst/EnergyPlus/unit/AdvancedAFN.unit.cc
  tst/EnergyPlus/unit/AirflowNetworkConditions.unit.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDX.unit.cc
  tst/EnergyPlus/unit/CurveManager.unit.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/EvaporativeCoolers.unit.cc
  tst/EnergyPlus/unit/FaultsManager.unit.cc
  tst/EnergyPlus/unit/FuelCellElectricGenerator.unit.cc
  tst/EnergyPlus/unit/HVACDXHeatPumpSystem.unit.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/IceThermalStorage.unit.cc
  tst/EnergyPlus/unit/StandardRatings.unit.cc
  tst/EnergyPlus/unit/SurfaceOctree.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/WaterToAirHeatPumpSimple.unit.cc
Labels: Refactoring
