Repository NREL/EnergyPlus, pull requests merged in 2023-04, with the labels that each got.

#9921 CppCheck ElectricBaseboardRadiator
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/ElectricBaseboardRadiator.hh
Labels: DoNotPublish

#9922 CppCheck convert to std::find_if [decent_ci_skip]
  src/EnergyPlus/BoilerSteam.cc
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/Boilers.hh
  src/EnergyPlus/CTElectricGenerator.cc
  src/EnergyPlus/CTElectricGenerator.hh
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerAbsorption.hh
  src/EnergyPlus/ChillerElectricASHRAE205.cc
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerElectricEIR.hh
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerExhaustAbsorption.hh
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.hh
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/ChillerIndirectAbsorption.hh
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/ChillerReformulatedEIR.hh
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.cc
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/CondenserLoopTowers.hh
  src/EnergyPlus/Construction.cc
  tst/EnergyPlus/unit/BoilerHotWater.unit.cc
Labels: DoNotPublish

#9927 CppCheck CurveManager Delight Daylight
  src/EnergyPlus/Construction.cc
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/DataEnvironment.cc
  src/EnergyPlus/DataEnvironment.hh
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/DesiccantDehumidifiers.hh
  src/EnergyPlus/DisplacementVentMgr.cc
Labels: DoNotPublish

#9923 Fixes Kiva:Foundation using wrong initial temperature
  src/EnergyPlus/HeatBalanceKivaManager.cc
  tst/EnergyPlus/unit/HeatBalanceKivaManager.unit.cc
Labels: Defect

#9932 CppCheck FanCoilUnits
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/FanCoilUnits.hh
  tst/EnergyPlus/unit/FanCoilUnits.unit.cc
  tst/EnergyPlus/unit/SZVAVModel.unit.cc
  tst/EnergyPlus/unit/WaterCoils.unit.cc
Labels: DoNotPublish

#9928 CppCheck ElecPower EvapCooler ExhSys ExtInterface
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/ElectricPowerServiceManager.hh
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/EvaporativeFluidCoolers.cc
  src/EnergyPlus/ExhaustAirSystemManager.cc
  src/EnergyPlus/ExhaustAirSystemManager.hh
  src/EnergyPlus/ExteriorEnergyUse.cc
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/ExternalInterface.hh
Labels: DoNotPublish

#9940 Minimal fix for VS Furnace Flow Rate when Fan is Off
  src/EnergyPlus/Furnaces.cc
  tst/EnergyPlus/unit/Furnaces.unit.cc
Labels: Defect

#9937 CppCheck Fans
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/Fans.hh
Labels: DoNotPublish

#9942 CppCheck General
  src/EnergyPlus/General.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/GeneratorDynamicsManager.cc
  src/EnergyPlus/GeneratorDynamicsManager.hh
  src/EnergyPlus/GeneratorFuelSupply.cc
  src/EnergyPlus/MicroCHPElectricGenerator.cc
Labels: DoNotPublish

#9964 CppCheck HVACCooledBeam
  src/EnergyPlus/HVACCooledBeam.cc
  src/EnergyPlus/HVACDXHeatPumpSystem.cc
  src/EnergyPlus/HVACDuct.cc
  src/EnergyPlus/HVACDuct.hh
  src/EnergyPlus/HVACFourPipeBeam.cc
Labels: DoNotPublish

#9931 Post-23.1 Cleanups
  .github/workflows/linux_release.yml
  .github/workflows/windows_release.yml
  CMakeLists.txt
  scripts/dev/check_for_enum_scope_usage.py
  scripts/dev/check_for_malformed_enums.py
  scripts/dev/generate_embeddable_epJSON_schema/CMakeLists.txt
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/OutsideEnergySources.cc
  src/EnergyPlus/PollutionModule.cc
  src/EnergyPlus/Pumps.cc
  src/EnergyPlus/RefrigeratedCase.cc
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/ScheduleManager.hh
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WaterManager.cc
Labels: DoNotPublish

#9954 Fix build errors on clang16
  third_party/kiva/cmake/compiler-flags.cmake
  third_party/kiva/vendor/boost-1.77.0/boost/container_hash/hash.hpp
Labels: DoNotPublish, Developer Issue

#9983 Update Decent CI
  .decent_ci-Linux.yaml
Labels: DoNotPublish

#9985 Protect lookup in zone index to avoid crash in debug
  src/EnergyPlus/OutputReportTabular.cc
Labels: Defect

#9974 Address UnitarySystem used as zone equipment does not allow NightCycle availability manager control
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
Labels: Defect
