Repository NREL/EnergyPlus, pull requests merged in 2023-03, with the labels that each got.

#9858 Fix bad uses of (plain) auto part 1: files A-F
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/BaseboardElectric.cc
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/CTElectricGenerator.cc
  src/EnergyPlus/ChillerElectricASHRAE205.cc
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/CrossVentMgr.cc
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DataGlobalConstants.cc
  src/EnergyPlus/DataSurfaceColors.cc
  src/EnergyPlus/DataSurfaceLists.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/EarthTube.cc
  src/EnergyPlus/EconomicLifeCycleCost.cc
  src/EnergyPlus/EconomicTariff.cc
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/EvaporativeFluidCoolers.cc
  src/EnergyPlus/ExhaustAirSystemManager.cc
  src/EnergyPlus/ExteriorEnergyUse.cc
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/FileSystem.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/General.cc
  src/EnergyPlus/GeneralRoutines.cc
  src/EnergyPlus/GeneralRoutines.hh
  src/EnergyPlus/GlobalNames.cc
  src/EnergyPlus/GlobalNames.hh
  src/EnergyPlus/GroundHeatExchangers.cc
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/InputProcessing/InputProcessor.hh
Labels: Refactoring

#9826 Electric Heating Coil Inlet and Outlet Air Conditions and Sensible Capacity Tabular Reporting Issue for Four Pipe FCU
  src/EnergyPlus/ReportCoilSelection.cc
  tst/EnergyPlus/unit/ReportCoilSelection.unit.cc
Labels: Defect

#9824 Bump github actions (to avoid deprecation warnings)
  .github/workflows/add_opened_pr_to_project.yml
  .github/workflows/clang-format-check.yml
  .github/workflows/cppcheck.yml
  .github/workflows/custom_check.yml
  .github/workflows/documentation-windows.yml
  .github/workflows/documentation.yml
  .github/workflows/linux_build.yml
  .github/workflows/linux_release.yml
  .github/workflows/mac_release.yml
  .github/workflows/pr_labels.yml
  .github/workflows/windows_release.yml
  .gitignore
  scripts/dev/colorize_cppcheck_results.py
  scripts/dev/license-check.py
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.cc
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/ExternalInterface.cc
  src/EnergyPlus/FileSystem.hh
  src/EnergyPlus/FluidProperties.cc
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc
  src/EnergyPlus/HVACInterfaceManager.cc
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/Psychrometrics.hh
Labels: DoNotPublish, Developer Issue

#9862 Updated with regressions main branch
  .decent_ci.yaml
  cmake/RunRegression.cmake
Labels: DoNotPublish

#9850 Fix UnitarySystem Setpoint Control
  src/EnergyPlus/UnitarySystem.cc
  testfiles/5Zone_Unitary_HXAssistedCoil.idf
  testfiles/5Zone_Unitary_VSDesuperheatWaterHeater.idf
  testfiles/5Zone_Unitary_VSDesuperheater.idf
  testfiles/EMSSetpointBasedMultiSpeedDXCoilOverrideControl.idf
  testfiles/WaterSideEconomizer_PreCoolCoil.idf
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#9866 #9817 - Enable hardened runtime on Windows installers
  .github/workflows/windows_release.yml
  CMakeLists.txt
  cmake/CompilerFlags.cmake
  cmake/Install.cmake
Labels: Defect, Developer Issue

#9867 Timestamp documentation corrections
  doc/input-output-reference/src/input-for-output.tex
Labels: Defect, Documentation

#9712 Export energyplusapi as a cmake target
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/api/runtime.cc
  src/EnergyPlus/api/runtime.h
Labels: DoNotPublish, Developer Issue

#9859 Cppcheck errors isolated
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PackagedThermalStorageCoil.cc
Labels: Defect

#9855 Fix issues with zero floor area or zero surfaces due to air boundaries
  src/EnergyPlus/Construction.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/RoomAirModelUserTempPattern.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  src/EnergyPlus/UFADManager.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#9864 CppCheck style suggestions for UnitarySystem
  src/EnergyPlus/Autosizing/Base.cc
  src/EnergyPlus/Autosizing/CoolingAirFlowSizing.cc
  src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc
  src/EnergyPlus/Autosizing/HeatingAirFlowSizing.cc
  src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc
  src/EnergyPlus/Autosizing/SystemAirFlowSizing.cc
  src/EnergyPlus/FanCoilUnits.cc
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/HVACStandAloneERV.cc
  src/EnergyPlus/HVACStandAloneERV.hh
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/HeatRecovery.hh
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/VariableSpeedCoils.hh
  tst/EnergyPlus/unit/HVACDXSystem.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: DoNotPublish

#9837 Addresses unitary system no load supply air flow rate incorrect sizing report
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#9843 Fix #9831 - Issue running a model with PIU + ReturnPlenu
  src/EnergyPlus/PoweredInductionUnits.cc
  src/EnergyPlus/ZonePlenum.cc
  tst/EnergyPlus/unit/PoweredInductionUnits.unit.cc
Labels: Defect, NotIDDChange

#9841 Addresses MultiSpeed AirToAirHP Total Electricity Rate is Double Counting the Supplemental Heater Electricity Rate
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/HVACMultiSpeedHeatPump.unit.cc
Labels: Defect

#9865 Clean up supp heat coil function
  src/EnergyPlus/UnitarySystem.cc
Labels: DoNotPublish

#9869 Avoid overwriting native csv output
  doc/auxiliary-programs/src/convertesomtr.tex
  doc/auxiliary-programs/src/technical-details-of-running-energyplus/energyplus-file-extensions.tex
  doc/auxiliary-programs/src/technical-details-of-running-energyplus/energyplus-files.tex
  doc/auxiliary-programs/src/technical-details-of-running-energyplus/ep-launch-program.tex
  doc/auxiliary-programs/src/weather-converter-program/source-weather-data-formats.tex
  doc/essentials/src/essentials.tex
  doc/getting-started/src/other-useful-programs-information/csvproc.tex
  doc/getting-started/src/other-useful-programs-information/hvac-diagram.tex
  doc/getting-started/src/other-useful-programs-information/library-files.tex
  doc/getting-started/src/other-useful-programs-information/results-processing.tex
  doc/getting-started/src/running-energyplus/energyplus-file-extensions.tex
  doc/getting-started/src/running-energyplus/ep-launch-program.tex
  doc/input-output-reference/src/input-for-output.tex
  doc/input-output-reference/src/output/using-readvarseso.tex
  doc/interface-developer/src/input-details.tex
  doc/interface-developer/src/input-details/idd-conventions.tex
  doc/module-developer/src/appendix-b-submissions-and-check-ins.tex
  doc/module-developer/src/energyplus-services/input-services.tex
  doc/module-developer/src/module-structure/code-readability-vs-speed-of-execution.tex
  doc/module-developer/src/modules-in-energyplus/what-is-a-module-anyway.tex
  doc/module-developer/src/output.tex
  doc/output-details-and-examples/src/output-files/eplusmtr-lt-ext-gt.tex
  doc/output-details-and-examples/src/output-files/eplusout-eio.tex
  doc/output-details-and-examples/src/output-files/eplusout-lt-ext-gt.tex
  doc/output-details-and-examples/src/output-files/readvars-rvaudit.tex
  doc/running-energyplus-from-command-line.md
  doc/tips-and-tricks-using-energyplus/src/datasets/datasets-aka-libraries.tex
  doc/tips-and-tricks-using-energyplus/src/design-day-weather-data/epw-weather-files.tex
  doc/tips-and-tricks-using-energyplus/src/hvac-sizing-equipment-simulation-and-controls/fan-types.tex
  scripts/Epl-run.bat
  scripts/RunEPlus.bat
  src/EnergyPlus/api/EnergyPlusPgm.cc
  testfiles/5ZoneVAV-Pri-SecLoop_csv.idf
Labels: Defect

#9844 Addresses Defrost Cycle Electricity Rate is not Included in Unitary System Electricity Rate
  doc/input-output-reference/src/overview/group-unitary-equipment.tex
  doc/input-output-reference/src/overview/group-zone-forced-air-units.tex
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DataHVACGlobals.hh
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
Labels: Defect

#9792 Fix issue with VRF Heat Pump COP and Electricity Rate
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/variable-refrigerant-flow-heat-pumps.tex
  doc/input-output-reference/src/overview/group-variable-refrigerant-flow-equipment.tex
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#9857 Remove the implicitly added condenser outlet node with random names in the Fuel-Fired plant loop heat pump model
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
Labels: DoNotPublish

#9761 EMS coil speed actuator not working for multispeed coils in UnitarySystem
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#9863 Address incorrect average temperature used for condensate volume calculation in DX and Water cooling coils
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/WaterCoils.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
Labels: Defect

#9872 Remove Scalar Auto Refs -- pass 2
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DataSurfaceLists.cc
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/DualDuct.cc
  src/EnergyPlus/ElectricBaseboardRadiator.cc
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/FluidCoolers.cc
  src/EnergyPlus/HVACCooledBeam.cc
  src/EnergyPlus/HVACDXHeatPumpSystem.cc
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/HVACInterfaceManager.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACSingleDuctInduc.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HWBaseboardRadiator.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalanceHAMTManager.cc
  src/EnergyPlus/HeatPumpWaterToWaterCOOLING.cc
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.cc
  src/EnergyPlus/HeatPumpWaterToWaterSimple.cc
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/HeatRecovery.hh
  src/EnergyPlus/Humidifiers.cc
  src/EnergyPlus/HybridUnitaryAirConditioners.cc
  src/EnergyPlus/MatrixDataManager.cc
  src/EnergyPlus/MoistureBalanceEMPDManager.cc
  src/EnergyPlus/MundtSimMgr.cc
  src/EnergyPlus/NonZoneEquipmentManager.cc
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/PackagedThermalStorageCoil.cc
  src/EnergyPlus/PollutionModule.cc
  src/EnergyPlus/PoweredInductionUnits.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/StandardRatings.cc
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
Labels: DoNotPublish, Refactoring

#9877 CppCheck Branch_files
  src/EnergyPlus/BranchInputManager.cc
  src/EnergyPlus/BranchInputManager.hh
  src/EnergyPlus/BranchNodeConnections.cc
  src/EnergyPlus/BranchNodeConnections.hh
  src/EnergyPlus/ChilledCeilingPanelSimple.cc
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/ChillerGasAbsorption.cc
  src/EnergyPlus/SystemReports.cc
Labels: DoNotPublish

#9879 CppCheck CondenserLoopTowers, CoolTower and ConvectionCoefficients
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/Construction.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/CoolTower.cc
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/CrossVentMgr.cc
Labels: DoNotPublish

#9889 Correct error in collection of AirflowNetwork element data
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
Labels: Defect

#9885 CppCheck Daylighting files
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
Labels: DoNotPublish

#9886 Fix Bad Auto: Part 3
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc
  src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.cc
  src/EnergyPlus/InputProcessing/CsvParser.cc
  src/EnergyPlus/InputProcessing/IdfParser.cc
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/InputProcessing/InputValidation.cc
  src/EnergyPlus/Plant/LoopSide.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SteamCoils.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/ThermalISO15099Calc.cc
  src/EnergyPlus/TranspiredCollector.cc
  src/EnergyPlus/UnitHeater.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UserDefinedComponents.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/WaterCoils.cc
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WindTurbine.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManagerExteriorData.cc
  src/EnergyPlus/WindowManagerExteriorOptical.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  src/EnergyPlus/WindowModel.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/api/datatransfer.cc
  src/EnergyPlus/api/func.cc
Labels: DoNotPublish, Refactoring

#9871 CppCheck warnings
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/BaseboardElectric.cc
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/BoilerSteam.cc
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/CTElectricGenerator.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/DElightManagerF.hh
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/InternalHeatGains.hh
  src/EnergyPlus/NodeInputManager.cc
  src/EnergyPlus/NodeInputManager.hh
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/PlantCondLoopOperation.cc
  src/EnergyPlus/ResultsFramework.hh
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SurfaceGroundHeatExchanger.cc
  src/EnergyPlus/UnitarySystem.cc
Labels: DoNotPublish

#9892 Fix Bad Auto 4 (with a bonus)
  src/EnergyPlus/BITF.hh
  src/EnergyPlus/BranchNodeConnections.cc
  src/EnergyPlus/Construction.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/EconomicLifeCycleCost.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/OutdoorAirUnit.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabularAnnual.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/Photovoltaics.cc
  src/EnergyPlus/PipeHeatTransfer.cc
  src/EnergyPlus/PlantCentralGSHP.cc
  src/EnergyPlus/PlantCondLoopOperation.cc
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  src/EnergyPlus/PlantPipingSystemsManager.cc
  src/EnergyPlus/PlantUtilities.cc
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PollutionModule.cc
  src/EnergyPlus/PondGroundHeatExchanger.cc
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/Pumps.cc
  src/EnergyPlus/RefrigeratedCase.cc
  src/EnergyPlus/ResultsFramework.cc
  src/EnergyPlus/RoomAirModelManager.cc
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/SQLiteProcedures.cc
  src/EnergyPlus/SZVAVModel.cc
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/TARCOGArgs.cc
  src/EnergyPlus/TARCOGCommon.hh
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowManagerExteriorOptical.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
Labels: DoNotPublish, Refactoring

#9890 CppCheck DemandManager and DesiccantDehumidifiers
  src/EnergyPlus/DemandManager.cc
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/DesiccantDehumidifiers.hh
Labels: DoNotPublish

#9898 Missing units in call to reportSizerOutput for VRF FluidCtrl
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
Labels: DoNotPublish

#9896 Fix Bad Auto: Part 2 (Take 2)
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/GlobalNames.cc
  src/EnergyPlus/GlobalNames.hh
  src/EnergyPlus/HVACFan.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACMultiSpeedHeatPump.cc
  src/EnergyPlus/HVACSingleDuctInduc.cc
  src/EnergyPlus/HVACStandAloneERV.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/IOFiles.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
Labels: DoNotPublish, Refactoring

#9899 Allow checksum workflow to upload assets
  .github/workflows/checksums.yml
Labels: DoNotPublish, Developer Issue

#9903 Hotfix misplaced declaration in GetSurfaceListsInputs
  src/EnergyPlus/DataSurfaceLists.cc
Labels: DoNotPublish

#9912 Prepare for EnergyPlus 23.1
  .gitignore
  cmake/Install.cmake
  idd/CMakeLists.txt
  release/Deprecation.in.html
  release/readme.in.html
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  src/Transition/CMakeLists.txt
  workflows/energyplus.py
  workflows/transition.py
Labels: DoNotPublish

#9913 Fix one MacTeX install issue
  .github/workflows/mac_release.yml
Labels: DoNotPublish

#9900 CppCheck EconomicLifeCycleCost and EconomicTariff
  src/EnergyPlus/EconomicLifeCycleCost.cc
  src/EnergyPlus/EconomicTariff.cc
Labels: DoNotPublish

#9876 CppCheck AirflowNetwork
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Elements.hpp
  src/EnergyPlus/AirflowNetwork/src/Elements.cpp
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/ExhaustAirSystemManager.cc
  src/EnergyPlus/HeatBalanceIntRadExchange.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SystemAvailabilityManager.cc
  src/EnergyPlus/UnitarySystem.cc
Labels: DoNotPublish

#9895 CppCheck EMSManager, EarthTube and EcoRoofManager
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/EarthTube.cc
  src/EnergyPlus/EcoRoofManager.cc
Labels: DoNotPublish

#9908 Address surfaceProperty:ExteriorNaturalVentedCavity results in convection model errors issue
  src/EnergyPlus/ConvectionCoefficients.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
Labels: Defect

#9914 Address Improve documentation for Zone Air Heat Balance Internal Convective Heat Gain Rate
  doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex
Labels: Defect, Documentation
