Repository NREL/EnergyPlus, pull requests merged in 2024-08, with the labels that each got.

#10639 Fix #10624 - Fix Transition from 23.2.0 to 24.2.0 when a HeatExchanger:AirToAir:SensibleAndLatent has blank effectiveness fields
  src/Transition/CreateNewIDFUsingRulesV24_1_0.f90
  src/Transition/InputProcessor.f90
Labels: Defect, NotIDDChange, AuxiliaryTool

#10610 Include fan power in EIO file
  src/EnergyPlus/Fans.cc
  tst/EnergyPlus/unit/Fans.unit.cc
Labels: Defect, OutputChange

#10628 Source side outlet tempearture calculation uses loadside heat tranfer rate
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Defect

#10362 An Improved Duct Model
  design/FY2024/DuctLoss.PNG
  design/FY2024/DuctModelRoadMap.md
  design/FY2024/DuctlossAddon.png
  design/FY2024/NFP-DuctHeatTransfer.md
  design/FY2024/ReturnLeaks.PNG
  design/FY2024/Schametic.PNG
  design/FY2024/SupplyLeaks.PNG
Labels: NewFeature, IDDChange

#10657 Fix #10656 - PolygonClipping: CLIPLINE produces NaN when line to clip is parallel to the maxX of the clip window
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SolarShading.hh
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: Defect

#10636 Avoid AFN fan array bounds error
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Solver.hpp
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
Labels: Defect

#10578 Enable Floating point exceptions by default in Debug mode (GCC/Clang)
  cmake/CompilerFlags.cmake
  src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  src/EnergyPlus/api/EnergyPlusPgm.cc
  src/EnergyPlus/main.cc
  tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/ElectricPowerServiceManager.unit.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/HVACMultiSpeedHeatPump.unit.cc
  tst/EnergyPlus/unit/HVACUnitaryBypassVAV.unit.cc
  tst/EnergyPlus/unit/MixedAir.unit.cc
  tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc
  tst/EnergyPlus/unit/RefrigeratedCase.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
  tst/EnergyPlus/unit/WindowManager.unit.cc
  tst/EnergyPlus/unit/main.cc
Labels: Defect, DoNotPublish, Developer Issue

#10637 Follow up to #10617 and allow other `ZoneHVAC:*` component with Airflow Network simulations
  doc/input-output-reference/src/overview/group-airflow-network.tex
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UnitarySystem.hh
  src/EnergyPlus/WindowAC.cc
  src/EnergyPlus/WindowAC.hh
  tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc
Labels: NewFeature, AirflowNetwork

#10653 Correction of Condensers Not Operating Based on Operation Scheme
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/CondenserLoopTowers.hh
  tst/EnergyPlus/unit/CondenserLoopTowers.unit.cc
Labels: Defect

#10646 Increase Slat Angle Sampling Frequency for Blind Properties
  src/EnergyPlus/Material.hh
  src/EnergyPlus/WindowManager.cc
Labels: Defect, SeverityLow, Refactoring

#10658 A couple API Endpoints
  scripts/dev/verify_idfs_in_cmake.py
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/DataRuntimeLanguage.hh
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  src/EnergyPlus/api/datatransfer.cc
  src/EnergyPlus/api/datatransfer.h
  src/EnergyPlus/api/datatransfer.py
  testfiles/_1ZoneUncontrolled_ForAPITesting.idf
  tst/EnergyPlus/api/TestDataTransfer.c
  tst/EnergyPlus/api/TestDataTransfer.py
Labels: NewFeature

#9996 Modernized Error Reporting
  design/FY2023/ImprovedErrorHandling.md
  src/EnergyPlus/Boilers.cc
  src/EnergyPlus/ChillerExhaustAbsorption.cc
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/DataSurfaceLists.cc
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/FuelCellElectricGenerator.cc
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/Humidifiers.cc
  src/EnergyPlus/Material.cc
  src/EnergyPlus/MicroturbineElectricGenerator.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MoistureBalanceEMPDManager.cc
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/PlantChillers.cc
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PluginManager.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/UtilityRoutines.hh
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/api/EnergyPlusPgm.cc
  src/EnergyPlus/api/datatransfer.cc
  src/EnergyPlus/api/runtime.cc
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: NewFeature, Refactoring

#10668 CppCheck FluidProperties through HVACUnitaryBypassVAV
  src/EnergyPlus/FluidProperties.cc
  src/EnergyPlus/FluidProperties.hh
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACInterfaceManager.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACManager.hh
  src/EnergyPlus/HVACStandAloneERV.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
Labels: DoNotPublish

#10672 CppCheck HVAC VRF
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
Labels: DoNotPublish

#10678 Don't catch std::exception in Debug mode so we can catch array bound errors in debugger
  src/EnergyPlus/api/EnergyPlusPgm.cc
Labels: DoNotPublish, Developer Issue

#10685 Indoor living wall update
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  src/EnergyPlus/IndoorGreen.cc
  src/Transition/SupportFiles/Report Variables 24-1-0 to 24-2-0.csv
  testfiles/IndoorLivingWall.idf
Labels: Defect, OutputChange

#10684 CppCheck StandardRatings and various through Humidifiers
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/BranchInputManager.cc
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/EconomicTariff.cc
  src/EnergyPlus/EvaporativeCoolers.cc
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/Humidifiers.cc
  src/EnergyPlus/StandardRatings.cc
Labels: DoNotPublish

#10691 CppCheck MixedAir
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixerComponent.cc
  src/EnergyPlus/MoistureBalanceEMPDManager.cc
  src/EnergyPlus/MundtSimMgr.cc
Labels: DoNotPublish

#10692 CppCheck NodeInputManager
  src/EnergyPlus/NodeInputManager.cc
  src/EnergyPlus/NonZoneEquipmentManager.cc
Labels: DoNotPublish

#10693 CppCheck PipeHeatTransfer
  src/EnergyPlus/PipeHeatTransfer.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/PlantCentralGSHP.cc
Labels: DoNotPublish

#10694 CppCheck PlantLoopCondOperation
  src/EnergyPlus/PlantCondLoopOperation.cc
Labels: DoNotPublish

#10695 CppCheck PlantPipingSystemsManager
  src/EnergyPlus/PlantPipingSystemsManager.cc
  src/EnergyPlus/PlantPressureSystem.cc
  src/EnergyPlus/PlantPressureSystem.hh
  src/EnergyPlus/PlantUtilities.cc
  src/EnergyPlus/PlantValves.cc
Labels: DoNotPublish
