Repository NREL/EnergyPlus, pull requests merged in 2024-05, with the labels that each got.

#10327 Do not apply capacity and power degradation to `Coil:Heating:DX:VariableSpeed` when timed defrost fraction is 0
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/coils.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/variable-refrigerant-flow-heat-pumps.tex
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
  tst/EnergyPlus/unit/VariableSpeedCoils.unit.cc
Labels: Defect

#10482 Correction of Location of Zone Equipment Get Routine
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc
  tst/EnergyPlus/unit/ConvectionCoefficients.unit.cc
  tst/EnergyPlus/unit/DElightManager.unit.cc
  tst/EnergyPlus/unit/DaylightingManager.unit.cc
  tst/EnergyPlus/unit/InternalHeatGains.unit.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
  tst/EnergyPlus/unit/PurchasedAirManager.unit.cc
  tst/EnergyPlus/unit/RoomAirflowNetwork.unit.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Defect

#10437 Add new people schedule columns to EIO/initialization summary to address #10314
  doc/output-details-and-examples/src/output-files/eplusout-eio.tex
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/ScheduleManager.hh
  src/Transition/OutputRulesFiles/OutputChanges24-1-0-to-24-2-0.md
  tst/EnergyPlus/unit/ScheduleManager.unit.cc
Labels: Defect, OutputChange, HighComplexityApproved

#10469 Include lighting return air fraction input during sizing when ZoneAirMassFlowConservation is used
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Defect

#10492 Fix array bounds error with EquivalentLayer window and shading surface
  src/EnergyPlus/WindowEquivalentLayer.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: Defect

#10248 New attempt at fixing #7464: outlet water temperature control issue for variable speed cooling tower
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/CondenserLoopTowers.hh
  tst/EnergyPlus/unit/CondenserLoopTowers.unit.cc
Labels: Defect

#10422 Fix EMS pump pressure override crash
  src/EnergyPlus/Pumps.cc
  tst/EnergyPlus/unit/Pumps.unit.cc
Labels: Defect

#10497 Water Use Equipment Shows Volumetric Flow Mismatch with Node Data
  src/EnergyPlus/WaterUse.cc
  src/EnergyPlus/WaterUse.hh
  tst/EnergyPlus/unit/WaterUse.unit.cc
Labels: Defect

#10510 Fix FMU Variable Update
  src/EnergyPlus/ExternalInterface.cc
Labels: Defect

#10479 Correct logic in supplemental water coil used in UnitarySystem
  src/EnergyPlus/UnitarySystem.cc
Labels: Defect

#10457 Align `PlantLowFlowRateToler` with `DataHVACGlobals::VerySmallMassFlow`
  src/EnergyPlus/DataConvergParams.hh
  src/EnergyPlus/Plant/LoopSide.cc
Labels: Defect

#10517 Run FMU tests as annual
  testfiles/CMakeLists.txt
Labels: DoNotPublish

#10516 Correction of Generic Contaminant Handling in Some Situations
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/VariableSpeedCoils.cc
  tst/EnergyPlus/unit/VariableSpeedCoils.unit.cc
  tst/EnergyPlus/unit/ZoneEquipmentManager.unit.cc
Labels: Defect

#10515 Fix VRF HeatRecovery Check
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#10500 Add convergence check for co2 and contaminant
  src/EnergyPlus/DataConvergParams.hh
  src/EnergyPlus/HVACInterfaceManager.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACManager.hh
  tst/EnergyPlus/unit/HVACInterfaceManager.unit.cc
  tst/EnergyPlus/unit/HVACManager.unit.cc
Labels: Defect

#10525 Fix #10355 - Correctly Set up Zone Internal Gains when Refrigeration:CompressorRack serves a Refrigeration:WalkIn object with "Zone" Heat Transfer Location
  src/EnergyPlus/RefrigeratedCase.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/RefrigeratedCase.unit.cc
Labels: Defect

#10528 Fix #10302 - CalcEquipmentFlowRates assert failure due to out of bounds std::array indexing
  src/EnergyPlus/SolarCollectors.cc
  src/EnergyPlus/SolarCollectors.hh
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/SolarCollectors.unit.cc
Labels: Defect
