Repository NREL/EnergyPlus, pull requests merged in 2024-11, with the labels that each got.

#10735 Fix wshp array bounds error and sizing
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
Labels: Defect

#10794 Remove dead code
  src/EnergyPlus/PlantUtilities.cc
  src/EnergyPlus/PlantUtilities.hh
Labels: DoNotPublish

#10649 Fix VRF FluidTCtrl negative outdoor unit fan power
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#10750 Fix Issue #10286 window material shade mis-alignment for Output:Constructions
  .github/workflows/test_pull_requests.yml
  src/EnergyPlus/WindowManager.cc
  src/Transition/OutputRulesFiles/OutputChanges24-2-0-to-25-1-0.md
Labels: Defect, OutputChange

#10827 Update Decent CI
  .decent_ci-Linux.yaml
  .decent_ci.yaml
  third_party/fmt-8.0.1/include/fmt/format.h
Labels: DoNotPublish

#10739 CppCheck OutputProcessor
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputProcessor.hh
Labels: DoNotPublish

#10740 CppCheck OutputReportTabular
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/OutputReportTabularAnnual.cc
  src/EnergyPlus/OutputReports.cc
  src/EnergyPlus/OutsideEnergySources.cc
  src/EnergyPlus/PhaseChangeModeling/HysteresisModel.cc
  src/EnergyPlus/PhotovoltaicThermalCollectors.cc
  src/EnergyPlus/Photovoltaics.cc
  src/EnergyPlus/Photovoltaics.hh
  src/EnergyPlus/PipeHeatTransfer.cc
  src/EnergyPlus/PlantLoadProfile.cc
Labels: DoNotPublish

#10756 CppCheck ScheduleManager
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/ScheduleManager.hh
  src/EnergyPlus/SimAirServingZones.cc
Labels: DoNotPublish

#10757 CppCheck SetPointManager
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/SetPointManager.hh
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/SimulationManager.hh
  src/EnergyPlus/SingleDuct.cc
  src/EnergyPlus/SingleDuct.hh
  src/EnergyPlus/SizingAnalysisObjects.cc
Labels: DoNotPublish

#10795 CppCheck SizingManager
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SizingManager.hh
Labels: DoNotPublish

#10495 Fix GHE Bugs
  .decent_ci-Linux.yaml
  dictionary.dic
  src/EnergyPlus/Data/BaseData.hh
  src/EnergyPlus/Data/CommonIncludes.hh
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/GroundHeatExchangers.cc
  src/EnergyPlus/GroundHeatExchangers.hh
  src/EnergyPlus/GroundTemperatureModeling/BaseGroundTemperatureModel.hh
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc
  src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.hh
  src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.cc
  src/EnergyPlus/GroundTemperatureModeling/GroundTemperatureModelManager.hh
  src/EnergyPlus/GroundTemperatureModeling/KusudaAchenbachGroundTemperatureModel.cc
  src/EnergyPlus/GroundTemperatureModeling/KusudaAchenbachGroundTemperatureModel.hh
  src/EnergyPlus/GroundTemperatureModeling/SiteBuildingSurfaceGroundTemperatures.cc
  src/EnergyPlus/GroundTemperatureModeling/SiteBuildingSurfaceGroundTemperatures.hh
  src/EnergyPlus/GroundTemperatureModeling/SiteDeepGroundTemperatures.cc
  src/EnergyPlus/GroundTemperatureModeling/SiteDeepGroundTemperatures.hh
  src/EnergyPlus/GroundTemperatureModeling/SiteFCFactorMethodGroundTemperatures.cc
  src/EnergyPlus/GroundTemperatureModeling/SiteFCFactorMethodGroundTemperatures.hh
  src/EnergyPlus/GroundTemperatureModeling/SiteShallowGroundTemperatures.cc
  src/EnergyPlus/GroundTemperatureModeling/SiteShallowGroundTemperatures.hh
  src/EnergyPlus/GroundTemperatureModeling/XingGroundTemperatureModel.cc
  src/EnergyPlus/GroundTemperatureModeling/XingGroundTemperatureModel.hh
  src/EnergyPlus/PipeHeatTransfer.hh
  src/EnergyPlus/PlantPipingSystemsManager.hh
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  tst/EnergyPlus/unit/FiniteDifferenceGroundTemperatureModel.unit.cc
  tst/EnergyPlus/unit/GroundHeatExchangers.unit.cc
  tst/EnergyPlus/unit/SiteGroundDomain.unit.cc
Labels: Defect

#10832 Add a problem matcher for gcc warnings/errors: for develop commits, and branch of PR
  .github/workflows/cpp-problem-matcher.json
  .github/workflows/test_develop_commits.yml
  .github/workflows/test_pull_requests.yml
Labels: DoNotPublish, Developer Issue
