Repository NREL/EnergyPlus, pull requests merged in 2024-03, with the labels that each got.

#10423 Update git-blame-ignore-revs for cleaner blaming on github and locally
  .git-blame-ignore-revs
Labels: DoNotPublish, Developer Issue

#10440 Pull the ARM build from GHA
  .github/workflows/mac_release.yml
Labels: DoNotPublish

#10424 Fix #10350 - typo in zone_time_step python api returning system time step instead
  src/EnergyPlus/api/datatransfer.py
Labels: Defect, APIChange

#10436 Fix typo in test files CMake list
  testfiles/CMakeLists.txt
Labels: Defect

#10429 IndoorLivingWall (DocUpdate)
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/indoor-living-wall.tex
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
Labels: DoNotPublish

#10425 Addressed EIRFuelFiredHeatPump object electric energy consumption output variable reports zero value
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Defect

#10435 Improved Controller:WaterCoil FindRoot error message with TemperatureAndHumidityRatio plus Limit setpoints by water temp
  src/EnergyPlus/HVACControllers.cc
  src/EnergyPlus/HVACControllers.hh
Labels: Defect

#10419 More robust internal gain subtotals
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DisplacementVentMgr.cc
  src/EnergyPlus/DisplacementVentMgr.hh
  src/EnergyPlus/HeatBalanceInternalHeatGains.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/UFADManager.cc
Labels: Defect

#10404 Heat Pump Plant Loop EIR refactoring
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  src/EnergyPlus/PlantLoopHeatPumpEIR.hh
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Refactoring

#10418 Fixes Supervisory Control Logic Problem For AirSource Plants
  src/EnergyPlus/Plant/EquipAndOperations.cc
  tst/EnergyPlus/unit/EquipAndOperations.unit.cc
Labels: Defect

#10447 Fix misassigned fields in `LocalAPIDataEntry` (`api/datatransfer.cc`)
  src/EnergyPlus/api/datatransfer.cc
Labels: Defect

#10442 Fix unshaded inside reveal array bounds error and add reveal and sill to Fenestration_RefBldgSmallHotelNew2004_Chicago
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/indoor-living-wall.tex
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  src/EnergyPlus/SolarShading.cc
  testfiles/Fenestration_RefBldgSmallHotelNew2004_Chicago.idf
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: Defect

#10449 Conditionally use openmp for ConvertInputFormat (allow turning it off)
  src/ConvertInputFormat/CMakeLists.txt
Labels: DoNotPublish

#10448 Final Polishing for 24.1
  .github/workflows/mac_release.yml
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  release/Deprecation.in.html
  release/readme.in.html
  src/ConvertInputFormat/CMakeLists.txt
Labels: DoNotPublish

#10450 Revert JSON TimeStep label
  src/EnergyPlus/ResultsFramework.cc
Labels: DoNotPublish

#10454 Fix #10453 - python38.dll missing on windows installers
  .github/workflows/windows_release.yml
  cmake/PythonGetLibAndLinkUp.cmake
  src/EnergyPlus/CMakeLists.txt
Labels: Defect
