Repository NREL/EnergyPlus, pull requests merged in 2024-09, with the labels that each got.

#10696 Fix Bug Uncovered in PR #10646
  src/EnergyPlus/SolarShading.cc
Labels: Defect, DoNotPublish

#10683 Completely Rebuild our CI System
  .decent_ci-Linux.yaml
  .decent_ci-MacOS.yaml
  .decent_ci-Windows.yaml
  .decent_ci.yaml
  .github/disabled-workflows/mac_test.yml
  .github/disabled-workflows/release.yml
  .github/disabled-workflows/windows_test.yml
  .github/unfinished-workflows/linux_test.yml
  .github/unfinished-workflows/linux_test_debug.yml
  .github/workflows/add_opened_pr_to_project.yml
  .github/workflows/build_checksums.yml
  .github/workflows/build_documentation.yml
  .github/workflows/build_wheels.yml
  .github/workflows/clang-format-check.yml
  .github/workflows/cppcheck.yml
  .github/workflows/custom_check.yml
  .github/workflows/documentation-windows.yml
  .github/workflows/documentation.yml
  .github/workflows/linux_build.yml
  .github/workflows/release_linux.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_windows.yml
  .github/workflows/test_code_integrity.yml
  .github/workflows/test_debug_builds.yml
  .github/workflows/test_develop_commits.yml
  .github/workflows/test_epjson.yml
  .github/workflows/test_pull_requests.yml
  .github/workflows/verify_pr_labels.yml
  .gitlab-ci.yml
  CMakeLists.txt
  cmake/CompilerFlags.cmake
  cmake/ProjectMacros.cmake
  cmake/RunRegression.cmake
  requirements.txt
  scripts/dev/add_to_project.sh
  scripts/dev/build_regression_summary.py
  scripts/dev/gha_coverage_summary.py
  scripts/dev/gha_regressions.py
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/DataSystemVariables.hh
  src/EnergyPlus/SimulationManager.cc
  third_party/.gitignore
  tst/EnergyPlus/unit/CommandLineInterface.unit.cc
  tst/EnergyPlus/unit/Timer.unit.cc
Labels: DoNotPublish

#10714 Revert "Completely Rebuild our CI System"
  .decent_ci-Linux.yaml
  .decent_ci-MacOS.yaml
  .decent_ci-Windows.yaml
  .decent_ci.yaml
  .github/disabled-workflows/mac_test.yml
  .github/disabled-workflows/release.yml
  .github/disabled-workflows/windows_test.yml
  .github/unfinished-workflows/linux_test.yml
  .github/unfinished-workflows/linux_test_debug.yml
  .github/workflows/add_opened_pr_to_project.yml
  .github/workflows/build_documentation.yml
  .github/workflows/build_wheels.yml
  .github/workflows/checksums.yml
  .github/workflows/clang-format-check.yml
  .github/workflows/cppcheck.yml
  .github/workflows/custom_check.yml
  .github/workflows/documentation-windows.yml
  .github/workflows/documentation.yml
  .github/workflows/epjson.yml
  .github/workflows/linux_build.yml
  .github/workflows/linux_release.yml
  .github/workflows/mac_release.yml
  .github/workflows/pr_labels.yml
  .github/workflows/test_code_integrity.yml
  .github/workflows/test_debug_builds.yml
  .github/workflows/test_develop_commits.yml
  .github/workflows/test_pull_requests.yml
  .github/workflows/windows_release.yml
  .gitlab-ci.yml
  CMakeLists.txt
  cmake/CompilerFlags.cmake
  cmake/ProjectMacros.cmake
  cmake/RunRegression.cmake
  requirements.txt
  scripts/dev/add_to_project.sh
  scripts/dev/build_regression_summary.py
  scripts/dev/gha_coverage_summary.py
  scripts/dev/gha_regressions.py
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/DataSystemVariables.hh
  src/EnergyPlus/SimulationManager.cc
  third_party/.gitignore
  tst/EnergyPlus/unit/CommandLineInterface.unit.cc
  tst/EnergyPlus/unit/Timer.unit.cc
Labels: DoNotPublish

#10715 Partially Rebuild our CI System
  .decent_ci-Linux.yaml
  .decent_ci-MacOS.yaml
  .github/disabled-workflows/mac_test.yml
  .github/disabled-workflows/release.yml
  .github/disabled-workflows/windows_test.yml
  .github/unfinished-workflows/linux_test.yml
  .github/unfinished-workflows/linux_test_debug.yml
  .github/workflows/README.md
  .github/workflows/add_opened_pr_to_project.yml
  .github/workflows/build_checksums.yml
  .github/workflows/build_documentation.yml
  .github/workflows/build_wheels.yml
  .github/workflows/clang-format-check.yml
  .github/workflows/cppcheck.yml
  .github/workflows/custom_check.yml
  .github/workflows/disabled_test_debug_builds.yml.txt
  .github/workflows/documentation-windows.yml
  .github/workflows/documentation.yml
  .github/workflows/linux_build.yml
  .github/workflows/release_linux.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_windows.yml
  .github/workflows/test_code_integrity.yml
  .github/workflows/test_develop_commits.yml
  .github/workflows/test_epjson.yml
  .github/workflows/test_pull_requests.yml
  .github/workflows/verify_pr_labels.yml
  .gitlab-ci.yml
  cmake/CompilerFlags.cmake
  cmake/ProjectMacros.cmake
  cmake/RunRegression.cmake
  requirements.txt
  scripts/dev/add_to_project.sh
  scripts/dev/build_regression_summary.py
  scripts/dev/gha_coverage_summary.py
  scripts/dev/gha_regressions.py
  src/EnergyPlus/DataSystemVariables.cc
  src/EnergyPlus/DataSystemVariables.hh
  src/EnergyPlus/SimulationManager.cc
  third_party/.gitignore
  tst/EnergyPlus/unit/CommandLineInterface.unit.cc
  tst/EnergyPlus/unit/Timer.unit.cc
Labels: DoNotPublish

#10717 Yet Another Silly Blind-Related Bug
  src/EnergyPlus/WindowManager.cc
Labels: Defect, DoNotPublish

#10618 Address HSPF2 calculation problems for multispeed DX system
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/StandardRatings.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
Labels: Defect

#10708 CppCheck WindowEquivalentLayer
  src/EnergyPlus/WindowEquivalentLayer.cc
  src/EnergyPlus/WindowEquivalentLayer.hh
Labels: DoNotPublish

#10700 CppCheck ZonePlenum
  src/EnergyPlus/ZonePlenum.cc
Labels: DoNotPublish

#10687 CppCheck log to log1p to see what diffs look like
  src/EnergyPlus/ConvectionCoefficients.cc
Labels: DoNotPublish

#10719 Fix airloop topology crash
  src/EnergyPlus/DataAirLoop.hh
  src/EnergyPlus/DataAirSystems.hh
  src/EnergyPlus/DataZoneEquipment.hh
  src/EnergyPlus/SystemReports.cc
Labels: DoNotPublish

#10713 Fix failed transition
  src/Transition/CreateNewIDFUsingRulesV24_2_0.f90
Labels: Defect

#10667 Enable cycling in continuous mode Fan:System in VRF FluidTCtrl model
  src/EnergyPlus/DXCoils.cc
Labels: Defect

#10706 CppCheck ZoneContaminantPredictorCorrector
  src/EnergyPlus/WindowModel.cc
  src/EnergyPlus/ZoneAirLoopEquipmentManager.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.cc
  src/EnergyPlus/ZoneContaminantPredictorCorrector.hh
  src/EnergyPlus/ZoneDehumidifier.cc
Labels: DoNotPublish

#10703 CppCheck DaylightingManager
  src/EnergyPlus/DaylightingManager.cc
Labels: DoNotPublish

#10698 CppCheck ZoneTempPredCorr
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
Labels: DoNotPublish

#10705 CppCheck ZoneEquipmentManager
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneEquipmentManager.hh
Labels: DoNotPublish

#10724 CppCheck PurchasedAirManager
  src/EnergyPlus/PurchasedAirManager.cc
Labels: DoNotPublish

#10725 CppCheck exp(x)-1 to expm1(x) test for diffs
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.cc
Labels: DoNotPublish

#10661 Fix `Fan:ZoneExhaust` AFN validation
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  tst/EnergyPlus/unit/AirflowNetworkHVAC.unit.cc
Labels: Defect, AirflowNetwork

#10635 Correction of Some Problems in the ChillerHeater Model
  design/FY2024/chiller_heater_part_load_fix.md
  src/EnergyPlus/PlantCentralGSHP.cc
  src/EnergyPlus/PlantCentralGSHP.hh
  tst/EnergyPlus/unit/PlantCentralGSHP.unit.cc
Labels: Defect

#10707 CppCheck WindowManager
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManager.hh
Labels: DoNotPublish

#10633 Fix coil speed number equal to zero
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#10679 Correct Use of Incorrect Index for VRF Cooling
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  testfiles/VariableRefrigerantFlow_5Zone.idf
  testfiles/VariableRefrigerantFlow_5Zone_wAirloop.idf
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#10732 Revert "Adopt the Extended Heat Index calculation in zone resilience"
  doc/engineering-reference/src/special-modules-reporting/resilience-metrics.tex
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/ExtendedHI.cc
  src/EnergyPlus/ExtendedHI.hh
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/ExtendedHI.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
Labels: DoNotPublish

#10729 CppCheck LowTempRadiantSystems
  src/EnergyPlus/LowTempRadiantSystem.cc
Labels: DoNotPublish

#10727 CppCheck DaylightingManager
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/DaylightingManager.hh
Labels: DoNotPublish

#10728 Fix HVAC Sizing Summary Min OA flow for Spaces
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneEquipmentManager.hh
Labels: Defect

#10682 Fix #10665 - HeatPump:AirToWater:FuelFired:Heating was not using Outside air temperatures to evaluate curves
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Defect, NotIDDChange

#10650 fix VRFFluidTCtrl OU Fan Power not considering system cycling
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#10557 Fixing cooling mode cooling coil cooling rate much higher than heat pump cooling rate and OU capacity
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/DXCoils.hh
  src/EnergyPlus/DataGlobalConstants.hh
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
  testfiles/CMakeLists.txt
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#10721 Convective Baseboard Crashing in Sizing Routine When Autosizing is Not Requested
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/BaseboardRadiator.hh
  testfiles/HVACStandAloneERV_Economizer.idf
  testfiles/VAVSingleDuctReheatBaseboard.idf
  testfiles/WindACRHControl.idf
  tst/EnergyPlus/unit/BaseboardRadiator.unit.cc
Labels: Defect

#10734 Indoor green update 2
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  src/EnergyPlus/IndoorGreen.cc
  src/EnergyPlus/IndoorGreen.hh
Labels: Defect

#10736 CppCheck InternalHeatGains
  src/EnergyPlus/InputProcessing/IdfParser.cc
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/Material.cc
Labels: DoNotPublish

#10744 Some pre-release operations
  .github/workflows/release_linux.yml
  release/Deprecation.in.html
  scripts/dev/build_regression_summary.py
  scripts/dev/gha_regressions.py
Labels: DoNotPublish

#10716 Initial Python App Packaging
  .github/workflows/release_linux.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_windows.yml
  cmake/PythonCopyStandardLib.py
  cmake/PythonFixUpOnMac.cmake
  cmake/install_codesign_script.cmake
  scripts/dev/create_shortcut.ps1
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PluginManager.hh
  src/EnergyPlus/PythonEngine.cc
  src/EnergyPlus/PythonEngine.hh
Labels: NewFeature

#10747 Fix transition duplicate TU and fix End-Use Subcategory value
  src/Transition/CreateNewIDFUsingRulesV24_2_0.f90
Labels: Defect

#10737 Update indoor living wall sensible heat gain calculation
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/indoor-living-wall.tex
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  src/EnergyPlus/IndoorGreen.cc
Labels: Defect

#10753 fix build issue when Link to Python is turned off
  .github/workflows/test_develop_commits.yml
  src/EnergyPlus/PythonEngine.cc
Labels: Defect

#10759 Update readme
  release/readme.in.html
Labels: DoNotPublish

#10768 Fix Foundation:Kiva Custom Block Material Input Processing
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/UtilityRoutines.hh
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#10772 Fix Convective Baseboard with Hard Sizes
  src/EnergyPlus/BaseboardRadiator.cc
  src/EnergyPlus/BaseboardRadiator.hh
  tst/EnergyPlus/unit/BaseboardRadiator.unit.cc
Labels: Defect

#10773 Fix Meter:Custom with mix of valid and invalid names
  src/EnergyPlus/OutputProcessor.cc
Labels: Defect
