Repository NREL/EnergyPlus, pull requests merged in 2024-12, with the labels that each got.

#10834 CppCheck update suppress warning
  .github/workflows/test_code_integrity.yml
Labels: DoNotPublish

#10836 CppCheck WindowManager
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/UserDefinedComponents.cc
  src/EnergyPlus/Vectors.cc
  src/EnergyPlus/Vectors.hh
  src/EnergyPlus/WaterUse.cc
  src/EnergyPlus/WeatherManager.cc
  src/EnergyPlus/WeatherManager.hh
  src/EnergyPlus/WindTurbine.cc
  src/EnergyPlus/WindowAC.cc
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManager.hh
Labels: DoNotPublish

#10839 CppCheck UnitVentilator
  src/EnergyPlus/UnitVentilator.cc
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/VariableSpeedCoils.cc
Labels: DoNotPublish

#10840 CppCheck SurfaceGeometry
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
Labels: DoNotPublish

#10838 CppCheck VentilatedSlab
  src/EnergyPlus/VentilatedSlab.cc
Labels: DoNotPublish

#10775 Fix Std. 62.1 VRP calculations for Secondary Recirculation Systems
  src/EnergyPlus/SizingManager.cc
Labels: Defect

#10793 Fix chiller chilling when it is off
  src/EnergyPlus/ChillerAbsorption.cc
  src/EnergyPlus/ChillerElectricASHRAE205.cc
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerIndirectAbsorption.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/PlantChillers.cc
  tst/EnergyPlus/unit/ChillerElectricEIR.unit.cc
Labels: Defect

#10844 Fix #10842 - When using pyenergyplus to run (via run_energyplus), PythonPlugin initializations errors lead to hang
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/PluginManager.cc
  tst/EnergyPlus/api/TestRuntimeReleasesTheGIL.py
  tst/EnergyPlus/api/TestRuntimeReleasesTheGIL/mcve_gil.idf
  tst/EnergyPlus/api/TestRuntimeReleasesTheGIL/mcve_gil.py
Labels: Defect, APIChange

#10867 Bump GCC on Decent CI to 13.3
  .decent_ci-Linux.yaml
Labels: DoNotPublish

#10869 Delete unused schedule
  testfiles/DOAToPTHP.idf
  testfiles/DOAToUnitarySystem.idf
Labels: Defect

#10859 Set the correct identifier for variable speed cooling tower in `GetTowerInput`
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/CondenserLoopTowers.hh
  tst/EnergyPlus/unit/CondenserLoopTowers.unit.cc
Labels: Defect
