Repository NREL/EnergyPlus, pull requests merged in 2024-02, with the labels that each got.

#10388 Add a new object type DataLoopNode::ConnectionObjectType
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/BranchNodeConnections.cc
  src/EnergyPlus/DataLoopNode.hh
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
Labels: Defect

#10295 Fill object defaults for blank or missing fields and fix Site:GroundReflectance:SnowModifier defaults
  src/EnergyPlus/InputProcessing/InputProcessor.cc
  src/EnergyPlus/OutputReports.cc
  tst/EnergyPlus/unit/InputProcessor.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#10377 Update our GHA to use 4 cores
  .github/workflows/custom_check.yml
  .github/workflows/documentation-windows.yml
  .github/workflows/documentation.yml
  .github/workflows/epjson.yml
  .github/workflows/linux_build.yml
  .github/workflows/linux_release.yml
  .github/workflows/windows_release.yml
Labels: DoNotPublish

#10382 Fixes source side sizing calculation for HeatPump:PlantLoop:EIR:Heating issue
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Defect

#10394 do not escape xml with invalid strings
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#10007 Minor build cleanups
  cmake/PythonCopyStandardLib.py
  doc/tools/parse_output_variables.py
  idd/schema/idd_parser.py
Labels: Refactoring

#10334 Correct crash with DOAS VS DX coils and fix system name in Coil Sizing tables
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/VariableSpeedCoils.cc
Labels: Defect

#10376 Correct system sizing when TU desisgn sizing object is used
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
Labels: Defect

#10405 Build Python Wheels for EnergyPlus - Preliminary Merge
  .github/workflows/build_wheels.yml
  .gitignore
  requirements.txt
  setup.py
Labels: DoNotPublish

#10406 Build python wheel - Quick Fixes
  .github/workflows/build_wheels.yml
  setup.py
Labels: DoNotPublish

#10408 Tiny tweaks for IO freeze
  .github/workflows/linux_release.yml
  setup.py
Labels: DoNotPublish

#10409 More IO freeze fixes.
  .github/workflows/mac_release.yml
  .github/workflows/windows_release.yml
Labels: DoNotPublish

#10412 #10306 - Static gfortran
  .github/workflows/mac_release.yml
Labels: Defect

#10411 More IO Freeze Fixes
  .github/workflows/mac_release.yml
  .gitignore
  .readthedocs.yml
  CMakeLists.txt
  cmake/Install.cmake
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/indoor-living-wall.tex
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
  idd/CMakeLists.txt
  scripts/dev/api_debug_helper.py
  setup.py
  src/EnergyPlus/PluginManager.cc
  third_party/CMakeLists.txt
Labels: DoNotPublish

#10413 Fixes JSON output regressions relative to 23.2
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/ResultsFramework.cc
Labels: Defect, DoNotPublish
