Repository NREL/EnergyPlus, pull requests merged in 2024-06, with the labels that each got.

#10529 Fix #10399 - Long elapsed times are not recorded correctly
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/DataSystemVariables.hh
  src/EnergyPlus/Timer.cc
  src/EnergyPlus/Timer.hh
  src/EnergyPlus/UtilityRoutines.cc
  src/EnergyPlus/UtilityRoutines.hh
  src/EnergyPlus/api/EnergyPlusPgm.cc
  tst/EnergyPlus/unit/CMakeLists.txt
  tst/EnergyPlus/unit/Timer.unit.cc
Labels: Defect

#10527 Properly set up CCACHE
  CMakeLists.txt
  third_party/ssc/jsoncpp/CMakeLists.txt
Labels: DoNotPublish, Developer Issue

#10532 #10531 - Use non-deprecated Github Actions
  .github/dependabot.yml
  .github/workflows/add_opened_pr_to_project.yml
  .github/workflows/build_wheels.yml
  .github/workflows/clang-format-check.yml
  .github/workflows/cppcheck.yml
  .github/workflows/custom_check.yml
  .github/workflows/documentation-windows.yml
  .github/workflows/documentation.yml
  .github/workflows/epjson.yml
  .github/workflows/linux_build.yml
  .github/workflows/linux_release.yml
  .github/workflows/mac_release.yml
  .github/workflows/pr_labels.yml
  .github/workflows/windows_release.yml
  scripts/dev/update_gha_actions.py
Labels: Defect, Developer Issue

#10526 Fix #10365 - IDD Files Have Inconsistent Encoding
  bin/EPDraw/Run-Mac/EPDrawGUI.app/Contents/MacOS/Energy+.idd
  idd/versions/V1-2-2-Energy+.idd
  idd/versions/V2-0-0-Energy+.idd
  idd/versions/V2-1-0-Energy+.idd
  idd/versions/V2-2-0-Energy+.idd
  idd/versions/V3-0-0-Energy+.idd
  idd/versions/V3-1-0-Energy+.idd
  idd/versions/V4-0-0-Energy+.idd
  idd/versions/V5-0-0-Energy+.idd
  idd/versions/V6-0-0-Energy+.idd
  idd/versions/V7-0-0-Energy+.idd
  idd/versions/V7-1-0-Energy+.idd
  idd/versions/V7-2-0-Energy+.idd
  idd/versions/V8-0-0-Energy+.idd
  idd/versions/V8-1-0-Energy+.idd
  idd/versions/V8-2-0-Energy+.idd
  idd/versions/V8-3-0-Energy+.idd
  scripts/dev/check_non_utf8.py
Labels: Defect, Developer Issue

#10539 Add Reporting of Incident Solar on Shading Surfaces
  src/EnergyPlus/SurfaceGeometry.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#10540 Fix #10534 - Chiller:Absorption does not autosize in some cases
  src/EnergyPlus/ChillerAbsorption.cc
  tst/EnergyPlus/unit/ChillerAbsorption.unit.cc
Labels: Defect

#10541 Addition of Limit Warnings for Node Temperatures in CondFD Solution Algorithm
  src/EnergyPlus/HeatBalFiniteDiffManager.cc
  src/EnergyPlus/HeatBalFiniteDiffManager.hh
  tst/EnergyPlus/unit/HeatBalFiniteDiffManager.unit.cc
Labels: Defect

#10536 Fix #9204 - Overcome StdOutputRecordCount's limit of about 2.1 billion
  src/EnergyPlus/ConfiguredFunctions.in.cc
  src/EnergyPlus/DataGlobals.hh
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Defect

#10542 SPM - Fortran Transition - throw if SPM names are not unique
  src/Transition/CreateNewIDFUsingRulesV24_2_0.f90
Labels: Refactoring

#10533 #9138 - Catch blank values in Schedule:File and Schedule:File:Shading and issue error
  src/EnergyPlus/InputProcessing/CsvParser.cc
  src/EnergyPlus/InputProcessing/CsvParser.hh
  src/EnergyPlus/ScheduleManager.cc
  tst/EnergyPlus/unit/Resources/schedule_file_with_blank.csv
  tst/EnergyPlus/unit/ScheduleManager.unit.cc
Labels: Defect

#10506 Add output wetbulb globe temperature in the csv output
  doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex
  src/EnergyPlus/DataHeatBalance.cc
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/HeatBalanceAirManager.hh
  src/Transition/OutputRulesFiles/OutputChanges24-1-0-to-24-2-0.md
  testfiles/1ZoneUncontrolled.idf
  testfiles/5ZoneAirCooledWithSpacesHVAC.idf
Labels: NewFeature

#10485 Initialize NodeData pressure in class initializer and DefaultNodeValues
  src/EnergyPlus/DataLoopNode.hh
  tst/EnergyPlus/unit/AirTerminalSingleDuctMixer.unit.cc
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#10379 Air-To-Water Heat Pump with Heat Recovery
  design/FY2024/NFP-AirToWaterHeatPumpHeatRecovery.md
  design/FY2024/chiller_with_heat_recovery.png
  design/FY2024/heater_with_heat_recovery.png
Labels: NewFeature

#10331 fix VRF_FluidTCtrl heating round 2
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  src/EnergyPlus/HVACVariableRefrigerantFlow.hh
Labels: Defect

#10546 Update issue_template (pivotal is gone)
  .github/issue_template.md
Labels: DoNotPublish

#10544 Add the transition rules to accompany #10455
  src/Transition/CreateNewIDFUsingRulesV24_2_0.f90
  src/Transition/InputRulesFiles/Rules24-1-0-to-24-2-0.md
Labels: NewFeature, IDDChange

#10558 Update Decent CI to use Python 3.12
  .decent_ci-Linux.yaml
  .decent_ci-MacOS.yaml
  .decent_ci-Windows.yaml
Labels: DoNotPublish

#10559 Update CBE Thermal Comfort Tool link in docs
  doc/input-output-reference/src/overview/group-internal-gains-people-lights-other.tex
Labels: DoNotPublish, Documentation

#10551 Correction of Mass Flow Rate Calculation for Pools Served by Low Heater Capacity
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/SwimmingPool.hh
  tst/EnergyPlus/unit/SwimmingPool.unit.cc
Labels: Defect

#10535 #10524 - SetpointManager:ReturnTemperature:Chilled/HotWater (useless) warnings from GetSpecificHeatGlycol
  src/EnergyPlus/SetPointManager.cc
  tst/EnergyPlus/unit/SetPointManager.unit.cc
Labels: Defect

#10554 Fix #10439 - Problems building with 3.12 on GHA - Bump python to 3.12.2
  .github/workflows/linux_release.yml
  .github/workflows/mac_release.yml
  .github/workflows/windows_release.yml
  CMakeLists.txt
  scripts/package_tests/runner.py
Labels: Defect, Developer Issue

#10561 Point Decent CI to mod regression branch to fix diffs
  .decent_ci.yaml
Labels: DoNotPublish

#10553 Improve error checking in SQLite database connection (again)
  src/EnergyPlus/SQLiteProcedures.cc
  src/EnergyPlus/SQLiteProcedures.hh
Labels: Defect, Refactoring

#10565 change unit of "Zone ITE Adjusted Return Air Temperature" from W to C
  src/EnergyPlus/InternalHeatGains.cc
Labels: Defect

#10311 NewFeature: Additional ASHRAE Metrics for E+ 24-1
  design/FY2024/NFP-90-1-Metrics-24-1.md
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.hh
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportPredefined.hh
  src/EnergyPlus/StandardRatings.cc
  src/EnergyPlus/StandardRatings.hh
  src/EnergyPlus/VariableSpeedCoils.cc
  src/Transition/OutputRulesFiles/OutputChanges24-1-0-to-24-2-0 .md
  tst/EnergyPlus/unit/DXCoils.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
  tst/EnergyPlus/unit/StandardRatings.unit.cc
Labels: NewFeature, OutputChange

#10498 Fix array bounds error for interzone windows and fix convexity of mirrored surfaces
  doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex
  src/EnergyPlus/DataGlobalConstants.hh
  src/EnergyPlus/DataSurfaces.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.hh
  src/EnergyPlus/SolarReflectionManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/Vectors.cc
  tst/EnergyPlus/unit/DataSurfaces.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/SurfaceGeometry.unit.cc
Labels: Defect

#10575 Fix #10279 - Make sure that assigning the result of a TendVariable (eg @TrendValue) results in proper actuator behavior
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/RuntimeLanguageProcessor.cc
  tst/EnergyPlus/unit/EMSManager.unit.cc
Labels: Defect

#10572 Correction of FEI Calculation
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/air-system-fans.tex
  doc/input-output-reference/src/overview/group-user-defined-hvac-and-plant-component.tex
  src/EnergyPlus/Fans.cc
  src/EnergyPlus/Fans.hh
  tst/EnergyPlus/unit/Fans.unit.cc
  tst/EnergyPlus/unit/HVACFan.unit.cc
Labels: Defect

#10581 Correction of Hybrid Model Reporting Issues
  doc/engineering-reference/src/alternative-modeling-processes/hybrid-model.tex
  doc/input-output-reference/src/overview/group-hybrid-model.tex
  src/EnergyPlus/HybridModel.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.hh
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Defect

#10549 Improve coil association in ReportCoilSelection coil sizing reports
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/ReportCoilSelection.hh
  src/EnergyPlus/VentilatedSlab.cc
  src/EnergyPlus/WaterCoils.cc
  tst/EnergyPlus/unit/ReportCoilSelection.unit.cc
Labels: Defect
