Repository NREL/EnergyPlus, pull requests merged in 2025-07, with the labels that each got.

#11091 Correction of Various Documentation Issues
  doc/input-output-reference/src/overview/group-airflow.tex
  doc/input-output-reference/src/overview/group-coil-cooling-dx.tex
  doc/input-output-reference/src/overview/group-daylighting.tex
  doc/input-output-reference/src/overview/group-design-objects.tex
  doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex
  doc/input-output-reference/src/overview/group-location-climate-weather-file-access.tex
  doc/input-output-reference/src/overview/group-plant-equipment.tex
  doc/input-output-reference/src/overview/group-schedules.tex
  doc/input-output-reference/src/overview/group-simulation-parameters.tex
  doc/readthedocs/sphinx/auxiliary-programs/auxiliary-programs.rst
  doc/readthedocs/sphinx/ems-application-guide/ems-application-guide.rst
  src/EnergyPlus/ScheduleManager.cc
Labels: Defect, Documentation

#11097 Correction of SetupOutputVariables.csv
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  src/EnergyPlus/SingleDuct.cc
  tst/EnergyPlus/unit/OutputProcessor.unit.cc
Labels: Defect, AuxiliaryTool

#11096 Correction of Error in Xing Ground Temperature Model Get Input
  src/EnergyPlus/GroundTemperatureModeling/XingGroundTemperatureModel.cc
  tst/EnergyPlus/unit/XingGroundTemperatureModel.unit.cc
Labels: Defect

#11115 Update build_documentation.yml
  .github/workflows/build_documentation.yml
Labels: DoNotPublish

#11104 Correct Error Message Level when Node Types are Undefined
  src/EnergyPlus/SimulationManager.cc
  testfiles/ASHRAE901_OfficeSmall_STD2019_Denver.idf
  tst/EnergyPlus/unit/SimulationManager.unit.cc
Labels: Defect

#11126 Fix a few EIO headers and newlines
  src/EnergyPlus/ConvectionCoefficients.cc
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/PlantPipingSystemsManager.cc
  src/EnergyPlus/RefrigeratedCase.cc
  src/EnergyPlus/SimulationManager.cc
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WindowManager.cc
Labels: Defect

#11119 Correction of Fanger PMV to Align with ASHRAE Standard 55/ISO 7730
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-005/occupant-thermal-comfort.tex
  src/EnergyPlus/ThermalComfort.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
Labels: Defect

#11133 Fix bad subscript in ZoneVentilation:DesignFlowRate warning
  src/EnergyPlus/HeatBalanceAirManager.cc
Labels: Defect
