Repository NREL/EnergyPlus, pull requests merged in 2025-09, with the labels that each got.

#11184 Hotfix #11179 - Adjust for alternate build
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/PythonEngine.cc
Labels: Defect, DoNotPublish, Developer Issue

#11173 #11054 - Part 2 - Crash with schedule with missing day types
  src/EnergyPlus/ScheduleManager.cc
  tst/EnergyPlus/unit/ScheduleManager.unit.cc
Labels: Defect, NotIDDChange

#11109 #10596 - Remove fmt fortran workarounds - Z & N (and S)
  src/EnergyPlus/Construction.cc
  src/EnergyPlus/DesiccantDehumidifiers.cc
  src/EnergyPlus/GeneratorFuelSupply.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatPumpWaterToWaterHEATING.cc
  src/EnergyPlus/IOFiles.hh
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  tst/EnergyPlus/unit/OutputFiles.unit.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect, OutputChange, Developer Issue

#11139 Correct Time Stamp Reported in EDD
  src/EnergyPlus/General.cc
  tst/EnergyPlus/unit/General.unit.cc
  tst/EnergyPlus/unit/MixedAir.unit.cc
  tst/EnergyPlus/unit/OutdoorAirUnit.unit.cc
  tst/EnergyPlus/unit/WaterThermalTanks.unit.cc
  tst/EnergyPlus/unit/WaterUse.unit.cc
Labels: Defect

#11190 Run and Cache Regressions on Develop And reuse in PR workflows
  .github/actions/configure-and-build/action.yml
  .github/actions/setup-runner/action.yml
  .github/workflows/clean_cache.yml
  .github/workflows/run_and_cache_regressions_develop.yml
  .github/workflows/test_pull_requests.yml
  third_party/zlib/CMakeLists.txt
Labels: NewFeature, Developer Issue

#11192 Cache regressions followup
  .github/actions/setup-runner/action.yml
  .github/workflows/run_and_cache_regressions_develop.yml
  .github/workflows/test_pull_requests.yml
  cmake/PythonInstallCLITools.py
  testfiles/CMakeLists.txt
Labels: Defect, DoNotPublish, Developer Issue

#11193 gha_regressions.py: run in parallel for speed gains
  scripts/dev/gha_regressions.py
Labels: Defect, DoNotPublish, Developer Issue

#11146 Correction of Return Temperature Output for Cooling Plant Loops and Condenser Loops in EIO Sizing Output
  src/EnergyPlus/Plant/PlantManager.cc
  tst/EnergyPlus/unit/PlantManager.unit.cc
Labels: Defect

#10998 Plant sizing report and equipment summary fixes
  src/EnergyPlus/Autosizing/Base.cc
  src/EnergyPlus/Autosizing/Base.hh
  src/EnergyPlus/DataSizing.hh
  src/EnergyPlus/HVACSizingSimulationManager.cc
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportPredefined.hh
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/Plant/Component.hh
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/SQLiteProcedures.cc
  src/EnergyPlus/SQLiteProcedures.hh
  src/EnergyPlus/SizingManager.cc
  src/Transition/OutputRulesFiles/OutputChanges25-1-0-to-25-2-0.md
  tst/EnergyPlus/unit/Autosizing/BaseClassSizing.unit.cc
  tst/EnergyPlus/unit/HVACSizingSimulationManager.unit.cc
  tst/EnergyPlus/unit/PlantManager.unit.cc
  tst/EnergyPlus/unit/SQLite.unit.cc
Labels: Defect, OutputChange, RPD

#11212 Fix develop arm builds
  .github/workflows/run_and_cache_regressions_develop.yml
  scripts/dev/ensure_unique_html_tables.py
  testfiles/CMakeLists.txt
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
  tst/EnergyPlus/unit/Autosizing/BaseClassSizing.unit.cc
  tst/EnergyPlus/unit/HVACFourPipeBeam.unit.cc
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/Psychrometrics.unit.cc
  tst/EnergyPlus/unit/ThermalComfort.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: DoNotPublish

#11169 Quick fix #11157 - Incorrect StoreType for Zone Combined Outdoor Air Volume Flow Rate output variables
  src/EnergyPlus/HeatBalanceAirManager.cc
Labels: Defect

#11203 Cycling ratio is applied twice during cycling operation for `HeatPump:PlantLoop:EIR:*` objects
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  tst/EnergyPlus/unit/PlantLoopHeatPumpEIR.unit.cc
Labels: Defect

#11017 Fix for 11016; Set correct water flow rate of companion cooling coils for WAHP applications using the `AirloopHVAC:UnitarySystem`
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  tst/EnergyPlus/unit/WaterToAirHeatPumpSimple.unit.cc
Labels: Defect

#11225 Addressed Reporting Problem in LEED Renewable Energy Source Summary Table
  src/EnergyPlus/ElectricPowerServiceManager.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#11135 Address variable speed DX cooling Coil does not run on latent only load
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: Defect

#11234 Github Actions Save Baseline Results
  .github/workflows/test_pull_requests.yml
Labels: DoNotPublish, github_actions

#11131 Address Coil:Cooling:DX Doesn't Use the Minimum Outside Air Temperature for Compressor Operation Field
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.hh
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.hh
  tst/EnergyPlus/unit/Coils/CoilCoolingDXCurveFitOperatingMode.unit.cc
Labels: Defect

#11118 Correct Missing Information in Exterior Fenestration Shaded State Table
  doc/input-output-reference/src/standard-output-reports/output-table-summaryreports.tex
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/WindowManagerExteriorThermal.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect, OutputChange

#11019 Use condenser capacity instead of evaporator capacity to determine water flow rate of WAHP coils
  doc/engineering-reference/src/loop-equipment-sizing-and-other-design-data/component-sizing.tex
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
  tst/EnergyPlus/unit/WaterToAirHeatPumpSimple.unit.cc
Labels: Defect
