Repository NREL/EnergyPlus, pull requests merged in 2025-05, with the labels that each got.

#11040 Enumeration Cleanup Pass
  scripts/dev/check_for_enum_scope_usage.py
  scripts/dev/check_for_malformed_enums.py
  src/EnergyPlus/DataGenerators.hh
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/DataPhotovoltaics.hh
  src/EnergyPlus/DataWater.hh
  src/EnergyPlus/DataZoneControls.hh
  src/EnergyPlus/EcoRoofManager.cc
  src/EnergyPlus/EconomicTariff.cc
  src/EnergyPlus/EconomicTariff.hh
  src/EnergyPlus/ElectricPowerServiceManager.cc
  src/EnergyPlus/ElectricPowerServiceManager.hh
  src/EnergyPlus/FuelCellElectricGenerator.cc
  src/EnergyPlus/FuelCellElectricGenerator.hh
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/LowTempRadiantSystem.cc
  src/EnergyPlus/LowTempRadiantSystem.hh
  src/EnergyPlus/Photovoltaics.cc
  src/EnergyPlus/PlantHeatExchangerFluidToFluid.cc
  src/EnergyPlus/PlantPipingSystemsManager.cc
  src/EnergyPlus/PlantPipingSystemsManager.hh
  src/EnergyPlus/PurchasedAirManager.cc
  src/EnergyPlus/PurchasedAirManager.hh
  src/EnergyPlus/RefrigeratedCase.cc
  src/EnergyPlus/RefrigeratedCase.hh
  src/EnergyPlus/WaterManager.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/EconomicLifeCycleCost.unit.cc
  tst/EnergyPlus/unit/EconomicTariff.unit.cc
  tst/EnergyPlus/unit/ElectricPowerServiceManager.unit.cc
  tst/EnergyPlus/unit/FuelCellElectricGenerator.unit.cc
  tst/EnergyPlus/unit/LowTempRadiantSystem.unit.cc
  tst/EnergyPlus/unit/PlantPipingSystemsManager.unit.cc
  tst/EnergyPlus/unit/PurchasedAirManager.unit.cc
Labels: DoNotPublish, Refactoring

#11041 Fix #10378 - bump nlohmann/json to support most recent clang/apple-clang
  src/EnergyPlus/InputProcessing/InputValidation.cc
  src/EnergyPlus/InputProcessing/InputValidation.hh
  third_party/PATCHES.md
  third_party/nlohmann/hedley.hpp
  third_party/nlohmann/hedley_undef.hpp
  third_party/nlohmann/json.hpp
  third_party/nlohmann/json3.12.0.patch
  third_party/nlohmann/json373.patch
  third_party/nlohmann/json_fwd.hpp
  third_party/nlohmann/json_literals.hpp
  third_party/nlohmann/json_literals.patch
  third_party/valijson/0001-Improve-error-messages.patch
  third_party/valijson/0002-Eliminate-avoiable-std-regex.patch
  third_party/valijson/compat/optional.hpp
  third_party/valijson/valijson/adapters/boost_json_adapter.hpp
  third_party/valijson/valijson/adapters/json11_adapter.hpp
  third_party/valijson/valijson/adapters/jsoncpp_adapter.hpp
  third_party/valijson/valijson/adapters/nlohmann_json_adapter.hpp
  third_party/valijson/valijson/adapters/picojson_adapter.hpp
  third_party/valijson/valijson/adapters/poco_json_adapter.hpp
  third_party/valijson/valijson/adapters/property_tree_adapter.hpp
  third_party/valijson/valijson/adapters/qtjson_adapter.hpp
  third_party/valijson/valijson/adapters/rapidjson_adapter.hpp
  third_party/valijson/valijson/adapters/std_string_adapter.hpp
  third_party/valijson/valijson/adapters/yaml_cpp_adapter.hpp
  third_party/valijson/valijson/constraints/basic_constraint.hpp
  third_party/valijson/valijson/constraints/concrete_constraints.hpp
  third_party/valijson/valijson/constraints/constraint.hpp
  third_party/valijson/valijson/constraints/constraint_visitor.hpp
  third_party/valijson/valijson/exceptions.hpp
  third_party/valijson/valijson/internal/adapter.hpp
  third_party/valijson/valijson/internal/basic_adapter.hpp
  third_party/valijson/valijson/internal/custom_allocator.hpp
  third_party/valijson/valijson/internal/frozen_value.hpp
  third_party/valijson/valijson/internal/json_pointer.hpp
  third_party/valijson/valijson/internal/json_reference.hpp
  third_party/valijson/valijson/internal/optional_bundled.hpp
  third_party/valijson/valijson/internal/uri.hpp
  third_party/valijson/valijson/schema.hpp
  third_party/valijson/valijson/schema_cache.hpp
  third_party/valijson/valijson/schema_parser.hpp
  third_party/valijson/valijson/subschema.hpp
  third_party/valijson/valijson/utils/boost_json_utils.hpp
  third_party/valijson/valijson/utils/nlohmann_json_utils.hpp
  third_party/valijson/valijson/utils/property_tree_utils.hpp
  third_party/valijson/valijson/utils/utf8_utils.hpp
  third_party/valijson/valijson/utils/yaml_cpp_utils.hpp
  third_party/valijson/valijson/validation_visitor.hpp
  third_party/valijson/valijson/validator.hpp
  third_party/valijson/valijson/valijson.patch
  tst/EnergyPlus/unit/DataSizing.unit.cc
  tst/EnergyPlus/unit/DataZoneEquipment.unit.cc
  tst/EnergyPlus/unit/HeatBalanceAirManager.unit.cc
  tst/EnergyPlus/unit/HeatBalanceManager.unit.cc
  tst/EnergyPlus/unit/ResultsFramework.unit.cc
Labels: Defect, NotIDDChange, Developer Issue

#11029 Fix Reheat Coil Multiplier report
  .github/workflows/test_pull_requests.yml
  src/EnergyPlus/SingleDuct.cc
  tst/EnergyPlus/unit/EconomicTariff.unit.cc
Labels: Defect

#11059 Quick fix array bound error in test
  src/EnergyPlus/EconomicTariff.cc
  tst/EnergyPlus/unit/EconomicTariff.unit.cc
Labels: DoNotPublish, Developer Issue

#11063 Fix Coil Sizing Report for Coil:Heating:Gas:MultiStage and Coil:Heating:Electric:MultiStage
  src/EnergyPlus/HeatingCoils.cc
Labels: Defect

#11080 Adjust #11051 - Fix EPVector out of range issue: good candidate for a lambda!
  src/EnergyPlus/MixedAir.cc
Labels: Defect, DoNotPublish

#11071 Fix order of curve independent variables for GAHP
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/air-system-compound-component-groups.tex
  testfiles/PlantLoopHeatPump_Fuel-Fired.idf
Labels: Defect

#11085 Fix #11054 - Crash with schedule with missing day types
  src/EnergyPlus/ScheduleManager.cc
  tst/EnergyPlus/unit/ScheduleManager.unit.cc
Labels: Defect
