Repository NREL/EnergyPlus, pull requests merged in 2025-02, with the labels that each got.

#10914 Add Space and Zone columns to Envelope Summary
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/OutputReportPredefined.cc
  src/EnergyPlus/OutputReportPredefined.hh
  src/Transition/OutputRulesFiles/OutputChanges24-2-0-to-25-1-0.md
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect, OutputChange

#10860 Fix #10718 - DXCoils StandardRatings OutputReportPredefined::addFootNoteSubTable produces invalid XML
  .github/workflows/test_pull_requests.yml
  CMakeLists.txt
  idd/CMakeLists.txt
  scripts/pytests/conftest.py
  scripts/pytests/requirements.txt
  scripts/pytests/test_xml_output.py
  src/EnergyPlus/CMakeLists.txt
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/StandardRatings.cc
  src/EnergyPlus/StandardRatings.hh
Labels: Defect

#10852 Correct reference entering air temperatures for the water to air heat pump dataset
  datasets/WaterToAirHeatPumps.idf
Labels: Defect, Documentation

#10897 Update conduction-through-the-walls.tex
  doc/engineering-reference/src/surface-heat-balance-manager-processes/conduction-through-the-walls.tex
Labels: Defect, Documentation

#10917 #10916 - Broken format strings in a few places like CurveManager
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/DemandManager.cc
  src/EnergyPlus/FluidCoolers.cc
  src/EnergyPlus/FluidProperties.cc
  src/EnergyPlus/WeatherManager.cc
  tst/EnergyPlus/unit/CurveManager.unit.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.cc
  tst/EnergyPlus/unit/Fixtures/EnergyPlusFixture.hh
Labels: Defect, NotIDDChange

#10920 Try with fvisibility=hidden on clang/GCC
  .github/workflows/test_pull_requests.yml
  CMakeLists.txt
  requirements.txt
  scripts/dev/gha_regressions.py
  src/.clang-format
  src/ConvertInputFormat/main.cpp
  src/EnergyPlus/AirflowNetwork/include/AirflowNetwork/Properties.hpp
  src/EnergyPlus/CommandLineInterface.cc
  src/EnergyPlus/DataStringGlobals.hh
  src/EnergyPlus/FileSystem.cc
  src/EnergyPlus/FileSystem.hh
  src/EnergyPlus/FromChars.hh
  src/EnergyPlus/General.cc
  src/EnergyPlus/HeatBalanceKivaManager.cc
  src/EnergyPlus/Platform.hh
  src/EnergyPlus/PluginManager.cc
  src/EnergyPlus/PluginManager.hh
  src/EnergyPlus/PsychCacheData.hh
  src/EnergyPlus/Psychrometrics.cc
  src/EnergyPlus/Psychrometrics.hh
  src/EnergyPlus/PythonEngine.cc
  src/EnergyPlus/PythonEngine.hh
  src/EnergyPlus/SolarShading.hh
  src/EnergyPlus/Timer.cc
  src/EnergyPlus/api/EnergyPlusAPI.h
  src/EnergyPlus/api/EnergyPlusPgm.cc
  src/EnergyPlus/api/func.h
  src/EnergyPlus/api/runtime.h
Labels: Performance, Developer Issue

#10783 Fix DOAS system sizing and add reporting
  src/EnergyPlus/AirLoopHVACDOAS.cc
  tst/EnergyPlus/unit/AirLoopHVACDOAS.unit.cc
Labels: Defect

#10909 Change unit used for enthalpy in the `Coil Sizing Details` report
  src/EnergyPlus/OutputReportPredefined.cc
Labels: Defect

#10901 Fix #10899 - `Output:Table:Monthly`: `SumOrAverageDuringHoursShown` doesn't follow previous variable
  src/EnergyPlus/OutputReportTabular.cc
  tst/EnergyPlus/unit/OutputReportTabular.unit.cc
Labels: Defect

#10915 #10888 - Chiller minimum load ratio is set in the IDF however does not appear in eplustbl.htm for Chiller:Electric:EIR and Chiller:Electric:ReformulatedEIR
  src/EnergyPlus/ChillerElectricEIR.cc
  src/EnergyPlus/ChillerReformulatedEIR.cc
  tst/EnergyPlus/unit/ChillerElectricEIR.unit.cc
  tst/EnergyPlus/unit/ChillerReformulatedEIR.unit.cc
Labels: Defect

#10369 Consolidate speed-dependent coil load ratio input parameters into a single parameter.
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/Coils/CoilCoolingDX.hh
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.hh
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitPerformance.hh
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.cc
  src/EnergyPlus/Coils/CoilCoolingDXCurveFitSpeed.hh
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/UnitarySystem.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDX.unit.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDXCurveFitOperatingMode.unit.cc
Labels: Defect

#10776 Variable speed PIUs: add example files fieldnames and revise error message
  src/EnergyPlus/PoweredInductionUnits.cc
  testfiles/5ZoneAirCooledConvCoef_VSFan.idf
Labels: Refactoring

#10846 Fan:SystemModel with discrete speed flow fractions crashes when speeds >= 2
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
  tst/EnergyPlus/unit/HVACVariableRefrigerantFlow.unit.cc
Labels: Defect

#10855 Fix #10817 - Avoid crash in FluidCooler/EvaporativeFluidCooler when Water flow rate autosized and no Sizing:Plant
  src/EnergyPlus/EvaporativeFluidCoolers.cc
  src/EnergyPlus/FluidCoolers.cc
  testfiles/EvaporativeFluidCooler.idf
  testfiles/EvaporativeFluidCooler_TwoSpeed.idf
  testfiles/FluidCooler.idf
  testfiles/FluidCoolerTwoSpeed.idf
  tst/EnergyPlus/unit/EvaporativeFluidCoolers.unit.cc
  tst/EnergyPlus/unit/FluidCoolers.unit.cc
Labels: Defect, NotIDDChange

#10763 Correct VAV maximum air flow fraction during reheat for heating dominated use cases
  src/EnergyPlus/SingleDuct.cc
  tst/EnergyPlus/unit/SingleDuct.unit.cc
  tst/EnergyPlus/unit/VAVDefMinMaxFlow.unit.cc
Labels: Defect

#10673 Fix #10663 - Fan runtime fraction < 1 when flow rate scaling using DesignSpecification:ZoneHVAC:Sizing
  src/EnergyPlus/WindowAC.cc
  tst/EnergyPlus/unit/WindowAC.unit.cc
Labels: Defect, NotIDDChange

#10934 Fix #10933 - Unable to read Site:GroundDomain:Slab with Site:GroundTemperature:Undisturbed:FiniteDifference
  src/EnergyPlus/PlantPipingSystemsManager.cc
  tst/EnergyPlus/unit/PlantPipingSystemsManager.unit.cc
Labels: Defect, NotIDDChange

#10928 Allow ConvertInputFormat to run with missing building and geometry
  .github/workflows/test_pull_requests.yml
  requirements.txt
  src/ConvertInputFormat/main.cpp
  tst/EnergyPlus/unit/FluidCoolers.unit.cc
Labels: DoNotPublish

#10930 Fix #10902 - CoolingTower:VariableSpeed:Merkel not reporting to Equipment Summary - Cooling Towers and Fluid Coolers
  src/EnergyPlus/CondenserLoopTowers.cc
  tst/EnergyPlus/unit/CondenserLoopTowers.unit.cc
Labels: Defect, NotIDDChange

#10850 Fix #10847 - EnergyPlus simulation crashes above a certain BaseDepth value for GroundHeatTransfer
  cmake/Fortran.cmake
  idd/BasementGHT.idd
  src/Basement/3DBasementHT.f90
  src/Basement/CMakeLists.txt
  src/Basement/tests/AutoGriddingDepthIsHigh.idf
  src/Basement/tests/AutoGriddingDepthIsLowish.idf
  src/Basement/tests/AutoGriddingDepthIsTooHigh.idf
Labels: Defect, AuxiliaryTool

#10932 #10923 - Quick fix Epl-run.bat
  scripts/Epl-run.bat
  scripts/RunEPlus.bat
Labels: DoNotPublish, AuxiliaryTool

#10939 Fix excess fluid properties warnings leading to huge err file size
  src/EnergyPlus/FluidProperties.cc
Labels: Defect

#10940 New outputs for infiltration and ventilation
  doc/input-output-reference/src/overview/group-airflow.tex
  src/EnergyPlus/DataHeatBalance.hh
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/ThermalChimney.cc
  src/Transition/OutputRulesFiles/OutputChanges24-2-0-to-25-1-0.md
  src/Transition/SupportFiles/Report Variables 24-2-0 to 25-1-0.csv
  testfiles/5ZoneVAV-ChilledWaterStorage-Mixed.idf
  testfiles/5ZoneVAV-ChilledWaterStorage-Mixed_DCV_MaxZd.idf
  testfiles/5ZoneVAV-ChilledWaterStorage-Mixed_DCV_MultiPath.idf
  testfiles/5ZoneVAV-ChilledWaterStorage-Stratified.idf
  testfiles/BasicsFiles/Exercise2.idf
  testfiles/BasicsFiles/Exercise2A-Solution.idf
  testfiles/BasicsFiles/Exercise2B-Solution.idf
  testfiles/BasicsFiles/Exercise2C-Solution.idf
  testfiles/DirectIndirectEvapCoolers.idf
  testfiles/DirectIndirectEvapCoolersVSAS.idf
  testfiles/EMSCustomOutputVariable.idf
  testfiles/EMSCustomSchedule.idf
  testfiles/EMSDemandManager_LargeOffice.idf
  testfiles/EMSDiscreteAirSystemSizes.idf
  testfiles/EMSReplaceTraditionalManagers_LargeOffice.idf
  testfiles/EMSTestMathAndKill.idf
  testfiles/FanCoil_HybridVent_VentSch.idf
  testfiles/HybridModel_4Zone_Solve_Infiltration_free_floating.idf
  testfiles/PerformancePrecision_ASHRAE9012016_SchoolSecondary_Denver.idf
  testfiles/PythonPluginCustomOutputVariable.idf
  testfiles/PythonPluginCustomSchedule.idf
  testfiles/PythonPluginCustomTrendVariable.idf
  testfiles/PythonPluginDemandManager_LargeOffice.idf
  testfiles/PythonPluginDiscreteAirSystemSizes.idf
  testfiles/PythonPluginReplaceTraditionalManagers_LargeOffice.idf
  testfiles/PythonPluginTestMathAndKill.idf
  testfiles/ReportDaylightFactors.idf
  testfiles/_1a-Long0.0.idf
  testfiles/_SmallOffice_Dulles.idf
  tst/EnergyPlus/unit/HVACManager.unit.cc
Labels: Defect, OutputChange

#10950 Io freeze fixes
  .github/workflows/release_mac.yml
  .github/workflows/release_windows.yml
  cmake/PythonFixUpTclTk.py
  scripts/dev/verify_signature.py
Labels: DoNotPublish

#10957 Fix documentation of heat pump heating rate description
  doc/input-output-reference/src/overview/group-variable-refrigerant-flow-equipment.tex
Labels: Defect, Documentation

#10954 Fix #10952 #10953 - Fixup tcl-tk issue on mac + add ubuntu arm64 runners
  .github/workflows/release_linux.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_windows.yml
  cmake/PythonFixUpTclTk.py
  scripts/package_tests/runner.py
Labels: Defect, AuxiliaryTool, Developer Issue

#10947 Fix space sizing output (spsz) when there is no space HVAC equipment
  doc/input-output-reference/src/overview/group-simulation-parameters.tex
  src/EnergyPlus/DataZoneEquipment.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/ZoneEquipmentManager.cc
  src/EnergyPlus/ZoneEquipmentManager.hh
Labels: Defect
