Repository NREL/EnergyPlus, pull requests merged in 2025-01, with the labels that each got.

#10875 CppCheck consts
  src/EnergyPlus/CurveManager.cc
  src/EnergyPlus/DataSizing.cc
  src/EnergyPlus/EMSManager.cc
  src/EnergyPlus/EconomicLifeCycleCost.cc
  src/EnergyPlus/FluidProperties.cc
  src/EnergyPlus/GroundHeatExchangers.cc
  src/EnergyPlus/GroundHeatExchangers.hh
  src/EnergyPlus/HeatBalanceAirManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/HighTempRadiantSystem.cc
  src/EnergyPlus/HybridEvapCoolingModel.cc
  src/EnergyPlus/IceThermalStorage.cc
  src/EnergyPlus/IceThermalStorage.hh
  src/EnergyPlus/IndoorGreen.cc
  src/EnergyPlus/IndoorGreen.hh
  src/EnergyPlus/InternalHeatGains.cc
  src/EnergyPlus/MixedAir.cc
  src/EnergyPlus/MixedAir.hh
  src/EnergyPlus/OutputProcessor.cc
  src/EnergyPlus/OutputReportTabular.cc
  src/EnergyPlus/OutputReportTabular.hh
  src/EnergyPlus/Plant/LoopSide.cc
  src/EnergyPlus/Plant/PlantManager.cc
  src/EnergyPlus/Plant/PlantManager.hh
  src/EnergyPlus/PlantPipingSystemsManager.cc
  src/EnergyPlus/PlantPipingSystemsManager.hh
  src/EnergyPlus/PlantValves.cc
  src/EnergyPlus/PollutionModule.cc
  src/EnergyPlus/ReportCoilSelection.cc
  src/EnergyPlus/ScheduleManager.cc
  src/EnergyPlus/ScheduleManager.hh
  src/EnergyPlus/SetPointManager.cc
  src/EnergyPlus/SimAirServingZones.cc
  src/EnergyPlus/SizingManager.cc
  src/EnergyPlus/SizingManager.hh
  src/EnergyPlus/SteamBaseboardRadiator.cc
  src/EnergyPlus/SteamBaseboardRadiator.hh
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/SurfaceGeometry.hh
  src/EnergyPlus/SwimmingPool.cc
  src/EnergyPlus/SystemReports.cc
  src/EnergyPlus/ThermalChimney.cc
  src/EnergyPlus/ThermalComfort.cc
  src/EnergyPlus/ThermalComfort.hh
  src/EnergyPlus/ThermalISO15099Calc.cc
  src/EnergyPlus/ThermalISO15099Calc.hh
  src/EnergyPlus/UFADManager.cc
  src/EnergyPlus/UFADManager.hh
  src/EnergyPlus/WaterThermalTanks.cc
  src/EnergyPlus/WaterToAirHeatPump.cc
  src/EnergyPlus/WaterToAirHeatPumpSimple.cc
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
Labels: DoNotPublish

#10879 CppCheck log1p HVACVariableRefrigerantFlow
  src/EnergyPlus/HVACVariableRefrigerantFlow.cc
Labels: DoNotPublish

#10870 Enhance epJSON Editor
  design/FY2025/NFP-epJSON-Editor-Enhancements.md
Labels: NewFeature, AuxiliaryTool

#10816 Corrects crash in DOAS fan sizing
  src/EnergyPlus/AirLoopHVACDOAS.cc
  src/EnergyPlus/Autosizing/SystemAirFlowSizing.cc
  tst/EnergyPlus/unit/Autosizing/SystemAirFlowSizing.unit.cc
Labels: Defect

#10849 Use LaTeX labels to reference figures in epw-csv-format-in-out.tex
  doc/auxiliary-programs/src/weather-converter-program/epw-csv-format-in-out.tex
Labels: Defect, Documentation

#10880 CppCheck expm1 log1p HeatRecovery
  src/EnergyPlus/HeatRecovery.cc
Labels: DoNotPublish

#10878 CppCheck expm1 FuelCellElectricGenerators
  src/EnergyPlus/FuelCellElectricGenerator.cc
Labels: DoNotPublish

#10804 Add plant worker function to get current equipment capacity
  src/EnergyPlus/CondenserLoopTowers.cc
  src/EnergyPlus/CondenserLoopTowers.hh
  src/EnergyPlus/Plant/Component.cc
  src/EnergyPlus/Plant/Component.hh
  src/EnergyPlus/PlantComponent.hh
  src/EnergyPlus/PlantCondLoopOperation.cc
  src/EnergyPlus/PlantCondLoopOperation.hh
  src/EnergyPlus/PlantLoopHeatPumpEIR.cc
  src/EnergyPlus/PlantLoopHeatPumpEIR.hh
Labels: Defect

#10892 Fix Issue #10890 Discovered During FluidAPI Refactor
  src/EnergyPlus/IceThermalStorage.cc
Labels: Defect

#10881 Add the NIST Life Cycle Cost Escalations for 2023 and 2024
  datasets/LCCusePriceEscalationDataSet2023.idf
  datasets/LCCusePriceEscalationDataSet2024.idf
  scripts/dev/update_nist_escalation.py
Labels: Defect

#10843 Fix #10826 - Possible Error in Slab
  CMakeLists.txt
  cmake/RunSimulation.cmake
  testfiles/SingleFamilyHouse_HP_Slab.idf
  testfiles/SingleFamilyHouse_HP_Slab_Dehumidification.idf
  testfiles/US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf
Labels: Defect, DoNotPublish, AuxiliaryTool, Developer Issue

#10861 Fix #10857 - Report System Summary:Thermostat Schedules depends on order of ZoneControl:Thermostat control types
  src/EnergyPlus/ZoneTempPredictorCorrector.cc
  tst/EnergyPlus/unit/ZoneTempPredictorCorrector.unit.cc
Labels: Defect

#10904 Fix #10895 - Expand IDF bug with HVACTemplate:System:DedicatedOutdoorAir for Heat Recovery Type 'Enthalpy'
  src/ExpandObjects/epfilter.f90
  testfiles/CMakeLists.txt
  testfiles/HVACTemplate-5ZonePTAC-DOAS-TwoHX.idf
  testfiles/emall.list
Labels: Defect, AuxiliaryTool

#10912 [Developer Issue] Remove emall.list
  testfiles/emall.list
Labels: DoNotPublish, Developer Issue

#10913 Fix #10894 - Use the newest Github Issue Template format via a Form
  .github/ISSUE_TEMPLATE/01-bug-report.yml
  .github/ISSUE_TEMPLATE/02-enhancement-request.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/issue_template.md
  .github/pull_request_template.md
Labels: DoNotPublish, Developer Issue

#10874 WindowManager Continued
  .github/workflows/test_pull_requests.yml
  src/EnergyPlus/Construction.cc
  src/EnergyPlus/Construction.hh
  src/EnergyPlus/DElightManagerF.cc
  src/EnergyPlus/DataSurfaces.hh
  src/EnergyPlus/DaylightingDevices.cc
  src/EnergyPlus/DaylightingManager.cc
  src/EnergyPlus/General.hh
  src/EnergyPlus/HeatBalanceManager.cc
  src/EnergyPlus/HeatBalanceSurfaceManager.cc
  src/EnergyPlus/SolarReflectionManager.cc
  src/EnergyPlus/SolarShading.cc
  src/EnergyPlus/SurfaceGeometry.cc
  src/EnergyPlus/WindowEquivalentLayer.hh
  src/EnergyPlus/WindowManager.cc
  src/EnergyPlus/WindowManager.hh
  tst/EnergyPlus/unit/HeatBalanceSurfaceManager.unit.cc
  tst/EnergyPlus/unit/SolarShading.unit.cc
Labels: DoNotPublish, Refactoring

#10905 [chore] Typo cooing -> cooling
  .git-blame-ignore-revs
  doc/auxiliary-programs/src/hvac-performance-curve-fit-tool/introduction-004.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-001/coils.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/air-system-compound-component-groups.tex
  doc/engineering-reference/src/simulation-models-encyclopedic-reference-003/centralheatpumpsystem.tex
  doc/input-output-reference/src/overview/group-unitary-equipment.tex
  src/EnergyPlus/AirflowNetwork/src/Solver.cpp
  src/EnergyPlus/ChillerReformulatedEIR.cc
  src/EnergyPlus/Coils/CoilCoolingDX.cc
  src/EnergyPlus/CostEstimateManager.cc
  src/EnergyPlus/DXCoils.cc
  src/EnergyPlus/Data/EnergyPlusData.cc
  src/EnergyPlus/Data/EnergyPlusData.hh
  src/EnergyPlus/Furnaces.cc
  src/EnergyPlus/HVACHXAssistedCoolingCoil.cc
  src/EnergyPlus/HVACManager.cc
  src/EnergyPlus/HVACUnitaryBypassVAV.cc
  src/EnergyPlus/HeatRecovery.cc
  src/EnergyPlus/HeatingCoils.cc
  src/EnergyPlus/UnitarySystem.cc
  src/EnergyPlus/WaterThermalTanks.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDX.unit.cc
  tst/EnergyPlus/unit/Coils/CoilCoolingDXCurveFitOperatingMode.unit.cc
  tst/EnergyPlus/unit/Furnaces.unit.cc
  tst/EnergyPlus/unit/StandardRatings.unit.cc
  tst/EnergyPlus/unit/UnitarySystem.unit.cc
Labels: DoNotPublish, Developer Issue

#10918 Compiler Warnings and Other Cleanups
  .github/workflows/test_pull_requests.yml
  scripts/dev/gha_regressions.py
  src/EnergyPlus/PlantLoopHeatPumpEIR.hh
  testfiles/_ResidentialBase.idf
Labels: DoNotPublish
